import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();
const CITY = 'ceske-budejovice';
const CN = 'Českých Budějovicích';
const CA = 'České Budějovice';

const profiles = [
  // ── ELEKTRIKÁŘ ───────────────────────────────────────────────────────────
  { fullName: 'Elektroinstalace Kratochvíl České Budějovice', phone: '+420 387 221 334', email: 'kratochvil@elektro-cb.cz', serviceId: 'elektrikar', cityId: CITY, address: 'Lannova třída 1122/18, České Budějovice', description: `Elektroinstalace Kratochvíl je zkušený elektrikář v ${CN} nabízející kompletní elektroinstalace, revize a opravy pro domácnosti i firmy. Elektrikář ${CA} zajistí rychlý výjezd a profesionální elektroinstalační práce v Jihočeském kraji.`, picturePath: null, active: true },
  { fullName: 'Elektro Matoušek České Budějovice', phone: '+420 387 334 560', email: 'matousek@elektro-cb.cz', serviceId: 'elektrikar', cityId: CITY, address: 'Piaristické náměstí 2345/29, České Budějovice', description: `Elektro Matoušek je elektrikář v ${CN} s 18 lety zkušeností v oblasti elektroinstalací bytů, domů a průmyslových objektů. Elektrikář ${CA} provádí montáž rozvaděčů, hromosvodů a fotovoltaiky.`, picturePath: null, active: true },
  { fullName: 'Elektroslužby Šustr České Budějovice', phone: '+420 603 441 780', email: null, serviceId: 'elektrikar', cityId: CITY, address: 'Rudolfovská třída 1234/14, České Budějovice', description: `Pavel Šustr je certifikovaný elektrikář v ${CN} provádějící revize elektroinstalací a montáž inteligentních domů. Elektrikář ${CA} nabídne rychlý servis a profesionální přístup.`, picturePath: null, active: true },
  { fullName: 'Elektrikář Kovanda České Budějovice', phone: '+420 728 234 902', email: 'kovanda@elektro-cb.cz', serviceId: 'elektrikar', cityId: CITY, address: 'F. A. Gerstnera 3456/38, České Budějovice', description: `Martin Kovanda je elektrikář ${CA} provádějící elektroinstalace nových staveb i rekonstrukcí. Nabízí montáž osvětlení, zásuvek a výměnu pojistkových skříní v ${CN} a Jihočeském kraji.`, picturePath: null, active: true },

  // ── INSTALATÉR ───────────────────────────────────────────────────────────
  { fullName: 'Instalatér Tůma České Budějovice', phone: '+420 387 100 234', email: 'tuma@instal-cb.cz', serviceId: 'instalater', cityId: CITY, address: 'Nové Vráto 2234/27, České Budějovice', description: `Instalatér Tůma nabízí kompletní instalatérské práce v ${CN} – opravy vodovodů, výměnu bojlerů a instalaci koupelen. Instalatér ${CA} zajistí rychlý výjezd a kvalitní práce.`, picturePath: null, active: true },
  { fullName: 'Vodo-Topo Šimánek České Budějovice', phone: '+420 603 441 870', email: 'simanek@vodotopo-cb.cz', serviceId: 'instalater', cityId: CITY, address: 'Lannova třída 3456/43, České Budějovice', description: `Vodo-Topo Šimánek je instalatér a topenář v ${CN} zaměřený na montáž plynových kotlů a podlahového vytápění. Instalatér ${CA} provádí kompletní rekonstrukce koupelen.`, picturePath: null, active: true },
  { fullName: 'Instalatérství Kůrka České Budějovice', phone: '+420 728 337 123', email: null, serviceId: 'instalater', cityId: CITY, address: 'Piaristické náměstí 4567/54, České Budějovice', description: `Instalatérství Kůrka nabízí veškeré instalatérské práce v ${CN}. Instalatér ${CA} se specializuje na opravy úniků vody a instalaci sanitárního vybavení.`, picturePath: null, active: true },
  { fullName: 'Petr Fišer – instalatér České Budějovice', phone: '+420 387 389 234', email: 'fiser@instal-cb.cz', serviceId: 'instalater', cityId: CITY, address: 'Rudolfovská třída 5678/67, České Budějovice', description: `Petr Fišer je instalatér ${CA} s 13 lety praxe v opravách a rekonstrukcích vodovodního a topenářského rozvodu. Instalatér v ${CN} nabídne pohotovostní servis 24/7.`, picturePath: null, active: true },

  // ── MALÍŘ ────────────────────────────────────────────────────────────────
  { fullName: 'Malíř Kubát České Budějovice', phone: '+420 387 228 456', email: 'kubat@malir-cb.cz', serviceId: 'malir', cityId: CITY, address: 'Lannova třída 2345/35, České Budějovice', description: `Malíř Kubát nabízí profesionální malování pokojů, bytů a kanceláří v ${CN} a okolí. Malíř ${CA} zajistí přípravu povrchů, stěrkování a výsledný nátěr dle přání zákazníka.`, picturePath: null, active: true },
  { fullName: 'Malířství Pok České Budějovice', phone: '+420 603 774 340', email: null, serviceId: 'malir', cityId: CITY, address: 'F. A. Gerstnera 3456/44, České Budějovice', description: `Malířství Pok provádí malování a lakýrnické práce pro domácnosti i firmy v ${CN}. Malíř ${CA} nabízí nátěry fasád, dekorativní techniky a výmalbu novostaveb.`, picturePath: null, active: true },
  { fullName: 'Jan Volf – malíř České Budějovice', phone: '+420 728 441 789', email: 'volf@malir-cb.cz', serviceId: 'malir', cityId: CITY, address: 'Nové Vráto 2345/23, České Budějovice', description: `Jan Volf je zkušený malíř pokojů v ${CN} s precizním přístupem k malování bytů a průmyslových prostor. Malíř ${CA} provádí nátěry na klíč včetně přípravy a nákupu materiálu.`, picturePath: null, active: true },
  { fullName: 'Malíř Šimánek České Budějovice', phone: '+420 602 554 123', email: 'simanek@malir-cb.cz', serviceId: 'malir', cityId: CITY, address: 'Piaristické náměstí 4567/57, České Budějovice', description: `Petr Šimánek je malíř a lakýrník v ${CN} nabízející veškeré malířské a lakýrnické práce. Malíř ${CA} se specializuje na nátěry fasád a interiérů bytů.`, picturePath: null, active: true },

  // ── TESAŘ ────────────────────────────────────────────────────────────────
  { fullName: 'Tesařství Mrázek České Budějovice', phone: '+420 387 441 780', email: 'mrazek@tesar-cb.cz', serviceId: 'tesar', cityId: CITY, address: 'Rudolfovská třída 3456/41, České Budějovice', description: `Tesařství Mrázek provádí výstavbu a rekonstrukci krovů a dřevěných konstrukcí v ${CN}. Tesař ${CA} realizuje pergoly, přístřešky a zahradní stavby v Jihočeském kraji.`, picturePath: null, active: true },
  { fullName: 'Krovy Boháč České Budějovice', phone: '+420 603 221 456', email: null, serviceId: 'tesar', cityId: CITY, address: 'Lannova třída 4567/56, České Budějovice', description: `Krovy Boháč je tesař v ${CN} specializující se na výstavbu nových krovů a rekonstrukce střešních konstrukcí. Tesař ${CA} realizuje dřevostavby a střešní práce pro rodinné domy.`, picturePath: null, active: true },
  { fullName: 'Tesař Vondrák České Budějovice', phone: '+420 728 234 780', email: 'vondrak@tesarcb.cz', serviceId: 'tesar', cityId: CITY, address: 'Nové Vráto 5678/71, České Budějovice', description: `Josef Vondrák je zkušený tesař v ${CN} provádějící veškeré tesařské práce od krovů po dřevěné terasy a altány. Tesař ${CA} nabízí montáž schodišť a přístřešků.`, picturePath: null, active: true },
  { fullName: 'Dřevostavby Pospíšil České Budějovice', phone: '+420 387 667 890', email: 'pospisil@drevostavby-cb.cz', serviceId: 'tesar', cityId: CITY, address: 'F. A. Gerstnera 6789/84, České Budějovice', description: `Dřevostavby Pospíšil je tesař a dřevostavitel v ${CN} nabízející výstavbu dřevěných domků a krovů. Tesař ${CA} realizuje zakázkové tesařské práce v celém Jihočeském kraji.`, picturePath: null, active: true },

  // ── TRUHLÁŘ ──────────────────────────────────────────────────────────────
  { fullName: 'Truhlářství Fišer České Budějovice', phone: '+420 387 335 660', email: 'fiser@truhlar-cb.cz', serviceId: 'truhlar', cityId: CITY, address: 'Piaristické náměstí 3456/49, České Budějovice', description: `Truhlářství Fišer vyrábí nábytek, dveře a kuchyně na zakázku v ${CN}. Truhlář ${CA} se specializuje na výrobu kuchyňských linek, skříní a dřevěných interiérů.`, picturePath: null, active: true },
  { fullName: 'Zakázkové truhlářství Tůma České Budějovice', phone: '+420 602 334 560', email: null, serviceId: 'truhlar', cityId: CITY, address: 'Rudolfovská třída 4567/55, České Budějovice', description: `Zakázkové truhlářství Tůma vyrábí nábytek a dřevěné interiéry na míru v ${CN}. Truhlář ${CA} nabízí výrobu postelí, stolů a zabudovaných systémů pro domy i byty.`, picturePath: null, active: true },
  { fullName: 'Truhlář Kratochvíl České Budějovice', phone: '+420 728 441 560', email: 'kratochvil@truhlarnacb.cz', serviceId: 'truhlar', cityId: CITY, address: 'Lannova třída 5678/67, České Budějovice', description: `Tomáš Kratochvíl je truhlář ${CA} s 17 lety zkušeností ve výrobě dřevěného nábytku a vestavěných skříní. Truhlářství v ${CN} realizuje dřevěné interiéry na klíč.`, picturePath: null, active: true },
  { fullName: 'Nábytek Šimon – truhlář České Budějovice', phone: '+420 387 678 345', email: 'simon@nabytek-cb.cz', serviceId: 'truhlar', cityId: CITY, address: 'Nové Vráto 6789/81, České Budějovice', description: `Dílna Šimon je truhlář a výrobce nábytku v ${CN} nabízející zakázkovou výrobu dřevěných prvků pro byty, domy a kanceláře. Truhlář ${CA} zajistí výrobu a montáž nábytku přímo u zákazníka.`, picturePath: null, active: true },

  // ── ZEDNÍK ───────────────────────────────────────────────────────────────
  { fullName: 'Zednictví Procházka České Budějovice', phone: '+420 387 229 340', email: 'prochazka@zednik-cb.cz', serviceId: 'zednik', cityId: CITY, address: 'F. A. Gerstnera 4567/55, České Budějovice', description: `Zednictví Procházka nabízí kompletní zednické práce v ${CN} – příčky, omítky, obklady a rekonstrukce bytů. Zedník ${CA} realizuje stavební práce pro rodinné domy i bytové jednotky.`, picturePath: null, active: true },
  { fullName: 'Stavební práce Boháč České Budějovice', phone: '+420 603 456 780', email: null, serviceId: 'zednik', cityId: CITY, address: 'Piaristické náměstí 5678/69, České Budějovice', description: `Stavební práce Boháč provádí zednické práce, obklady a dlažby v ${CN} a okolí. Zedník ${CA} zajistí renovaci koupelen, pokládku dlažby a veškeré rekonstrukční práce.`, picturePath: null, active: true },
  { fullName: 'Zedník Kovář České Budějovice', phone: '+420 728 223 456', email: 'kovar@zednik-cb.cz', serviceId: 'zednik', cityId: CITY, address: 'Rudolfovská třída 6789/87, České Budějovice', description: `Ladislav Kovář je zkušený zedník v ${CN} provádějící omítky, zdění příček a rekonstrukce bytů. Zedník ${CA} nabízí kompletní stavební práce od základů po finální úpravy povrchů.`, picturePath: null, active: true },
  { fullName: 'Stavební firma Šustr České Budějovice', phone: '+420 387 112 890', email: 'sustr@stav-cb.cz', serviceId: 'zednik', cityId: CITY, address: 'Lannova třída 7890/101, České Budějovice', description: `Stavební firma Šustr nabízí kompletní zednické a stavební práce v ${CN}. Zedník ${CA} realizuje zdění, betonáže, stropy a příčky pro soukromé i firemní zákazníky.`, picturePath: null, active: true },

  // ── KLEMPÍŘ ──────────────────────────────────────────────────────────────
  { fullName: 'Klempířství Matoušek České Budějovice', phone: '+420 387 120 780', email: 'matousek@klempir-cb.cz', serviceId: 'klempir', cityId: CITY, address: 'Nové Vráto 4567/51, České Budějovice', description: `Klempířství Matoušek nabízí kompletní klempířské a pokrývačské práce v ${CN} – oplechování střech, parapety a okapy. Klempíř ${CA} provádí montáž a opravy střech.`, picturePath: null, active: true },
  { fullName: 'Střechy Pok České Budějovice', phone: '+420 603 667 560', email: null, serviceId: 'klempir', cityId: CITY, address: 'F. A. Gerstnera 5678/71, České Budějovice', description: `Střechy Pok je klempíř a pokrývač v ${CN} se zaměřením na pokládku střešní krytiny a klempířské práce. Klempíř ${CA} poskytuje záruky na veškeré provedené práce.`, picturePath: null, active: true },
  { fullName: 'Klempíř Mrázek České Budějovice', phone: '+420 728 890 234', email: 'mrazek@klempir-cb.cz', serviceId: 'klempir', cityId: CITY, address: 'Piaristické náměstí 6789/85, České Budějovice', description: `Karel Mrázek je klempíř ${CA} s 20 lety zkušeností s montáží okapů, oplechováním komínů a opravami střech. Klempíř v ${CN} zajistí kvalitní klempířské práce za přijatelné ceny.`, picturePath: null, active: true },
  { fullName: 'Klempíř Vondrák České Budějovice', phone: '+420 387 334 890', email: 'vondrak@klempir-cb.cz', serviceId: 'klempir', cityId: CITY, address: 'Rudolfovská třída 7890/99, České Budějovice', description: `Roman Vondrák je klempíř v ${CN} nabízející opravy střech, oplechování říms a montáž venkovních žaluzií. Klempíř ${CA} pracuje s pozinkovaným, titanzinkovým i měděným plechem.`, picturePath: null, active: true },

  // ── AUTOSERVIS ───────────────────────────────────────────────────────────
  { fullName: 'Autoservis Kubát České Budějovice', phone: '+420 387 252 900', email: 'info@autoservis-kubat.cz', serviceId: 'autoservis', cityId: CITY, address: 'Průmyslová 1234/15, České Budějovice', description: `Autoservis Kubát nabízí komplexní opravy a servis vozidel všech značek v ${CN}. Autoservis ${CA} zajistí pravidelné prohlídky, výměnu oleje, brzd a diagnostiku pro zákazníky z Jihočeského kraje.`, picturePath: null, active: true },
  { fullName: 'Car Service České Budějovice – Tůma', phone: '+420 603 334 780', email: 'tuma@carservice-cb.cz', serviceId: 'autoservis', cityId: CITY, address: 'Lannova třída 2345/28, České Budějovice', description: `Car Service Tůma je autoservis v ${CN} zaměřený na opravy motorů, převodovek a klimatizací. Autoservis ${CA} provádí STK přípravu a komplexní servis osobních i užitkových vozidel.`, picturePath: null, active: true },
  { fullName: 'Auto Šimon – servis České Budějovice', phone: '+420 387 339 127', email: null, serviceId: 'autoservis', cityId: CITY, address: 'Nové Vráto 3456/43, České Budějovice', description: `Auto Šimon je rodinný autoservis v ${CN} s tradicí přes 20 let, specializující se na osobní vozy a dodávky. Autoservis ${CA} nabízí pneuservis, geometrii náprav a karosářské práce.`, picturePath: null, active: true },
  { fullName: 'Autoservis Boháč České Budějovice', phone: '+420 728 667 234', email: 'bohac@autocb.cz', serviceId: 'autoservis', cityId: CITY, address: 'F. A. Gerstnera 4567/57, České Budějovice', description: `Autoservis Boháč je certifikovaný servis v ${CN} pro osobní i užitková vozidla. Autoservis ${CA} zajistí diagnostiku závad, opravy elektroniky a pravidelnou údržbu vozidel.`, picturePath: null, active: true },

  // ── IT TECHNIK ───────────────────────────────────────────────────────────
  { fullName: 'PC Servis České Budějovice – Kratochvíl', phone: '+420 387 241 801', email: 'kratochvil@pc-cb.cz', serviceId: 'it-technik', cityId: CITY, address: 'Lannova třída 1234/20, České Budějovice', description: `PC Servis Kratochvíl je IT technik v ${CN} nabízející opravy počítačů, notebooků a tiskáren pro firmy i domácnosti. IT technik ${CA} zajistí instalaci systémů, obnovu dat a správu sítí.`, picturePath: null, active: true },
  { fullName: 'IT pohotovost České Budějovice – Fišer', phone: '+420 603 778 560', email: 'fiser@it-cb.cz', serviceId: 'it-technik', cityId: CITY, address: 'Piaristické náměstí 2345/31, České Budějovice', description: `IT pohotovost Fišer je zkušený IT technik ${CA} s 16 lety praxe v opravách PC a správě IT infrastruktury. Nabízí nonstop IT pohotovost a vzdálenou správu počítačů v ${CN}.`, picturePath: null, active: true },
  { fullName: 'Comtech České Budějovice', phone: '+420 387 100 700', email: 'info@comtech-cb.cz', serviceId: 'it-technik', cityId: CITY, address: 'Rudolfovská třída 3456/39, České Budějovice', description: `Comtech je profesionální IT servis v ${CN} zaměřený na opravy počítačů, datové zálohy a kybernetickou bezpečnost. IT technik ${CA} poskytuje komplexní ICT podporu pro firmy.`, picturePath: null, active: true },
  { fullName: 'Počítačový servis Vondrák České Budějovice', phone: '+420 728 445 890', email: null, serviceId: 'it-technik', cityId: CITY, address: 'Nové Vráto 4567/59, České Budějovice', description: `Počítačový servis Vondrák nabízí opravy a upgrade PC a notebooků v ${CN} za dostupné ceny. IT technik ${CA} zajistí reinstalaci systémů, odstranění virů a nastavení Wi-Fi sítí.`, picturePath: null, active: true },

  // ── FOTOGRAF ─────────────────────────────────────────────────────────────
  { fullName: 'Foto Studio Kratochvílová České Budějovice', phone: '+420 603 447 882', email: 'info@fotocb.cz', serviceId: 'fotograf', cityId: CITY, address: 'F. A. Gerstnera 5678/71, České Budějovice', description: `Foto Studio Kratochvílová je profesionální fotografka v ${CN} se zaměřením na rodinné, těhotenské a newborn fotografie. Fotograf ${CA} nabízí moderní fotografické studio a venkovní focení.`, picturePath: null, active: true },
  { fullName: 'Reportážní fotograf Matoušek České Budějovice', phone: '+420 387 108 540', email: 'matousek@foto-cb.cz', serviceId: 'fotograf', cityId: CITY, address: 'Lannova třída 6789/87, České Budějovice', description: `Michal Matoušek je reportážní a reklamní fotograf v ${CN} s 13 lety zkušeností. Fotograf ${CA} nabízí firemní fotografii, produktové focení a reportáže z akcí v Jihočeském kraji.`, picturePath: null, active: true },
  { fullName: 'Svatební fotograf Kubát České Budějovice', phone: '+420 728 112 901', email: 'kubat@svatebnifoto-cb.cz', serviceId: 'fotograf', cityId: CITY, address: 'Nové Vráto 7890/101, České Budějovice', description: `Tomáš Kubát je svatební fotograf v ${CN} specializující se na svatební reportáže a portrétní fotografii. Fotograf ${CA} zachytí každý vzácný okamžik vašeho dne.`, picturePath: null, active: true },
  { fullName: 'FotoArt České Budějovice – Pávková', phone: '+420 387 334 120', email: 'pavkova@fotoart-cb.cz', serviceId: 'fotograf', cityId: CITY, address: 'Piaristické náměstí 8901/115, České Budějovice', description: `FotoArt Pávková je fotografka v ${CN} nabízející portréty, rodinnou a těhotenskou fotografii ve studiu i exteriéru. Fotograf ${CA} klade důraz na přirozené zachycení emocí.`, picturePath: null, active: true },

  // ── UČITEL / LEKTOR ──────────────────────────────────────────────────────
  { fullName: 'Jazyková škola Sigma České Budějovice', phone: '+420 387 220 712', email: 'cb@sigma-jazyky.cz', serviceId: 'ucitel', cityId: CITY, address: 'Lannova třída 1345/22, České Budějovice', description: `Jazyková škola Sigma nabízí kurzy angličtiny, němčiny a španělštiny v ${CN} pro děti i dospělé. Zkušení lektoři v ${CA} zajistí efektivní výuku jazyků a přípravu na mezinárodní certifikáty.`, picturePath: null, active: true },
  { fullName: 'Jazykové centrum České Budějovice', phone: '+420 387 220 780', email: 'info@jazykove-centrum-cb.cz', serviceId: 'ucitel', cityId: CITY, address: 'Rudolfovská třída 1345/23, České Budějovice', description: `Jazykové centrum ${CA} nabízí firemní i individuální kurzy angličtiny, němčiny a francouzštiny. Lektor ${CA} zajistí výuku na míru přímo ve firmě nebo v moderních učebnách.`, picturePath: null, active: true },
  { fullName: 'Doučování České Budějovice – Mgr. Tůmová', phone: '+420 728 441 560', email: null, serviceId: 'ucitel', cityId: CITY, address: 'Nové Vráto 2345/25, České Budějovice', description: `Mgr. Tůmová je zkušená lektorka nabízející doučování matematiky, angličtiny a přírodopisu v ${CN}. Lektor ${CA} zajistí individuální přístup k žákům základních a středních škol.`, picturePath: null, active: true },
  { fullName: 'Bc. Šustr – lektor angličtiny České Budějovice', phone: '+420 603 334 780', email: 'sustr@lektor-cb.cz', serviceId: 'ucitel', cityId: CITY, address: 'F. A. Gerstnera 3456/43, České Budějovice', description: `Bc. Šustr je certifikovaný lektor angličtiny v ${CN} s 10 lety praxe ve výuce dospělých a firemní klientely. Lektor ${CA} nabízí individuální i skupinové kurzy na všech úrovních znalostí.`, picturePath: null, active: true },

  // ── RESTAURACE ───────────────────────────────────────────────────────────
  { fullName: 'Restaurace Budvarka České Budějovice', phone: '+420 387 229 287', email: 'info@budvarka-cb.cz', serviceId: 'restaurace', cityId: CITY, address: 'náměstí Přemysla Otakara II. 23, České Budějovice', description: `Restaurace Budvarka je tradiční česká restaurace v centru ${CN} nabízející českou a jihočeskou kuchyni. Restaurace ${CA} je oblíbená mezi místními i turisty pro příjemnou atmosféru a čerstvé Budvar pivo.`, picturePath: null, active: true },
  { fullName: 'Jihočeská restaurace U Šimka České Budějovice', phone: '+420 387 220 522', email: 'usikmka@restaurace-cb.cz', serviceId: 'restaurace', cityId: CITY, address: 'Lannova třída 14, České Budějovice', description: `Jihočeská restaurace U Šimka nabízí autentickou jihočeskou kuchyni v ${CN}. Restaurace ${CA} se specializuje na pečené vepřové, kachnu a tradiční jihočeské speciality.`, picturePath: null, active: true },
  { fullName: 'Restaurace Masné Krámy České Budějovice', phone: '+420 603 334 456', email: null, serviceId: 'restaurace', cityId: CITY, address: 'Krajinská 13, České Budějovice', description: `Restaurace Masné Krámy je oblíbená restaurace v ${CN} nabízející denní menu a jihočeskou kuchyni. Restaurace ${CA} láká místní i turisty na domácí jídla z čerstvých surovin.`, picturePath: null, active: true },
  { fullName: 'Pivnice U Budvara České Budějovice', phone: '+420 387 345 678', email: 'info@pivnice-budvar.cz', serviceId: 'restaurace', cityId: CITY, address: 'U Budvary 42, České Budějovice', description: `Pivnice U Budvara je tradiční hospoda v ${CN} s autentickým prostředím a poctivou českou kuchyní. Restaurace ${CA} nabízí guláš, řízek a Budvar přímo ze sudů.`, picturePath: null, active: true },

  // ── ZUBAŘ ────────────────────────────────────────────────────────────────
  { fullName: 'MDDr. Kratochvílová – zubní ordinace České Budějovice', phone: '+420 387 110 890', email: 'kratochvilova@zubar-cb.cz', serviceId: 'zubar', cityId: CITY, address: 'Lannova třída 2234/32, České Budějovice', description: `MDDr. Kratochvílová provozuje zubní ordinaci v ${CN} nabízející kompletní stomatologickou péči pro děti i dospělé. Zubař ${CA} zajistí ošetření zubů, bělení a ortodontické poradenství.`, picturePath: null, active: true },
  { fullName: 'Stomatologie Kubát České Budějovice', phone: '+420 387 224 177', email: 'kubat@stom-cb.cz', serviceId: 'zubar', cityId: CITY, address: 'Rudolfovská třída 3456/43, České Budějovice', description: `Stomatologie Kubát je zubní ordinace v ${CN} zaměřená na estetickou stomatologii, implantáty a dentální hygienu. Zubař ${CA} přijímá nové pacienty a nabízí individuální přístup.`, picturePath: null, active: true },
  { fullName: 'Zubní ordinace Fišer České Budějovice', phone: '+420 387 128 901', email: null, serviceId: 'zubar', cityId: CITY, address: 'Nové Vráto 4567/49, České Budějovice', description: `MUDr. Fišer provozuje zubní ordinaci v ${CN} s komplexními stomatologickými službami včetně chirurgie a protetiky. Zubař ${CA} zajistí odbornou péči o chrup v příjemném prostředí.`, picturePath: null, active: true },
  { fullName: 'Dentální centrum České Budějovice', phone: '+420 387 901 234', email: 'info@dental-cb.cz', serviceId: 'zubar', cityId: CITY, address: 'F. A. Gerstnera 5678/73, České Budějovice', description: `Dentální centrum ${CA} je moderní zubní klinika nabízející komplexní péči od prevence po implantologii. Zubař ${CA} nabídne bezbolestné ošetření, ortodoncii a dentální hygienu pro celou rodinu.`, picturePath: null, active: true },

  // ── LÉKAŘ ────────────────────────────────────────────────────────────────
  { fullName: 'MUDr. Mrázková – praktická lékařka České Budějovice', phone: '+420 387 110 455', email: 'mrazkova@lekar-cb.cz', serviceId: 'lekar', cityId: CITY, address: 'Lannova třída 2234/29, České Budějovice', description: `MUDr. Mrázková je praktická lékařka v ${CN} s komplexní zdravotní péčí pro dospělé. Lékař ${CA} přijímá nové pacienty a zajistí pravidelné prohlídky a vydávání receptů.`, picturePath: null, active: true },
  { fullName: 'MUDr. Šimánek – internista České Budějovice', phone: '+420 387 261 233', email: 'simanek@interna-cb.cz', serviceId: 'lekar', cityId: CITY, address: 'Piaristické náměstí 3345/43, České Budějovice', description: `MUDr. Šimánek je internista v ${CN} specializující se na diagnostiku a léčbu interních onemocnění. Lékař ${CA} nabídne odborné vyšetření a individuální léčebný plán.`, picturePath: null, active: true },
  { fullName: 'Poliklinika České Budějovice – zdravotní centrum', phone: '+420 387 103 111', email: 'info@poliklinika-cb.cz', serviceId: 'lekar', cityId: CITY, address: 'B. Němcové 54/3, České Budějovice', description: `Poliklinika ${CA} je zdravotní centrum s širokým spektrem praktických a odborných lékařů. Lékař ${CA} nabízí komplexní zdravotní péči pro obyvatele ${CN} a Jihočeského kraje.`, picturePath: null, active: true },
  { fullName: 'MUDr. Vondrák – pediatr České Budějovice', phone: '+420 387 118 766', email: null, serviceId: 'lekar', cityId: CITY, address: 'Nové Vráto 4567/57, České Budějovice', description: `MUDr. Vondrák je dětský lékař – pediatr v ${CN} pečující o zdravý vývoj dětí od narození. Lékař ${CA} poskytuje preventivní prohlídky, očkování a léčbu dětských nemocí.`, picturePath: null, active: true },

  // ── PSYCHOLOG ─────────────────────────────────────────────────────────────
  { fullName: 'PhDr. Kubátová – psycholog České Budějovice', phone: '+420 387 243 210', email: 'kubatova@psycholog-cb.cz', serviceId: 'psycholog', cityId: CITY, address: 'Lannova třída 3456/51, České Budějovice', description: `PhDr. Kubátová je psycholog v ${CN} nabízející individuální psychoterapii, párové poradenství a krizovou intervenci. Psycholog ${CA} pomáhá klientům zvládat úzkosti, deprese a životní krize.`, picturePath: null, active: true },
  { fullName: 'Mgr. Fišer – psychoterapeut České Budějovice', phone: '+420 603 234 341', email: 'fiser@terapie-cb.cz', serviceId: 'psycholog', cityId: CITY, address: 'Rudolfovská třída 4456/57, České Budějovice', description: `Mgr. Fišer je psychoterapeut v ${CN} s výcvikem v kognitivně-behaviorální terapii. Psycholog ${CA} nabízí individuální, párovou a skupinovou terapii pro dospělé i adolescenty.`, picturePath: null, active: true },
  { fullName: 'Centrum psychologické pomoci České Budějovice', phone: '+420 387 989 123', email: 'info@cpp-cb.cz', serviceId: 'psycholog', cityId: CITY, address: 'Nové Vráto 5678/63, České Budějovice', description: `Centrum psychologické pomoci ${CA} je poradenské centrum s týmem zkušených psychologů. Psycholog ${CA} nabízí diagnostiku, poradenství a terapii pro děti, dospělé i rodiny.`, picturePath: null, active: true },
  { fullName: 'Mgr. Šustrová – terapeutka České Budějovice', phone: '+420 728 345 123', email: null, serviceId: 'psycholog', cityId: CITY, address: 'F. A. Gerstnera 6789/87, České Budějovice', description: `Mgr. Šustrová je psycholožka a terapeutka v ${CN} specializující se na práci s traumatem a úzkostí. Psycholog ${CA} pracuje s dospělými i dětmi metodou EMDR a systemické terapie.`, picturePath: null, active: true },

  // ── PRÁVNÍK ──────────────────────────────────────────────────────────────
  { fullName: 'JUDr. Kratochvíl – advokát České Budějovice', phone: '+420 387 122 891', email: 'kratochvil@advokatcb.cz', serviceId: 'pravnik', cityId: CITY, address: 'náměstí Přemysla Otakara II. 36, České Budějovice', description: `JUDr. Kratochvíl je advokát v ${CN} zaměřený na občanské, obchodní a rodinné právo. Právník ${CA} nabízí právní poradenství, sepis smluv a zastupování klientů před soudy v Jihočeském kraji.`, picturePath: null, active: true },
  { fullName: 'Advokátní kancelář Tůma České Budějovice', phone: '+420 387 310 067', email: 'tuma@ak-cb.cz', serviceId: 'pravnik', cityId: CITY, address: 'Lannova třída 1122/16, České Budějovice', description: `Advokátní kancelář Tůma je právní firma v ${CN} specializující se na pracovní právo, nemovitosti a obchodní spory. Právník ${CA} zajistí komplexní právní zastoupení.`, picturePath: null, active: true },
  { fullName: 'JUDr. Vondrák – notář České Budějovice', phone: '+420 387 228 445', email: 'vondrak@notar-cb.cz', serviceId: 'pravnik', cityId: CITY, address: 'Rudolfovská třída 1234/19, České Budějovice', description: `JUDr. Vondrák je notář a právník v ${CN} zajišťující sepisování závětí, kupních smluv a ověřování podpisů. Právník ${CA} poskytuje notářské a právní služby pro fyzické i právnické osoby.`, picturePath: null, active: true },
  { fullName: 'Mgr. Pávková – rodinné právo České Budějovice', phone: '+420 728 220 789', email: null, serviceId: 'pravnik', cityId: CITY, address: 'Nové Vráto 2345/27, České Budějovice', description: `Mgr. Pávková je právnička v ${CN} specializující se na rodinné právo, rozvody a opatrovnická řízení. Právník ${CA} nabídne empatické a profesionální zastupování v soudních sporech.`, picturePath: null, active: true },

  // ── ÚČETNÍ ───────────────────────────────────────────────────────────────
  { fullName: 'Účetní poradenství Kubátová České Budějovice', phone: '+420 387 243 210', email: 'kubatova@ucetni-cb.cz', serviceId: 'ucetni', cityId: CITY, address: 'F. A. Gerstnera 3456/43, České Budějovice', description: `Účetní poradenství Kubátová nabízí vedení účetnictví, daňové přiznání a mzdovou agendu pro firmy v ${CN}. Účetní ${CA} poskytuje kompletní ekonomické poradenství pro OSVČ i právnické osoby.`, picturePath: null, active: true },
  { fullName: 'ECO Consulting České Budějovice', phone: '+420 387 421 800', email: 'info@eco-consulting-cb.cz', serviceId: 'ucetni', cityId: CITY, address: 'Piaristické náměstí 4567/57, České Budějovice', description: `ECO Consulting je účetní firma v ${CN} specializující se na podvojné účetnictví, DPH a daňovou optimalizaci. Účetní ${CA} zajistí přesné zpracování daňových přiznání a roční závěrky.`, picturePath: null, active: true },
  { fullName: 'Bc. Šustrová – účetní a mzdy České Budějovice', phone: '+420 728 334 456', email: 'sustrova@ucetni-mzdy-cb.cz', serviceId: 'ucetni', cityId: CITY, address: 'Lannova třída 5678/73, České Budějovice', description: `Bc. Šustrová je účetní v ${CN} se specializací na zpracování mezd, daňové přiznání a vedení daňové evidence. Účetní ${CA} nabízí přesné a spolehlivé zpracování dokladů pro malé a střední firmy.`, picturePath: null, active: true },
  { fullName: 'AUDIT ČESKÉ BUDĚJOVICE – účetní kancelář', phone: '+420 603 457 890', email: 'audit@uc-cb.cz', serviceId: 'ucetni', cityId: CITY, address: 'Rudolfovská třída 6789/85, České Budějovice', description: `AUDIT ${CA.toUpperCase()} je účetní kancelář v ${CN} nabízející komplexní ekonomické a daňové poradenství pro podnikatele. Účetní ${CA} zpracuje daňová přiznání a roční závěrky i pro zahraniční firmy.`, picturePath: null, active: true },

  // ── KADEŘNÍK ─────────────────────────────────────────────────────────────
  { fullName: 'Kadeřnictví Kratochvílová České Budějovice', phone: '+420 387 111 345', email: null, serviceId: 'kadernik', cityId: CITY, address: 'Lannova třída 2345/37, České Budějovice', description: `Kadeřnictví Kratochvílová nabízí střihy, barvení a styling vlasů pro ženy i muže v ${CN}. Kadeřník ${CA} pracuje s prémiovou kosmetikou a zajistí individuální poradenství.`, picturePath: null, active: true },
  { fullName: 'Salon Petra – kadeřnictví České Budějovice', phone: '+420 387 258 900', email: 'petra@salon-cb.cz', serviceId: 'kadernik', cityId: CITY, address: 'Rudolfovská třída 2345/33, České Budějovice', description: `Salon Petra je moderní kadeřnický salon v ${CN} se zkušenými stylisty. Kadeřník ${CA} nabízí barvení, melír, keratin a svatební účesy v příjemném salonu.`, picturePath: null, active: true },
  { fullName: 'Kadeřnictví Vondrák České Budějovice', phone: '+420 728 445 789', email: null, serviceId: 'kadernik', cityId: CITY, address: 'Nové Vráto 3456/39, České Budějovice', description: `Kadeřnictví Vondrák je rodinný salon v ${CN} nabízející kompletní kadeřnické služby – střihy, barvení a rekonstrukce vlasů. Kadeřník ${CA} zajistí péči o vlasy v přátelské atmosféře.`, picturePath: null, active: true },
  { fullName: 'Studio Atelier – kadeřnictví České Budějovice', phone: '+420 387 235 678', email: 'atelier@kadernictvi-cb.cz', serviceId: 'kadernik', cityId: CITY, address: 'F. A. Gerstnera 4567/57, České Budějovice', description: `Studio Atelier je prémiové kadeřnické studio v ${CN} zaměřené na moderní trendy v barvení a stylingu vlasů. Kadeřník ${CA} nabízí konzultace, střihy a speciální ošetření vlasů.`, picturePath: null, active: true },

  // ── ARCHITEKT ────────────────────────────────────────────────────────────
  { fullName: 'Ing. arch. Kratochvíl – architekt České Budějovice', phone: '+420 387 422 780', email: 'kratochvil@architektcb.cz', serviceId: 'architekt', cityId: CITY, address: 'náměstí Přemysla Otakara II. 44, České Budějovice', description: `Ing. arch. Kratochvíl je architekt v ${CN} nabízející projektování rodinných domů a bytových rekonstrukcí. Architekt ${CA} navrhuje funkční a estetická řešení s důrazem na nízkoenergetické standardy.`, picturePath: null, active: true },
  { fullName: 'Ateliér JIH – architekti České Budějovice', phone: + '420 387 534 122', email: 'info@atelierjib.cz', serviceId: 'architekt', cityId: CITY, address: 'Lannova třída 2345/36, České Budějovice', description: `Ateliér JIH je architektonické studio v ${CN} s portfoliem rezidenčních, komerčních a veřejných staveb. Architekt ${CA} nabídne kompletní projektové služby od studie po realizaci.`, picturePath: null, active: true },
  { fullName: 'Ing. arch. Tůmová – interiéry České Budějovice', phone: '+420 728 882 445', email: 'tumova@interier-cb.cz', serviceId: 'architekt', cityId: CITY, address: 'Rudolfovská třída 3456/45, České Budějovice', description: `Ing. arch. Tůmová je architektka a interiérová designérka v ${CN} zaměřená na návrhy interiérů bytů a kanceláří. Architekt ${CA} navrhuje prostory s ohledem na funkčnost a přání klienta.`, picturePath: null, active: true },
  { fullName: 'STUDIO BUDĚJOVICE – architekti', phone: '+420 387 620 110', email: 'info@studio-budejovice.cz', serviceId: 'architekt', cityId: CITY, address: 'Nové Vráto 4567/51, České Budějovice', description: `STUDIO BUDĚJOVICE je architektonická kancelář v ${CN} realizující rodinné domy, rekonstrukce a urbanistické projekty. Architekt ${CA} zajistí projekt od konceptu přes povolení až po dozor na stavbě.`, picturePath: null, active: true },

  // ── REALITNÍ MAKLÉŘ ──────────────────────────────────────────────────────
  { fullName: 'RE/MAX České Budějovice – realitní kancelář', phone: '+420 387 244 555', email: 'remax@remax-cb.cz', serviceId: 'realitni-makler', cityId: CITY, address: 'náměstí Přemysla Otakara II. 55, České Budějovice', description: `RE/MAX ${CA} je realitní kancelář s týmem zkušených makléřů pro prodej a pronájem bytů a domů v ${CN}. Realitní makléř ${CA} zajistí odborné ocenění nemovitosti a efektivní marketing.`, picturePath: null, active: true },
  { fullName: 'Realitní kancelář Kratochvíl České Budějovice', phone: '+420 387 310 700', email: 'kratochvil@rk-cb.cz', serviceId: 'realitni-makler', cityId: CITY, address: 'Lannova třída 3456/49, České Budějovice', description: `Realitní kancelář Kratochvíl je zavedená realitní firma v ${CN} s 13 lety zkušeností na trhu s nemovitostmi. Realitní makléř ${CA} pomůže s koupí, prodejem i pronájmem nemovitostí v Jihočeském kraji.`, picturePath: null, active: true },
  { fullName: 'STING realitní České Budějovice', phone: '+420 728 888 341', email: 'info@sting-reality-cb.cz', serviceId: 'realitni-makler', cityId: CITY, address: 'Rudolfovská třída 4567/57, České Budějovice', description: `STING realitní je dynamická realitní kancelář v ${CN} zaměřená na prodej bytů a domů. Realitní makléř ${CA} nabídne profesionální fotografii, 3D prohlídky a právní servis.`, picturePath: null, active: true },
  { fullName: 'Reality Vondrák České Budějovice', phone: '+420 603 003 789', email: null, serviceId: 'realitni-makler', cityId: CITY, address: 'Nové Vráto 5678/65, České Budějovice', description: `Reality Vondrák je realitní makléř v ${CN} specializující se na rezidenční nemovitosti. Makléř ${CA} nabídne individuální přístup a kompletní administrativní servis při prodeji i nákupu bytu.`, picturePath: null, active: true },

  // ── ZAHRADNÍK ────────────────────────────────────────────────────────────
  { fullName: 'Zahradnictví Kratochvíl České Budějovice', phone: '+420 728 334 780', email: 'kratochvil@zahradnictvi-cb.cz', serviceId: 'zahradnik', cityId: CITY, address: 'Průmyslová 2345/28, České Budějovice', description: `Zahradnictví Kratochvíl nabízí kompletní zahradnické práce v ${CN} – sekání trávníků, výsadbu rostlin a zakládání zahrad. Zahradník ${CA} zajistí pravidelnou údržbu zahrady pro soukromníky i firmy.`, picturePath: null, active: true },
  { fullName: 'Green Garden České Budějovice', phone: '+420 387 456 234', email: 'info@greengarden-cb.cz', serviceId: 'zahradnik', cityId: CITY, address: 'Nové Vráto 3456/43, České Budějovice', description: `Green Garden je zahradní firma v ${CN} nabízející návrhy a realizaci zahrad a teras. Zahradník ${CA} provede kompletní terénní úpravy, automatické zavlažování a instalaci zahradních prvků.`, picturePath: null, active: true },
  { fullName: 'Zahradní úpravy Šimon České Budějovice', phone: '+420 728 441 780', email: null, serviceId: 'zahradnik', cityId: CITY, address: 'F. A. Gerstnera 4567/59, České Budějovice', description: `Zahradní úpravy Šimon je zahradník v ${CN} zajišťující terénní úpravy, výsadbu stromů a sezónní péči o zahrady. Zahradník ${CA} nabídne osobní poradenství a realizaci zahradních projektů.`, picturePath: null, active: true },
  { fullName: 'Arboristika České Budějovice – Tůma', phone: '+420 603 017 890', email: 'tuma@arboristika-cb.cz', serviceId: 'zahradnik', cityId: CITY, address: 'Průmyslová 5678/71, České Budějovice', description: `Arboristika Tůma nabízí profesionální péči o stromy, kácení a ošetřování dřevin v ${CN}. Zahradník ${CA} provede výškové práce, redukci korun a odborné posudky zdraví stromů.`, picturePath: null, active: true },

  // ── ÚKLID ────────────────────────────────────────────────────────────────
  { fullName: 'Čistota České Budějovice – úklidová firma', phone: '+420 387 890 234', email: 'info@cistota-cb.cz', serviceId: 'uklid', cityId: CITY, address: 'Lannova třída 4567/63, České Budějovice', description: `Čistota ${CA} je profesionální úklidová firma nabízející pravidelný i jednorázový úklid bytů a kanceláří v ${CN}. Úklid ${CA} zajistí čisté prostředí s ekologickými čisticími prostředky.`, picturePath: null, active: true },
  { fullName: 'CleanPro České Budějovice', phone: '+420 603 778 901', email: 'cleanpro@uklid-cb.cz', serviceId: 'uklid', cityId: CITY, address: 'Rudolfovská třída 5678/73, České Budějovice', description: `CleanPro je úklidová společnost v ${CN} specializující se na úklid po rekonstrukci a generální úklid domácností. Úklid ${CA} nabídne rychlý nástup a záruky spokojenosti.`, picturePath: null, active: true },
  { fullName: 'Paní na úklid České Budějovice – Kratochvílová', phone: '+420 728 456 789', email: null, serviceId: 'uklid', cityId: CITY, address: 'Nové Vráto 4567/59, České Budějovice', description: `Paní Kratochvílová nabízí pravidelný domácí úklid bytů a domů v ${CN} s osobním přístupem a spolehlivostí. Úklid ${CA} – domácí pomoc pro rodiny a seniory v ${CN}.`, picturePath: null, active: true },
  { fullName: 'TopClean České Budějovice', phone: '+420 387 345 678', email: 'info@topclean-cb.cz', serviceId: 'uklid', cityId: CITY, address: 'F. A. Gerstnera 5678/75, České Budějovice', description: `TopClean je úklidová firma v ${CN} s komplexní nabídkou čistění koberců, čalounění a mytí oken. Úklid ${CA} provádí profesionální dezinfekce a sanace bytů, kanceláří i průmyslových prostor.`, picturePath: null, active: true },

  // ── STĚHOVACÍ FIRMA ──────────────────────────────────────────────────────
  { fullName: 'Stěhování České Budějovice – Kubát Transport', phone: '+420 387 334 120', email: 'kubat@stehovanicb.cz', serviceId: 'stehovaci-firma', cityId: CITY, address: 'Průmyslová 3456/43, České Budějovice', description: `Stěhování ${CA} Kubát Transport nabízí profesionální stěhování bytů, kanceláří a firem v ${CN} a celé ČR. Stěhovací firma ${CA} zajistí bezpečné zabalení, přepravu a složení nábytku.`, picturePath: null, active: true },
  { fullName: 'Fast Move České Budějovice', phone: '+420 603 791 345', email: 'info@fastmove-cb.cz', serviceId: 'stehovaci-firma', cityId: CITY, address: 'Lannova třída 5678/75, České Budějovice', description: `Fast Move je rychlá stěhovací firma v ${CN} zajišťující stěhování bytů i firem s vlastním vozovým parkem. Stěhovací firma ${CA} nabídne bezpečnostní balení, demontáž a montáž nábytku.`, picturePath: null, active: true },
  { fullName: 'Stěhování Tůma České Budějovice', phone: '+420 728 678 234', email: null, serviceId: 'stehovaci-firma', cityId: CITY, address: 'Nové Vráto 6789/89, České Budějovice', description: `Stěhování Tůma je spolehlivá stěhovací firma v ${CN} s vlastními stěhovacími vozidly a pojištěním nákladu. Stěhovací firma ${CA} realizuje stěhování po ${CN} i mezinárodní přepravu.`, picturePath: null, active: true },
  { fullName: 'Profi Stěhování České Budějovice', phone: '+420 387 234 890', email: 'profistehov@cb-move.cz', serviceId: 'stehovaci-firma', cityId: CITY, address: 'Průmyslová 4567/57, České Budějovice', description: `Profi Stěhování ${CA} je komplexní stěhovací firma pro domácnosti i firmy v Jihočeském kraji. Stěhovací firma ${CA} zajistí expresní i plánované stěhování s péčí o každý kus majetku.`, picturePath: null, active: true },

  // ── TRENÉR ───────────────────────────────────────────────────────────────
  { fullName: 'Fitness trenér Kratochvíl České Budějovice', phone: '+420 728 441 890', email: 'kratochvil@fitnes-cb.cz', serviceId: 'trener', cityId: CITY, address: 'Lannova třída 5678/79, České Budějovice', description: `Fitness trenér Kratochvíl je osobní trenér v ${CN} nabízející tréninkové plány a nutriční poradenství. Trenér ${CA} pomůže s hubnutím, nabíráním svalové hmoty a zlepšením kondice.`, picturePath: null, active: true },
  { fullName: 'Gabriela Kubátová – osobní trenérka České Budějovice', phone: '+420 387 560 234', email: 'kubatova@trener-cb.cz', serviceId: 'trener', cityId: CITY, address: 'Rudolfovská třída 5678/73, České Budějovice', description: `Gabriela Kubátová je certifikovaná osobní trenérka v ${CN} specializující se na funkční trénink a pilates. Trenér ${CA} nabídne individuální fitness program pro dosažení sportovních cílů.`, picturePath: null, active: true },
  { fullName: 'Sportovní centrum Dynamo České Budějovice', phone: '+420 387 455 666', email: 'info@dynamo-cb.cz', serviceId: 'trener', cityId: CITY, address: 'Nám. Přemysla Otakara I. 1, České Budějovice', description: `Sportovní centrum Dynamo nabízí trenéry a sportovní kurzy pro děti i dospělé v ${CN}. Trenér ${CA} zajistí kondičníkurzy, skupinové lekce jógy a fitness tréninky v moderním centru.`, picturePath: null, active: true },
  { fullName: 'Mgr. Šimon – trenér atletiky České Budějovice', phone: '+420 728 228 901', email: null, serviceId: 'trener', cityId: CITY, address: 'Nové Vráto 6789/89, České Budějovice', description: `Mgr. Šimon je trenér atletiky a kondičního tréninku v ${CN} s licencí ČAS. Trenér ${CA} pracuje s dětmi, juniory i dospělými závodníky na atletickém stadionu v ${CN}.`, picturePath: null, active: true },

  // ── PŘEKLADATEL ──────────────────────────────────────────────────────────
  { fullName: 'Překladatelské centrum České Budějovice', phone: '+420 387 441 760', email: 'info@prekladcb.cz', serviceId: 'prekladatel', cityId: CITY, address: 'náměstí Přemysla Otakara II. 64, České Budějovice', description: `Překladatelské centrum ${CA} nabízí odborné překlady z němčiny, angličtiny a dalších jazyků pro firmy i jednotlivce. Překladatel ${CA} zajistí přesné překlady smluv, technických dokumentů a úředních listin.`, picturePath: null, active: true },
  { fullName: 'Mgr. Kratochvílová – překladatelka České Budějovice', phone: '+420 728 778 450', email: 'kratochvilova@prekladcb.cz', serviceId: 'prekladatel', cityId: CITY, address: 'Lannova třída 2345/33, České Budějovice', description: `Mgr. Kratochvílová je soudní překladatelka pro němčinu a angličtinu v ${CN} s oprávněním od Krajského soudu. Překladatel ${CA} provede úřední překlady dokumentů pro státní orgány.`, picturePath: null, active: true },
  { fullName: 'ProTranslate České Budějovice', phone: '+420 387 229 112', email: 'info@protranslate-cb.cz', serviceId: 'prekladatel', cityId: CITY, address: 'Rudolfovská třída 3456/43, České Budějovice', description: `ProTranslate je překladatelská agentura v ${CN} zajišťující překlady do více než 25 jazyků pro firmy a instituce. Překladatel ${CA} nabídne expresní i standardní překlad s garancí kvality.`, picturePath: null, active: true },
  { fullName: 'Bc. Vondrák – tlumočník České Budějovice', phone: '+420 603 113 456', email: null, serviceId: 'prekladatel', cityId: CITY, address: 'Nové Vráto 3456/41, České Budějovice', description: `Bc. Vondrák je překladatel a tlumočník pro angličtinu a němčinu v ${CN}. Překladatel ${CA} nabízí konsekutivní tlumočení na konferencích, jednáních a firemních akcích.`, picturePath: null, active: true },

  // ── GRAFIK ───────────────────────────────────────────────────────────────
  { fullName: 'Grafické studio Kratochvíl České Budějovice', phone: '+420 387 450 890', email: 'kratochvil@grafika-cb.cz', serviceId: 'grafik', cityId: CITY, address: 'náměstí Přemysla Otakara II. 72, České Budějovice', description: `Grafické studio Kratochvíl nabízí komplexní grafické služby v ${CN} – loga, firemní identitu, tisk a webdesign. Grafik ${CA} zajistí profesionální vizuální komunikaci pro firmy v Jihočeském kraji.`, picturePath: null, active: true },
  { fullName: 'PixelArt České Budějovice – grafický design', phone: '+420 728 334 780', email: 'info@pixelart-cb.cz', serviceId: 'grafik', cityId: CITY, address: 'Lannova třída 4567/63, České Budějovice', description: `PixelArt ${CA} je grafické studio specializující se na digitální design, tvorbu webů a reklamní kampaně. Grafik ${CA} nabídne kreativní řešení pro marketing a branding firem.`, picturePath: null, active: true },
  { fullName: 'Bc. Pávková – grafička České Budějovice', phone: '+420 603 887 123', email: 'pavkova.grafika@cb.cz', serviceId: 'grafik', cityId: CITY, address: 'Rudolfovská třída 5678/73, České Budějovice', description: `Bc. Pávková je freelance grafička v ${CN} nabízející návrhy letáků, plakátů a obalového designu. Grafik ${CA} pracuje pro agentury i přímé klienty s rychlými dodacími lhůtami.`, picturePath: null, active: true },
  { fullName: 'Studia Kreativa České Budějovice', phone: '+420 387 556 890', email: 'studio@kreativa-cb.cz', serviceId: 'grafik', cityId: CITY, address: 'Nové Vráto 4567/51, České Budějovice', description: `Studia Kreativa je grafická agentura v ${CN} s kompletními kreativními službami – logo, web, video a sociální sítě. Grafik ${CA} pomůže firmám budovat silnou vizuální značku a efektivní online prezentaci.`, picturePath: null, active: true },
];

async function main() {
  let count = 0;
  for (const p of profiles) {
    const created = await prisma.provider.create({ data: p });
    console.log(`✓ ${created.fullName}`);
    count++;
  }
  console.log(`\nDone. Added ${count} profiles.`);
}
main().catch(console.error).finally(() => prisma.$disconnect());
