import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();
const CITY = 'praha';

const profiles = [
  // ── PSYCHOLOG ─────────────────────────────────────────────────────────────
  { fullName: 'PhDr. Markéta Horáčková – psycholog Praha', phone: '+420 777 321 456', email: 'ordinace@horáčková-psycholog.cz', serviceId: 'psycholog', cityId: CITY, address: 'Mánesova 28, Praha 2 – Vinohrady', description: 'PhDr. Markéta Horáčková je zkušená psycholožka a psychoterapeutka se soukromou ordinací v Praze 2 Vinohrady. Nabízí individuální psychoterapii, krizovou intervenci a poradenství pro dospělé klienty v Praze.', picturePath: null, active: true },
  { fullName: 'Mgr. Tomáš Kovářík – psychoterapie Praha', phone: '+420 603 112 874', email: 'tomas.kovarik@psychoterapie-praha.cz', serviceId: 'psycholog', cityId: CITY, address: 'Blanická 17, Praha 2 – Vinohrady', description: 'Mgr. Tomáš Kovářík poskytuje kognitivně-behaviorální psychoterapii a psychologické poradenství v srdci Prahy 2. Specializuje se na léčbu úzkostí, depresí a vztahových problémů u dospělých klientů v Praze.', picturePath: null, active: true },
  { fullName: 'PhDr. Jana Procházková – psycholog Praha 6', phone: '+420 724 556 009', email: 'jana.prochazkova@psycholog-dejvice.cz', serviceId: 'psycholog', cityId: CITY, address: 'Dejvická 14, Praha 6 – Dejvice', description: 'PhDr. Jana Procházková je certifikovaná psycholožka s praxí přes 15 let, ordinující v Praze 6 Dejvice. Nabízí psychoterapii pro dospělé a adolescenty, párové poradenství a koučink v Praze.', picturePath: null, active: true },
  { fullName: 'Mgr. Radek Šimůnek – psychologická poradna Praha', phone: '+420 731 004 217', email: null, serviceId: 'psycholog', cityId: CITY, address: 'Korunní 44, Praha 10 – Vinohrady', description: 'Mgr. Radek Šimůnek provozuje psychologickou poradnu v Praze 10 zaměřenou na stres, burn-out a osobnostní rozvoj. Jako psycholog Praha nabízí bezpečné a diskrétní prostředí pro terapii dospělých klientů.', picturePath: null, active: true },

  // ── PRAVNIK ───────────────────────────────────────────────────────────────
  { fullName: 'JUDr. Petra Nováková – advokátní kancelář Praha', phone: '+420 222 518 830', email: 'novakova@ak-novakova.cz', serviceId: 'pravnik', cityId: CITY, address: 'Václavské náměstí 36, Praha 1 – Nové Město', description: 'JUDr. Petra Nováková provozuje renomovanou advokátní kancelář na Václavském náměstí v Praze 1 se specializací na obchodní a pracovní právo. Advokát Praha nabízí právní poradenství, zastoupení před soudem a sepisování smluv.', picturePath: null, active: true },
  { fullName: 'Mgr. Ondřej Beneš – advokát Praha', phone: '+420 257 317 600', email: 'benes@akbenes.cz', serviceId: 'pravnik', cityId: CITY, address: 'Platnéřská 4, Praha 1 – Staré Město', description: 'Mgr. Ondřej Beneš je advokát se sídlem v historickém centru Prahy 1 specializující se na nemovitostní právo, dědictví a rodinné právo. Advokátní kancelář Praha poskytuje komplexní právní služby fyzickým i právnickým osobám.', picturePath: null, active: true },
  { fullName: 'JUDr. Ing. Miroslav Fiala – právní kancelář Praha', phone: '+420 296 188 155', email: 'fiala@pravni-kancelar-fiala.cz', serviceId: 'pravnik', cityId: CITY, address: 'Wenceslas Square 56, Praha 1', description: 'JUDr. Ing. Miroslav Fiala je zkušený advokát a daňový poradce sídlící v centru Prahy 1 s více než 20 lety praxe. Právní kancelář Praha se specializuje na obchodní spory, insolvence a corporate právo.', picturePath: null, active: true },
  { fullName: 'Mgr. Lucie Červenková – advokátka Praha', phone: '+420 734 875 321', email: 'cervenkova@advokat-smichov.cz', serviceId: 'pravnik', cityId: CITY, address: 'Nádražní 32, Praha 5 – Smíchov', description: 'Mgr. Lucie Červenková je advokátka v Praze 5 Smíchov zaměřená na rodinné právo, rozvodová řízení a péči o nezletilé. Jako právník Praha zastupuje klienty před soudy a poskytuje diskrétní právní poradenství.', picturePath: null, active: true },

  // ── UCETNI ────────────────────────────────────────────────────────────────
  { fullName: 'Ing. Hana Blažková – účetní Praha', phone: '+420 222 513 474', email: 'blazkova@ucetnictvi-blazkova.cz', serviceId: 'ucetni', cityId: CITY, address: 'Italská 12, Praha 2 – Vinohrady', description: 'Ing. Hana Blažková je certifikovaná účetní se sídlem v Praze 2 nabízející vedení účetnictví, daňové přiznání a mzdové služby. Účetní Praha poskytuje komplexní finanční poradenství pro malé a střední firmy po celé Praze.', picturePath: null, active: true },
  { fullName: 'Účetní centrum Praha s.r.o.', phone: '+420 266 710 022', email: 'info@ucetni-centrum-praha.cz', serviceId: 'ucetni', cityId: CITY, address: 'Argentinská 38, Praha 7 – Holešovice', description: 'Účetní centrum Praha s.r.o. je moderní účetní firma v Praze 7 Holešovice zajišťující daňové poradenství, vedení účetnictví a zpracování mezd. Poskytuje spolehlivé účetní a daňové služby pro podnikatele a firmy v Praze.', picturePath: null, active: true },
  { fullName: 'Ing. Karel Šulc – daňový poradce Praha', phone: '+420 602 443 991', email: 'sulc@danovy-poradce-praha.cz', serviceId: 'ucetni', cityId: CITY, address: 'Sokolovská 94, Praha 8 – Karlín', description: 'Ing. Karel Šulc je certifikovaný daňový poradce a účetní v Praze 8 Karlín se specializací na DPH, daň z příjmů a optimalizaci daňové zátěže. Nabízí účetní a daňové poradenství pro fyzické i právnické osoby v Praze.', picturePath: null, active: true },
  { fullName: 'ProAccount Praha – účetní kancelář', phone: '+420 241 471 133', email: 'info@proaccount.cz', serviceId: 'ucetni', cityId: CITY, address: 'Ohradní 65, Praha 4 – Nusle', description: 'ProAccount Praha je účetní kancelář v Praze 4 s dlouholetou tradicí vedení účetnictví, controllingu a mzdové agendy. Tým zkušených účetních Praha zajišťuje přesnou a včasnou správu financí pro firmy všech velikostí.', picturePath: null, active: true },

  // ── KADERNIK ─────────────────────────────────────────────────────────────
  { fullName: 'Salon Elixír – kadeřnictví Praha 2', phone: '+420 222 251 806', email: 'salon@elixir-kadernictvi.cz', serviceId: 'kadernik', cityId: CITY, address: 'Náměstí Míru 9, Praha 2 – Vinohrady', description: 'Salon Elixír je moderní kadeřnický salon na náměstí Míru v Praze 2 nabízející střihy, barvení a keratinové ošetření vlasů. Kadeřník Praha Vinohrady zajišťuje profesionální vlasové služby pro muže i ženy.', picturePath: null, active: true },
  { fullName: 'Hair Studio Kristýna – kadeřnictví Praha', phone: '+420 605 332 774', email: null, serviceId: 'kadernik', cityId: CITY, address: 'Štefánikova 21, Praha 5 – Smíchov', description: 'Hair Studio Kristýna je oblíbené kadeřnictví v Praze 5 Smíchov se specializací na moderní střihy, balayage a vlasové pečující procedury. Kadeřník Praha Smíchov nabízí individuální přístup a příjemnou atmosféru.', picturePath: null, active: true },
  { fullName: 'Barbershop Pánský střih Praha', phone: '+420 731 808 202', email: 'info@pansky-strih-praha.cz', serviceId: 'kadernik', cityId: CITY, address: 'Seifertova 45, Praha 3 – Žižkov', description: 'Barbershop Pánský střih je klasický holič a kadeřník pro muže v Praze 3 Žižkov s tradiční atmosférou a moderními technikami. Nabízí pánské střihy, úpravu vousů a holení v srdci Prahy.', picturePath: null, active: true },
  { fullName: 'Salon Vogue – kadeřnictví Praha 8', phone: '+420 283 842 261', email: 'vogue.salon@email.cz', serviceId: 'kadernik', cityId: CITY, address: 'Zenklova 36, Praha 8 – Libeň', description: 'Salon Vogue je profesionální kadeřnictví v Praze 8 Libeň nabízející kompletní vlasové služby od střihů po trvalé ondulace a rekonstrukci vlasů. Kadeřník Praha 8 poskytuje vlasové poradenství a moderní stylizaci pro každého.', picturePath: null, active: true },

  // ── ARCHITEKT ────────────────────────────────────────────────────────────
  { fullName: 'Ing. arch. Pavel Veselý – architektonický ateliér Praha', phone: '+420 224 236 800', email: 'vesely@ateliervesely.cz', serviceId: 'architekt', cityId: CITY, address: 'Rybná 14, Praha 1 – Staré Město', description: 'Ing. arch. Pavel Veselý je autorizovaný architekt se sídlem v Praze 1 se zaměřením na bytové interiéry, rekonstrukce a novostavby rodinných domů. Architektonický ateliér Praha nabízí komplexní projektovou dokumentaci a autorský dozor.', picturePath: null, active: true },
  { fullName: 'Ing. arch. Klára Ježková – interior design Praha', phone: '+420 736 119 043', email: 'klara.jezkova@design-praha.cz', serviceId: 'architekt', cityId: CITY, address: 'Náměstí Bratří Synků 7, Praha 4 – Nusle', description: 'Ing. arch. Klára Ježková je designérka interiérů a architektka v Praze 4 specializující se na moderní a minimalistické interiéry bytů a komerčních prostor. Architektura Praha v jejím podání spojuje estetiku s funkcionalitou a udržitelností.', picturePath: null, active: true },
  { fullName: 'Atelier D+K architekti Praha', phone: '+420 257 220 548', email: 'info@atelierdak.cz', serviceId: 'architekt', cityId: CITY, address: 'Holečkova 31, Praha 5 – Smíchov', description: 'Atelier D+K je pražský architektonický ateliér v Praze 5 Smíchov zaměřený na návrhy veřejných budov, komerčních center a rezidenčních projektů. Architekti Praha zajišťují kompletní projektovou přípravu od studie po realizaci.', picturePath: null, active: true },
  { fullName: 'Ing. arch. Martin Houser – HOUSER architekti', phone: '+420 603 808 944', email: 'houser@houser-architekti.cz', serviceId: 'architekt', cityId: CITY, address: 'Milady Horákové 57, Praha 7 – Holešovice', description: 'Ing. arch. Martin Houser vede architektonickou kancelář HOUSER architekti v Praze 7 Holešovice se specializací na rekonstrukce historických objektů a pasivní domy. Architekt Praha nabízí inovativní řešení pro náročné stavební projekty v Praze a okolí.', picturePath: null, active: true },

  // ── REALITNI-MAKLER ───────────────────────────────────────────────────────
  { fullName: 'RE/MAX Alfa – Jan Procházka Praha', phone: '+420 800 900 900', email: 'jan.prochazka@remax-alfa.cz', serviceId: 'realitni-makler', cityId: CITY, address: 'Václavské náměstí 846/1, Praha 1 – Nové Město', description: 'Jan Procházka je zkušený realitní makléř RE/MAX Alfa s kanceláří na Václavském náměstí v Praze 1 specializující se na prodej a pronájem bytů v centru Prahy. Realitní makléř Praha zajišťuje profesionální ocenění nemovitostí a bezpečný převod vlastnictví.', picturePath: null, active: true },
  { fullName: 'Century 21 – Monika Švehlová realitní makléř Praha', phone: '+420 602 888 211', email: 'svehlova@century21.cz', serviceId: 'realitni-makler', cityId: CITY, address: 'Budějovická 1, Praha 4 – Michle', description: 'Monika Švehlová je realitní makléřka Century 21 v Praze 4 zaměřená na rezidenční nemovitosti v Praze 4, 5 a 10. Realitní kancelář Praha Century 21 nabízí prodej bytů, rodinných domů a komerčních prostor s garancí kvality.', picturePath: null, active: true },
  { fullName: 'David Kratochvíl – realitní makléř Praha', phone: '+420 725 631 009', email: 'kratochvil@reality-praha.cz', serviceId: 'realitni-makler', cityId: CITY, address: 'Korunní 18, Praha 2 – Vinohrady', description: 'David Kratochvíl je nezávislý realitní makléř se sídlem v Praze 2 Vinohrady s více než 12 lety zkušeností na pražském trhu s nemovitostmi. Nabízí prodej, pronájem a správu nemovitostí v Praze s individuálním přístupem ke každému klientovi.', picturePath: null, active: true },
  { fullName: 'Svoboda & Williams – Tereza Nováčková Praha', phone: '+420 224 247 070', email: 'novackova@svoboda-williams.com', serviceId: 'realitni-makler', cityId: CITY, address: 'Klimentská 46, Praha 1 – Nové Město', description: 'Tereza Nováčková je prémiovým realitním makléřem agentury Svoboda & Williams v Praze 1 se specializací na luxusní byty a exkluzivní nemovitosti v Praze. Realitní makléř Praha Svoboda & Williams zajišťuje diskrétní a profesionální realitní služby.', picturePath: null, active: true },

  // ── ZAHRADNIK ────────────────────────────────────────────────────────────
  { fullName: 'Zahradnické služby Zelený ráj Praha', phone: '+420 602 774 321', email: 'info@zelenyraj-praha.cz', serviceId: 'zahradnik', cityId: CITY, address: 'Výpadová 14, Praha 5 – Jinonice', description: 'Zahradnické služby Zelený ráj nabízí sekání trávy, zakládání zahrad a údržbu zeleně pro soukromé zákazníky i firmy v Praze. Zahradník Praha zajišťuje celoroční péči o zahrady a zelené plochy v celé Praze a okolí.', picturePath: null, active: true },
  { fullName: 'Ladislav Horak – zahradník Praha', phone: '+420 774 225 668', email: null, serviceId: 'zahradnik', cityId: CITY, address: 'K Netlukám 887, Praha 10 – Strašnice', description: 'Ladislav Horak je zkušený zahradník v Praze 10 nabízející výsadbu okrasných dřevin, zakládání trávníků a kompletní zahradní úpravy. Zahradník Praha Strašnice poskytuje spolehlivé a cenově dostupné zahradnické práce pro rodinné domy a zahrady v Praze.', picturePath: null, active: true },
  { fullName: 'GardenPro Praha s.r.o.', phone: '+420 266 316 811', email: 'info@gardenpro.cz', serviceId: 'zahradnik', cityId: CITY, address: 'Prosecká 64, Praha 9 – Prosek', description: 'GardenPro Praha je profesionální zahradnická firma v Praze 9 Prosek s komplexní nabídkou péče o zahradu, zahradní architektury a zavlažovacích systémů. Zahradník Praha GardenPro realizuje zahrady na klíč od projektu až po hotové dílo.', picturePath: null, active: true },
  { fullName: 'Michal Doubrava – zahradní úpravy Praha', phone: '+420 733 458 812', email: 'doubrava.zahrada@email.cz', serviceId: 'zahradnik', cityId: CITY, address: 'Antala Staška 34, Praha 4 – Chodov', description: 'Michal Doubrava je samostatný zahradník v Praze 4 Chodov se zaměřením na tvorbu a rekonstrukci zahrad, řez stromů a keřů. Nabízí rychlou a spolehlivou zahradní údržbu pro rodinné domy a bytové komplexy v Praze.', picturePath: null, active: true },

  // ── ZEDNIK ────────────────────────────────────────────────────────────────
  { fullName: 'Stavební firma Beton Praha s.r.o.', phone: '+420 281 863 400', email: 'info@beton-stavby-praha.cz', serviceId: 'zednik', cityId: CITY, address: 'Kbelská 60, Praha 9 – Hloubětín', description: 'Stavební firma Beton Praha s.r.o. je renomovaný zedník a stavební firma v Praze 9 se specializací na zdění, omítky a rekonstrukce bytových jader. Zednické práce Praha zajišťuje na klíč od hrubé stavby po finální povrchové úpravy.', picturePath: null, active: true },
  { fullName: 'Radovan Marek – zednické práce Praha', phone: '+420 603 591 227', email: null, serviceId: 'zednik', cityId: CITY, address: 'Ke Stírce 55, Praha 8 – Bohnice', description: 'Radovan Marek je zkušený zedník v Praze 8 nabízející zednické a obkladačské práce, rekonstrukce koupelen a pokládání dlažeb. Zedník Praha zajišťuje kvalitní řemeslné práce s garancí a přesným dodržením termínů.', picturePath: null, active: true },
  { fullName: 'Petr Vávra – stavební a zednické práce Praha', phone: '+420 724 980 115', email: 'vavra.stavby@gmail.com', serviceId: 'zednik', cityId: CITY, address: 'Laudova 1025/4, Praha 6 – Řepy', description: 'Petr Vávra je řemeslník a zedník v Praze 6 s více než 15 lety praxe v provádění zednických, obkladačských a rekonstrukčních prací. Zednik Praha Řepy nabízí profesionální stavební práce za smluvní ceny pro domácnosti i firmy v Praze.', picturePath: null, active: true },
  { fullName: 'STAVOS Praha – zednické a stavební práce', phone: '+420 257 950 113', email: 'stavos@stavos-praha.cz', serviceId: 'zednik', cityId: CITY, address: 'Peroutkova 2, Praha 5 – Smíchov', description: 'STAVOS Praha je stavební firma v Praze 5 Smíchov provádějící kompletní zednické práce, rekonstrukce bytů a komerčních prostor. Zednické práce Praha od STAVOS zahrnují zdění, omítky, sádrokarton a veškeré stavební dokončovací práce.', picturePath: null, active: true },

  // ── KLEMPIR ───────────────────────────────────────────────────────────────
  { fullName: 'Klempířství Novák Praha', phone: '+420 281 912 345', email: 'info@klempirstvi-novak.cz', serviceId: 'klempir', cityId: CITY, address: 'Průmyslová 22, Praha 10 – Hostivař', description: 'Klempířství Novák je profesionální klempíř a pokrývač v Praze 10 Hostivař specializující se na pokládání střešních krytin, oplechování a odvodnění střech. Klempíř Praha Novák zajišťuje spolehlivé klempířské a pokrývačské práce pro rodinné domy i bytové domy v Praze.', picturePath: null, active: true },
  { fullName: 'Ing. Jiří Kratochvíl – klempíř a pokrývač Praha', phone: '+420 603 218 774', email: 'kratochvil@klempir-praha.cz', serviceId: 'klempir', cityId: CITY, address: 'Ciolkovského 862/9, Praha 6 – Ruzyně', description: 'Jiří Kratochvíl je zkušený klempíř a pokrývač v Praze 6 s rozsáhlou praxí v instalaci plechových střech, žlabů, svodů a oplechování komínů. Klempíř Praha Kratochvíl poskytuje odborné klempířské práce s využitím kvalitních materiálů a zárukou.', picturePath: null, active: true },
  { fullName: 'KlempServer Praha s.r.o.', phone: '+420 266 030 810', email: 'info@klempserver.cz', serviceId: 'klempir', cityId: CITY, address: 'Freyova 12, Praha 9 – Vysočany', description: 'KlempServer Praha je moderní klempířská firma v Praze 9 Vysočany nabízející veškeré klempířské práce, montáž střešních oken a fotovoltaických systémů. Klempíř Praha KlempServer realizuje zakázky pro rodinné i průmyslové objekty po celé Praze.', picturePath: null, active: true },
  { fullName: 'Pavel Šedivý – klempíř Praha', phone: '+420 773 551 630', email: null, serviceId: 'klempir', cityId: CITY, address: 'Přecechtělova 2456/2, Praha 13 – Stodůlky', description: 'Pavel Šedivý je samostatný klempíř a pokrývač v Praze 13 Stodůlky provádějící klempířské práce, opravy střech a instalace okapových systémů. Klempíř Praha Šedivý nabízí rychlý zásah, havarijní opravy střech a cenově výhodné klempířské práce v Praze.', picturePath: null, active: true },

  // ── UKLID ────────────────────────────────────────────────────────────────
  { fullName: 'MaidPro Praha – úklidová společnost', phone: '+420 225 380 650', email: 'info@maidpro.cz', serviceId: 'uklid', cityId: CITY, address: 'Žitná 25, Praha 1 – Nové Město', description: 'MaidPro Praha je profesionální úklidová firma v centru Prahy 1 nabízející pravidelný úklid domácností, generální úklid a čistění koberců. Úklid Praha MaidPro zajišťuje spolehlivé, ekologické čisticí služby pro byty, kanceláře a obchodní prostory v Praze.', picturePath: null, active: true },
  { fullName: 'CLEAN POINT Praha s.r.o.', phone: '+420 222 311 911', email: 'info@cleanpoint-praha.cz', serviceId: 'uklid', cityId: CITY, address: 'Bubenská 1477/1, Praha 7 – Holešovice', description: 'CLEAN POINT Praha je úklidová firma v Praze 7 Holešovice se specializací na úklid kancelářských prostor, průmyslových objektů a bytových domů. Úklidová služba Praha CLEAN POINT zajišťuje profesionální čistotu s využitím certifikovaných čisticích prostředků.', picturePath: null, active: true },
  { fullName: 'Ivana Houšková – úklid domácností Praha', phone: '+420 776 443 210', email: null, serviceId: 'uklid', cityId: CITY, address: 'Sokolská 44, Praha 2 – Nové Město', description: 'Ivana Houšková nabízí spolehlivý a diskrétní úklid domácností, bytů a rodinných domů v Praze 2 a okolí. Úklid Praha Houšková zajišťuje pravidelné i jednorázové čistění interiérů s individuálním přístupem a garancí spokojenosti.', picturePath: null, active: true },
  { fullName: 'Top Čistota Praha – úklidová agentura', phone: '+420 241 763 022', email: 'info@top-cistota.cz', serviceId: 'uklid', cityId: CITY, address: 'Zálesí 99, Praha 4 – Modřany', description: 'Top Čistota Praha je úklidová agentura v Praze 4 Modřany poskytující kompletní čisticí služby pro domácnosti, firmy a stavební objekty po kolaudaci. Úklid Praha Top Čistota nabízí flexibilní termíny, prověřený personál a konkurenční ceny.', picturePath: null, active: true },

  // ── TRUHLAR ──────────────────────────────────────────────────────────────
  { fullName: 'Truhlářství Beneš Praha', phone: '+420 257 320 541', email: 'truhlarstvi.benes@email.cz', serviceId: 'truhlar', cityId: CITY, address: 'Kříženeckého náměstí 322/5, Praha 5 – Hlubočepy', description: 'Truhlářství Beneš je rodinná truhlářská dílna v Praze 5 Hlubočepy s více než 30 lety tradice výroby nábytku na míru, vestavěných skříní a kuchyňských linek. Truhlář Praha Beneš realizuje zakázky z masivu i dřevotřísky s precizním zpracováním.', picturePath: null, active: true },
  { fullName: 'Martin Novotný – truhlář a tesař Praha', phone: '+420 737 882 553', email: 'novotny.truhlarna@email.cz', serviceId: 'truhlar', cityId: CITY, address: 'Tachovské náměstí 3, Praha 3 – Žižkov', description: 'Martin Novotný je zkušený truhlář a tesař v Praze 3 Žižkov nabízející výrobu nábytku na zakázku, renovace starožitností a opravy parket. Truhlář Praha Novotný pracuje s tradičními řemeslnými technikami a kvalitnými materiály.', picturePath: null, active: true },
  { fullName: 'Dřevodílna Praha – Vladimír Kříž', phone: '+420 603 722 449', email: 'kriz@drevodilna-praha.cz', serviceId: 'truhlar', cityId: CITY, address: 'Prosecká 6, Praha 9 – Prosek', description: 'Vladimír Kříž provozuje moderní dřevodílnu v Praze 9 Prosek zaměřenou na výrobu kuchyní, koupelnového nábytku a dřevěných schodišť na míru. Truhlář Praha Kříž nabízí 3D návrhy interiérů a kompletní realizaci od projektu po montáž v Praze.', picturePath: null, active: true },
  { fullName: 'ARTWOOD s.r.o. – truhlářství Praha', phone: '+420 284 820 010', email: 'info@artwood-praha.cz', serviceId: 'truhlar', cityId: CITY, address: 'Kundratka 17, Praha 8 – Libeň', description: 'ARTWOOD s.r.o. je designové truhlářství v Praze 8 Libeň specializující se na luxusní nábytek na míru, obklady stěn a designové prvky interiérů. Truhlář Praha ARTWOOD kombinuje tradiční řemeslo s moderním designem pro náročné zákazníky v Praze.', picturePath: null, active: true },

  // ── STEHOVACI-FIRMA ───────────────────────────────────────────────────────
  { fullName: 'Stěhování Praha EXPRES s.r.o.', phone: '+420 800 100 022', email: 'info@stehování-expres.cz', serviceId: 'stehovaci-firma', cityId: CITY, address: 'Sokolovská 270/192, Praha 9 – Vysočany', description: 'Stěhování Praha EXPRES je profesionální stěhovací firma v Praze 9 zajišťující stěhování bytů, kanceláří a celých firem po celé Praze i do zahraničí. Stěhovací firma Praha EXPRES nabízí balonový výtah, balicí služby a pojištění stěhovaného majetku.', picturePath: null, active: true },
  { fullName: 'MOVING.CZ – stěhovací služba Praha', phone: '+420 222 988 810', email: 'info@moving.cz', serviceId: 'stehovaci-firma', cityId: CITY, address: 'Kolbenova 616/38, Praha 9 – Hloubětín', description: 'MOVING.CZ je spolehlivá stěhovací firma sídlící v Praze 9 s moderní flotilou vozidel a zkušeným personálem pro stěhování v Praze a okolí. Stěhování Praha MOVING.CZ zajišťuje rychlé, šetrné a cenově přijatelné stěhování bytů i kanceláří.', picturePath: null, active: true },
  { fullName: 'Bravo Stěhování Praha', phone: '+420 773 906 530', email: 'info@bravo-stehování.cz', serviceId: 'stehovaci-firma', cityId: CITY, address: 'Nádražní 75, Praha 5 – Smíchov', description: 'Bravo Stěhování Praha je stěhovací firma v Praze 5 Smíchov s více než 15 lety zkušeností se stěhováním domácností, kanceláří a průmyslových zařízení. Stěhovací firma Praha Bravo nabízí komplexní logistiku, demontáž nábytku a klimatizované sklady.', picturePath: null, active: true },
  { fullName: 'Stěhovací služba Rychlá Praha', phone: '+420 602 651 234', email: null, serviceId: 'stehovaci-firma', cityId: CITY, address: 'Průběžná 48, Praha 10 – Strašnice', description: 'Stěhovací služba Rychlá Praha je cenově dostupná stěhovací firma v Praze 10 Strašnice ideální pro stěhování malých bytů, jednotlivých předmětů a výstavní techniky. Stěhování Praha Rychlá zajišťuje flexibilní termíny a stěhování v rámci celé Prahy i mimo ni.', picturePath: null, active: true },

  // ── TRENER ───────────────────────────────────────────────────────────────
  { fullName: 'Jakub Franěk – osobní trenér Praha', phone: '+420 737 444 981', email: 'jakub.franek@fitness-praha.cz', serviceId: 'trener', cityId: CITY, address: 'Náměstí Míru 15, Praha 2 – Vinohrady', description: 'Jakub Franěk je certifikovaný osobní trenér v Praze 2 Vinohrady se specializací na funkční trénink, silový rozvoj a hubnutí. Osobní trenér Praha Franěk sestaví individuální tréninkový plán a jídelníček přesně na míru vašim cílům.', picturePath: null, active: true },
  { fullName: 'Lucie Mrázová – fitness trenér Praha', phone: '+420 775 200 889', email: 'lucie.mrazova@personal-trainer.cz', serviceId: 'trener', cityId: CITY, address: 'Milady Horákové 40, Praha 7 – Holešovice', description: 'Lucie Mrázová je osobní fitness trenérka v Praze 7 Holešovice zaměřená na ženský trénink, rehabilitační cvičení a výživové poradenství. Trenér Praha Mrázová nabízí osobní i skupinový trénink v moderně vybaveném studiu nebo v exteriéru v Praze.', picturePath: null, active: true },
  { fullName: 'Pavel Šuster – running coach Praha', phone: '+420 602 317 445', email: 'pavel.suster@runcoach.cz', serviceId: 'trener', cityId: CITY, address: 'Wilsonova 300/10, Praha 2 – Vinohrady', description: 'Pavel Šuster je profesionální běžecký trenér a running coach v Praze specializující se na přípravu na maratony, půlmaratony a vytrvalostní závody. Trenér Praha Šuster sestavuje individuální tréninkové plány a provází klienty celým závodním rokem v Praze.', picturePath: null, active: true },
  { fullName: 'FitPoint Praha – osobní trenér', phone: '+420 284 684 333', email: 'info@fitpoint-praha.cz', serviceId: 'trener', cityId: CITY, address: 'Na Pankráci 30, Praha 4 – Nusle', description: 'FitPoint Praha je fitness centrum v Praze 4 Nusle s týmem certifikovaných osobních trenérů zaměřených na silový trénink, výživu a kondiční přípravu. Osobní trenér Praha FitPoint nabízí vstupní diagnostiku, individuální tréninky a skupinové lekce v Praze.', picturePath: null, active: true },

  // ── PREKLADATEL ───────────────────────────────────────────────────────────
  { fullName: 'Mgr. Eva Kolářová – překladatelka Praha', phone: '+420 222 513 011', email: 'eva.kolarova@prekladky.cz', serviceId: 'prekladatel', cityId: CITY, address: 'Mánesova 62, Praha 2 – Vinohrady', description: 'Mgr. Eva Kolářová je certifikovaná překladatelka v Praze 2 Vinohrady s jazykovou specializací na angličtinu, němčinu a francouzštinu. Překladatel Praha Kolářová zajišťuje odborné překlady právních, technických a marketingových textů pro firmy i soukromé klienty v Praze.', picturePath: null, active: true },
  { fullName: 'Překlady Praha s.r.o. – překladatelská agentura', phone: '+420 224 815 460', email: 'info@preklady-praha.cz', serviceId: 'prekladatel', cityId: CITY, address: 'Na Příkopě 22, Praha 1 – Nové Město', description: 'Překlady Praha s.r.o. je překladatelská agentura v centru Prahy 1 nabízející překlady do více než 30 jazyků včetně úředních překladů s razítkem soudního tlumočníka. Překladatelská firma Praha zajišťuje rychlé termíny, korektury a lokalizaci dokumentů pro firmy v Praze.', picturePath: null, active: true },
  { fullName: 'Mgr. Tomáš Ružička – překladatel a tlumočník Praha', phone: '+420 736 201 887', email: 'ruzicka@prekladatel-tlumocnik.cz', serviceId: 'prekladatel', cityId: CITY, address: 'Korunní 30, Praha 10 – Vinohrady', description: 'Mgr. Tomáš Ružička je soudní tlumočník a překladatel v Praze 10 Vinohrady se specializací na slovenštinu, polštinu a ruštinu. Překladatel Praha Ružička poskytuje tlumočení při soudních jednáních, notářských úkonech a obchodních jednáních v Praze.', picturePath: null, active: true },
  { fullName: 'Ing. Petra Horáková – technické překlady Praha', phone: '+420 777 654 003', email: 'p.horakova@techpreklad.cz', serviceId: 'prekladatel', cityId: CITY, address: 'Argentinská 8, Praha 7 – Holešovice', description: 'Ing. Petra Horáková je specialistka na technické překlady v Praze 7 Holešovice se zaměřením na strojírenství, IT a farmaceutiku. Překladatel Praha Horáková zajišťuje přesné odborné překlady z angličtiny a němčiny s terminologickou konzistencí pro výrobní firmy v Praze.', picturePath: null, active: true },

  // ── GRAFIK ───────────────────────────────────────────────────────────────
  { fullName: 'Ondřej Vlček – grafický designér Praha', phone: '+420 739 333 201', email: 'ondrej@vlcek-design.cz', serviceId: 'grafik', cityId: CITY, address: 'Řehořova 18, Praha 3 – Žižkov', description: 'Ondřej Vlček je freelance grafický designér v Praze 3 Žižkov specializující se na tvorbu log, vizuálních identit a reklamních materiálů pro startupy i zavedené firmy. Grafik Praha Vlček nabízí kreativní a moderní grafické návrhy s rychlým dodáním a neomezeným počtem revizí.', picturePath: null, active: true },
  { fullName: 'Studio Deset – grafický design Praha', phone: '+420 222 560 810', email: 'info@studio-deset.cz', serviceId: 'grafik', cityId: CITY, address: 'Křižíkova 14, Praha 8 – Karlín', description: 'Studio Deset je kreativní designové studio v Praze 8 Karlín zaměřené na branding, tvorbu webových stránek a printový design. Grafik Praha Studio Deset vytváří konzistentní vizuální identity a komunikační materiály pro firmy v Praze a celé ČR.', picturePath: null, active: true },
  { fullName: 'Karolína Dvořáčková – grafička Praha', phone: '+420 733 101 958', email: 'karolina.dvorackova@graficka-praha.cz', serviceId: 'grafik', cityId: CITY, address: 'Štefánikova 8, Praha 5 – Smíchov', description: 'Karolína Dvořáčková je grafická designérka v Praze 5 Smíchov se specializací na knižní grafiku, ilustrace a infografiky pro nakladatelství a digitální média. Grafik Praha Dvořáčková nabízí originální a pečlivě zpracovaný grafický design s citem pro detail.', picturePath: null, active: true },
  { fullName: 'PixelArt Praha – grafické studio', phone: '+420 255 740 390', email: 'info@pixelart-praha.cz', serviceId: 'grafik', cityId: CITY, address: 'Dělnická 43, Praha 7 – Holešovice', description: 'PixelArt Praha je plnoservisní grafické studio v Praze 7 Holešovice poskytující digitální design, animace a UX/UI řešení pro mobilní aplikace a webové platformy. Grafik Praha PixelArt je partnerem pro kreativní projekty agentury i přímých klientů v Praze.', picturePath: null, active: true },
];

async function main() {
  let count = 0;
  for (const p of profiles) {
    const created = await prisma.provider.create({ data: p });
    console.log(`✓ ${created.fullName}`);
    count++;
  }
  console.log(`\nDone. Added ${count} profiles.`);
}
main().catch(console.error).finally(() => prisma.$disconnect());
