import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();
const CITY = 'liberec';

const profiles = [
  // ── ELEKTRIKÁŘ ───────────────────────────────────────────────────────────
  { fullName: 'Elektroinstalace Horáček Liberec', phone: '+420 482 711 234', email: 'horacek@elektro-liberec.cz', serviceId: 'elektrikar', cityId: CITY, address: 'Moskevská 1234/22, Liberec 1', description: 'Elektroinstalace Horáček je zkušený elektrikář v Liberci nabízející komplexní elektroinstalace, revize a opravy pro domácnosti i firmy. Elektrikář Liberec zajistí rychlý výjezd a profesionální elektroinstalační práce v Libereckém kraji.', picturePath: null, active: true },
  { fullName: 'Elektro Novák Liberec', phone: '+420 485 108 560', email: 'novak@elektro-lbc.cz', serviceId: 'elektrikar', cityId: CITY, address: '1. máje 789/14, Liberec 1', description: 'Elektro Novák je elektrikář v Liberci s 18 lety zkušeností v oblasti elektroinstalací bytů, domů a průmyslových objektů. Elektrikář Liberec provádí montáž rozvaděčů, hromosvodů a fotovoltaiky.', picturePath: null, active: true },
  { fullName: 'Elektroslužby Šimánek Liberec', phone: '+420 604 221 780', email: null, serviceId: 'elektrikar', cityId: CITY, address: 'Valdštejnská 2345/31, Liberec 1', description: 'Pavel Šimánek je certifikovaný elektrikář v Liberci provádějící revize elektroinstalací, montáž inteligentních domů a opravy závad. Elektrikář Liberec nabídne rychlý servis a profesionální přístup.', picturePath: null, active: true },
  { fullName: 'Elektrikář Dvořák Liberec', phone: '+420 728 334 902', email: 'dvorak@elektro-lbc.cz', serviceId: 'elektrikar', cityId: CITY, address: 'Rumjancevova 456/8, Liberec 1', description: 'Martin Dvořák je elektrikář Liberec provádějící elektroinstalace nových staveb i rekonstrukcí. Nabízí montáž osvětlení, zásuvek a výměnu pojistkových skříní v Liberci a Libereckém kraji.', picturePath: null, active: true },

  // ── INSTALATÉR ───────────────────────────────────────────────────────────
  { fullName: 'Instalatér Blaha Liberec', phone: '+420 485 100 234', email: 'blaha@instal-liberec.cz', serviceId: 'instalater', cityId: CITY, address: 'Sokolská 1122/19, Liberec 1', description: 'Instalatér Blaha nabízí kompletní instalatérské práce v Liberci – opravy vodovodů, výměnu bojlerů a instalaci koupelen. Instalatér Liberec zajistí rychlý výjezd a kvalitní práce pro domácnosti i firmy.', picturePath: null, active: true },
  { fullName: 'Vodo-Topo Janků Liberec', phone: '+420 602 441 870', email: 'janku@vodotopo-lbc.cz', serviceId: 'instalater', cityId: CITY, address: 'Jablonecká 3456/45, Liberec 5', description: 'Vodo-Topo Janků je instalatér a topenář v Liberci zaměřený na montáž a servis plynových kotlů, radiátorů a podlahového vytápění. Instalatér Liberec provádí kompletní rekonstrukce koupelen.', picturePath: null, active: true },
  { fullName: 'Instalatérství Kříž Liberec', phone: '+420 728 667 123', email: null, serviceId: 'instalater', cityId: CITY, address: 'Rochlická 2234/28, Liberec 6', description: 'Instalatérství Kříž nabízí veškeré instalatérské a topenářské práce v Liberci. Instalatér Liberec se specializuje na opravy úniků vody, výměnu vodovodního potrubí a instalaci sanitárního vybavení.', picturePath: null, active: true },
  { fullName: 'Petr Malý – instalatér Liberec', phone: '+420 603 889 234', email: 'maly@instal-lbc.cz', serviceId: 'instalater', cityId: CITY, address: 'Moskevská 4567/67, Liberec 1', description: 'Petr Malý je instalatér Liberec s 12 lety praxe v opravách a rekonstrukcích vodovodního a topenářského rozvodu. Instalatér v Liberci nabídne pohotovostní servis 24/7 pro odstranění havárií.', picturePath: null, active: true },

  // ── MALÍŘ ────────────────────────────────────────────────────────────────
  { fullName: 'Malíř Novotný Liberec', phone: '+420 485 228 456', email: 'novotny@malir-liberec.cz', serviceId: 'malir', cityId: CITY, address: '1. máje 2345/37, Liberec 1', description: 'Malíř Novotný nabízí profesionální malování pokojů, bytů a kanceláří v Liberci a okolí. Malíř pokojů Liberec zajistí přípravu povrchů, stěrkování a výsledný nátěr dle přání zákazníka.', picturePath: null, active: true },
  { fullName: 'Malířství Vácha Liberec', phone: '+420 602 774 340', email: null, serviceId: 'malir', cityId: CITY, address: 'Sokolská 3456/44, Liberec 1', description: 'Malířství Vácha provádí malování a lakýrnické práce pro domácnosti i firmy v Liberci. Malíř Liberec nabízí nátěry fasád, dekorativní techniky a výmalbu novostaveb v Libereckém kraji.', picturePath: null, active: true },
  { fullName: 'Ondřej Havel – malíř Liberec', phone: '+420 723 441 789', email: 'havel@malir-lbc.cz', serviceId: 'malir', cityId: CITY, address: 'Valdštejnská 1234/16, Liberec 1', description: 'Ondřej Havel je zkušený malíř pokojů v Liberci s precizním přístupem k malování bytů, domů a průmyslových prostor. Malíř Liberec provádí nátěry na klíč včetně přípravy a nákupu materiálu.', picturePath: null, active: true },
  { fullName: 'Malíř Šimánek Liberec', phone: '+420 728 554 123', email: 'simanek@malirlbc.cz', serviceId: 'malir', cityId: CITY, address: 'Rumjancevova 2345/29, Liberec 1', description: 'Petr Šimánek je malíř a lakýrník v Liberci nabízející veškeré malířské a lakýrnické práce. Malíř Liberec se specializuje na nátěry kovových konstrukcí, fasád a interiérů bytů.', picturePath: null, active: true },

  // ── TESAŘ ────────────────────────────────────────────────────────────────
  { fullName: 'Tesařství Beneš Liberec', phone: '+420 485 441 780', email: 'benes@tesar-liberec.cz', serviceId: 'tesar', cityId: CITY, address: 'Jablonecká 2345/34, Liberec 5', description: 'Tesařství Beneš provádí výstavbu a rekonstrukci krovů, střech a dřevěných konstrukcí v Liberci. Tesař Liberec realizuje pergoly, přístřešky a dřevěné zahradní stavby v Libereckém kraji.', picturePath: null, active: true },
  { fullName: 'Krovy Jelínek Liberec', phone: '+420 603 221 456', email: null, serviceId: 'tesar', cityId: CITY, address: 'Rochlická 1122/21, Liberec 6', description: 'Krovy Jelínek je tesař v Liberci specializující se na výstavbu nových krovů a rekonstrukce střešních konstrukcí. Tesař Liberec realizuje dřevostavby a střešní práce pro rodinné domy.', picturePath: null, active: true },
  { fullName: 'Tesař Kvapil Liberec', phone: '+420 728 334 780', email: 'kvapil@tesarlbc.cz', serviceId: 'tesar', cityId: CITY, address: '1. máje 3456/49, Liberec 1', description: 'Josef Kvapil je zkušený tesař v Liberci provádějící veškeré tesařské práce od krovů po dřevěné terasy a altány. Tesař Liberec nabízí montáž schodišť a zahradních přístřešků v Liberci a okolí.', picturePath: null, active: true },
  { fullName: 'Dřevostavby Horáček Liberec', phone: '+420 602 667 890', email: 'horacek@drevostavby-lbc.cz', serviceId: 'tesar', cityId: CITY, address: 'Moskevská 3456/51, Liberec 1', description: 'Dřevostavby Horáček je tesař a dřevostavitel v Liberci nabízející výstavbu dřevěných domků a krovů. Tesař Liberec realizuje zakázkové tesařské práce v celém Libereckém kraji.', picturePath: null, active: true },

  // ── TRUHLÁŘ ──────────────────────────────────────────────────────────────
  { fullName: 'Truhlářství Baloun Liberec', phone: '+420 485 335 660', email: 'baloun@truhlar-liberec.cz', serviceId: 'truhlar', cityId: CITY, address: 'Sokolská 2345/36, Liberec 1', description: 'Truhlářství Baloun vyrábí nábytek, dveře a kuchyně na zakázku v Liberci. Truhlář Liberec se specializuje na výrobu kuchyňských linek, skříní a dřevěných interiérů pro zákazníky v Libereckém kraji.', picturePath: null, active: true },
  { fullName: 'Zakázkové truhlářství Beneš Liberec', phone: '+420 602 334 560', email: null, serviceId: 'truhlar', cityId: CITY, address: 'Valdštejnská 3456/43, Liberec 1', description: 'Zakázkové truhlářství Beneš vyrábí nábytek a dřevěné interiéry na míru v Liberci. Truhlář Liberec nabízí výrobu postelí, stolů a zabudovaných systémů pro domy i byty.', picturePath: null, active: true },
  { fullName: 'Truhlář Novák Liberec', phone: '+420 728 441 560', email: 'novak@truhlarnalbc.cz', serviceId: 'truhlar', cityId: CITY, address: 'Rumjancevova 3456/47, Liberec 1', description: 'Tomáš Novák je truhlář Liberec s 15 lety zkušeností ve výrobě dřevěného nábytku, schodišť a vestavěných skříní. Truhlářství v Liberci realizuje dřevěné interiéry na klíč dle individuálního návrhu.', picturePath: null, active: true },
  { fullName: 'Nábytek Mrázek – truhlář Liberec', phone: '+420 603 778 345', email: 'mrazek@nabytek-lbc.cz', serviceId: 'truhlar', cityId: CITY, address: 'Jablonecká 4567/58, Liberec 5', description: 'Dílna Mrázek je truhlář a výrobce nábytku v Liberci nabízející zakázkovou výrobu dřevěných prvků pro byty, domy a kanceláře. Truhlář Liberec zajistí výrobu a montáž nábytku přímo u zákazníka.', picturePath: null, active: true },

  // ── ZEDNÍK ───────────────────────────────────────────────────────────────
  { fullName: 'Zednictví Holub Liberec', phone: '+420 485 229 340', email: 'holub@zednik-liberec.cz', serviceId: 'zednik', cityId: CITY, address: '1. máje 4567/63, Liberec 1', description: 'Zednictví Holub nabízí kompletní zednické práce v Liberci – příčky, omítky, obklady a rekonstrukce bytů. Zedník Liberec realizuje stavební práce pro rodinné domy i bytové jednotky v Libereckém kraji.', picturePath: null, active: true },
  { fullName: 'Stavební práce Kovar Liberec', phone: '+420 602 556 780', email: null, serviceId: 'zednik', cityId: CITY, address: 'Sokolská 4567/61, Liberec 1', description: 'Stavební práce Kovař provádí zednické práce, obklady a dlažby v Liberci a okolí. Zedník Liberec zajistí renovaci koupelen, pokládku dlažby a veškeré rekonstrukční práce.', picturePath: null, active: true },
  { fullName: 'Zedník Špaček Liberec', phone: '+420 728 223 456', email: 'spacek@zednik-lbc.cz', serviceId: 'zednik', cityId: CITY, address: 'Moskevská 5678/79, Liberec 1', description: 'Ladislav Špaček je zkušený zedník v Liberci provádějící omítky, zdění příček a rekonstrukce bytů. Zedník Liberec nabízí kompletní stavební práce od základů po finální úpravy povrchů.', picturePath: null, active: true },
  { fullName: 'Stavební firma Polák Liberec', phone: '+420 603 112 890', email: 'polak@stav-lbc.cz', serviceId: 'zednik', cityId: CITY, address: 'Rochlická 2345/37, Liberec 6', description: 'Stavební firma Polák nabízí kompletní zednické a stavební práce v Liberci. Zedník Liberec realizuje zdění, betonáže, stropy a příčky pro soukromé i firemní zákazníky.', picturePath: null, active: true },

  // ── KLEMPÍŘ ──────────────────────────────────────────────────────────────
  { fullName: 'Klempířství Novák Liberec', phone: '+420 485 120 780', email: 'novak@klempir-liberec.cz', serviceId: 'klempir', cityId: CITY, address: 'Valdštejnská 4567/59, Liberec 1', description: 'Klempířství Novák nabízí kompletní klempířské a pokrývačské práce v Liberci – oplechování střech, parapety a okapy. Klempíř Liberec provádí montáž a opravy střech pro rodinné domy i bytové komplexy.', picturePath: null, active: true },
  { fullName: 'Střechy Horáček Liberec', phone: '+420 602 667 560', email: null, serviceId: 'klempir', cityId: CITY, address: 'Jablonecká 3456/46, Liberec 5', description: 'Střechy Horáček je klempíř a pokrývač v Liberci se zaměřením na pokládku střešní krytiny a klempířské práce. Klempíř Liberec poskytuje záruky na veškeré provedené práce v Libereckém kraji.', picturePath: null, active: true },
  { fullName: 'Klempíř Beneš Liberec', phone: '+420 728 890 234', email: 'benes@klempir-lbc.cz', serviceId: 'klempir', cityId: CITY, address: 'Rumjancevova 4567/63, Liberec 1', description: 'Karel Beneš je klempíř Liberec s 20 lety zkušeností s montáží okapů, oplechováním komínů a opravami střech. Klempíř v Liberci zajistí kvalitní klempířské práce za přijatelné ceny.', picturePath: null, active: true },
  { fullName: 'Klempíř Dvořák Liberec', phone: '+420 603 334 890', email: 'dvorak@klempir-lbc.cz', serviceId: 'klempir', cityId: CITY, address: 'Rochlická 3456/49, Liberec 6', description: 'Roman Dvořák je klempíř v Liberci nabízející opravy střech, oplechování říms a montáž venkovních žaluzií. Klempíř Liberec pracuje s pozinkovaným, titanzinkovým i měděným plechem.', picturePath: null, active: true },

  // ── AUTOSERVIS ───────────────────────────────────────────────────────────
  { fullName: 'Autoservis Kříž Liberec', phone: '+420 485 252 900', email: 'info@autoservis-kriz.cz', serviceId: 'autoservis', cityId: CITY, address: 'Průmyslová 1234/15, Liberec 10', description: 'Autoservis Kříž nabízí komplexní opravy a servis vozidel všech značek v Liberci. Autoservis Liberec zajistí pravidelné prohlídky, výměnu oleje, brzd a diagnostiku pro zákazníky z Libereckého kraje.', picturePath: null, active: true },
  { fullName: 'Car Service Liberec – Holub', phone: '+420 602 334 780', email: 'holub@carservice-lbc.cz', serviceId: 'autoservis', cityId: CITY, address: 'Londýnská 2345/28, Liberec 1', description: 'Car Service Holub je autoservis v Liberci zaměřený na opravy motorů, převodovek a klimatizací. Autoservis Liberec provádí STK přípravu a komplexní servis osobních i užitkových vozidel.', picturePath: null, active: true },
  { fullName: 'Auto Novák – servis Liberec', phone: '+420 485 339 127', email: null, serviceId: 'autoservis', cityId: CITY, address: 'Jablonecká 5678/77, Liberec 5', description: 'Auto Novák je rodinný autoservis v Liberci s tradicí přes 20 let, specializující se na osobní vozy a dodávky. Autoservis Liberec nabízí pneuservis, geometrii náprav a karosářské práce.', picturePath: null, active: true },
  { fullName: 'Autoservis Machač Liberec', phone: '+420 728 667 234', email: 'machac@autolbc.cz', serviceId: 'autoservis', cityId: CITY, address: 'Sokolská 5678/79, Liberec 1', description: 'Autoservis Machač je certifikovaný servis v Liberci pro osobní i užitková vozidla. Autoservis Liberec zajistí diagnostiku závad, opravy elektroniky a pravidelnou údržbu vozidel.', picturePath: null, active: true },

  // ── IT TECHNIK ───────────────────────────────────────────────────────────
  { fullName: 'PC Servis Liberec – Novák', phone: '+420 485 241 801', email: 'novak@pc-liberec.cz', serviceId: 'it-technik', cityId: CITY, address: 'Moskevská 2345/34, Liberec 1', description: 'PC Servis Novák je IT technik v Liberci nabízející opravy počítačů, notebooků a tiskáren pro firmy i domácnosti. IT technik Liberec zajistí instalaci systémů, obnovu dat a správu sítí.', picturePath: null, active: true },
  { fullName: 'IT pohotovost Liberec – Beneš', phone: '+420 602 778 560', email: 'benes@it-liberec.cz', serviceId: 'it-technik', cityId: CITY, address: '1. máje 5678/81, Liberec 1', description: 'IT pohotovost Beneš je zkušený IT technik Liberec s 18 lety praxe v opravách PC a správě IT infrastruktury. Nabízí nonstop IT pohotovost a vzdálenou správu počítačů v Liberci.', picturePath: null, active: true },
  { fullName: 'Comtech Liberec', phone: '+420 485 100 700', email: 'info@comtech-liberec.cz', serviceId: 'it-technik', cityId: CITY, address: 'Sokolská 6789/91, Liberec 1', description: 'Comtech je profesionální IT servis v Liberci zaměřený na opravy počítačů, datové zálohy a kybernetickou bezpečnost. IT technik Liberec poskytuje komplexní ICT podporu pro firmy v Libereckém kraji.', picturePath: null, active: true },
  { fullName: 'Počítačový servis Holub Liberec', phone: '+420 728 445 890', email: null, serviceId: 'it-technik', cityId: CITY, address: 'Valdštejnská 5678/77, Liberec 1', description: 'Počítačový servis Holub nabízí opravy a upgrade PC a notebooků v Liberci za dostupné ceny. IT technik Liberec zajistí reinstalaci systémů, odstranění virů a nastavení Wi-Fi sítí.', picturePath: null, active: true },

  // ── FOTOGRAF ─────────────────────────────────────────────────────────────
  { fullName: 'Foto Studio Horáčková Liberec', phone: '+420 602 447 882', email: 'info@fotohoracek.cz', serviceId: 'fotograf', cityId: CITY, address: 'Rumjancevova 5678/81, Liberec 1', description: 'Foto Studio Horáčková je profesionální fotografka v Liberci se zaměřením na rodinné, těhotenské a newborn fotografie. Fotograf Liberec nabízí moderní fotografické studio a venkovní focení.', picturePath: null, active: true },
  { fullName: 'Reportážní fotograf Blažek Liberec', phone: '+420 485 108 540', email: 'blazek@foto-lbc.cz', serviceId: 'fotograf', cityId: CITY, address: 'Jablonecká 6789/96, Liberec 5', description: 'Michal Blažek je reportážní a reklamní fotograf v Liberci s 12 lety zkušeností. Fotograf Liberec nabízí firemní fotografii, produktové focení a reportáže z akcí v Libereckém kraji.', picturePath: null, active: true },
  { fullName: 'Svatební fotograf Novák Liberec', phone: '+420 728 112 901', email: 'novak@svatebnifoto-lbc.cz', serviceId: 'fotograf', cityId: CITY, address: 'Moskevská 6789/97, Liberec 1', description: 'Tomáš Novák je svatební fotograf v Liberci specializující se na svatební reportáže a portrétní fotografii. Fotograf Liberec zachytí každý vzácný okamžik vašeho dne s přirozeným a citlivým přístupem.', picturePath: null, active: true },
  { fullName: 'FotoArt Liberec – Marková', phone: '+420 603 334 120', email: 'markova@fotoart-lbc.cz', serviceId: 'fotograf', cityId: CITY, address: 'Rochlická 4567/61, Liberec 6', description: 'FotoArt Marková je fotografka v Liberci nabízející portréty, rodinnou a těhotenskou fotografii ve studiu i exteriéru. Fotograf Liberec klade důraz na přirozené zachycení emocí a osobitý styl.', picturePath: null, active: true },

  // ── UČITEL / LEKTOR ──────────────────────────────────────────────────────
  { fullName: 'Jazyková škola Polyglot Liberec', phone: '+420 485 104 444', email: 'liberec@polyglot.cz', serviceId: 'ucitel', cityId: CITY, address: '1. máje 1122/18, Liberec 1', description: 'Jazyková škola Polyglot nabízí kurzy angličtiny, němčiny a dalších jazyků v Liberci pro děti i dospělé. Zkušení lektoři v Liberci zajistí efektivní výuku a přípravu na mezinárodní certifikáty.', picturePath: null, active: true },
  { fullName: 'Jazykové centrum Liberec', phone: '+420 485 220 780', email: 'info@jazykove-centrum-lbc.cz', serviceId: 'ucitel', cityId: CITY, address: 'Moskevská 1345/25, Liberec 1', description: 'Jazykové centrum Liberec nabízí firemní i individuální kurzy angličtiny, němčiny a ruštiny. Lektor Liberec zajistí výuku na míru přímo ve firmě nebo v moderních učebnách v centru Liberce.', picturePath: null, active: true },
  { fullName: 'Doučování Liberec – Mgr. Nováková', phone: '+420 728 441 560', email: null, serviceId: 'ucitel', cityId: CITY, address: 'Sokolská 2345/38, Liberec 1', description: 'Mgr. Nováková je zkušená lektorka nabízející doučování matematiky, angličtiny a češtiny v Liberci. Lektor Liberec zajistí individuální přístup k žákům základních a středních škol.', picturePath: null, active: true },
  { fullName: 'Bc. Kopecký – lektor angličtiny Liberec', phone: '+420 603 334 780', email: 'kopecky@lektor-lbc.cz', serviceId: 'ucitel', cityId: CITY, address: 'Valdštejnská 2345/33, Liberec 1', description: 'Bc. Kopecký je certifikovaný lektor angličtiny v Liberci s 8 lety praxe ve výuce dospělých a firemní klientely. Lektor Liberec nabízí individuální i skupinové kurzy na všech úrovních znalostí.', picturePath: null, active: true },

  // ── RESTAURACE ───────────────────────────────────────────────────────────
  { fullName: 'Restaurace Zlatý Lev Liberec', phone: '+420 485 104 234', email: 'info@zlaty-lev-liberec.cz', serviceId: 'restaurace', cityId: CITY, address: 'Náměstí Dr. E. Beneše 3, Liberec 1', description: 'Restaurace Zlatý Lev je tradiční česká restaurace v centru Liberce nabízející českou kuchyni a plzeňské pivo. Restaurace v Liberci je oblíbená mezi turisty i místními hosty pro příjemnou atmosféru.', picturePath: null, active: true },
  { fullName: 'Pivovarská restaurace Konrad Liberec', phone: '+420 485 226 600', email: 'info@konrad-pivovar.cz', serviceId: 'restaurace', cityId: CITY, address: 'Pivovarská 8, Liberec 10', description: 'Pivovarská restaurace Konrad je unikátní restaurace v Liberci s vlastním pivovarem vyrábějícím pivo Konrad. Restaurace Liberec nabízí tradiční českou kuchyni a pivní degustace přímo v areálu pivovaru.', picturePath: null, active: true },
  { fullName: 'Bistro U Nisy Liberec', phone: '+420 604 334 456', email: null, serviceId: 'restaurace', cityId: CITY, address: 'Sokolská 3456/46, Liberec 1', description: 'Bistro U Nisy je oblíbená restaurace v Liberci nabízející denní menu a českou kuchyni za dostupné ceny. Restaurace Liberec láká místní i turisty na domácí jídla připravená z čerstvých surovin.', picturePath: null, active: true },
  { fullName: 'Restaurant Česká Hospoda Liberec', phone: '+420 485 445 678', email: 'info@hospoda-liberec.cz', serviceId: 'restaurace', cityId: CITY, address: 'Rumjancevova 1234/18, Liberec 1', description: 'Česká Hospoda je tradiční restaurace v Liberci s autentickým prostředím a poctivou českou kuchyní. Restaurace v Liberci nabízí guláš, svíčkovou a regionální speciality v srdci města.', picturePath: null, active: true },

  // ── ZUBAŘ ────────────────────────────────────────────────────────────────
  { fullName: 'MDDr. Kříž – zubní ordinace Liberec', phone: '+420 485 110 890', email: 'kriz@zubar-liberec.cz', serviceId: 'zubar', cityId: CITY, address: 'Moskevská 2234/30, Liberec 1', description: 'MDDr. Kříž provozuje zubní ordinaci v Liberci nabízející kompletní stomatologickou péči pro děti i dospělé. Zubař Liberec zajistí ošetření zubů, bělení a ortodontické poradenství v moderně vybavené ordinaci.', picturePath: null, active: true },
  { fullName: 'Stomatologie Novotná Liberec', phone: '+420 485 224 177', email: 'novotna@stom-liberec.cz', serviceId: 'zubar', cityId: CITY, address: '1. máje 3456/51, Liberec 1', description: 'Stomatologie Novotná je zubní ordinace v Liberci zaměřená na estetickou stomatologii, implantáty a dentální hygienu. Zubař Liberec přijímá nové pacienty a nabízí individuální přístup.', picturePath: null, active: true },
  { fullName: 'Zubní ordinace Horáček Liberec', phone: '+420 485 128 901', email: null, serviceId: 'zubar', cityId: CITY, address: 'Sokolská 4567/63, Liberec 1', description: 'MUDr. Horáček provozuje zubní ordinaci v Liberci s komplexními stomatologickými službami včetně chirurgie a protetiky. Zubař Liberec zajistí odbornou péči o chrup v klidném a příjemném prostředí.', picturePath: null, active: true },
  { fullName: 'Dentální centrum Liberec', phone: '+420 485 901 234', email: 'info@dental-liberec.cz', serviceId: 'zubar', cityId: CITY, address: 'Valdštejnská 5678/79, Liberec 1', description: 'Dentální centrum Liberec je moderní zubní klinika nabízející komplexní péči od prevence po implantologii. Zubař Liberec nabídne bezbolestné ošetření, ortodoncii a dentální hygienu pro celou rodinu.', picturePath: null, active: true },

  // ── LÉKAŘ ────────────────────────────────────────────────────────────────
  { fullName: 'MUDr. Horáčková – praktická lékařka Liberec', phone: '+420 485 110 455', email: 'horackovamd@lekar-liberec.cz', serviceId: 'lekar', cityId: CITY, address: '1. máje 2234/35, Liberec 1', description: 'MUDr. Horáčková je praktická lékařka v Liberci s komplexní zdravotní péčí pro dospělé. Lékař Liberec přijímá nové pacienty a zajistí pravidelné prohlídky, očkování a vydávání receptů.', picturePath: null, active: true },
  { fullName: 'MUDr. Beneš – internista Liberec', phone: '+420 485 261 233', email: 'benes@interna-liberec.cz', serviceId: 'lekar', cityId: CITY, address: 'Moskevská 3345/45, Liberec 1', description: 'MUDr. Beneš je internista v Liberci specializující se na diagnostiku a léčbu interních onemocnění. Lékař Liberec nabídne odborné vyšetření a individuální léčebný plán pro pacienty.', picturePath: null, active: true },
  { fullName: 'Poliklinika Liberec – zdravotní středisko', phone: '+420 485 103 111', email: 'info@poliklinikalbc.cz', serviceId: 'lekar', cityId: CITY, address: 'Husova 357/10, Liberec 1', description: 'Poliklinika Liberec je zdravotní středisko s širokým spektrem praktických a odborných lékařů. Lékař Liberec – poliklinika nabízí komplexní zdravotní péči pro obyvatele Liberce a Libereckého kraje.', picturePath: null, active: true },
  { fullName: 'MUDr. Houšková – pediatr Liberec', phone: '+420 485 118 766', email: null, serviceId: 'lekar', cityId: CITY, address: 'Sokolská 5678/81, Liberec 1', description: 'MUDr. Houšková je dětská lékařka – pediatr v Liberci pečující o zdravý vývoj dětí od narození. Lékař Liberec poskytuje preventivní prohlídky, očkování a léčbu dětských nemocí.', picturePath: null, active: true },

  // ── PSYCHOLOG ─────────────────────────────────────────────────────────────
  { fullName: 'PhDr. Machačová – psycholog Liberec', phone: '+420 485 243 210', email: 'machacova@psycholog-liberec.cz', serviceId: 'psycholog', cityId: CITY, address: 'Rumjancevova 3456/49, Liberec 1', description: 'PhDr. Machačová je psycholog v Liberci nabízející individuální psychoterapii, párové poradenství a krizovou intervenci. Psycholog Liberec pomáhá klientům zvládat úzkosti, deprese a životní krize.', picturePath: null, active: true },
  { fullName: 'Mgr. Horáček – psychoterapeut Liberec', phone: '+420 602 334 341', email: 'horacek@terapie-lbc.cz', serviceId: 'psycholog', cityId: CITY, address: 'Moskevská 4456/61, Liberec 1', description: 'Mgr. Horáček je psychoterapeut v Liberci s výcvikem v kognitivně-behaviorální terapii. Psycholog Liberec nabízí individuální, párovou a skupinovou terapii pro dospělé i adolescenty.', picturePath: null, active: true },
  { fullName: 'Centrum psychologické pomoci Liberec', phone: '+420 485 989 123', email: 'info@cpp-liberec.cz', serviceId: 'psycholog', cityId: CITY, address: '1. máje 6789/97, Liberec 1', description: 'Centrum psychologické pomoci Liberec je poradenské centrum s týmem zkušených psychologů. Psycholog Liberec nabízí diagnostiku, poradenství a terapii pro děti, dospělé i rodiny.', picturePath: null, active: true },
  { fullName: 'Mgr. Kopecká – terapeutka Liberec', phone: '+420 728 445 123', email: null, serviceId: 'psycholog', cityId: CITY, address: 'Sokolská 6789/93, Liberec 1', description: 'Mgr. Kopecká je psycholožka a terapeutka v Liberci specializující se na práci s traumatem a úzkostí. Psycholog Liberec pracuje s dospělými i dětmi metodou EMDR a systemické terapie.', picturePath: null, active: true },

  // ── PRÁVNÍK ──────────────────────────────────────────────────────────────
  { fullName: 'JUDr. Holub – advokát Liberec', phone: '+420 485 122 891', email: 'holub@advokatlib.cz', serviceId: 'pravnik', cityId: CITY, address: 'Náměstí Dr. E. Beneše 15, Liberec 1', description: 'JUDr. Holub je advokát v Liberci zaměřený na občanské, obchodní a rodinné právo. Právník Liberec nabízí právní poradenství, sepis smluv a zastupování klientů před soudy v Libereckém kraji.', picturePath: null, active: true },
  { fullName: 'Advokátní kancelář Beneš Liberec', phone: '+420 485 310 067', email: 'benes@ak-liberec.cz', serviceId: 'pravnik', cityId: CITY, address: 'Moskevská 1122/16, Liberec 1', description: 'Advokátní kancelář Beneš je právní firma v Liberci specializující se na pracovní právo, nemovitosti a obchodní spory. Právník Liberec zajistí komplexní právní zastoupení a poradenství.', picturePath: null, active: true },
  { fullName: 'JUDr. Dvořák – notář Liberec', phone: '+420 485 228 445', email: 'dvorak@notar-liberec.cz', serviceId: 'pravnik', cityId: CITY, address: '1. máje 1234/21, Liberec 1', description: 'JUDr. Dvořák je notář a právník v Liberci zajišťující sepisování závětí, kupních smluv a ověřování podpisů. Právník Liberec poskytuje notářské a právní služby pro fyzické i právnické osoby.', picturePath: null, active: true },
  { fullName: 'Mgr. Horáčková – rodinné právo Liberec', phone: '+420 728 220 789', email: null, serviceId: 'pravnik', cityId: CITY, address: 'Valdštejnská 1122/14, Liberec 1', description: 'Mgr. Horáčková je právnička v Liberci specializující se na rodinné právo, rozvody a opatrovnická řízení. Právník Liberec nabídne empatické a profesionální zastupování v soudních sporech.', picturePath: null, active: true },

  // ── ÚČETNÍ ───────────────────────────────────────────────────────────────
  { fullName: 'Účetní poradenství Nová Liberec', phone: '+420 485 243 210', email: 'nova@ucetni-liberec.cz', serviceId: 'ucetni', cityId: CITY, address: 'Rumjancevova 2345/31, Liberec 1', description: 'Účetní poradenství Nová nabízí vedení účetnictví, daňové přiznání a mzdovou agendu pro firmy v Liberci. Účetní Liberec poskytuje kompletní ekonomické poradenství pro OSVČ i právnické osoby.', picturePath: null, active: true },
  { fullName: 'ECO Consulting Liberec', phone: '+420 485 421 800', email: 'info@eco-consulting-lbc.cz', serviceId: 'ucetni', cityId: CITY, address: '1. máje 3456/53, Liberec 1', description: 'ECO Consulting je účetní firma v Liberci specializující se na podvojné účetnictví, DPH a daňovou optimalizaci. Účetní Liberec zajistí přesné zpracování daňových přiznání a roční závěrky.', picturePath: null, active: true },
  { fullName: 'Bc. Novotná – účetní a mzdy Liberec', phone: '+420 728 234 456', email: 'novotna@ucetni-mzdy-lbc.cz', serviceId: 'ucetni', cityId: CITY, address: 'Sokolská 2345/38, Liberec 1', description: 'Bc. Novotná je účetní v Liberci se specializací na zpracování mezd, daňové přiznání a vedení daňové evidence. Účetní Liberec nabízí přesné a spolehlivé zpracování dokladů pro malé a střední firmy.', picturePath: null, active: true },
  { fullName: 'AUDIT LIBEREC – účetní kancelář', phone: '+420 602 457 890', email: 'audit@ucliberec.cz', serviceId: 'ucetni', cityId: CITY, address: 'Valdštejnská 3456/45, Liberec 1', description: 'AUDIT LIBEREC je účetní kancelář v Liberci nabízející komplexní ekonomické a daňové poradenství pro podnikatele. Účetní Liberec zpracuje daňová přiznání, roční závěrky i reporty pro zahraniční firmy.', picturePath: null, active: true },

  // ── KADEŘNÍK ─────────────────────────────────────────────────────────────
  { fullName: 'Kadeřnictví Nováčková Liberec', phone: '+420 485 111 345', email: null, serviceId: 'kadernik', cityId: CITY, address: 'Moskevská 2345/36, Liberec 1', description: 'Kadeřnictví Nováčková nabízí střihy, barvení a styling vlasů pro ženy i muže v Liberci. Kadeřník Liberec pracuje s prémiovou kosmetikou a zajistí individuální poradenství o péči o vlasy.', picturePath: null, active: true },
  { fullName: 'Salon Klára – kadeřnictví Liberec', phone: '+420 485 258 900', email: 'klara@salon-liberec.cz', serviceId: 'kadernik', cityId: CITY, address: '1. máje 4567/65, Liberec 1', description: 'Salon Klára je moderní kadeřnický salon v Liberci se zkušenými stylisty a kadeřnicemi. Kadeřník Liberec nabízí barvení, melír, keratin a svatební účesy v příjemném salonu.', picturePath: null, active: true },
  { fullName: 'Kadeřnictví Horáčková Liberec', phone: '+420 728 445 789', email: null, serviceId: 'kadernik', cityId: CITY, address: 'Sokolská 3456/50, Liberec 1', description: 'Kadeřnictví Horáčková je rodinný salon v Liberci nabízející kompletní kadeřnické služby – střihy, barvení a rekonstrukce vlasů. Kadeřník Liberec zajistí péči o vlasy v přátelské atmosféře.', picturePath: null, active: true },
  { fullName: 'Studio Versus – kadeřnictví Liberec', phone: '+420 485 235 678', email: 'versus@kadernictvi-liberec.cz', serviceId: 'kadernik', cityId: CITY, address: 'Rumjancevova 3456/47, Liberec 1', description: 'Studio Versus je prémiové kadeřnické studio v Liberci zaměřené na moderní trendy v barvení a stylingu vlasů. Kadeřník Liberec nabízí konzultace, střihy a speciální ošetření vlasů pro náročné klientky.', picturePath: null, active: true },

  // ── ARCHITEKT ────────────────────────────────────────────────────────────
  { fullName: 'Ing. arch. Novák – architekt Liberec', phone: '+420 485 422 780', email: 'novak@architektlbc.cz', serviceId: 'architekt', cityId: CITY, address: 'Náměstí Dr. E. Beneše 22, Liberec 1', description: 'Ing. arch. Novák je architekt v Liberci nabízející projektování rodinných domů a bytových rekonstrukcí. Architekt Liberec navrhuje funkční a estetická řešení s důrazem na nízkoenergetické standardy.', picturePath: null, active: true },
  { fullName: 'Ateliér LIBEREC – architekti', phone: '+420 485 534 122', email: 'info@atelierlbc.cz', serviceId: 'architekt', cityId: CITY, address: 'Moskevská 1234/20, Liberec 1', description: 'Ateliér LIBEREC je architektonické studio s portfoliem rezidenčních, komerčních a veřejných staveb v Liberci. Architekt Liberec nabídne kompletní projektové služby od studie po realizaci.', picturePath: null, active: true },
  { fullName: 'Ing. arch. Horáčková – interiéry Liberec', phone: '+420 728 882 445', email: 'horackovaarch@interier-lbc.cz', serviceId: 'architekt', cityId: CITY, address: '1. máje 2345/37, Liberec 1', description: 'Ing. arch. Horáčková je architektka a interiérová designérka v Liberci zaměřená na komplexní návrhy interiérů bytů a kanceláří. Architekt Liberec navrhuje prostory s ohledem na funkčnost a přání klienta.', picturePath: null, active: true },
  { fullName: 'STUDIO SEVER – architekti Liberec', phone: '+420 485 620 110', email: 'sever@studio-sever.cz', serviceId: 'architekt', cityId: CITY, address: 'Valdštejnská 2345/35, Liberec 1', description: 'STUDIO SEVER je architektonická kancelář v Liberci realizující rodinné domy, rekonstrukce a urbanistické projekty. Architekt Liberec zajistí projekt od konceptu přes povolení až po dozor na stavbě.', picturePath: null, active: true },

  // ── REALITNÍ MAKLÉŘ ──────────────────────────────────────────────────────
  { fullName: 'RE/MAX Liberec – realitní kancelář', phone: '+420 485 244 555', email: 'remax@remax-liberec.cz', serviceId: 'realitni-makler', cityId: CITY, address: 'Náměstí Dr. E. Beneše 31, Liberec 1', description: 'RE/MAX Liberec je realitní kancelář s týmem zkušených makléřů pro prodej a pronájem bytů a domů v Liberci. Realitní makléř Liberec zajistí odborné ocenění nemovitosti a efektivní marketing.', picturePath: null, active: true },
  { fullName: 'Realitní kancelář Beneš Liberec', phone: '+420 485 310 700', email: 'benes@rk-liberec.cz', serviceId: 'realitni-makler', cityId: CITY, address: 'Moskevská 1345/26, Liberec 1', description: 'Realitní kancelář Beneš je zavedená realitní firma v Liberci s 12 lety zkušeností na trhu s nemovitostmi. Realitní makléř Liberec pomůže s koupí, prodejem i pronájmem nemovitostí v Libereckém kraji.', picturePath: null, active: true },
  { fullName: 'STING realitní Liberec', phone: '+420 728 888 341', email: 'info@sting-reality-lbc.cz', serviceId: 'realitni-makler', cityId: CITY, address: '1. máje 5678/83, Liberec 1', description: 'STING realitní je dynamická realitní kancelář v Liberci zaměřená na prodej bytů a domů v Liberci a okolí. Realitní makléř Liberec nabídne profesionální fotografii, 3D prohlídky a právní servis.', picturePath: null, active: true },
  { fullName: 'Reality Kopřiva Liberec', phone: '+420 603 003 789', email: null, serviceId: 'realitni-makler', cityId: CITY, address: 'Sokolská 4567/65, Liberec 1', description: 'Reality Kopřiva je realitní makléř v Liberci specializující se na rezidenční nemovitosti. Makléř Liberec nabídne individuální přístup a kompletní administrativní servis při prodeji i nákupu bytu.', picturePath: null, active: true },

  // ── ZAHRADNÍK ────────────────────────────────────────────────────────────
  { fullName: 'Zahradnictví Horáček Liberec', phone: '+420 728 334 780', email: 'horacek@zahradnictvi-lbc.cz', serviceId: 'zahradnik', cityId: CITY, address: 'Jablonecká 4567/60, Liberec 5', description: 'Zahradnictví Horáček nabízí kompletní zahradnické práce v Liberci – sekání trávníků, výsadbu rostlin a zakládání zahrad. Zahradník Liberec zajistí pravidelnou údržbu zahrady pro soukromníky i firmy.', picturePath: null, active: true },
  { fullName: 'Green Garden Liberec', phone: '+420 485 456 234', email: 'info@greengarden-lbc.cz', serviceId: 'zahradnik', cityId: CITY, address: 'Rochlická 5678/73, Liberec 6', description: 'Green Garden je zahradní firma v Liberci nabízející návrhy a realizaci zahrad a teras. Zahradník Liberec provede kompletní terénní úpravy, automatické zavlažování a instalaci zahradních prvků.', picturePath: null, active: true },
  { fullName: 'Zahradní úpravy Novák Liberec', phone: '+420 728 441 780', email: null, serviceId: 'zahradnik', cityId: CITY, address: 'Moskevská 5678/81, Liberec 1', description: 'Zahradní úpravy Novák je zahradník v Liberci zajišťující terénní úpravy, výsadbu stromů a sezónní péči o zahrady. Zahradník Liberec nabídne osobní poradenství a realizaci zahradních projektů.', picturePath: null, active: true },
  { fullName: 'Arboristika Liberec – Haas', phone: '+420 603 017 890', email: 'haas@arboristika-lbc.cz', serviceId: 'zahradnik', cityId: CITY, address: 'Valdštejnská 5678/79, Liberec 1', description: 'Arboristika Liberec Haas nabízí profesionální péči o stromy, kácení a ošetřování dřevin v Liberci. Zahradník Liberec provede výškové práce, redukci korun a odborné posudky zdraví stromů.', picturePath: null, active: true },

  // ── ÚKLID ────────────────────────────────────────────────────────────────
  { fullName: 'Čistota Liberec – úklidová firma', phone: '+420 485 890 234', email: 'info@cistota-liberec.cz', serviceId: 'uklid', cityId: CITY, address: 'Sokolská 5678/83, Liberec 1', description: 'Čistota Liberec je profesionální úklidová firma nabízející pravidelný i jednorázový úklid bytů a kanceláří v Liberci. Úklid Liberec zajistí čisté prostředí s ekologickými čisticími prostředky.', picturePath: null, active: true },
  { fullName: 'CleanPro Liberec', phone: '+420 602 778 901', email: 'cleanpro@uklid-liberec.cz', serviceId: 'uklid', cityId: CITY, address: 'Rumjancevova 4567/65, Liberec 1', description: 'CleanPro je úklidová společnost v Liberci specializující se na úklid po rekonstrukci a generální úklid domácností. Úklid Liberec nabídne rychlý nástup a záruky spokojenosti na veškeré práce.', picturePath: null, active: true },
  { fullName: 'Paní na úklid Liberec – Nováčková', phone: '+420 728 456 789', email: null, serviceId: 'uklid', cityId: CITY, address: 'Jablonecká 7890/109, Liberec 5', description: 'Paní Nováčková nabízí pravidelný domácí úklid bytů a domů v Liberci s osobním přístupem a spolehlivostí. Úklid Liberec – domácí pomoc pro rodiny a seniory v Liberci a přilehlém okolí.', picturePath: null, active: true },
  { fullName: 'TopClean Liberec', phone: '+420 485 345 678', email: 'info@topclean-liberec.cz', serviceId: 'uklid', cityId: CITY, address: 'Moskevská 6789/99, Liberec 1', description: 'TopClean je úklidová firma v Liberci s komplexní nabídkou čistění koberců, čalounění a mytí oken. Úklid Liberec provádí profesionální dezinfekce a sanace bytů, kanceláří i průmyslových prostor.', picturePath: null, active: true },

  // ── STĚHOVACÍ FIRMA ──────────────────────────────────────────────────────
  { fullName: 'Stěhování Liberec – Novák Transport', phone: '+420 485 334 120', email: 'novak@stehovanilbc.cz', serviceId: 'stehovaci-firma', cityId: CITY, address: 'Sokolská 7890/107, Liberec 1', description: 'Stěhování Liberec Novák Transport nabízí profesionální stěhování bytů, kanceláří a firem v Liberci a celé ČR. Stěhovací firma Liberec zajistí bezpečné zabalení, přepravu a složení nábytku.', picturePath: null, active: true },
  { fullName: 'Fast Move Liberec', phone: '+420 602 791 345', email: 'info@fastmove-lbc.cz', serviceId: 'stehovaci-firma', cityId: CITY, address: 'Rumjancevova 5678/83, Liberec 1', description: 'Fast Move je rychlá stěhovací firma v Liberci zajišťující stěhování bytů i firem s vlastním vozovým parkem. Stěhovací firma Liberec nabídne bezpečnostní balení, demontáž a montáž nábytku.', picturePath: null, active: true },
  { fullName: 'Stěhování Holub Liberec', phone: '+420 728 678 234', email: null, serviceId: 'stehovaci-firma', cityId: CITY, address: 'Jablonecká 8901/123, Liberec 5', description: 'Stěhování Holub je spolehlivá stěhovací firma v Liberci s vlastními stěhovacími vozidly a pojištěním nákladu. Stěhovací firma Liberec realizuje stěhování po Liberci i mezinárodní přepravu.', picturePath: null, active: true },
  { fullName: 'Profi Stěhování Liberec', phone: '+420 603 234 890', email: 'profistehov@lbc-move.cz', serviceId: 'stehovaci-firma', cityId: CITY, address: 'Valdštejnská 6789/95, Liberec 1', description: 'Profi Stěhování Liberec je komplexní stěhovací firma pro domácnosti i firmy v Libereckém kraji. Stěhovací firma Liberec zajistí expresní i plánované stěhování s péčí o každý kus majetku.', picturePath: null, active: true },

  // ── TRENÉR ───────────────────────────────────────────────────────────────
  { fullName: 'Fitness trenér Holík Liberec', phone: '+420 728 441 890', email: 'holik@fitnes-liberec.cz', serviceId: 'trener', cityId: CITY, address: 'Sokolská 8901/121, Liberec 1', description: 'Fitness trenér Holík je osobní trenér v Liberci nabízející tréninkové plány a nutriční poradenství. Trenér Liberec pomůže s hubnutím, nabíráním svalové hmoty a zlepšením kondice.', picturePath: null, active: true },
  { fullName: 'Monika Dvořáková – osobní trenérka Liberec', phone: '+420 485 560 234', email: 'dvorakova@trener-lbc.cz', serviceId: 'trener', cityId: CITY, address: 'Rumjancevova 6789/97, Liberec 1', description: 'Monika Dvořáková je certifikovaná osobní trenérka v Liberci specializující se na funkční trénink a pilates. Trenér Liberec nabídne individuální fitness program pro dosažení zdravotních i sportovních cílů.', picturePath: null, active: true },
  { fullName: 'Sportovní centrum Liberec – Novák', phone: '+420 485 455 666', email: 'info@sportlbc.cz', serviceId: 'trener', cityId: CITY, address: 'Školní 900/3, Liberec 2', description: 'Sportovní centrum Novák nabízí trenéry a sportovní kurzy pro děti i dospělé v Liberci. Trenér Liberec zajistí kondičníkurzy, skupinové lekce jógy a fitness tréninky v moderně vybaveném centru.', picturePath: null, active: true },
  { fullName: 'Mgr. Beneš – trenér atletiky Liberec', phone: '+420 728 228 901', email: null, serviceId: 'trener', cityId: CITY, address: 'Jablonecká 9012/134, Liberec 5', description: 'Mgr. Beneš je trenér atletiky a kondičního tréninku v Liberci s licencí ČAS. Trenér Liberec pracuje s dětmi, juniory i dospělými závodníky na atletickém stadionu v Liberci.', picturePath: null, active: true },

  // ── PŘEKLADATEL ──────────────────────────────────────────────────────────
  { fullName: 'Překladatelské centrum Liberec', phone: '+420 485 441 760', email: 'info@prekladlbc.cz', serviceId: 'prekladatel', cityId: CITY, address: 'Náměstí Dr. E. Beneše 41, Liberec 1', description: 'Překladatelské centrum Liberec nabízí odborné překlady z němčiny, angličtiny a dalších jazyků pro firmy i jednotlivce. Překladatel Liberec zajistí přesné překlady smluv, technických dokumentů a úředních listin.', picturePath: null, active: true },
  { fullName: 'Mgr. Nováková – překladatelka Liberec', phone: '+420 728 778 450', email: 'novakova@prekladlbc.cz', serviceId: 'prekladatel', cityId: CITY, address: 'Moskevská 2345/32, Liberec 1', description: 'Mgr. Nováková je soudní překladatelka pro němčinu a angličtinu v Liberci s oprávněním od Krajského soudu. Překladatel Liberec provede úřední překlady dokumentů pro státní orgány a instituce.', picturePath: null, active: true },
  { fullName: 'ProTranslate Liberec', phone: '+420 485 229 112', email: 'info@protranslate-lbc.cz', serviceId: 'prekladatel', cityId: CITY, address: '1. máje 2345/39, Liberec 1', description: 'ProTranslate je překladatelská agentura v Liberci zajišťující překlady do více než 25 jazyků pro firmy a instituce. Překladatel Liberec nabídne expresní i standardní překlad s garancí kvality.', picturePath: null, active: true },
  { fullName: 'Bc. Horáčková – tlumočnice Liberec', phone: '+420 602 113 456', email: null, serviceId: 'prekladatel', cityId: CITY, address: 'Sokolská 2345/40, Liberec 1', description: 'Bc. Horáčková je překladatelka a tlumočnice pro angličtinu a němčinu v Liberci. Překladatel Liberec nabízí konsekutivní tlumočení na konferencích, jednáních a firemních akcích.', picturePath: null, active: true },

  // ── GRAFIK ───────────────────────────────────────────────────────────────
  { fullName: 'Grafické studio Novák Liberec', phone: '+420 485 450 890', email: 'novak@grafika-lbc.cz', serviceId: 'grafik', cityId: CITY, address: 'Náměstí Dr. E. Beneše 52, Liberec 1', description: 'Grafické studio Novák nabízí komplexní grafické služby v Liberci – loga, firemní identitu, tisk a webdesign. Grafik Liberec zajistí profesionální vizuální komunikaci pro firmy v Libereckém kraji.', picturePath: null, active: true },
  { fullName: 'PixelArt Liberec – grafický design', phone: '+420 728 334 780', email: 'info@pixelart-lbc.cz', serviceId: 'grafik', cityId: CITY, address: 'Moskevská 3456/47, Liberec 1', description: 'PixelArt Liberec je grafické studio specializující se na digitální design, tvorbu webů a reklamní kampaně. Grafik Liberec nabídne kreativní řešení pro marketing a branding firem.', picturePath: null, active: true },
  { fullName: 'Bc. Horáčková – grafička Liberec', phone: '+420 602 887 123', email: 'horackovagrafika@liberec.cz', serviceId: 'grafik', cityId: CITY, address: '1. máje 4567/67, Liberec 1', description: 'Bc. Horáčková je freelance grafička v Liberci nabízející návrhy letáků, plakátů a obalového designu. Grafik Liberec pracuje pro agentury i přímé klienty s rychlými dodacími lhůtami.', picturePath: null, active: true },
  { fullName: 'Studia Kreativa Liberec', phone: '+420 485 556 890', email: 'studio@kreativa-lbc.cz', serviceId: 'grafik', cityId: CITY, address: 'Sokolská 4567/63, Liberec 1', description: 'Studia Kreativa je grafická agentura v Liberci s kompletními kreativními službami – logo, web, video a sociální sítě. Grafik Liberec pomůže firmám budovat silnou vizuální značku a efektivní online prezentaci.', picturePath: null, active: true },
];

async function main() {
  let count = 0;
  for (const p of profiles) {
    const created = await prisma.provider.create({ data: p });
    console.log(`✓ ${created.fullName}`);
    count++;
  }
  console.log(`\nDone. Added ${count} profiles.`);
}
main().catch(console.error).finally(() => prisma.$disconnect());
