import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();
const CITY = 'ostrava';

const profiles = [
  // ── ELEKTRIKÁŘ ────────────────────────────────────────────────────────────
  { fullName: 'Elektro Vávra Ostrava', phone: '+420 731 224 556', email: 'info@elektrovavra.cz', serviceId: 'elektrikar', cityId: CITY, address: 'Nádražní 28, Ostrava', description: 'Elektro Vávra nabízí veškeré elektroinstalační práce pro domácnosti i firmy v Ostravě. Elektrikář Ostrava zajišťuje montáž rozvaděčů, elektrorevize a havarijní opravy 24 hodin denně.', picturePath: null, active: true },
  { fullName: 'Jiří Blaha – elektrikář Ostrava', phone: '+420 776 334 118', email: null, serviceId: 'elektrikar', cityId: CITY, address: 'Jurečkova 14, Ostrava', description: 'Jiří Blaha provádí komplexní elektroinstalace a opravy v Ostravě s více než 12 lety praxe. Elektrikář v Ostravě nabízí rychlé výjezdy a instalaci osvětlení pro byty i průmyslové objekty.', picturePath: null, active: true },
  { fullName: 'ELEKTROSERVIS Ostrava s.r.o.', phone: '+420 596 112 345', email: 'info@elektroservis-ostrava.cz', serviceId: 'elektrikar', cityId: CITY, address: '28. října 117, Ostrava', description: 'ELEKTROSERVIS Ostrava se specializuje na silnoproudé a slaboproudé elektroinstalace v Ostravě a Moravskoslezském kraji. Firma zajišťuje projekci, montáž i revize elektrických zařízení.', picturePath: null, active: true },
  { fullName: 'Pavel Horáček – elektroinstalace Ostrava', phone: '+420 608 447 229', email: 'horacek@elektro-ostrava.cz', serviceId: 'elektrikar', cityId: CITY, address: 'Sokolská 33, Ostrava', description: 'Pavel Horáček je zkušený elektrikář v Ostravě zaměřený na rekonstrukce bytů a rodinných domů. Provádí veškeré elektroinstalační práce v Ostravě včetně montáže fotovoltaiky.', picturePath: null, active: true },

  // ── INSTALATÉR ────────────────────────────────────────────────────────────
  { fullName: 'Instalatér Ostrava – Radek Kolář', phone: '+420 731 558 224', email: 'kolar.instalater@seznam.cz', serviceId: 'instalater', cityId: CITY, address: 'Zámecká 8, Ostrava', description: 'Radek Kolář nabízí profesionální instalatérské a topenářské práce v Ostravě a okolí. Instalatér Ostrava zajišťuje montáž, opravy a rekonstrukce vodovodních rozvodů a topných systémů.', picturePath: null, active: true },
  { fullName: 'Vodo-topo Blažek Ostrava', phone: '+420 596 225 678', email: 'info@vodotopo-ostrava.cz', serviceId: 'instalater', cityId: CITY, address: 'Hornopolní 22, Ostrava', description: 'Vodo-topo Blažek je zavedená instalatérská firma v Ostravě s tradicí od roku 2001. Instalatér Ostrava provádí montáž kotlů, podlahového vytápění a kompletní rekonstrukce koupelen.', picturePath: null, active: true },
  { fullName: 'Nonstop instalatér Ostrava', phone: '+420 800 200 400', email: 'info@instalater-ostrava.cz', serviceId: 'instalater', cityId: CITY, address: 'Nádražní 55, Ostrava', description: 'Nonstop instalatér Ostrava zajišťuje havarijní opravy vody a kanalizace 24/7. Rychlý výjezd instalatéra po celé Ostravě do 30 minut od zavolání.', picturePath: null, active: true },
  { fullName: 'Martin Šimánek – instalatér Ostrava', phone: '+420 776 113 448', email: null, serviceId: 'instalater', cityId: CITY, address: 'Závodní 84, Ostrava – Vítkovice', description: 'Martin Šimánek poskytuje instalatérské služby v Ostravě zaměřené na montáž a opravy vodovodních baterií a sanitárního zařízení. Instalatér Ostrava nabízí rychlý servis pro domácnosti i firmy.', picturePath: null, active: true },

  // ── MALÍŘ ─────────────────────────────────────────────────────────────────
  { fullName: 'Malíř pokojů Ostrava – Tomáš Vrána', phone: '+420 608 334 667', email: 'vrana.malir@gmail.com', serviceId: 'malir', cityId: CITY, address: 'Sokolská 12, Ostrava', description: 'Tomáš Vrána je profesionální malíř pokojů v Ostravě s více než 18 lety zkušeností. Malíř Ostrava nabízí kompletní malování bytů, kanceláří a průmyslových prostor za přijatelné ceny.', picturePath: null, active: true },
  { fullName: 'Malířství Krejčí Ostrava', phone: '+420 776 221 334', email: 'krejci.malir@seznam.cz', serviceId: 'malir', cityId: CITY, address: 'Výstavní 10, Ostrava – Hrabůvka', description: 'Malířství Krejčí nabízí profesionální malování bytů, domů a komerčních prostor v Ostravě. Malíř pokojů Ostrava zajišťuje výmalby, nátěry fasád a dekorativní techniky.', picturePath: null, active: true },
  { fullName: 'Petr Šula – malíř Ostrava', phone: '+420 731 445 228', email: null, serviceId: 'malir', cityId: CITY, address: 'Ostrava – Poruba', description: 'Petr Šula provádí malířské a natěračské práce v Ostravě pro domácnosti i firmy za konkurenční ceny. Malíř Ostrava se zaměřuje na rekonstrukce bytů a nátěry fasád.', picturePath: null, active: true },
  { fullName: 'MALOV-OSTRAVA s.r.o.', phone: '+420 596 445 778', email: 'info@malov-ostrava.cz', serviceId: 'malir', cityId: CITY, address: '28. října 55, Ostrava', description: 'MALOV-OSTRAVA je zavedená malířská firma v Ostravě realizující zakázky pro soukromé i firemní klienty. Malíř pokojů Ostrava provádí stříkání barev, termoizolační nátěry a ochranu proti vlhkosti.', picturePath: null, active: true },

  // ── TESAŘ ─────────────────────────────────────────────────────────────────
  { fullName: 'Tesařství Novák Ostrava', phone: '+420 731 228 441', email: 'novak@tesar-ostrava.cz', serviceId: 'tesar', cityId: CITY, address: 'Pohraniční 52, Ostrava – Hrabová', description: 'Tesařství Novák nabízí komplexní tesařské práce v Ostravě – stavba krovů, střešních konstrukcí a pergol. Tesař Ostrava realizuje zakázky pro rodinné domy i bytové komplexy v Moravskoslezském kraji.', picturePath: null, active: true },
  { fullName: 'Radek Polách – tesař Ostrava', phone: '+420 776 554 227', email: null, serviceId: 'tesar', cityId: CITY, address: 'Ostrava – Třebovice', description: 'Radek Polách je zkušený tesař v Ostravě specializující se na dřevěné střešní konstrukce a přestavby podkroví. Tesař Ostrava provádí veškeré dřevěné konstrukce pro novostavby i rekonstrukce.', picturePath: null, active: true },
  { fullName: 'DŘEVOSTAVBY Ostrava s.r.o.', phone: '+420 596 334 119', email: 'info@drevostavby-ostrava.cz', serviceId: 'tesar', cityId: CITY, address: 'Místecká 45, Ostrava – Hrabová', description: 'DŘEVOSTAVBY Ostrava realizuje dřevěné stavby, krovy a zahradní altány v Ostravě a okolí. Tesař Ostrava nabízí kompletní tesařské práce na klíč s dodržením termínů a garancí kvality.', picturePath: null, active: true },
  { fullName: 'Ladislav Baran – tesař a pokrývač Ostrava', phone: '+420 608 229 554', email: null, serviceId: 'tesar', cityId: CITY, address: 'Rudná 87, Ostrava – Svinov', description: 'Ladislav Baran nabízí tesařské a pokrývačské práce v Ostravě včetně stavby krovů a zateplení střech. Tesař Ostrava garantuje precizní provedení a rychlé dokončení zakázky.', picturePath: null, active: true },

  // ── TRUHLÁŘ ───────────────────────────────────────────────────────────────
  { fullName: 'Truhlářství Dvořák Ostrava', phone: '+420 596 225 441', email: 'info@truhlarstvi-dvorak-ostrava.cz', serviceId: 'truhlar', cityId: CITY, address: 'Frýdlantská 18, Ostrava – Ostrava-Jih', description: 'Truhlářství Dvořák vyrábí nábytek na míru a provádí truhlářské práce v Ostravě již přes 20 let. Truhlář Ostrava nabízí výrobu kuchyňských linek, vestavěných skříní a dřevěných schodišť.', picturePath: null, active: true },
  { fullName: 'ARTWOOD Ostrava – nábytek na míru', phone: '+420 731 447 335', email: 'artwood@ostrava.cz', serviceId: 'truhlar', cityId: CITY, address: 'Nádražní 100, Ostrava', description: 'ARTWOOD Ostrava je moderní truhlářství zaměřené na výrobu designového nábytku v Ostravě. Truhlář Ostrava zpracovává zakázky od projektu přes výrobu až po montáž u zákazníka.', picturePath: null, active: true },
  { fullName: 'František Vávra – truhlář Ostrava', phone: '+420 776 338 112', email: null, serviceId: 'truhlar', cityId: CITY, address: 'Ostrava – Poruba', description: 'František Vávra je zkušený truhlář v Ostravě nabízející výrobu a montáž nábytku, schodišť a parket. Truhlář Ostrava pracuje s masivním dřevem i moderními materiály dle přání zákazníka.', picturePath: null, active: true },
  { fullName: 'Interiéry Ostrava – Kratochvíl', phone: '+420 596 557 229', email: 'kratochvil@interiery-ostrava.cz', serviceId: 'truhlar', cityId: CITY, address: 'Hornopolní 44, Ostrava', description: 'Kratochvíl interiéry vyrábí nábytek na míru a interiérové prvky pro zákazníky v Ostravě. Truhlář Ostrava se specializuje na vestavěné skříně, kuchyně a posuvné dveřní systémy.', picturePath: null, active: true },

  // ── ZUBAŘ ─────────────────────────────────────────────────────────────────
  { fullName: 'MUDr. Jana Poláchová – zubní ordinace Ostrava', phone: '+420 596 112 667', email: 'polachova@zubar-ostrava.cz', serviceId: 'zubar', cityId: CITY, address: 'Nádražní 18, Ostrava', description: 'MUDr. Jana Poláchová provozuje moderní zubní ordinaci v centru Ostravy s komplexní péčí pro dospělé i děti. Zubař Ostrava nabízí preventivní prohlídky, bělení zubů, implantáty a estetickou stomatologii.', picturePath: null, active: true },
  { fullName: 'MDDr. Pavel Krejčí – zubař Ostrava', phone: '+420 731 556 448', email: null, serviceId: 'zubar', cityId: CITY, address: 'Jurečkova 20, Ostrava – Moravská Ostrava', description: 'MDDr. Pavel Krejčí vede zubní ordinaci v Ostravě zaměřenou na bezbolestné ošetření a moderní stomatologii. Zubař Ostrava přijímá nové pacienty a nabízí pohotovostní ošetření.', picturePath: null, active: true },
  { fullName: 'Stomatologie Ostrava – MUDr. Eva Horáčková', phone: '+420 596 445 889', email: 'horáčková@stomatologie-ostrava.cz', serviceId: 'zubar', cityId: CITY, address: 'Sokolská 52, Ostrava', description: 'MUDr. Eva Horáčková provozuje stomatologickou ordinaci v Ostravě se specializací na protetiku a implantologii. Zubní ordinace Ostrava nabízí celistvou péči o chrup od prevence přes léčbu.', picturePath: null, active: true },
  { fullName: 'Zubní klinika Ostrava Centrum', phone: '+420 596 223 447', email: 'info@zubniklinka-ostrava.cz', serviceId: 'zubar', cityId: CITY, address: '28. října 33, Ostrava', description: 'Zubní klinika Ostrava Centrum poskytuje komplexní stomatologické služby v Ostravě včetně ortodoncie. Zubař Ostrava přijímá pacienty všech věkových kategorií a nabízí pohodlné ošetření.', picturePath: null, active: true },

  // ── STĚHOVÁNÍ ─────────────────────────────────────────────────────────────
  { fullName: 'Stěhování Ostrava – Rychlý přesun', phone: '+420 731 447 226', email: 'info@stehovani-ostrava.cz', serviceId: 'stehovaci-firma', cityId: CITY, address: 'Nádražní 78, Ostrava', description: 'Rychlý přesun Ostrava zajišťuje spolehlivé stěhování bytů, domů a kanceláří po celé Ostravě. Stěhovací firma Ostrava nabízí balení, transport i montáž nábytku v cílovém místě.', picturePath: null, active: true },
  { fullName: 'MOVERS Ostrava s.r.o.', phone: '+420 596 334 778', email: 'info@movers-ostrava.cz', serviceId: 'stehovaci-firma', cityId: CITY, address: 'Místecká 22, Ostrava', description: 'MOVERS Ostrava je profesionální stěhovací firma s moderním vybavením v Ostravě. Stěhování Ostrava pro byty, kanceláře i průmyslové provozy v rámci celého Moravskoslezského kraje.', picturePath: null, active: true },
  { fullName: 'Stěhovací firma Beneš Ostrava', phone: '+420 776 228 445', email: null, serviceId: 'stehovaci-firma', cityId: CITY, address: 'Závodní 15, Ostrava – Vítkovice', description: 'Beneš stěhování nabízí spolehlivé a cenově dostupné stěhování v Ostravě a okolí. Stěhovací firma Ostrava zajišťuje ochranu nábytku, odvoz odpadu a vyklizení bytů na klíč.', picturePath: null, active: true },
  { fullName: 'EXPRESS Stěhování Ostrava', phone: '+420 608 558 337', email: 'express@stehovani-ostrava.cz', serviceId: 'stehovaci-firma', cityId: CITY, address: 'Hornopolní 66, Ostrava', description: 'EXPRESS Stěhování Ostrava zajišťuje rychlé a bezpečné stěhování pro domácnosti i firmy. Stěhovací firma Ostrava disponuje vlastními vozy a zkušenou posádkou dostupnou 7 dní v týdnu.', picturePath: null, active: true },

  // ── ZAHRADNÍK ─────────────────────────────────────────────────────────────
  { fullName: 'Zahradnictví Ostrava – Petr Marek', phone: '+420 731 336 558', email: 'zahrada@marek-ostrava.cz', serviceId: 'zahradnik', cityId: CITY, address: 'Výstavní 33, Ostrava – Hrabová', description: 'Petr Marek nabízí komplexní zahradnické práce v Ostravě – zakládání zahrad, pravidelná údržba a terénní úpravy. Zahradník Ostrava provádí sekání trávníku, stříhání živých plotů a výsadbu.', picturePath: null, active: true },
  { fullName: 'Green Ostrava – zahradní služby', phone: '+420 776 445 119', email: 'info@green-ostrava.cz', serviceId: 'zahradnik', cityId: CITY, address: 'Ostrava – Poruba', description: 'Green Ostrava je profesionální zahradnická firma nabízející návrh, realizaci a údržbu zahrad v Ostravě. Zahradník Ostrava se specializuje na anglické trávníky, závlahové systémy a realizaci zahrad na klíč.', picturePath: null, active: true },
  { fullName: 'Zahradnické práce Ostrava – Horáček', phone: '+420 608 447 221', email: null, serviceId: 'zahradnik', cityId: CITY, address: 'Ostrava – Svinov', description: 'Horáček zahradnictví zajišťuje veškeré zahradnické práce pro soukromé zahrady i firemní areály v Ostravě. Zahradník Ostrava nabízí celoroční péči o zahradu a likvidaci zahradního odpadu.', picturePath: null, active: true },
  { fullName: 'Zahradní centrum FLORA Ostrava', phone: '+420 596 558 334', email: 'flora@zahrada-ostrava.cz', serviceId: 'zahradnik', cityId: CITY, address: 'Místecká 110, Ostrava – Hrabová', description: 'FLORA Ostrava je zahradnická firma s dlouholetou tradicí specializující se na zakládání a obnovu zahrad v Ostravě. Zahradník Ostrava provádí výsadbu stromů, keřů a trvalkových záhonů.', picturePath: null, active: true },

  // ── ÚKLID ─────────────────────────────────────────────────────────────────
  { fullName: 'Úklidová firma ProClean Ostrava', phone: '+420 731 229 443', email: 'info@proclean-ostrava.cz', serviceId: 'uklid', cityId: CITY, address: 'Nádražní 44, Ostrava', description: 'ProClean Ostrava nabízí profesionální úklidové služby pro domácnosti, kanceláře a průmyslové prostory. Úklidová firma Ostrava provádí generální úklidy, čištění koberců a mytí oken.', picturePath: null, active: true },
  { fullName: 'CleanService Ostrava s.r.o.', phone: '+420 596 441 667', email: 'clean@cleanservice-ostrava.cz', serviceId: 'uklid', cityId: CITY, address: 'Sokolská 77, Ostrava', description: 'CleanService Ostrava je spolehlivá úklidová firma v Ostravě poskytující pravidelný i jednorázový úklid. Úklid Ostrava zajišťuje diskrétní a kvalitní úklidové služby s ekologickými prostředky.', picturePath: null, active: true },
  { fullName: 'Úklid Ostrava – Jana Šimková', phone: '+420 776 664 118', email: null, serviceId: 'uklid', cityId: CITY, address: 'Ostrava – Zábřeh', description: 'Jana Šimková nabízí spolehlivý úklid bytů a domácností v Ostravě za příznivé ceny. Úklid Ostrava zahrnuje pravidelné i generální čištění, žehlení a péči o domácnost.', picturePath: null, active: true },
  { fullName: 'TOP Čistota Ostrava', phone: '+420 608 338 227', email: 'info@top-cistota-ostrava.cz', serviceId: 'uklid', cityId: CITY, address: 'Hornopolní 29, Ostrava', description: 'TOP Čistota Ostrava poskytuje prémiové úklidové služby pro domácnosti a firmy v Ostravě. Úklidová firma Ostrava nabízí čištění po rekonstrukci, dezinfekci a mytí fasád budov.', picturePath: null, active: true },

  // ── ZEDNÍK ────────────────────────────────────────────────────────────────
  { fullName: 'Zednické práce Ostrava – Pavel Horák', phone: '+420 731 441 223', email: 'horak.zednik@email.cz', serviceId: 'zednik', cityId: CITY, address: 'Ostrava – Poruba', description: 'Pavel Horák nabízí kompletní zednické a stavební práce v Ostravě zahrnující rekonstrukce bytů, omítky a obklady. Zedník Ostrava provádí zakázky pro soukromé i komerční zákazníky.', picturePath: null, active: true },
  { fullName: 'STAVOSTRAVA s.r.o.', phone: '+420 596 667 228', email: 'info@stavostrava.cz', serviceId: 'zednik', cityId: CITY, address: 'Nádražní 122, Ostrava', description: 'STAVOSTRAVA je stavební firma v Ostravě nabízející kompletní zednické práce, rekonstrukce a novostavby. Zedník Ostrava zajišťuje zdění, omítání, pokládku dlažby a veškeré stavební práce na klíč.', picturePath: null, active: true },
  { fullName: 'Michal Blažek – zedník Ostrava', phone: '+420 776 558 334', email: null, serviceId: 'zednik', cityId: CITY, address: 'Ostrava – Hrabůvka', description: 'Michal Blažek je zkušený zedník v Ostravě nabízející rekonstrukce koupelen a pokládku dlažby. Zedník Ostrava pracuje precizně a s garancí kvality pro zákazníky v celé Ostravě.', picturePath: null, active: true },
  { fullName: 'Rekonstrukce bytů Ostrava – Sedlák', phone: '+420 608 221 447', email: 'sedlak.stavby@gmail.com', serviceId: 'zednik', cityId: CITY, address: 'Závodní 88, Ostrava – Vítkovice', description: 'Sedlák rekonstrukce nabízí komplexní stavební a zednické práce v Ostravě se zaměřením na rekonstrukce bytů. Zedník Ostrava provádí sádrokartony, obklady, omítky a celkové přestavby interiérů.', picturePath: null, active: true },

  // ── IT TECHNIK ────────────────────────────────────────────────────────────
  { fullName: 'PC Servis Ostrava', phone: '+420 596 214 778', email: 'info@pcservis-ostrava.cz', serviceId: 'it-technik', cityId: CITY, address: 'Nádražní 12, Ostrava', description: 'PC Servis Ostrava nabízí kompletní počítačový servis a IT podporu pro firmy i domácnosti. IT technik Ostrava zajišťuje opravy notebooků, správu sítí a instalaci softwaru s rychlým výjezdem.', picturePath: null, active: true },
  { fullName: 'IT Pohotovost Ostrava', phone: '+420 776 663 441', email: 'pohotovost@it-ostrava.cz', serviceId: 'it-technik', cityId: CITY, address: 'Sokolská 53, Ostrava', description: 'IT Pohotovost Ostrava je nonstop počítačový servis dostupný 24/7 pro zákazníky v Ostravě. IT technik Ostrava řeší opravy počítačů, obnovu dat a správu IT infrastruktury firem.', picturePath: null, active: true },
  { fullName: 'TechServis Ostrava s.r.o.', phone: '+420 596 776 118', email: 'help@techservis-ostrava.cz', serviceId: 'it-technik', cityId: CITY, address: 'Hornopolní 35, Ostrava', description: 'TechServis Ostrava je specializovaná IT firma poskytující servis počítačů, serverů a počítačových sítí. IT technik Ostrava nabízí cloudové řešení, zálohování dat a kybernetickou bezpečnost.', picturePath: null, active: true },
  { fullName: 'Ondřej Mašek – IT technik Ostrava', phone: '+420 731 884 557', email: null, serviceId: 'it-technik', cityId: CITY, address: 'Ostrava – Poruba', description: 'Ondřej Mašek je zkušený IT technik v Ostravě poskytující servis a opravy počítačů pro domácnosti i malé firmy. IT podpora Ostrava zahrnuje instalaci systémů, nastavení sítě a opravu závad.', picturePath: null, active: true },

  // ── ÚČETNÍ ────────────────────────────────────────────────────────────────
  { fullName: 'Ing. Petra Blažková – účetní Ostrava', phone: '+420 596 221 889', email: 'blazkova@ucetni-ostrava.cz', serviceId: 'ucetni', cityId: CITY, address: 'Nádražní 18, Ostrava', description: 'Ing. Petra Blažková nabízí komplexní účetní a daňové poradenství pro firmy i živnostníky v Ostravě. Účetní Ostrava zajišťuje vedení účetnictví, zpracování mezd a daňová přiznání.', picturePath: null, active: true },
  { fullName: 'ÚČTO Ostrava s.r.o.', phone: '+420 776 334 662', email: 'info@ucto-ostrava.cz', serviceId: 'ucetni', cityId: CITY, address: 'Jurečkova 28, Ostrava', description: 'ÚČTO Ostrava je moderní účetní kancelář poskytující vedení účetnictví a daňové poradenství v Ostravě. Účetní firma Ostrava spolupracuje s malými i středními podniky a nabízí online účetnictví.', picturePath: null, active: true },
  { fullName: 'Daňová kancelář Ostrava – Ing. Novák', phone: '+420 596 558 334', email: 'novak@dane-ostrava.cz', serviceId: 'ucetni', cityId: CITY, address: 'Sokolská 22, Ostrava', description: 'Ing. Novák vede daňovou kancelář v Ostravě s více než 15 lety praxe v oblasti účetnictví a daní. Účetní Ostrava zpracovává daňová přiznání, roční uzávěrky a zastupuje klienty na finančním úřadu.', picturePath: null, active: true },
  { fullName: 'Účetnictví Ostrava – Horáčková', phone: '+420 608 447 229', email: null, serviceId: 'ucetni', cityId: CITY, address: 'Ostrava – Zábřeh', description: 'Horáčková účetnictví nabízí vedení podvojného i jednoduchého účetnictví pro firmy v Ostravě. Účetní Ostrava se specializuje na IT firmy a freelancery s garancí přesnosti a termínů.', picturePath: null, active: true },

  // ── PRÁVNÍK ───────────────────────────────────────────────────────────────
  { fullName: 'JUDr. Karel Novák – advokát Ostrava', phone: '+420 596 215 667', email: 'ak@novak-ostrava.cz', serviceId: 'pravnik', cityId: CITY, address: 'Nádražní 34, Ostrava', description: 'JUDr. Karel Novák je zkušený advokát v Ostravě zaměřený na obchodní právo a nemovitosti. Advokátní kancelář Ostrava poskytuje právní poradenství fyzickým i právnickým osobám.', picturePath: null, active: true },
  { fullName: 'Mgr. Eva Horáčková – advokátka Ostrava', phone: '+420 776 229 441', email: 'horačková@advokatostrava.cz', serviceId: 'pravnik', cityId: CITY, address: 'Jurečkova 4, Ostrava', description: 'Mgr. Eva Horáčková je advokátka v Ostravě specializující se na rodinné právo a pracovní spory. Právník Ostrava nabízí konzultace a zastoupení před soudem v celé České republice.', picturePath: null, active: true },
  { fullName: 'AK IUSTITIA Ostrava s.r.o.', phone: '+420 596 336 778', email: 'info@iustitia-ostrava.cz', serviceId: 'pravnik', cityId: CITY, address: 'Sokolská 16, Ostrava', description: 'Advokátní kancelář IUSTITIA Ostrava poskytuje komplexní právní služby pro firmy i jednotlivce. Právník Ostrava se specializuje na obchodní právo, trestní obhajobu a správní řízení.', picturePath: null, active: true },
  { fullName: 'JUDr. Tomáš Sedlák – advokát Ostrava', phone: '+420 731 665 228', email: 't.sedlak@advokatostrava.cz', serviceId: 'pravnik', cityId: CITY, address: '28. října 71, Ostrava', description: 'JUDr. Tomáš Sedlák je advokát v Ostravě s praxí v oblasti trestního práva a civilních sporů. Právník Ostrava zastupuje klienty před všemi stupni soudů v Moravskoslezském kraji.', picturePath: null, active: true },

  // ── AUTOSERVIS ────────────────────────────────────────────────────────────
  { fullName: 'Autoservis Ostrava – Vávra', phone: '+420 596 441 226', email: 'vavra@autoservis-ostrava.cz', serviceId: 'autoservis', cityId: CITY, address: 'Místecká 828, Ostrava – Hrabová', description: 'Autoservis Vávra v Ostravě nabízí kompletní opravy a servis osobních i dodávkových vozidel. Autoservis Ostrava zajišťuje diagnostiku, výměnu oleje, brzd a pravidelné servisní prohlídky.', picturePath: null, active: true },
  { fullName: 'Bosch Servis Ostrava – AutoTech', phone: '+420 596 528 711', email: 'autotech@bosch-ostrava.cz', serviceId: 'autoservis', cityId: CITY, address: 'Rudná 119, Ostrava – Svinov', description: 'AutoTech je certifikovaný Bosch Car Service v Ostravě s komplexní nabídkou autoopravárenských služeb. Autoservis Ostrava provádí elektrodiagnostiku, klimatizaci a geometrii náprav.', picturePath: null, active: true },
  { fullName: 'AUTO-OPRAVNA Horáček Ostrava', phone: '+420 731 447 334', email: null, serviceId: 'autoservis', cityId: CITY, address: 'Závodní 222, Ostrava – Vítkovice', description: 'AUTO-OPRAVNA Horáček je rodinný autoservis v Ostravě s více než 15 lety zkušeností s opravami vozidel. Autoservis Ostrava zajišťuje klempířské práce, mechanické opravy a pneuservis.', picturePath: null, active: true },
  { fullName: 'Rychloservis Ostrava', phone: '+420 776 229 885', email: 'info@rychloservis-ostrava.cz', serviceId: 'autoservis', cityId: CITY, address: 'Hornopolní 64, Ostrava', description: 'Rychloservis Ostrava je autoservis zaměřený na rychlé a cenově dostupné opravy vozidel. Autoservis Ostrava nabízí výměnu oleje za 30 minut, opravu pneumatik a výměnu autoskel.', picturePath: null, active: true },

  // ── FOTOGRAF ──────────────────────────────────────────────────────────────
  { fullName: 'Ateliér Ostrava – Lukáš Veselý', phone: '+420 731 556 334', email: 'info@foto-vesely-ostrava.cz', serviceId: 'fotograf', cityId: CITY, address: 'Nádražní 15, Ostrava', description: 'Lukáš Veselý je profesionální fotograf v Ostravě zaměřený na svatební fotografii, portréty a firemní focení. Fotografické studio Ostrava nabízí kreativní přístup a moderní vybavení.', picturePath: null, active: true },
  { fullName: 'Foto Horáček – fotograf Ostrava', phone: '+420 596 221 778', email: 'studio@fotohoracek.cz', serviceId: 'fotograf', cityId: CITY, address: 'Sokolská 39, Ostrava', description: 'Foto Horáček je zavedené fotografické studio v Ostravě s tradicí od roku 2006. Fotograf Ostrava se specializuje na portrétní, rodinnou a produktovou fotografii.', picturePath: null, active: true },
  { fullName: 'Monika Bílá – fotografka Ostrava', phone: '+420 776 443 227', email: 'foto@monikabila-ostrava.cz', serviceId: 'fotograf', cityId: CITY, address: 'Ostrava – Poruba', description: 'Monika Bílá je fotografka v Ostravě specializující se na těhotenské, novorozenecké a rodinné fotografie. Fotograf Ostrava nabízí příjemnou atmosféru a profesionální výsledky.', picturePath: null, active: true },
  { fullName: 'Studio Vision Ostrava', phone: '+420 596 338 112', email: 'info@studiovision-ostrava.cz', serviceId: 'fotograf', cityId: CITY, address: 'Jurečkova 22, Ostrava', description: 'Studio Vision Ostrava je profesionální fotografické a video studio zaměřené na reklamní produkci. Fotograf Ostrava zajišťuje produktové focení, video reklamy a firemní prezentace.', picturePath: null, active: true },

  // ── KADEŘNÍK ──────────────────────────────────────────────────────────────
  { fullName: 'Kadeřnictví Salon Prestige Ostrava', phone: '+420 596 215 334', email: 'prestige@kadernictvi-ostrava.cz', serviceId: 'kadernik', cityId: CITY, address: 'Nádražní 12, Ostrava', description: 'Salon Prestige je prémiové kadeřnictví v centru Ostravy nabízející střihy, barvení a keratinové ošetření vlasů. Kadeřník Ostrava zajišťuje péči o vlasy pro muže i ženy.', picturePath: null, active: true },
  { fullName: 'Hair Studio Ostrava – Markéta', phone: '+420 776 221 558', email: null, serviceId: 'kadernik', cityId: CITY, address: 'Sokolská 23, Ostrava', description: 'Hair Studio Markéta je oblíbené kadeřnictví v Ostravě se specializací na moderní střihy a barvení. Kadeřník Ostrava nabízí konzultace zdarma a ošetření vlasů prémiovými produkty.', picturePath: null, active: true },
  { fullName: 'Kadeřnictví Martin Horák Ostrava', phone: '+420 731 558 443', email: 'martin@kadernik-ostrava.cz', serviceId: 'kadernik', cityId: CITY, address: 'Hornopolní 38, Ostrava', description: 'Martin Horák je zkušený kadeřník v Ostravě s více než 16 lety praxe v oboru péče o vlasy. Kadeřnictví Ostrava nabízí dámské i pánské střihy, trvalé, barvení a rekonstrukci vlasů.', picturePath: null, active: true },
  { fullName: 'TOP Kadeřnictví Ostrava', phone: '+420 596 778 229', email: 'info@top-kadernictvi-ostrava.cz', serviceId: 'kadernik', cityId: CITY, address: '28. října 27, Ostrava', description: 'TOP Kadeřnictví Ostrava je moderní salon nabízející komplexní vlasové služby pro celou rodinu v Ostravě. Kadeřník Ostrava provádí střihy, barvení, melírování a svatební účesy.', picturePath: null, active: true },

  // ── LÉKAŘ ─────────────────────────────────────────────────────────────────
  { fullName: 'MUDr. Jana Kopecká – praktická lékařka Ostrava', phone: '+420 596 213 778', email: 'kopecka@lekar-ostrava.cz', serviceId: 'lekar', cityId: CITY, address: 'Jurečkova 38, Ostrava', description: 'MUDr. Jana Kopecká je praktická lékařka v Ostravě přijímající nové pacienty. Ordinace praktického lékaře Ostrava nabízí preventivní prohlídky, očkování a doporučení ke specialistům.', picturePath: null, active: true },
  { fullName: 'MUDr. Petr Valenta – obvodní lékař Ostrava', phone: '+420 731 441 663', email: null, serviceId: 'lekar', cityId: CITY, address: 'Sokolská 62, Ostrava', description: 'MUDr. Petr Valenta vede ordinaci praktického lékaře pro dospělé v Ostravě. Lékař Ostrava zajišťuje odběry krve, EKG a pracovnělékařské prohlídky.', picturePath: null, active: true },
  { fullName: 'Poliklinika Ostrava – MUDr. Kratochvíl', phone: '+420 596 558 889', email: 'kratochvil@poliklinika-ostrava.cz', serviceId: 'lekar', cityId: CITY, address: 'Hornopolní 22, Ostrava', description: 'MUDr. Kratochvíl ordinuje jako praktický lékař v Ostravě v moderně vybavené poliklinice. Praktický lékař Ostrava přijímá nové pacienty a nabízí komplexní primární zdravotní péči.', picturePath: null, active: true },
  { fullName: 'MUDr. Alena Mrázová – lékař Ostrava', phone: '+420 776 334 558', email: 'mrazova@lekar-ostrava.cz', serviceId: 'lekar', cityId: CITY, address: 'Nádražní 48, Ostrava', description: 'MUDr. Alena Mrázová je praktická lékařka v Ostravě s individuálním přístupem k pacientům. Lékař Ostrava se specializuje na preventivní medicínu a léčbu chronických onemocnění.', picturePath: null, active: true },

  // ── KLEMPÍŘ ───────────────────────────────────────────────────────────────
  { fullName: 'Klempířství Ostrava – Jan Hrubý', phone: '+420 731 335 441', email: 'hruby@klempir-ostrava.cz', serviceId: 'klempir', cityId: CITY, address: 'Ostrava – Hrabová', description: 'Jan Hrubý je zkušený klempíř v Ostravě nabízející oplechování střech, výrobu okapových žlabů a opravy střešního pláště. Klempíř Ostrava provádí veškeré klempířské práce pro domy i bytové komplexy.', picturePath: null, active: true },
  { fullName: 'Střechy a klempířství Ostrava – Novák', phone: '+420 776 663 228', email: null, serviceId: 'klempir', cityId: CITY, address: 'Rudná 78, Ostrava – Svinov', description: 'Novák střechy a klempířství nabízí kompletní střešní a klempířské práce v Ostravě. Klempíř Ostrava provádí pokládku střešní krytiny, oplechování komínů a montáž střešních oken.', picturePath: null, active: true },
  { fullName: 'KLEM-OSTRAVA s.r.o.', phone: '+420 596 441 778', email: 'info@klem-ostrava.cz', serviceId: 'klempir', cityId: CITY, address: 'Závodní 15, Ostrava', description: 'KLEM-OSTRAVA je profesionální klempířská firma specializující se na oplechování atik, teras a balkonů v Ostravě. Klempíř Ostrava zajišťuje montáž titanzinkových a měděných klempířských prvků.', picturePath: null, active: true },
  { fullName: 'Josef Sedlák – klempíř a pokrývač Ostrava', phone: '+420 608 447 118', email: null, serviceId: 'klempir', cityId: CITY, address: 'Ostrava – Poruba', description: 'Josef Sedlák je klempíř a pokrývač v Ostravě s 12 lety praxe v oblasti střešních prací. Klempíř Ostrava nabízí opravy střech, výměnu klempířských prvků a montáž sněhových zábran.', picturePath: null, active: true },

  // ── REALITNÍ MAKLÉŘ ───────────────────────────────────────────────────────
  { fullName: 'RE/MAX Ostrava – Pavel Kratochvíl', phone: '+420 596 218 667', email: 'kratochvil@remax-ostrava.cz', serviceId: 'realitni-makler', cityId: CITY, address: 'Nádražní 22, Ostrava', description: 'Pavel Kratochvíl je zkušený realitní makléř RE/MAX v Ostravě specializující se na prodej a pronájem bytů. Realitní makléř Ostrava zajišťuje kompletní realitní servis od ocenění po podpis smlouvy.', picturePath: null, active: true },
  { fullName: 'Century 21 Ostrava – Jana Horáková', phone: '+420 776 558 334', email: 'horakova@century21-ostrava.cz', serviceId: 'realitni-makler', cityId: CITY, address: 'Sokolská 41, Ostrava', description: 'Jana Horáková je realitní makléřka Century 21 v Ostravě se zaměřením na rezidenční nemovitosti. Realitní kancelář Ostrava nabízí profesionální fotografie a rychlý prodej nemovitostí.', picturePath: null, active: true },
  { fullName: 'REALITY Ostrava – Martin Beneš', phone: '+420 596 334 889', email: 'info@reality-ostrava.cz', serviceId: 'realitni-makler', cityId: CITY, address: 'Jurečkova 102, Ostrava', description: 'REALITY Ostrava je zavedená realitní kancelář s rozsáhlým portfoliem bytů, domů a komerčních prostor. Realitní makléř Ostrava zajišťuje kupní smlouvy a průběžnou komunikaci.', picturePath: null, active: true },
  { fullName: 'M&M Reality Ostrava', phone: '+420 776 556 228', email: 'ostrava@mmreality.cz', serviceId: 'realitni-makler', cityId: CITY, address: 'Hornopolní 48, Ostrava', description: 'M&M Reality Ostrava je realitní kancelář s celonárodní sítí poskytující poradenství v Ostravě. Realitní makléř Ostrava pomáhá s prodejem, koupí a pronájmem nemovitostí za nejlepší cenu.', picturePath: null, active: true },

  // ── RESTAURACE ────────────────────────────────────────────────────────────
  { fullName: 'Restaurace Pivnice Zlatá Praha Ostrava', phone: '+420 596 112 458', email: 'info@pivnice-ostrava.cz', serviceId: 'restaurace', cityId: CITY, address: 'Nádražní 15, Ostrava', description: 'Pivnice Zlatá Praha je tradiční česká restaurace v centru Ostravy nabízející poctivou českou kuchyni a čerstvé pivo. Restaurace Ostrava láká hosty na domácí svíčkovou, guláš a pravidelné denní menu.', picturePath: null, active: true },
  { fullName: 'Restaurace U Divadla Ostrava', phone: '+420 596 221 334', email: 'info@udivadla-ostrava.cz', serviceId: 'restaurace', cityId: CITY, address: 'Divadelní 1, Ostrava', description: 'Restaurace U Divadla je oblíbená česká restaurace v Ostravě s příjemnou atmosférou a českou kuchyní. Restaurace Ostrava nabízí denní menu, rodinné oslavy a firemní bankety.', picturePath: null, active: true },
  { fullName: 'Koliba Ostrava – moravská kuchyně', phone: '+420 731 448 221', email: 'koliba@koliba-ostrava.cz', serviceId: 'restaurace', cityId: CITY, address: 'Sokolská 28, Ostrava', description: 'Koliba Ostrava nabízí tradiční moravskou a slovenskou kuchyni v autentickém rustikálním prostředí. Restaurace v Ostravě je oblíbeným místem pro rodinné i firemní večeře a oslavy.', picturePath: null, active: true },
  { fullName: 'Steakhouse Grill Ostrava', phone: '+420 596 557 118', email: 'info@steakhouse-ostrava.cz', serviceId: 'restaurace', cityId: CITY, address: '28. října 44, Ostrava', description: 'Steakhouse Grill Ostrava je moderní restaurace specializující se na grilovaná masa a steaky v Ostravě. Restaurace Ostrava nabízí prémiové hovězí steaky, burgers a mezinárodní kuchyni.', picturePath: null, active: true },

  // ── ARCHITEKT ─────────────────────────────────────────────────────────────
  { fullName: 'Ing. arch. Martin Kopecký – architekt Ostrava', phone: '+420 596 215 445', email: 'kopecky@atelier-ostrava.cz', serviceId: 'architekt', cityId: CITY, address: 'Jurečkova 56, Ostrava', description: 'Ing. arch. Martin Kopecký vede architektonický ateliér v Ostravě zaměřený na rodinné domy a komerční stavby. Architekt Ostrava nabízí projektovou dokumentaci, interiérový design a autorský dozor.', picturePath: null, active: true },
  { fullName: 'Architektonické studio Ostrava – Dvořák', phone: '+420 776 336 118', email: 'dvorak@arch-ostrava.cz', serviceId: 'architekt', cityId: CITY, address: 'Sokolská 8, Ostrava', description: 'Architektonické studio Dvořák realizuje projekty rodinných domů a revitalizací v Ostravě. Architekt Ostrava se specializuje na moderní a udržitelnou architekturu s důrazem na funkčnost.', picturePath: null, active: true },
  { fullName: 'Studio arch. Blaha Ostrava', phone: '+420 596 667 334', email: 'blaha@arch-ostrava.cz', serviceId: 'architekt', cityId: CITY, address: 'Hornopolní 44, Ostrava', description: 'Architektonické studio Blaha v Ostravě se zaměřuje na interiérový design a rekonstrukce rodinných domů. Architekt Ostrava přináší inovativní řešení prostoru s respektem k rozpočtu klienta.', picturePath: null, active: true },
  { fullName: 'Ing. arch. Jana Polachová – architekt Ostrava', phone: '+420 731 228 447', email: 'polachova@architekt-ostrava.cz', serviceId: 'architekt', cityId: CITY, address: 'Ostrava – Poruba', description: 'Jana Polachová je architektka v Ostravě s bohatými zkušenostmi s rekonstrukcemi bytových interiérů. Architekt Ostrava nabízí 3D vizualizace, stavební povolení a kompletní projektovou dokumentaci.', picturePath: null, active: true },

  // ── PSYCHOLOG ─────────────────────────────────────────────────────────────
  { fullName: 'PhDr. Jana Vávra – psycholog Ostrava', phone: '+420 596 213 556', email: 'vavra@psycholog-ostrava.cz', serviceId: 'psycholog', cityId: CITY, address: 'Nádražní 34, Ostrava', description: 'PhDr. Jana Vávra je klinická psycholožka v Ostravě nabízející individuální psychoterapii pro dospělé. Psycholog Ostrava se specializuje na zvládání úzkostí, depresí a životních krizí.', picturePath: null, active: true },
  { fullName: 'Centrum psychologie Ostrava', phone: '+420 776 441 228', email: 'info@psychologie-ostrava.cz', serviceId: 'psycholog', cityId: CITY, address: 'Sokolská 22, Ostrava', description: 'Centrum psychologie Ostrava poskytuje psychoterapii a poradenství pro jednotlivce i páry. Psycholog Ostrava nabízí online i prezenční konzultace se zkušenými terapeuty.', picturePath: null, active: true },
  { fullName: 'Mgr. Pavel Horáček – psychoterapeut Ostrava', phone: '+420 731 556 339', email: null, serviceId: 'psycholog', cityId: CITY, address: 'Jurečkova 91, Ostrava', description: 'Mgr. Pavel Horáček je psychoterapeut v Ostravě pracující metodou kognitivně-behaviorální terapie. Psycholog Ostrava nabízí konzultace zaměřené na stres, fóbie a vztahové problémy.', picturePath: null, active: true },
  { fullName: 'Psychologická poradna Ostrava – Mgr. Novotná', phone: '+420 596 334 771', email: 'novotna@poradna-ostrava.cz', serviceId: 'psycholog', cityId: CITY, address: 'Hornopolní 10, Ostrava', description: 'Mgr. Novotná vede psychologickou poradnu v Ostravě zaměřenou na párovou terapii a rodinné poradenství. Psycholog Ostrava nabízí diskrétní konzultace v centru Ostravy i online.', picturePath: null, active: true },

  // ── OSOBNÍ TRENÉR ─────────────────────────────────────────────────────────
  { fullName: 'Osobní trenér Ostrava – Jakub Marek', phone: '+420 731 558 226', email: 'marek@trener-ostrava.cz', serviceId: 'trener', cityId: CITY, address: 'Nádražní 26, Ostrava', description: 'Jakub Marek je certifikovaný osobní trenér v Ostravě zaměřený na silový trénink a hubnutí. Osobní trenér Ostrava sestaví individuální tréninkový plán a jídelníček pro každého klienta.', picturePath: null, active: true },
  { fullName: 'FitOstrava – personal training', phone: '+420 776 338 447', email: 'info@fitostrava.cz', serviceId: 'trener', cityId: CITY, address: 'Sokolská 61, Ostrava', description: 'FitOstrava je moderní studio osobního tréninku se zkušenými trenéry zaměřenými na kondici. Osobní trenér Ostrava nabízí individuální lekce, skupinové tréninky a online coaching.', picturePath: null, active: true },
  { fullName: 'Lukáš Veselý – trenér Ostrava', phone: '+420 608 449 225', email: null, serviceId: 'trener', cityId: CITY, address: 'Ostrava – Poruba', description: 'Lukáš Veselý je osobní trenér v Ostravě s certifikací v oblasti sportovní přípravy. Trenér Ostrava nabízí trénink v tělocvičně i v přírodě pro klienty z celého Moravskoslezského kraje.', picturePath: null, active: true },
  { fullName: 'PowerGym Ostrava – fitness trenér', phone: '+420 596 441 118', email: 'info@powergym-ostrava.cz', serviceId: 'trener', cityId: CITY, address: 'Hornopolní 85, Ostrava', description: 'PowerGym Ostrava je fitness studio s osobními trenéry zaměřenými na silový trénink v Ostravě. Osobní trenér Ostrava pomáhá klientům dosáhnout fitness cílů profesionálním vedením.', picturePath: null, active: true },

  // ── PŘEKLADATEL ───────────────────────────────────────────────────────────
  { fullName: 'Skřivánek Ostrava – překlady', phone: '+420 596 257 800', email: 'ostrava@skrivanek.cz', serviceId: 'prekladatel', cityId: CITY, address: 'Nádražní 6, Ostrava', description: 'Skřivánek Ostrava je přední překladatelská agentura nabízející překlady do více než 80 jazyků. Překladatel Ostrava zajišťuje odborné překlady, tlumočení a lokalizaci pro firmy i jednotlivce.', picturePath: null, active: true },
  { fullName: 'Překlady Ostrava – Mgr. Jana Horáková', phone: '+420 776 229 558', email: 'horakova@preklady-ostrava.cz', serviceId: 'prekladatel', cityId: CITY, address: 'Sokolská 24, Ostrava', description: 'Mgr. Jana Horáková je soudní překladatelka v Ostravě specializující se na angličtinu a němčinu. Překladatel Ostrava provádí úřední překlady s razítkem a odborné překlady.', picturePath: null, active: true },
  { fullName: 'TransOstrava s.r.o.', phone: '+420 596 338 667', email: 'info@transostrava.cz', serviceId: 'prekladatel', cityId: CITY, address: 'Jurečkova 35, Ostrava', description: 'TransOstrava je překladatelská agentura v Ostravě zaměřená na technické a právní překlady. Překladatel Ostrava spolupracuje s rodilými mluvčími a garantuje přesnost a rychlé dodání.', picturePath: null, active: true },
  { fullName: 'Pavel Sedlák – překladatel Ostrava', phone: '+420 608 447 336', email: null, serviceId: 'prekladatel', cityId: CITY, address: 'Ostrava – Poruba', description: 'Pavel Sedlák je zkušený překladatel v Ostravě nabízející překlady z češtiny do angličtiny a němčiny. Překladatel Ostrava zajišťuje přesné překlady obchodní a technické dokumentace.', picturePath: null, active: true },

  // ── GRAFICKÝ DESIGNER ─────────────────────────────────────────────────────
  { fullName: 'Grafické studio PIXEL Ostrava', phone: '+420 596 215 778', email: 'info@pixel-ostrava.cz', serviceId: 'grafik', cityId: CITY, address: 'Nádražní 6, Ostrava', description: 'Grafické studio PIXEL Ostrava nabízí kompletní grafické služby – logo, webdesign a branding. Grafický designer Ostrava vytváří vizuální identitu pro firmy po celém Moravskoslezském kraji.', picturePath: null, active: true },
  { fullName: 'Martin Novák – grafický designer Ostrava', phone: '+420 776 447 229', email: 'martin@grafik-ostrava.cz', serviceId: 'grafik', cityId: CITY, address: 'Sokolská 73, Ostrava', description: 'Martin Novák je freelance grafický designer v Ostravě specializující se na tvorbu log a firemní identity. Grafik Ostrava nabízí rychlé dodání a moderní kreativní přístup za příznivé ceny.', picturePath: null, active: true },
  { fullName: 'Creative Studio Ostrava', phone: '+420 596 776 334', email: 'info@creativestudio-ostrava.cz', serviceId: 'grafik', cityId: CITY, address: 'Hornopolní 59, Ostrava', description: 'Creative Studio Ostrava je grafické a reklamní studio nabízející webdesign a grafiku pro sociální sítě. Grafický designer Ostrava pomáhá firmám budovat silnou vizuální identitu.', picturePath: null, active: true },
  { fullName: 'Eva Polachová – grafička Ostrava', phone: '+420 731 338 554', email: 'eva@grafika-ostrava.cz', serviceId: 'grafik', cityId: CITY, address: 'Ostrava – Poruba', description: 'Eva Polachová je kreativní grafická designérka v Ostravě zaměřená na ilustrace a obalový design. Grafik Ostrava nabízí originální výstupy pro malé i velké klienty.', picturePath: null, active: true },

  // ── UČITEL / LEKTOR ───────────────────────────────────────────────────────
  { fullName: 'Jazyková škola Hello Ostrava', phone: '+420 596 237 723', email: 'ostrava@hello.cz', serviceId: 'ucitel', cityId: CITY, address: 'Nádražní 1, Ostrava', description: 'Jazyková škola Hello Ostrava nabízí kurzy angličtiny, němčiny a španělštiny pro dospělé i firmy. Lektor Ostrava zajišťuje skupinové i individuální kurzy s certifikovanými učiteli.', picturePath: null, active: true },
  { fullName: 'Lingua Centrum Ostrava', phone: '+420 596 217 468', email: 'ostrava@lingua-centrum.cz', serviceId: 'ucitel', cityId: CITY, address: 'Jurečkova 17, Ostrava', description: 'Lingua Centrum Ostrava je jazyková škola nabízející přípravné kurzy na Cambridge a jiné mezinárodní zkoušky. Lektor Ostrava poskytuje výuku angličtiny, němčiny a italštiny pro začátečníky i pokročilé.', picturePath: null, active: true },
  { fullName: 'Doučování Ostrava – Mgr. Lucie Bílá', phone: '+420 776 558 113', email: 'doucovani@ostrava-lekce.cz', serviceId: 'ucitel', cityId: CITY, address: 'Ostrava – Poruba', description: 'Mgr. Lucie Bílá nabízí doučování matematiky, fyziky a chemie pro žáky základních a středních škol v Ostravě. Lektor Ostrava přizpůsobuje výuku individuálním potřebám každého studenta.', picturePath: null, active: true },
  { fullName: 'Akademie jazyků Ostrava', phone: '+420 596 445 661', email: 'info@akademie-jazyku-ostrava.cz', serviceId: 'ucitel', cityId: CITY, address: 'Sokolská 67, Ostrava', description: 'Akademie jazyků Ostrava je moderní jazyková škola s online i prezenční výukou angličtiny a dalších jazyků. Lektoři Ostrava nabízejí firemní kurzy a intenzivní víkendové kurzy pro všechny úrovně.', picturePath: null, active: true },
];

async function main() {
  let count = 0;
  for (const p of profiles) {
    const created = await prisma.provider.create({ data: p });
    console.log(`✓ ${created.fullName}`);
    count++;
  }
  console.log(`\nDone. Added ${count} profiles.`);
}
main().catch(console.error).finally(() => prisma.$disconnect());
