import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();
const CITY = 'ceske-budejovice';

const profiles = [
  // ── ÚKLID (cleaning) ──────────────────────────────────────────────────────
  { fullName: 'FiJi úklid s.r.o.', email: 'uklidcb@uklidcb.cz', phone: '+420 607 188 284', serviceId: 'uklid', cityId: CITY, address: 'Rožnovská 2361/14, 370 07 České Budějovice', description: 'Profesionální úklidová firma — čištění domácností, kanceláří, výloh a průmyslových prostor.', picturePath: null, active: true },
  { fullName: 'FORTEL CB s.r.o. — úklid', email: 'info@fortel-uklid.cz', phone: '+420 602 419 000', serviceId: 'uklid', cityId: CITY, address: 'Budovcova 1, 370 01 České Budějovice', description: 'Úklidové služby pro domácnosti i firmy. Pravidelný i jednorázový úklid, mytí oken.', picturePath: null, active: true },
  { fullName: 'Miroslava Pistorová — úklidové práce', email: 'pistorova.uklid@email.cz', phone: '+420 602 545 813', serviceId: 'uklid', cityId: CITY, address: 'Barcala 1441/39, 370 05 České Budějovice', description: 'Úklid bytů, domů a kanceláří. Spolehlivá a diskrétní služba v Českých Budějovicích.', picturePath: null, active: true },
  { fullName: 'Andulka services s.r.o. — úklid', email: 'ceske.budejovice@naseandulka.cz', phone: null, serviceId: 'uklid', cityId: CITY, address: 'Žižkova tř. 309/12, 370 01 České Budějovice', description: 'Profesionální úklidové služby — domácnosti, kanceláře, výklid bytů po stěhování.', picturePath: null, active: true },

  // ── ZEDNÍK (mason) ────────────────────────────────────────────────────────
  { fullName: 'Zedníci České Budějovice', email: 'info@zednici-budejovice.cz', phone: '+420 774 777 787', serviceId: 'zednik', cityId: CITY, address: 'České Budějovice', description: 'Zednické práce — zdění, omítky, rekonstrukce, opravy. Jihočeský kraj.', picturePath: null, active: true },
  { fullName: 'Pavel Pravda — BAREVNE-FASADY.CZ', email: 'info@barevne-fasady.cz', phone: '+420 774 777 787', serviceId: 'zednik', cityId: CITY, address: 'České Budějovice 6', description: 'Zednické práce a fasády. Zateplení, omítky, fasádní nátěry. České Budějovice a okolí.', picturePath: null, active: true },

  // ── IT TECHNIK ────────────────────────────────────────────────────────────
  { fullName: 'Hernet s.r.o. — IT správa a sítě', email: 'info@hernet.cz', phone: '+420 602 409 267', serviceId: 'it-technik', cityId: CITY, address: 'Novohradská 16, 370 01 České Budějovice', description: 'Správa IT infrastruktury, počítačové sítě, cloud řešení pro firmy. České Budějovice.', picturePath: null, active: true },
  { fullName: 'PCCB.CZ — servis počítačů a notebooků', email: 'servis@pccb.cz', phone: '+420 728 320 818', serviceId: 'it-technik', cityId: CITY, address: 'Antonína Barcala 34, 370 05 České Budějovice', description: 'Opravy a servis počítačů, notebooků, tabletů. Instalace softwaru, viry, zálohy dat.', picturePath: null, active: true },
  { fullName: 'SERVIS-PC s.r.o.', email: 'obchod@servispc.cz', phone: '+420 603 518 402', serviceId: 'it-technik', cityId: CITY, address: 'Skuherského 1421/64, 370 01 České Budějovice', description: 'Servis PC a notebooků, prodej hardware, IT podpora pro firmy i domácnosti.', picturePath: null, active: true },
  { fullName: 'PC-CB — počítačový servis', email: 'info@pc-cb.cz', phone: '+420 773 936 449', serviceId: 'it-technik', cityId: CITY, address: 'Příčná 328/3, Rudolfov, České Budějovice', description: 'Opravy počítačů a notebooků, instalace OS, výlety za zákazníkem, IT konzultace.', picturePath: null, active: true },
  { fullName: 'Počítačová pohotovost', email: null, phone: '+420 603 757 677', serviceId: 'it-technik', cityId: CITY, address: 'České Budějovice', description: 'Pohotovostní IT servis — rychlá oprava počítačů a notebooků, výjezd k zákazníkovi.', picturePath: null, active: true },

  // ── ÚČETNÍ (accountant) ───────────────────────────────────────────────────
  { fullName: 'DAFI a.s. — účetnictví a daně', email: 'dafi@dafi.cz', phone: '+420 386 105 910', serviceId: 'ucetni', cityId: CITY, address: 'Dr. Stejskala 111/6, 370 01 České Budějovice', description: 'Komplexní účetní a daňové služby pro firmy i živnostníky. České Budějovice.', picturePath: null, active: true },
  { fullName: 'NEUMANN účetnictví s.r.o.', email: 'info@neucto.cz', phone: '+420 602 116 861', serviceId: 'ucetni', cityId: CITY, address: 'Senovážné nám. 248/2, 370 01 České Budějovice', description: 'Vedení účetnictví, daňové přiznání, mzdy a personalistika. Jihočeský kraj.', picturePath: null, active: true },
  { fullName: 'BENE CB spol. s r.o. — účetnictví', email: 'office@benecb.cz', phone: '+420 385 310 171', serviceId: 'ucetni', cityId: CITY, address: 'E. Rošického 460/12, 370 05 České Budějovice', description: 'Účetnictví, daně, mzdy a ekonomické poradenství pro malé a střední firmy.', picturePath: null, active: true },
  { fullName: 'Účetnictví CB', email: 'info@ucetnictvicb.cz', phone: '+420 604 650 095', serviceId: 'ucetni', cityId: CITY, address: 'České Budějovice', description: 'Vedení daňové evidence a účetnictví, zpracování mezd, daňová přiznání.', picturePath: null, active: true },

  // ── PRÁVNÍK (lawyer) ──────────────────────────────────────────────────────
  { fullName: 'ARROWS advokátní kancelář s.r.o.', email: 'office@arws.cz', phone: '+420 606 784 404', serviceId: 'pravnik', cityId: CITY, address: 'Lidická tř. 2331/6a, 370 01 České Budějovice', description: 'Advokátní kancelář — obchodní právo, nemovitosti, pracovní právo, vymáhání pohledávek.', picturePath: null, active: true },
  { fullName: 'JUDr. Helena Nutilová — advokátka', email: 'ak.nutilova@gmail.com', phone: '+420 773 673 311', serviceId: 'pravnik', cityId: CITY, address: 'Vodní 231/5, 370 01 České Budějovice', description: 'Advokátka — rodinné právo, smlouvy, dědictví, trestní právo. České Budějovice.', picturePath: null, active: true },
  { fullName: 'AK Bartelsenová — advokátní kancelář', email: 'info@akbartelsenova.cz', phone: '+420 723 843 864', serviceId: 'pravnik', cityId: CITY, address: 'Dvořákova 21, 370 01 České Budějovice', description: 'Advokátní kancelář — občanské, obchodní a rodinné právo, zastupování u soudu.', picturePath: null, active: true },
  { fullName: 'Čutková — Advokáti Budějovice', email: 'cutkova@advokatibudejovice.cz', phone: '+420 387 200 681', serviceId: 'pravnik', cityId: CITY, address: 'Široká 432/11, 370 01 České Budějovice', description: 'Advokátní kancelář — nemovitosti, pracovní právo, správní řízení, podnikatelské právo.', picturePath: null, active: true },
  { fullName: 'Bayers — advokátní kancelář', email: null, phone: '+420 773 400 414', serviceId: 'pravnik', cityId: CITY, address: 'Jeremiášova 1705/18, 370 01 České Budějovice', description: 'Advokátní kancelář s dlouholetou tradicí. Komplexní právní služby v Českých Budějovicích.', picturePath: null, active: true },
  { fullName: 'Mgr. Václav Kubička — advokát', email: 'kubicka.vaclav@seznam.cz', phone: '+420 776 281 699', serviceId: 'pravnik', cityId: CITY, address: 'České Budějovice', description: 'Advokát — občanské právo, smlouvy, nemovitosti, exekuce, rodinné věci.', picturePath: null, active: true },

  // ── AUTOSERVIS ────────────────────────────────────────────────────────────
  { fullName: 'Jiří Seiml — autoservis', email: 'j-seiml@volny.cz', phone: '+420 602 474 381', serviceId: 'autoservis', cityId: CITY, address: 'Třebotovice 2481, 370 06 České Budějovice', description: 'Autoservis — opravy osobních vozů, diagnostika, výměna oleje, brzdy, pneuservis.', picturePath: null, active: true },
  { fullName: 'AUTOSERVIS K+F s.r.o.', email: 'info@autoserviskf.cz', phone: '+420 602 175 634', serviceId: 'autoservis', cityId: CITY, address: 'K Lučinám 577, 370 01 České Budějovice', description: 'Komplexní autoservis — opravy, karoserie, diagnostika, pneuservis. České Budějovice.', picturePath: null, active: true },
  { fullName: 'Autoservis Petr Rada — Bosch Car Service', email: 'serviscb@autoservisrada.cz', phone: '+420 731 508 905', serviceId: 'autoservis', cityId: CITY, address: 'Prostřední 2842/2, 370 04 České Budějovice', description: 'Autorizovaný Bosch Car Service — diagnostika, opravy, servisní prohlídky všech značek.', picturePath: null, active: true },
  { fullName: 'Maroušek s.r.o. — autoservis a pneuservis', email: 'marousekautoservis@seznam.cz', phone: '+420 602 537 990', serviceId: 'autoservis', cityId: CITY, address: 'Lidická tř. 1123/226, 370 07 České Budějovice', description: 'Autoservis a pneuservis — opravy, přezutí, geometrie, výměna oleje.', picturePath: null, active: true },
  { fullName: 'AUTA-SERVIS s.r.o.', email: 'info@auta-servis.cz', phone: '+420 725 259 912', serviceId: 'autoservis', cityId: CITY, address: 'Pekárenská 251/79a, 370 04 České Budějovice', description: 'Autoservis — opravy všech značek, STK příprava, klimatizace, diagnostika.', picturePath: null, active: true },
  { fullName: 'Autoservis Čížek', email: 'info@autoserviscizek.cz', phone: '+420 724 249 735', serviceId: 'autoservis', cityId: CITY, address: 'České Vrbné 2347, 370 11 České Budějovice', description: 'Autoservis — kompletní opravy vozidel, elektroinstalace, diagnostika, pneuservis.', picturePath: null, active: true },

  // ── FOTOGRAF ──────────────────────────────────────────────────────────────
  { fullName: 'Jana Valíčková — fotografka', email: 'foto@janavalickova.cz', phone: '+420 601 230 243', serviceId: 'fotograf', cityId: CITY, address: 'Nerudova 989/6, 370 04 České Budějovice', description: 'Profesionální fotografka — portréty, svatby, rodinné fotografie, firemní focení.', picturePath: null, active: true },
  { fullName: 'Michal Landa — fotograf', email: 'michal@landafoto.cz', phone: '+420 603 731 116', serviceId: 'fotograf', cityId: CITY, address: 'Pražská tř. 14/209, 370 10 České Budějovice', description: 'Fotograf — svatby, reportáže, produktové fotografie, architektura a interiéry.', picturePath: null, active: true },
  { fullName: 'Adéla Andersová — fotografka', email: 'andersova@post.cz', phone: '+420 797 997 632', serviceId: 'fotograf', cityId: CITY, address: 'nám. Přemysla Otakara II. 84/24, 370 01 České Budějovice', description: 'Fotografka — portréty, těhotenské a novorozenecké focení, rodinné fotografie.', picturePath: null, active: true },
  { fullName: 'Fotoateliér GAVEX', email: 'info@gavex.cz', phone: '+420 722 448 451', serviceId: 'fotograf', cityId: CITY, address: 'Na Zlaté stoce 567/35, 370 05 České Budějovice', description: 'Fotoateliér — pasové fotografie, portréty, školní fotografie, firemní fotografie.', picturePath: null, active: true },
  { fullName: 'Jaroslav Klíma — BASTA foto', email: 'klm.basta@seznam.cz', phone: '+420 737 059 822', serviceId: 'fotograf', cityId: CITY, address: 'Volejbalistů 1793/3, 370 01 České Budějovice', description: 'Fotograf — reportážní, sportovní a dokumentární fotografie. České Budějovice a okolí.', picturePath: null, active: true },

  // ── KADEŘNÍK ──────────────────────────────────────────────────────────────
  { fullName: 'Kadeřnictví bez objednání — M. Štegbauerová', email: 'stegbauerova.m@seznam.cz', phone: '+420 776 604 437', serviceId: 'kadernik', cityId: CITY, address: 'Lidická tř. 456/60, 370 01 České Budějovice', description: 'Kadeřnictví bez objednání — pánské a dětské střihy, rychlé a profesionální.', picturePath: null, active: true },
  { fullName: 'Kadeřnický salon Zuzana Špačková', email: 'kadernicky.salon@centrum.cz', phone: '+420 776 792 660', serviceId: 'kadernik', cityId: CITY, address: 'Na Sádkách 689/2, 370 05 České Budějovice', description: 'Dámský a pánský kadeřnický salon — střihy, barvení, melírování, styling.', picturePath: null, active: true },
  { fullName: 'Lucie Klimešová — kadeřnictví', email: null, phone: '+420 773 451 948', serviceId: 'kadernik', cityId: CITY, address: 'Dr. Bureše 1212/15, 370 05 České Budějovice', description: 'Kadeřnictví — pánské a dětské střihy, příjemné prostředí, přijatelné ceny.', picturePath: null, active: true },
  { fullName: 'Kadeřnický salón La Passion — Eliška Nebeská', email: 'eliska.stosova@seznam.cz', phone: '+420 724 620 566', serviceId: 'kadernik', cityId: CITY, address: 'Hradební 293/25, 370 01 České Budějovice', description: 'Dámský a pánský kadeřnický salón — střihy, barvení, keratinové ošetření, styling.', picturePath: null, active: true },
  { fullName: 'Hair Studio Onyx — Jitka Drozdová', email: 'xmarge@seznam.cz', phone: '+420 724 921 315', serviceId: 'kadernik', cityId: CITY, address: 'Krajinská 224/37, 370 01 České Budějovice', description: 'Hair studio — dámské a pánské střihy, barvení, melírování, prodlužování vlasů.', picturePath: null, active: true },
  { fullName: 'Studio Beauty — Vladimíra Peřinková', email: 'vladzi110@gmail.com', phone: '+420 733 578 386', serviceId: 'kadernik', cityId: CITY, address: 'Na Sadech 6/5, 370 01 České Budějovice', description: 'Kadeřnické a kosmetické studio — střihy, barvení, manikúra, péče o pleť.', picturePath: null, active: true },

  // ── LÉKAŘ (doctor) ────────────────────────────────────────────────────────
  { fullName: 'EUC Klinika — praktické lékařství', email: 'recepce.ceskebudejovice@eucklinika.cz', phone: '+420 389 109 109', serviceId: 'lekar', cityId: CITY, address: 'Matice školské 1786/17, 370 01 České Budějovice', description: 'Privátní klinika — praktický lékař pro dospělé, preventivní prohlídky, očkování.', picturePath: null, active: true },
  { fullName: 'MUDr. Denisa Mrázková — praktická lékařka', email: 'denisa.mrazkova@euc.cz', phone: '+420 387 730 218', serviceId: 'lekar', cityId: CITY, address: 'Matice školské 1786/17, 370 01 České Budějovice', description: 'Praktická lékařka pro dospělé — preventivní prohlídky, léčba, pracovní neschopnost.', picturePath: null, active: true },
  { fullName: 'MUDr. Bohumír Beneda', email: 'bbeneda@yahoo.com', phone: '+420 387 204 034', serviceId: 'lekar', cityId: CITY, address: 'E. Beneše 2686/36, 370 06 České Budějovice', description: 'Praktický lékař pro dospělé — ordinace v Českých Budějovicích, přijímá nové pacienty.', picturePath: null, active: true },
  { fullName: 'MedicalHelp — praktická medicína', email: 'infocb@medicalhelp.cz', phone: '+420 739 009 222', serviceId: 'lekar', cityId: CITY, address: 'Jar. Ježka 384/65, 370 06 České Budějovice', description: 'Ordinace praktického lékaře pro dospělé. Soukromá medicína, bez čekání.', picturePath: null, active: true },
  { fullName: 'MEDALEX s.r.o. — MUDr. Lubomír Procházka', email: 'lubomir26@seznam.cz', phone: '+420 387 422 054', serviceId: 'lekar', cityId: CITY, address: 'Pražská tř. 1014/71, 370 04 České Budějovice', description: 'Praktický lékař — prevence, diagnostika, léčba. Ordinace v Českých Budějovicích.', picturePath: null, active: true },

  // ── KLEMPÍŘ ───────────────────────────────────────────────────────────────
  { fullName: 'PFK Klempířství', email: 'info@pfk-klempirstvi.cz', phone: '+420 724 841 523', serviceId: 'klempir', cityId: CITY, address: 'U Malše 125/2, 370 01 České Budějovice', description: 'Klempířství — oplechování střech, okapy, parapety, opravy klempířských prvků.', picturePath: null, active: true },
  { fullName: 'Klempířství František Gajdoš', email: 'frantisekgajdos01@seznam.cz', phone: '+420 723 572 807', serviceId: 'klempir', cityId: CITY, address: 'Lidická tř. 2221/275, 370 07 České Budějovice', description: 'Klempíř — výroba a montáž okapů, oplechování střech, vikýřů a komínů.', picturePath: null, active: true },
  { fullName: 'Klempířství — Dušan Šálek', email: 'dusan.salek@seznam.cz', phone: '+420 602 470 209', serviceId: 'klempir', cityId: CITY, address: 'J. Bendy 1393/26, 370 05 České Budějovice', description: 'Klempířské práce — okapy, střešní oplechování, parapety, fasádní prvky.', picturePath: null, active: true },
  { fullName: 'Jiří Krátký — klempířství a pokrývačství', email: 'kratky.klempirstvi@centrum.cz', phone: '+420 732 826 338', serviceId: 'klempir', cityId: CITY, address: 'Bezdrevská 1163/9, 370 11 České Budějovice', description: 'Klempíř a pokrývač — střechy, okapy, oplechování, plechové střešní krytiny.', picturePath: null, active: true },
  { fullName: 'Radek John — klempířství', email: 'r.john@seznam.cz', phone: '+420 605 955 392', serviceId: 'klempir', cityId: CITY, address: 'Zavadilka 2087, 370 05 České Budějovice', description: 'Klempířské práce — oplechování, okapy, parapety, opravy střech a klempířských prvků.', picturePath: null, active: true },

  // ── REALITNÍ MAKLÉŘ ───────────────────────────────────────────────────────
  { fullName: 'BD Reality CB s.r.o. — Radka Bryxová', email: 'bryxova@bdreality.cz', phone: '+420 724 300 767', serviceId: 'realitni-makler', cityId: CITY, address: 'Kubatova 6, 370 04 České Budějovice', description: 'Realitní makléřka — prodej a pronájem bytů, domů a komerčních nemovitostí v Jihočeském kraji.', picturePath: null, active: true },
  { fullName: 'RONDO s.r.o. — realitní kancelář', email: 'rondo@rondocb.cz', phone: '+420 777 101 001', serviceId: 'realitni-makler', cityId: CITY, address: 'Mánesova 423/60, 370 01 České Budějovice', description: 'Realitní kancelář — prodej, pronájem a správa nemovitostí. České Budějovice a okolí.', picturePath: null, active: true },
  { fullName: 'Kontakt servis CZ — Milan Černoch', email: 'milan.cernoch@kontaktservis.cz', phone: '+420 603 534 453', serviceId: 'realitni-makler', cityId: CITY, address: 'Pražská třída 563/99, 370 04 České Budějovice', description: 'Realitní makléř — zprostředkování prodeje a pronájmu nemovitostí, investiční poradenství.', picturePath: null, active: true },
  { fullName: 'M&M Reality — pobočka České Budějovice', email: 'ceskebudejovice@mmreality.cz', phone: '+420 603 316 012', serviceId: 'realitni-makler', cityId: CITY, address: 'Na Sadech 2033/21, České Budějovice', description: 'Realitní kancelář M&M Reality — prodej a pronájem bytů, domů, pozemků a komerčních prostor.', picturePath: null, active: true },
  { fullName: 'Jaroslav Pavlas — realitní makléř', email: 'pavlas.jaroslav@papreality.cz', phone: '+420 728 141 476', serviceId: 'realitni-makler', cityId: CITY, address: 'Lannova tř. 205/16, 370 01 České Budějovice', description: 'Osobní realitní makléř — individuální přístup, prodej a pronájem nemovitostí v ČB.', picturePath: null, active: true },
  { fullName: 'Iva Lexová — RE/MAX makléřka', email: 'iva.lexova@re-max.cz', phone: '+420 608 174 488', serviceId: 'realitni-makler', cityId: CITY, address: 'České Budějovice', description: 'Realitní makléřka RE/MAX — prodej bytů, rodinných domů a pozemků v Jihočeském kraji.', picturePath: null, active: true },

  // ── RESTAURACE ────────────────────────────────────────────────────────────
  { fullName: 'Restaurace BESEDA', email: 'restaurace@restauracebeseda.cz', phone: '+420 387 319 604', serviceId: 'restaurace', cityId: CITY, address: 'Na Sadech 2036/18, 370 01 České Budějovice', description: 'Tradiční česká kuchyně v centru Českých Budějovic. Obědy, večeře, pořádání akcí.', picturePath: null, active: true },
  { fullName: 'Restaurace U Flíčků', email: 'info@uflicku.cz', phone: '+420 776 101 119', serviceId: 'restaurace', cityId: CITY, address: 'Husova 38/93, 370 05 České Budějovice', description: 'Rodinná restaurace s českou kuchyní — denní menu, pivo, příjemná atmosféra.', picturePath: null, active: true },
  { fullName: 'Masné krámy', email: 'info@masne-kramy.cz', phone: '+420 387 201 301', serviceId: 'restaurace', cityId: CITY, address: 'Krajinská 13, 370 01 České Budějovice', description: 'Historická restaurace v gotickém sklepení. Česká a jihočeská kuchyně, Budvar.', picturePath: null, active: true },
  { fullName: 'La Vié Restaurant', email: 'info@lavierestaurant.cz', phone: '+420 606 181 131', serviceId: 'restaurace', cityId: CITY, address: 'Novohradská 317/2, 370 01 České Budějovice', description: 'Moderní restaurace — mezinárodní kuchyně, firemní večeře, romantické posezení.', picturePath: null, active: true },
  { fullName: 'Hoch Špalíček', email: 'provoz@hochspalicek.cz', phone: '+420 602 753 333', serviceId: 'restaurace', cityId: CITY, address: 'Vltavské nábřeží 688/3, 370 05 České Budějovice', description: 'Restaurace s výhledem na řeku Vltavu. Česká kuchyně, grilované speciality, letní terasa.', picturePath: null, active: true },

  // ── ARCHITEKT ─────────────────────────────────────────────────────────────
  { fullName: 'MYDVAARCHITEKTI s.r.o.', email: 'info@mydvaarchitekti.cz', phone: '+420 724 606 304', serviceId: 'architekt', cityId: CITY, address: 'Dobrovodská 2054/53a, 370 06 České Budějovice', description: 'Architektonické studio — projekty rodinných domů, rekonstrukce, interiéry, územní studie.', picturePath: null, active: true },
  { fullName: 'Projektový ateliér AD s.r.o.', email: 'atelierad@atelierad.cz', phone: '+420 605 277 998', serviceId: 'architekt', cityId: CITY, address: 'Husova třída 1821/4, 370 01 České Budějovice', description: 'Projektový ateliér — architektura, stavební projekty, rekonstrukce, interiérový design.', picturePath: null, active: true },
  { fullName: 'ARKUS5 s.r.o. — Ing. Vladan Daněk', email: 'danek.arkus5@seznam.cz', phone: '+420 777 287 516', serviceId: 'architekt', cityId: CITY, address: 'K. Weise 1675, České Budějovice', description: 'Architektonická kancelář — projekty novostaveb a rekonstrukcí, inženýrská činnost.', picturePath: null, active: true },
  { fullName: '3D ARCHITECTS s.r.o.', email: 'stadlik@3darch.cz', phone: '+420 607 242 083', serviceId: 'architekt', cityId: CITY, address: 'Lidická 179/47, České Budějovice', description: 'Architekti — projekty rodinných domů, bytů, komerčních staveb, 3D vizualizace.', picturePath: null, active: true },

  // ── PSYCHOLOG ─────────────────────────────────────────────────────────────
  { fullName: 'PhDr. Eva Vávrová — psychologická poradna AURA', email: 'eva.vavrova.psycholog@gmail.com', phone: '+420 724 135 213', serviceId: 'psycholog', cityId: CITY, address: 'Jírovcova 2814/66, 370 01 České Budějovice', description: 'Soukromá psycholožka — individuální terapie, poradenství, diagnostika dospělých i dětí.', picturePath: null, active: true },
  { fullName: 'PhDr. Vladimír Forst — psychologická ordinace', email: 'forst.psycholog@seznam.cz', phone: '+420 603 895 363', serviceId: 'psycholog', cityId: CITY, address: 'Matice školské 1786/17, České Budějovice', description: 'Psychologická ordinace — psychoterapie, poradenství, diagnostika, rodinné poradenství.', picturePath: null, active: true },
  { fullName: 'Mgr. Zdeňka Bajgarová — soukromý psycholog', email: 'bajgarova@soukromypsycholog.cz', phone: '+420 607 912 170', serviceId: 'psycholog', cityId: CITY, address: 'Kanovnická 390/11, České Budějovice', description: 'Psycholožka a terapeutka — individuální a párová terapie, krizová intervence.', picturePath: null, active: true },
  { fullName: 'Středisko pro rodinu — psychologické poradenství', email: 'spramv@gmail.com', phone: '+420 387 438 703', serviceId: 'psycholog', cityId: CITY, address: 'Nádražní 47, 370 01 České Budějovice', description: 'Poradenství pro rodiny a páry, individuální terapie, linka důvěry. České Budějovice.', picturePath: null, active: true },
];

async function main() {
  let count = 0;
  for (const p of profiles) {
    const created = await prisma.provider.create({ data: p });
    console.log(`✓ ${created.fullName}`);
    count++;
  }
  console.log(`\nDone. Added ${count} profiles.`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
