import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();
const CITY = 'plzen';

const profiles = [
  // ── ELEKTRIKÁŘ ───────────────────────────────────────────────────────────
  { fullName: 'Elektroslužby Novák Plzeň', phone: '+420 377 224 506', email: 'novak@elektros-plzen.cz', serviceId: 'elektrikar', cityId: CITY, address: 'Tylova 1572/57, Plzeň 3', description: 'Elektroslužby Novák jsou zkušení elektrikáři v Plzni nabízející kompletní elektroinstalace, revize a opravy pro domácnosti i firmy. Elektrikář Plzeň zajistí rychlý zásah a profesionální práce po celém Plzeňském kraji.', picturePath: null, active: true },
  { fullName: 'M&V Elektro Plzeň', phone: '+420 603 412 870', email: 'info@mv-elektro.cz', serviceId: 'elektrikar', cityId: CITY, address: 'Klatovská třída 89, Plzeň 3', description: 'M&V Elektro je profesionální elektrikář v Plzni specializující se na elektroinstalace bytů, rodinných domů a průmyslových objektů. Elektrikář Plzeň provádí revize elektroinstalací a odstraňování poruch elektrického vedení.', picturePath: null, active: true },
  { fullName: 'Elektroinstalace Šimánek Plzeň', phone: '+420 728 341 099', email: 'simanek@elektro-plzen.cz', serviceId: 'elektrikar', cityId: CITY, address: 'Masarykova třída 22, Plzeň 1', description: 'Pavel Šimánek je certifikovaný elektrikář v Plzni s více než 20 lety praxe v oblasti elektroinstalací a revizí. Elektrikář Plzeň nabízí montáž rozvaděčů, datových sítí a fotovoltaických systémů.', picturePath: null, active: true },
  { fullName: 'Elektrikář Dvořák Plzeň', phone: '+420 777 521 344', email: null, serviceId: 'elektrikar', cityId: CITY, address: 'Americká 2765/19, Plzeň 1', description: 'Martin Dvořák je zkušený elektrikář Plzeň nabízející elektroinstalační práce, výměnu pojistkových skříní a zapojení spotřebičů v Plzni a okolí. Rychlý výjezd a spolehlivý servis pro zákazníky z Plzeňského kraje.', picturePath: null, active: true },

  // ── INSTALATÉR ───────────────────────────────────────────────────────────
  { fullName: 'Instalatér Procházka Plzeň', phone: '+420 377 318 205', email: 'prochazka@instal-plzen.cz', serviceId: 'instalater', cityId: CITY, address: 'Slovanská alej 2182/26, Plzeň 2', description: 'Instalatér Procházka nabízí komplexní instalatérské práce v Plzni včetně oprav vodovodů, výměny bojlerů a instalace koupelen. Instalatér Plzeň zajistí rychlý výjezd a kvalitní práce pro domácnosti i firmy.', picturePath: null, active: true },
  { fullName: 'Vodo-Topo Štefan Plzeň', phone: '+420 602 588 741', email: 'stefan@vodotopo-plzen.cz', serviceId: 'instalater', cityId: CITY, address: 'Rokycanská 1439/12, Plzeň 2', description: 'Vodo-Topo Štefan je instalatér a topenář v Plzni s dlouholetou zkušeností s montáží a servisem plynových kotlů a topení. Instalatér Plzeň provádí kompletní rekonstrukce koupelen a vodovodních rozvodů.', picturePath: null, active: true },
  { fullName: 'Instalatérství Krejčí Plzeň', phone: '+420 739 214 563', email: null, serviceId: 'instalater', cityId: CITY, address: 'Lochotínská 1078/11, Plzeň 3', description: 'Instalatérství Krejčí nabízí veškeré instalatérské a topenářské práce v Plzni a přilehlém okolí. Instalatér Plzeň se specializuje na výměnu radiátorů, opravu úniků vody a instalaci podlahového vytápění.', picturePath: null, active: true },
  { fullName: 'Petr Havel – instalatér Plzeň', phone: '+420 608 773 412', email: 'havel.instal@centrum.cz', serviceId: 'instalater', cityId: CITY, address: 'Borská 2553/27, Plzeň 1', description: 'Petr Havel je instalatér Plzeň s 15 lety praxe v opravách a rekonstrukcích vodovodního a topenářského rozvodu. Nabízí pohotovostní instalatérský servis v Plzni 24/7 pro odstranění havárií.', picturePath: null, active: true },

  // ── MALÍŘ ────────────────────────────────────────────────────────────────
  { fullName: 'Malíř Holub Plzeň', phone: '+420 602 341 788', email: 'holub@malir-plzen.cz', serviceId: 'malir', cityId: CITY, address: 'Přemyslova 1734/8, Plzeň 2', description: 'Malíř Holub nabízí profesionální malování pokojů, bytů a kanceláří v Plzni a okolí. Malíř pokojů Plzeň zajistí kompletní přípravu povrchů, stěrkování a výsledný nátěr dle přání zákazníka.', picturePath: null, active: true },
  { fullName: 'Malířství Vácha Plzeň', phone: '+420 377 459 122', email: 'vacha@malirvaca.cz', serviceId: 'malir', cityId: CITY, address: 'Košutecká 1213/5, Plzeň 3', description: 'Malířství Vácha provádí malování a lakýrnické práce pro domácnosti i firmy v Plzni. Malíř Plzeň nabízí dekorativní techniky, nátěry fasád a výmalbu novostaveb v celém Plzeňském kraji.', picturePath: null, active: true },
  { fullName: 'Ondřej Ryba – malíř Plzeň', phone: '+420 723 556 890', email: null, serviceId: 'malir', cityId: CITY, address: 'Jateční 2768/30, Plzeň 1', description: 'Ondřej Ryba je zkušený malíř pokojů v Plzni s precizním přístupem k malování bytů, domů a průmyslových prostor. Malíř Plzeň provádí nátěry na klíč včetně přípravy a nákupu materiálu.', picturePath: null, active: true },
  { fullName: 'Malíř lakýrník Beneš Plzeň', phone: '+420 605 214 677', email: 'benes@malirlak.cz', serviceId: 'malir', cityId: CITY, address: 'Nepomucká 768/14, Plzeň 4', description: 'Malíř a lakýrník Beneš nabízí veškeré malířské a lakýrnické práce v Plzni a Plzeňském kraji. Specializuje se na nátěry kovových konstrukcí, fasád a výmalbu interiérů v Plzni.', picturePath: null, active: true },

  // ── TESAŘ ────────────────────────────────────────────────────────────────
  { fullName: 'Tesařství Mašek Plzeň', phone: '+420 602 871 344', email: 'masek@tesarplzen.cz', serviceId: 'tesar', cityId: CITY, address: 'Doubravecká 2148/3, Plzeň 4', description: 'Tesařství Mašek provádí výstavbu a rekonstrukci krovů, střech a dřevěných konstrukcí v Plzni a okolí. Tesař Plzeň zajistí realizaci pergol, přístřešků a dřevěných zahradních staveb.', picturePath: null, active: true },
  { fullName: 'Krovy Šulc Plzeň', phone: '+420 377 528 641', email: 'sulc@krovy-plzen.cz', serviceId: 'tesar', cityId: CITY, address: 'Radčická 456/7, Plzeň 6', description: 'Krovy Šulc je tesař v Plzni specializující se na výstavbu nových krovů a rekonstrukce střešních konstrukcí. Tesař Plzeň realizuje dřevostavby a střešní práce pro rodinné domy v celém Plzeňském kraji.', picturePath: null, active: true },
  { fullName: 'Tesař Říha Plzeň', phone: '+420 728 903 215', email: null, serviceId: 'tesar', cityId: CITY, address: 'Bochovská 1109/18, Plzeň 1', description: 'Josef Říha je zkušený tesař v Plzni provádějící veškeré tesařské práce od krovů po dřevěné terasy a altány. Tesař Plzeň nabízí montáž schodišť, pergol a zahradních přístřešků v Plzni a okolí.', picturePath: null, active: true },
  { fullName: 'Dřevostavby Korda Plzeň', phone: '+420 603 115 877', email: 'korda@drevostavby-plzen.cz', serviceId: 'tesar', cityId: CITY, address: 'Prokopova 1882/12, Plzeň 3', description: 'Dřevostavby Korda je tesař a dřevostavitel v Plzni nabízející výstavbu dřevěných domků, krovů a střešních systémů. Tesař Plzeň realizuje zakázkové tesařské práce v Plzeňském kraji.', picturePath: null, active: true },

  // ── TRUHLÁŘ ──────────────────────────────────────────────────────────────
  { fullName: 'Truhlářství Marek Plzeň', phone: '+420 377 441 209', email: 'marek@truhlar-plzen.cz', serviceId: 'truhlar', cityId: CITY, address: 'Náměstí Republiky 28, Plzeň 1', description: 'Truhlářství Marek vyrábí nábytek, dveře a okna na zakázku v Plzni. Truhlář Plzeň se specializuje na výrobu kuchyňských linek, skříní a dřevěných interiérů pro zákazníky v Plzni a okolí.', picturePath: null, active: true },
  { fullName: 'Zakázkové truhlářství Blaha Plzeň', phone: '+420 603 782 440', email: 'blaha@truhlarna-plzen.cz', serviceId: 'truhlar', cityId: CITY, address: 'Žižkova 2314/19, Plzeň 1', description: 'Zakázkové truhlářství Blaha vyrábí nábytek a dřevěné interiéry na míru v Plzni. Truhlář Plzeň nabízí výrobu postelí, stolů, skříní a zabudovaných systémů pro domy i byty.', picturePath: null, active: true },
  { fullName: 'Truhlář Nový Plzeň', phone: '+420 724 551 088', email: null, serviceId: 'truhlar', cityId: CITY, address: 'Slovanská alej 3109/33, Plzeň 2', description: 'Tomáš Nový je truhlář Plzeň s 18 lety zkušeností ve výrobě dřevěného nábytku, schodišť a vestavěných skříní. Truhlářství v Plzni realizuje kompletní dřevěné interiéry na klíč dle individuálního návrhu.', picturePath: null, active: true },
  { fullName: 'Nábytek Švec – truhlář Plzeň', phone: '+420 602 334 779', email: 'svec@nabytekplzen.cz', serviceId: 'truhlar', cityId: CITY, address: 'Americká 1560/40, Plzeň 1', description: 'Dílna Švec je truhlář a výrobce nábytku v Plzni nabízející zakázkovou výrobu dřevěných prvků pro byty, domy a kanceláře. Truhlář Plzeň zajistí výrobu a montáž nábytku přímo u zákazníka.', picturePath: null, active: true },

  // ── ZEDNÍK ───────────────────────────────────────────────────────────────
  { fullName: 'Zednictví Kopecký Plzeň', phone: '+420 377 334 891', email: 'kopecky@zednik-plzen.cz', serviceId: 'zednik', cityId: CITY, address: 'Klatovská třída 211/45, Plzeň 3', description: 'Zednictví Kopecký nabízí kompletní zednické práce v Plzni – příčky, omítky, obklady a rekonstrukce bytů. Zedník Plzeň realizuje stavební práce pro rodinné domy i bytové jednotky v Plzeňském kraji.', picturePath: null, active: true },
  { fullName: 'Stavební práce Hůrka Plzeň', phone: '+420 602 881 507', email: 'hurka@stavba-plzen.cz', serviceId: 'zednik', cityId: CITY, address: 'Lochotínská 890/28, Plzeň 3', description: 'Stavební práce Hůrka provádí zednické práce, obklady a dlažby v Plzni a okolí. Zedník Plzeň zajistí renovaci koupelen, pokládku dlažby a veškeré rekonstrukční práce.', picturePath: null, active: true },
  { fullName: 'Zedník Špaček Plzeň', phone: '+420 723 667 344', email: null, serviceId: 'zednik', cityId: CITY, address: 'Rokycanská 2345/8, Plzeň 2', description: 'Ladislav Špaček je zkušený zedník v Plzni provádějící omítky, zdění příček a rekonstrukce bytů. Zedník Plzeň nabízí kompletní stavební práce od základů po finální úpravy povrchů.', picturePath: null, active: true },
  { fullName: 'Stavební firma Polák Plzeň', phone: '+420 608 112 453', email: 'polak@stav-plzen.cz', serviceId: 'zednik', cityId: CITY, address: 'Borská 3781/14, Plzeň 1', description: 'Stavební firma Polák nabízí kompletní zednické a stavební práce v Plzni. Zedník Plzeň realizuje zdění, betonáže, stropy, příčky a dokončovací práce pro soukromé i firemní zákazníky.', picturePath: null, active: true },

  // ── KLEMPÍŘ ──────────────────────────────────────────────────────────────
  { fullName: 'Klempířství Soukup Plzeň', phone: '+420 377 512 334', email: 'soukup@klempir-plzen.cz', serviceId: 'klempir', cityId: CITY, address: 'Tylova 2298/41, Plzeň 3', description: 'Klempířství Soukup nabízí kompletní klempířské a pokrývačské práce v Plzni – oplechování střech, parapety a okapy. Klempíř Plzeň provádí montáž a opravy střech pro rodinné domy i bytové komplexy.', picturePath: null, active: true },
  { fullName: 'Střechy Janda Plzeň', phone: '+420 602 441 870', email: 'janda@strechaJanda.cz', serviceId: 'klempir', cityId: CITY, address: 'Masarykova třída 1234/17, Plzeň 1', description: 'Střechy Janda je klempíř a pokrývač v Plzni se zaměřením na pokládku střešní krytiny, klempířské práce a opravy střech. Klempíř Plzeň poskytuje záruky na veškeré provedené práce.', picturePath: null, active: true },
  { fullName: 'Klempíř Růžička Plzeň', phone: '+420 728 774 512', email: null, serviceId: 'klempir', cityId: CITY, address: 'Přemyslova 899/22, Plzeň 2', description: 'Karel Růžička je klempíř Plzeň s 22 lety zkušeností s montáží okapů, oplechováním komínů a opravami střech. Klempíř v Plzni zajistí kvalitní klempířské práce za přijatelné ceny.', picturePath: null, active: true },
  { fullName: 'Klempíř Vlček Plzeň', phone: '+420 603 558 217', email: 'vlcek@klempir-plzen.cz', serviceId: 'klempir', cityId: CITY, address: 'Košutecká 1677/6, Plzeň 3', description: 'Roman Vlček je klempíř v Plzni nabízející opravy střech, oplechování říms, parapetů a montáž venkovních žaluzií. Klempíř Plzeň pracuje s pozinkovaným, titanzinkovým i měděným plechem.', picturePath: null, active: true },

  // ── AUTOSERVIS ───────────────────────────────────────────────────────────
  { fullName: 'Autoservis Kovář Plzeň', phone: '+420 377 258 900', email: 'info@autoservis-kovar.cz', serviceId: 'autoservis', cityId: CITY, address: 'Jateční 3125/55, Plzeň 1', description: 'Autoservis Kovář nabízí komplexní opravy a servis vozidel všech značek v Plzni. Autoservis Plzeň zajistí pravidelné prohlídky, výměnu oleje, brzd a diagnostiku elektroniky pro zákazníky z Plzeňského kraje.', picturePath: null, active: true },
  { fullName: 'Car Service Plzeň – Holub', phone: '+420 602 774 223', email: 'holub@carservice-plzen.cz', serviceId: 'autoservis', cityId: CITY, address: 'Borská 4588/72, Plzeň 1', description: 'Car Service Holub je autoservis v Plzni zaměřený na opravy motorů, převodovek a klimatizací. Autoservis Plzeň provádí STK přípravu a komplexní servis osobních i užitkových vozidel.', picturePath: null, active: true },
  { fullName: 'Auto Šulc – servis Plzeň', phone: '+420 377 390 127', email: 'sulc@autoplzen.cz', serviceId: 'autoservis', cityId: CITY, address: 'Rokycanská 5001/19, Plzeň 2', description: 'Auto Šulc je rodinný autoservis v Plzni s tradicí přes 25 let, specializující se na osobní vozy a dodávky. Autoservis Plzeň nabízí pneuservis, geometrii náprav a karosářské práce.', picturePath: null, active: true },
  { fullName: 'Autoservis Starý Plzeň', phone: '+420 728 904 456', email: null, serviceId: 'autoservis', cityId: CITY, address: 'Klatovská třída 3398/88, Plzeň 3', description: 'Autoservis Starý je certifikovaný servis v Plzni pro osobní i užitková vozidla. Autoservis Plzeň zajistí diagnostiku závad, opravy elektroniky a pravidelnou údržbu vozidel za konkurenční ceny.', picturePath: null, active: true },

  // ── IT TECHNIK ───────────────────────────────────────────────────────────
  { fullName: 'PC Servis Plzeň – Kříž', phone: '+420 377 327 801', email: 'kriz@pc-plzen.cz', serviceId: 'it-technik', cityId: CITY, address: 'Americká 2109/33, Plzeň 1', description: 'PC Servis Kříž je IT technik v Plzni nabízející opravy počítačů, notebooků a tiskáren pro firmy i domácnosti. IT technik Plzeň zajistí instalaci systémů, obnovu dat a správu sítí.', picturePath: null, active: true },
  { fullName: 'IT pohotovost Plzeň – Navrátil', phone: '+420 603 889 214', email: 'navratil@it-plzen.cz', serviceId: 'it-technik', cityId: CITY, address: 'Náměstí Republiky 14, Plzeň 1', description: 'IT pohotovost Navrátil je zkušený IT technik Plzeň s 20 lety praxe v opravách PC a správě IT infrastruktury. Nabízí nonstop IT pohotovost a vzdálenou správu počítačů v Plzni a okolí.', picturePath: null, active: true },
  { fullName: 'BIT Computer Plzeň', phone: '+420 377 465 700', email: 'info@bit-computer.cz', serviceId: 'it-technik', cityId: CITY, address: 'Slovanská alej 3456/44, Plzeň 2', description: 'BIT Computer je profesionální IT servis v Plzni zaměřený na opravy počítačů, datové zálohy a kybernetickou bezpečnost. IT technik Plzeň poskytuje komplexní ICT podporu pro firmy v Plzeňském kraji.', picturePath: null, active: true },
  { fullName: 'Počítačový servis Pospíšil Plzeň', phone: '+420 728 113 670', email: null, serviceId: 'it-technik', cityId: CITY, address: 'Lochotínská 2345/16, Plzeň 3', description: 'Počítačový servis Pospíšil nabízí opravy a upgrade PC a notebooků v Plzni za dostupné ceny. IT technik Plzeň zajistí reinstalaci systémů, odstranění virů a nastavení Wi-Fi sítí.', picturePath: null, active: true },

  // ── FOTOGRAF ─────────────────────────────────────────────────────────────
  { fullName: 'Foto Studio Novotná Plzeň', phone: '+420 602 547 882', email: 'info@fotonovotna.cz', serviceId: 'fotograf', cityId: CITY, address: 'Masarykova třída 890/11, Plzeň 1', description: 'Foto Studio Novotná je profesionální fotografka v Plzni se zaměřením na rodinné, těhotenské a newborn fotografie. Fotograf Plzeň nabízí moderní fotografické studio a venkovní focení v Plzni a okolí.', picturePath: null, active: true },
  { fullName: 'Reportážní fotograf Blažek Plzeň', phone: '+420 377 221 540', email: 'blazek@foto-plzen.cz', serviceId: 'fotograf', cityId: CITY, address: 'Žižkova 1789/25, Plzeň 1', description: 'Michal Blažek je reportážní a reklamní fotograf v Plzni s více než 15 lety zkušeností. Fotograf Plzeň nabízí firemní fotografii, produktové focení a reportáže z akcí pro klienty v Plzni a okolí.', picturePath: null, active: true },
  { fullName: 'Svatební fotograf Šebela Plzeň', phone: '+420 728 334 901', email: 'sebela@svatebnifoto.cz', serviceId: 'fotograf', cityId: CITY, address: 'Slovanská alej 2876/38, Plzeň 2', description: 'Tomáš Šebela je svatební fotograf v Plzni specializující se na svatební reportáže a portrétní fotografii. Fotograf Plzeň zachytí každý vzácný okamžik vašeho dne s citlivým a přirozeným přístupem.', picturePath: null, active: true },
  { fullName: 'FotoArt Plzeň – Marková', phone: '+420 603 778 120', email: 'markova@fotoart-plzen.cz', serviceId: 'fotograf', cityId: CITY, address: 'Doubravecká 1122/9, Plzeň 4', description: 'FotoArt Marková je fotografka v Plzni nabízející portréty, rodinnou a těhotenskou fotografii ve studiu i exteriéru. Fotograf Plzeň klade důraz na přirozené zachycení emocí a osobitý styl.', picturePath: null, active: true },

  // ── UČITEL / LEKTOR ──────────────────────────────────────────────────────
  { fullName: 'Jazyková škola Cloverleaf Plzeň', phone: '+420 377 320 712', email: 'info@cloverleaf.cz', serviceId: 'ucitel', cityId: CITY, address: 'Americká 1778/22, Plzeň 1', description: 'Jazyková škola Cloverleaf nabízí kurzy angličtiny, němčiny a španělštiny v Plzni pro děti i dospělé. Zkušení lektoři v Plzni zajistí efektivní výuku jazyků a přípravu na mezinárodní certifikáty.', picturePath: null, active: true },
  { fullName: 'Jazyková škola Everesta Plzeň', phone: '+420 377 387 866', email: 'plzen@everesta.cz', serviceId: 'ucitel', cityId: CITY, address: 'Náměstí Republiky 1, Plzeň 1', description: 'Jazyková škola Everesta v Plzni nabízí firemní i individuální jazykové kurzy angličtiny a němčiny. Lektor Plzeň zajistí výuku na míru přímo ve firmě nebo v moderních učebnách v centru Plzně.', picturePath: null, active: true },
  { fullName: 'Doučování Plzeň – Mgr. Horáčková', phone: '+420 604 215 788', email: 'horackovas@douc-plzen.cz', serviceId: 'ucitel', cityId: CITY, address: 'Klatovská třída 456/31, Plzeň 3', description: 'Mgr. Horáčková je zkušená lektorka a učitelka nabízející doučování matematiky, angličtiny a fyziky v Plzni. Lektor Plzeň zajistí individuální přístup k žákům základních a středních škol.', picturePath: null, active: true },
  { fullName: 'Bc. Šimek – lektor angličtiny Plzeň', phone: '+420 728 441 003', email: null, serviceId: 'ucitel', cityId: CITY, address: 'Rooseveltova 2234/7, Plzeň 2', description: 'Bc. Šimek je certifikovaný lektor angličtiny v Plzni s 10 lety praxe ve výuce dospělých a firemní klientely. Lektor angličtiny Plzeň nabízí individuální i skupinové kurzy na všech úrovních znalostí.', picturePath: null, active: true },

  // ── RESTAURACE ───────────────────────────────────────────────────────────
  { fullName: 'Restaurace Šnajdr Plzeň', phone: '+420 377 236 899', email: 'info@restaurace-snajdr.cz', serviceId: 'restaurace', cityId: CITY, address: 'Náměstí Republiky 12, Plzeň 1', description: 'Restaurace Šnajdr je rodinný podnik v centru Plzně nabízející tradiční českou kuchyni s čerstvými surovinami. Restaurace v Plzni nabízí denní polední menu a večerní à la carte v příjemném prostředí.', picturePath: null, active: true },
  { fullName: 'Pivovarská restaurace Purkmistr Plzeň', phone: '+420 377 994 311', email: 'info@purkmistr.cz', serviceId: 'restaurace', cityId: CITY, address: 'Selská náves 21, Plzeň 7 – Černotín', description: 'Pivovarská restaurace Purkmistr je jedinečná restaurace v Plzni s vlastním pivovarem a penziátem. Restaurace Plzeň nabízí autentickou českou kuchyni a domácí pivo v historickém prostředí.', picturePath: null, active: true },
  { fullName: 'Restaurace Šeherezáda Plzeň', phone: '+420 377 327 665', email: null, serviceId: 'restaurace', cityId: CITY, address: 'Americká 2341/53, Plzeň 1', description: 'Restaurace Šeherezáda nabízí orientální a českou kuchyni v Plzni v příjemném prostředí s rychlou obsluhou. Restaurace v Plzni je oblíbená pro firemní obědy i večerní setkání.', picturePath: null, active: true },
  { fullName: 'Bistro U Prazdroje Plzeň', phone: '+420 602 891 234', email: 'bistro@uprazdroje.cz', serviceId: 'restaurace', cityId: CITY, address: 'U Prazdroje 7, Plzeň 1', description: 'Bistro U Prazdroje je oblíbená restaurace v Plzni v srdci pivovarnického čtvrti, nabízející českou kuchyni s plzeňským pivem. Restaurace Plzeň je ideálním místem pro turisty i místní obyvatele.', picturePath: null, active: true },

  // ── ZUBAŘ ────────────────────────────────────────────────────────────────
  { fullName: 'MDDr. Kvasnicová – zubní ordinace Plzeň', phone: '+420 377 441 890', email: 'kvasnicova@zubarplzen.cz', serviceId: 'zubar', cityId: CITY, address: 'Masarykova třída 1122/31, Plzeň 1', description: 'MDDr. Kvasnicová provozuje zubní ordinaci v Plzni nabízející kompletní stomatologickou péči pro děti i dospělé. Zubař Plzeň zajistí ošetření zubů, bělení a ortodontické poradenství v moderně vybavené ordinaci.', picturePath: null, active: true },
  { fullName: 'Stomatologie Procházka Plzeň', phone: '+420 377 524 177', email: 'info@stom-prochazka.cz', serviceId: 'zubar', cityId: CITY, address: 'Americká 3398/44, Plzeň 1', description: 'Stomatologie Procházka je zubní ordinace v Plzni zaměřená na estetickou stomatologii, implantáty a dentální hygienu. Zubař Plzeň přijímá nové pacienty a nabízí individuální přístup ke každému klientovi.', picturePath: null, active: true },
  { fullName: 'Zubní ordinace Vích Plzeň', phone: '+420 377 328 901', email: null, serviceId: 'zubar', cityId: CITY, address: 'Klatovská třída 2789/56, Plzeň 3', description: 'MUDr. Vích provozuje zubní ordinaci v Plzni s komplexními stomatologickými službami včetně chirurgie a protetiky. Zubař Plzeň zajistí odbornou péči o chrup v příjemném a klidném prostředí.', picturePath: null, active: true },
  { fullName: 'Dentální centrum Plzeň', phone: '+420 377 901 234', email: 'info@dental-plzen.cz', serviceId: 'zubar', cityId: CITY, address: 'Slovanská alej 4567/78, Plzeň 2', description: 'Dentální centrum Plzeň je moderní zubní klinika s komplexní péčí od prevence po implantologii. Zubař Plzeň nabízí bezbolestné ošetření, ortodoncii a dentální hygienu pro celou rodinu.', picturePath: null, active: true },

  // ── LÉKAŘ ────────────────────────────────────────────────────────────────
  { fullName: 'MUDr. Kovaříková – praktický lékař Plzeň', phone: '+420 377 237 455', email: 'kovarikova@lekar-plzen.cz', serviceId: 'lekar', cityId: CITY, address: 'Náměstí Republiky 34, Plzeň 1', description: 'MUDr. Kovaříková je praktická lékařka v Plzni s komplexní zdravotní péčí pro dospělé. Lékař Plzeň přijímá nové pacienty a zajistí pravidelné prohlídky, očkování a vydávání receptů.', picturePath: null, active: true },
  { fullName: 'MUDr. Pešek – internista Plzeň', phone: '+420 377 461 233', email: 'pesek@internapesek.cz', serviceId: 'lekar', cityId: CITY, address: 'Husova třída 2345/18, Plzeň 1', description: 'MUDr. Pešek je internista v Plzni specializující se na diagnostiku a léčbu interních onemocnění. Lékař Plzeň nabídne odborné vyšetření a individuální léčebný plán pro pacienty v Plzeňském kraji.', picturePath: null, active: true },
  { fullName: 'Poliklinika Lochotín Plzeň', phone: '+420 377 103 111', email: 'info@poliklinikalochotin.cz', serviceId: 'lekar', cityId: CITY, address: 'Edvarda Beneše 1128/15, Plzeň 3', description: 'Poliklinika Lochotín je zdravotní středisko v Plzni s širokým spektrem praktických a odborných lékařů. Lékař Plzeň – poliklinika nabízí komplexní zdravotní péči pro obyvatele Plzně a Plzeňského kraje.', picturePath: null, active: true },
  { fullName: 'MUDr. Šimánková – pediatr Plzeň', phone: '+420 377 318 766', email: null, serviceId: 'lekar', cityId: CITY, address: 'Slovanská alej 1567/51, Plzeň 2', description: 'MUDr. Šimánková je dětská lékařka – pediatr v Plzni pečující o zdravý vývoj dětí od narození. Lékař Plzeň poskytuje preventivní prohlídky, očkování a léčbu dětských nemocí.', picturePath: null, active: true },

  // ── PSYCHOLOG ─────────────────────────────────────────────────────────────
  { fullName: 'PhDr. Zemanová – psycholog Plzeň', phone: '+420 377 443 210', email: 'zemanova@psycholog-plzen.cz', serviceId: 'psycholog', cityId: CITY, address: 'Americká 1890/28, Plzeň 1', description: 'PhDr. Zemanová je psycholog v Plzni nabízející individuální psychoterapii, párové poradenství a krizovou intervenci. Psycholog Plzeň pomáhá klientům zvládat úzkosti, deprese a životní změny.', picturePath: null, active: true },
  { fullName: 'Mgr. Forman – psychoterapeut Plzeň', phone: '+420 602 778 341', email: 'forman@terapie-plzen.cz', serviceId: 'psycholog', cityId: CITY, address: 'Náměstí Republiky 56, Plzeň 1', description: 'Mgr. Forman je psychoterapeut v Plzni s výcvikem v kognitivně-behaviorální terapii. Psycholog Plzeň nabízí individuální, párovou a skupinovou terapii pro dospělé.', picturePath: null, active: true },
  { fullName: 'Centrum psychologické pomoci Plzeň', phone: '+420 377 989 123', email: 'info@cpp-plzen.cz', serviceId: 'psycholog', cityId: CITY, address: 'Husova třída 1122/7, Plzeň 1', description: 'Centrum psychologické pomoci Plzeň je poradenské centrum s týmem zkušených psychologů a terapeutů. Psycholog Plzeň nabízí diagnostiku, poradenství a terapii pro děti, dospělé i rodiny.', picturePath: null, active: true },
  { fullName: 'Mgr. Houšková – terapeutka Plzeň', phone: '+420 728 445 667', email: null, serviceId: 'psycholog', cityId: CITY, address: 'Klatovská třída 890/63, Plzeň 3', description: 'Mgr. Houšková je psycholožka a terapeutka v Plzni specializující se na práci s traumatem, úzkostí a seberozvojem. Psycholog Plzeň pracuje s dospělými i adolescenty metodou EMDR a systemické terapie.', picturePath: null, active: true },

  // ── PRÁVNÍK ──────────────────────────────────────────────────────────────
  { fullName: 'JUDr. Mašek – advokát Plzeň', phone: '+420 377 322 891', email: 'masek@advokatplzen.cz', serviceId: 'pravnik', cityId: CITY, address: 'Náměstí Republiky 22, Plzeň 1', description: 'JUDr. Mašek je advokát v Plzni zaměřený na občanské, obchodní a rodinné právo. Právník Plzeň nabízí právní poradenství, sepis smluv a zastupování klientů před soudy v Plzeňském kraji.', picturePath: null, active: true },
  { fullName: 'Advokátní kancelář Šimánek Plzeň', phone: '+420 377 410 067', email: 'simanek@ak-plzen.cz', serviceId: 'pravnik', cityId: CITY, address: 'Žižkova 2567/44, Plzeň 1', description: 'Advokátní kancelář Šimánek je právní firma v Plzni specializující se na pracovní právo, nemovitosti a obchodní spory. Právník Plzeň zajistí komplexní právní zastoupení a poradenství.', picturePath: null, active: true },
  { fullName: 'JUDr. Horáček – notář Plzeň', phone: '+420 377 328 445', email: 'horacek@notar-plzen.cz', serviceId: 'pravnik', cityId: CITY, address: 'Americká 3211/29, Plzeň 1', description: 'JUDr. Horáček je notář a právník v Plzni zajišťující sepisování závětí, darování, kupních smluv a ověřování podpisů. Právník Plzeň poskytuje notářské a právní služby pro fyzické i právnické osoby.', picturePath: null, active: true },
  { fullName: 'Mgr. Veselá – rodinné právo Plzeň', phone: '+420 604 220 789', email: null, serviceId: 'pravnik', cityId: CITY, address: 'Husova třída 678/12, Plzeň 1', description: 'Mgr. Veselá je právnička v Plzni specializující se na rodinné právo, rozvody a opatrovnická řízení. Právník Plzeň nabídne empatické a profesionální zastupování v soudních sporech o děti.', picturePath: null, active: true },

  // ── ÚČETNÍ ───────────────────────────────────────────────────────────────
  { fullName: 'Účetní poradenství Malá Plzeň', phone: '+420 377 443 210', email: 'mala@ucetni-plzen.cz', serviceId: 'ucetni', cityId: CITY, address: 'Náměstí Republiky 3, Plzeň 1', description: 'Účetní poradenství Malá nabízí vedení účetnictví, daňové přiznání a mzdovou agendu pro firmy v Plzni. Účetní Plzeň poskytuje kompletní ekonomické poradenství pro OSVČ i právnické osoby.', picturePath: null, active: true },
  { fullName: 'ECO Consulting Plzeň', phone: '+420 377 521 800', email: 'info@eco-consulting-plzen.cz', serviceId: 'ucetni', cityId: CITY, address: 'Klatovská třída 1890/35, Plzeň 3', description: 'ECO Consulting je účetní firma v Plzni specializující se na podvojné účetnictví, DPH a daňovou optimalizaci. Účetní Plzeň zajistí přesné zpracování daňových přiznání a roční závěrky.', picturePath: null, active: true },
  { fullName: 'Bc. Křenková – účetní a mzdy Plzeň', phone: '+420 728 334 456', email: 'krenkova@ucetni-mzdy.cz', serviceId: 'ucetni', cityId: CITY, address: 'Slovanská alej 2123/19, Plzeň 2', description: 'Bc. Křenková je účetní v Plzni se specializací na zpracování mezd, daňové přiznání a vedení daňové evidence. Účetní Plzeň nabízí přesné a spolehlivé zpracování dokladů pro malé a střední firmy.', picturePath: null, active: true },
  { fullName: 'AUDIT PLZEŇ – účetní kancelář', phone: '+420 602 557 890', email: 'audit@ucplzen.cz', serviceId: 'ucetni', cityId: CITY, address: 'Americká 3456/61, Plzeň 1', description: 'AUDIT PLZEŇ je účetní kancelář v Plzni nabízející komplexní ekonomické a daňové poradenství pro podnikatele. Účetní Plzeň zpracuje daňová přiznání, roční závěrky i reporty pro zahraniční mateřské firmy.', picturePath: null, active: true },

  // ── KADEŘNÍK ─────────────────────────────────────────────────────────────
  { fullName: 'Kadeřnictví Nováčková Plzeň', phone: '+420 377 221 345', email: null, serviceId: 'kadernik', cityId: CITY, address: 'Masarykova třída 789/14, Plzeň 1', description: 'Kadeřnictví Nováčková nabízí střihy, barvení a styling vlasů pro ženy i muže v Plzni. Kadeřník Plzeň pracuje s prémiovou kosmetikou a zajistí individuální poradenství o péči o vlasy.', picturePath: null, active: true },
  { fullName: 'Salon Erika – kadeřnictví Plzeň', phone: '+420 377 458 900', email: 'erika@salon-erika.cz', serviceId: 'kadernik', cityId: CITY, address: 'Žižkova 1345/8, Plzeň 1', description: 'Salon Erika je moderní kadeřnický salon v Plzni se zkušenými stylisty a kadeřnicemi. Kadeřník Plzeň nabízí barvení, melír, keratin a svatební účesy v příjemném prostředí salonu.', picturePath: null, active: true },
  { fullName: 'Kadeřnictví Kopecká Plzeň', phone: '+420 602 445 123', email: null, serviceId: 'kadernik', cityId: CITY, address: 'Slovanská alej 988/27, Plzeň 2', description: 'Kadeřnictví Kopecká je rodinný salon v Plzni nabízející kompletní kadeřnické služby – střihy, barvení a rekonstrukce vlasů. Kadeřník Plzeň zajistí péči o vlasy v přátelské a příjemné atmosféře.', picturePath: null, active: true },
  { fullName: 'Studio Versus – kadeřnictví Plzeň', phone: '+420 377 335 678', email: 'versus@kadernictvi-plzen.cz', serviceId: 'kadernik', cityId: CITY, address: 'Lochotínská 2334/22, Plzeň 3', description: 'Studio Versus je prémiové kadeřnické studio v Plzni zaměřené na moderní trendy v barvení a styling vlasů. Kadeřník Plzeň nabízí konzultace, střihy a speciální ošetření vlasů pro náročné klientky.', picturePath: null, active: true },

  // ── ARCHITEKT ────────────────────────────────────────────────────────────
  { fullName: 'Ing. arch. Houšek – architekt Plzeň', phone: '+420 377 422 780', email: 'housek@architektplzen.cz', serviceId: 'architekt', cityId: CITY, address: 'Náměstí Republiky 45, Plzeň 1', description: 'Ing. arch. Houšek je architekt v Plzni nabízející projektování rodinných domů, bytových rekonstrukcí a komerčních prostor. Architekt Plzeň navrhuje funkční a estetická řešení s důrazem na nízkoenergetické standardy.', picturePath: null, active: true },
  { fullName: 'Ateliér Trojúhelník – architekti Plzeň', phone: '+420 377 534 122', email: 'info@trojuhelnik-architekti.cz', serviceId: 'architekt', cityId: CITY, address: 'Americká 2234/37, Plzeň 1', description: 'Ateliér Trojúhelník je architektonické studio v Plzni s portfoliem rezidenčních, komerčních a veřejných staveb. Architekt Plzeň nabídne kompletní projektové služby od studie po realizaci.', picturePath: null, active: true },
  { fullName: 'Ing. arch. Součková – interiéry Plzeň', phone: '+420 603 882 445', email: 'souckova@interier-plzen.cz', serviceId: 'architekt', cityId: CITY, address: 'Husova třída 890/9, Plzeň 1', description: 'Ing. arch. Součková je architektka a interiérová designérka v Plzni zaměřená na komplexní návrhy interiérů bytů a kanceláří. Architekt Plzeň navrhuje prostory s ohledem na funkčnost, estetiku a přání klienta.', picturePath: null, active: true },
  { fullName: 'STUDIO A.T.A. – architekti Plzeň', phone: '+420 377 620 110', email: 'ata@studio-ata.cz', serviceId: 'architekt', cityId: CITY, address: 'Klatovská třída 3210/67, Plzeň 3', description: 'STUDIO A.T.A. je architektonická kancelář v Plzni realizující rodinné domy, rekonstrukce a urbanistické projekty. Architekt Plzeň zajistí profesionální projekt od konceptu přes povolení až po dozor na stavbě.', picturePath: null, active: true },

  // ── REALITNÍ MAKLÉŘ ──────────────────────────────────────────────────────
  { fullName: 'RE/MAX Alfa – realitní kancelář Plzeň', phone: '+420 377 244 555', email: 'alfa@remax-plzen.cz', serviceId: 'realitni-makler', cityId: CITY, address: 'Americká 3567/50, Plzeň 1', description: 'RE/MAX Alfa je realitní kancelář v Plzni s týmem zkušených makléřů pro prodej a pronájem bytů, domů a komerčních prostor. Realitní makléř Plzeň zajistí odborné ocenění nemovitosti a efektivní marketing.', picturePath: null, active: true },
  { fullName: 'Realitní kancelář Plzeň – Soukup', phone: '+420 377 310 700', email: 'soukup@rk-plzen.cz', serviceId: 'realitni-makler', cityId: CITY, address: 'Náměstí Republiky 78, Plzeň 1', description: 'Realitní kancelář Soukup je zavedená realitní firma v Plzni s více než 15 lety zkušeností na trhu s nemovitostmi. Realitní makléř Plzeň pomůže s koupí, prodejem i pronájmem nemovitostí v Plzeňském kraji.', picturePath: null, active: true },
  { fullName: 'STING realitní Plzeň', phone: '+420 602 888 341', email: 'info@sting-reality.cz', serviceId: 'realitni-makler', cityId: CITY, address: 'Slovanská alej 4321/62, Plzeň 2', description: 'STING realitní je dynamická realitní kancelář v Plzni zaměřená na prodej novostaveb a investičních bytů. Realitní makléř Plzeň nabídne profesionální fotografii, 3D prohlídky a právní servis k nemovitostem.', picturePath: null, active: true },
  { fullName: 'Reality Kopřiva – makléř Plzeň', phone: '+420 728 003 456', email: null, serviceId: 'realitni-makler', cityId: CITY, address: 'Žižkova 3456/55, Plzeň 1', description: 'Reality Kopřiva je realitní makléř v Plzni specializující se na rezidenční nemovitosti v Plzni a okolí. Makléř Plzeň nabídne individuální přístup, provizi jen při úspěšném prodeji a kompletní administrativní servis.', picturePath: null, active: true },

  // ── ZAHRADNÍK ────────────────────────────────────────────────────────────
  { fullName: 'Zahradnictví Šimon Plzeň', phone: '+420 602 334 780', email: 'simon@zahradnictvi-plzen.cz', serviceId: 'zahradnik', cityId: CITY, address: 'Doubravecká 3456/18, Plzeň 4', description: 'Zahradnictví Šimon nabízí kompletní zahradnické práce v Plzni – sekání trávníků, výsadbu rostlin a zakládání zahrad. Zahradník Plzeň zajistí pravidelnou údržbu zahrady a péči o zeleň pro soukromníky i firmy.', picturePath: null, active: true },
  { fullName: 'Green Garden Plzeň', phone: '+420 377 556 234', email: 'info@greengarden-plzen.cz', serviceId: 'zahradnik', cityId: CITY, address: 'Nepomucká 1234/33, Plzeň 4', description: 'Green Garden je zahradní firma v Plzni nabízející návrhy a realizaci zahrad, terasy a zelené střechy. Zahradník Plzeň provede kompletní terénní úpravy, automatické zavlažování a instalaci zahradních prvků.', picturePath: null, active: true },
  { fullName: 'Zahradní úpravy Novák Plzeň', phone: '+420 728 441 234', email: null, serviceId: 'zahradnik', cityId: CITY, address: 'Bochovská 2345/11, Plzeň 1', description: 'Zahradní úpravy Novák je zahradník v Plzni zajišťující terénní úpravy, výsadbu stromů a sezónní péči o zahrady. Zahradník Plzeň nabídne osobní poradenství a realizaci zahradních projektů.', picturePath: null, active: true },
  { fullName: 'Arboristika Plzeň – Haas', phone: '+420 603 117 890', email: 'haas@arboristika-plzen.cz', serviceId: 'zahradnik', cityId: CITY, address: 'Radčická 789/4, Plzeň 6', description: 'Arboristika Plzeň Haas nabízí profesionální péči o stromy, kácení a ošetřování dřevin v Plzni. Zahradník Plzeň provede výškové práce, redukci korun a odborné posudky o zdravotním stavu stromů.', picturePath: null, active: true },

  // ── ÚKLID ────────────────────────────────────────────────────────────────
  { fullName: 'Čistota Plzeň – úklidová firma', phone: '+420 377 890 234', email: 'info@cistota-plzen.cz', serviceId: 'uklid', cityId: CITY, address: 'Masarykova třída 2345/28, Plzeň 1', description: 'Čistota Plzeň je profesionální úklidová firma nabízející pravidelný i jednorázový úklid bytů a kanceláří v Plzni. Úklid Plzeň zajistí čisté prostředí s ekologickými čisticími prostředky a spolehlivým týmem.', picturePath: null, active: true },
  { fullName: 'CleanPro Plzeň', phone: '+420 602 778 901', email: 'cleanpro@uklid-plzen.cz', serviceId: 'uklid', cityId: CITY, address: 'Klatovská třída 4567/91, Plzeň 3', description: 'CleanPro je úklidová společnost v Plzni specializující se na úklid po rekonstrukci, výluce a generální úklid domácností. Úklid Plzeň nabídne rychlý nástup a záruky spokojenosti na veškeré provedené práce.', picturePath: null, active: true },
  { fullName: 'Paní na úklid Plzeň – Procházková', phone: '+420 728 556 789', email: null, serviceId: 'uklid', cityId: CITY, address: 'Slovanská alej 3456/47, Plzeň 2', description: 'Paní Procházková nabízí pravidelný domácí úklid bytů a domů v Plzni s osobním přístupem a spolehlivostí. Úklid Plzeň – domácí pomoc pro rodiny a seniory v Plzni a přilehlém okolí.', picturePath: null, active: true },
  { fullName: 'TopClean Plzeň', phone: '+420 377 445 678', email: 'info@topclean-plzen.cz', serviceId: 'uklid', cityId: CITY, address: 'Americká 5678/84, Plzeň 1', description: 'TopClean je úklidová firma v Plzni s komplexní nabídkou čistění koberců, čalounění a mytí oken. Úklid Plzeň provádí profesionální dezinfekce a sanace bytů, kanceláří i průmyslových prostor.', picturePath: null, active: true },

  // ── STĚHOVACÍ FIRMA ──────────────────────────────────────────────────────
  { fullName: 'Stěhování Plzeň – Novák Transport', phone: '+420 377 334 120', email: 'novak@stehovaniplzen.cz', serviceId: 'stehovaci-firma', cityId: CITY, address: 'Borská 6789/108, Plzeň 1', description: 'Stěhování Plzeň Novák Transport nabízí profesionální stěhování bytů, kanceláří a firem v Plzni a celé ČR. Stěhovací firma Plzeň zajistí bezpečné zabalení, přepravu a složení nábytku na novém místě.', picturePath: null, active: true },
  { fullName: 'Fast Move Plzeň', phone: '+420 602 891 345', email: 'info@fastmove-plzen.cz', serviceId: 'stehovaci-firma', cityId: CITY, address: 'Rokycanská 7890/44, Plzeň 2', description: 'Fast Move je rychlá stěhovací firma v Plzni zajišťující stěhování bytů i firem s vlastním vozovým parkem. Stěhovací firma Plzeň nabídne bezpečnostní balení, demontáž a montáž nábytku.', picturePath: null, active: true },
  { fullName: 'Stěhování Dvořák Plzeň', phone: '+420 728 778 234', email: null, serviceId: 'stehovaci-firma', cityId: CITY, address: 'Lochotínská 5678/39, Plzeň 3', description: 'Stěhování Dvořák je spolehlivá stěhovací firma v Plzni s vlastními stěhovacími vozidly a pojištěním nákladu. Stěhovací firma Plzeň realizuje stěhování po Plzni i mezinárodní přepravu.', picturePath: null, active: true },
  { fullName: 'Profi Stěhování Plzeň', phone: '+420 603 334 456', email: 'profistehov@plzen-move.cz', serviceId: 'stehovaci-firma', cityId: CITY, address: 'Doubravecká 4567/27, Plzeň 4', description: 'Profi Stěhování Plzeň je komplexní stěhovací firma pro domácnosti i firmy v Plzeňském kraji. Stěhovací firma Plzeň zajistí expresní i plánované stěhování s přesností a péčí o každý kus majetku.', picturePath: null, active: true },

  // ── TRENÉR ───────────────────────────────────────────────────────────────
  { fullName: 'Fitness trenér Holík Plzeň', phone: '+420 728 441 890', email: 'holik@fitnes-plzen.cz', serviceId: 'trener', cityId: CITY, address: 'Americká 6789/95, Plzeň 1', description: 'Fitness trenér Holík je osobní trenér v Plzni nabízející sestavení tréninkových plánů a nutriční poradenství. Trenér Plzeň pomůže s hubnutím, nabíráním svalové hmoty a zlepšením kondice.', picturePath: null, active: true },
  { fullName: 'Jana Moučková – osobní trenérka Plzeň', phone: '+420 377 560 234', email: 'mouckova@trenerplzen.cz', serviceId: 'trener', cityId: CITY, address: 'Slovanská alej 5678/71, Plzeň 2', description: 'Jana Moučková je certifikovaná osobní trenérka v Plzni specializující se na funkční trénink, jógu a pilates. Trenér Plzeň nabídne individuální fitness program a motivaci pro dosažení zdravotních i sportovních cílů.', picturePath: null, active: true },
  { fullName: 'Sportovní centrum Lokomotiva Plzeň', phone: '+420 377 455 666', email: 'info@lokomotivaplzen.cz', serviceId: 'trener', cityId: CITY, address: 'Úslavská 75, Plzeň 2', description: 'Sportovní centrum Lokomotiva nabízí trenéry a sportovní kurzy pro děti i dospělé v Plzni. Trenér Plzeň v areálu Lokomotivy zajistí atletiku, plavání a skupinové kondičníkurzy.', picturePath: null, active: true },
  { fullName: 'Mgr. Šimánek – trenér atletiky Plzeň', phone: '+420 603 228 901', email: null, serviceId: 'trener', cityId: CITY, address: 'Lochotínská 4321/33, Plzeň 3', description: 'Mgr. Šimánek je trenér atletiky a kondičního tréninku v Plzni s licencí ČSAS. Trenér Plzeň pracuje s dětmi, juniory i dospělými závodníky na atletickém stadionu v Plzni.', picturePath: null, active: true },

  // ── PŘEKLADATEL ──────────────────────────────────────────────────────────
  { fullName: 'Překladatelské centrum Plzeň', phone: '+420 377 441 760', email: 'info@prekladplzen.cz', serviceId: 'prekladatel', cityId: CITY, address: 'Náměstí Republiky 34, Plzeň 1', description: 'Překladatelské centrum Plzeň nabízí odborné překlady z angličtiny, němčiny a dalších jazyků pro firmy i jednotlivce. Překladatel Plzeň zajistí přesné překlady smluv, technických dokumentů a úředních listin.', picturePath: null, active: true },
  { fullName: 'Mgr. Horáková – překladatelka Plzeň', phone: '+420 603 778 450', email: 'horakova@prekladplzen.cz', serviceId: 'prekladatel', cityId: CITY, address: 'Americká 1122/16, Plzeň 1', description: 'Mgr. Horáková je soudní překladatelka pro němčinu a angličtinu v Plzni s oprávněním od Krajského soudu. Překladatel Plzeň provede úřední překlady dokumentů s apostilou pro státní orgány a instituce.', picturePath: null, active: true },
  { fullName: 'ProTranslate Plzeň', phone: '+420 377 329 112', email: 'info@protranslate-plzen.cz', serviceId: 'prekladatel', cityId: CITY, address: 'Husova třída 2345/38, Plzeň 1', description: 'ProTranslate je překladatelská agentura v Plzni zajišťující překlady do více než 30 jazyků pro firmy a instituce. Překladatel Plzeň nabídne expresní i standardní překlad s garancí kvality a diskrétnosti.', picturePath: null, active: true },
  { fullName: 'Bc. Červenková – tlumočnice Plzeň', phone: '+420 728 113 456', email: null, serviceId: 'prekladatel', cityId: CITY, address: 'Slovanská alej 3456/54, Plzeň 2', description: 'Bc. Červenková je překladatelka a tlumočnice pro angličtinu a francouzštinu v Plzni. Překladatel Plzeň nabízí konsekutivní a simultánní tlumočení na konferencích, jednáních a firemních akcích.', picturePath: null, active: true },

  // ── GRAFIK ───────────────────────────────────────────────────────────────
  { fullName: 'Grafické studio Vávra Plzeň', phone: '+420 377 450 890', email: 'vavra@grafika-plzen.cz', serviceId: 'grafik', cityId: CITY, address: 'Náměstí Republiky 67, Plzeň 1', description: 'Grafické studio Vávra nabízí komplexní grafické služby v Plzni – loga, firemní identitu, tisk a webdesign. Grafik Plzeň zajistí profesionální vizuální komunikaci pro startupy i zavedené firmy.', picturePath: null, active: true },
  { fullName: 'PixelArt Plzeň – grafický design', phone: '+420 602 334 780', email: 'info@pixelart-plzen.cz', serviceId: 'grafik', cityId: CITY, address: 'Americká 2345/42, Plzeň 1', description: 'PixelArt Plzeň je grafické studio specializující se na digitální design, tvorbu webů a reklamní kampaně. Grafik Plzeň nabídne kreativní řešení pro marketing a branding firem v Plzeňském kraji.', picturePath: null, active: true },
  { fullName: 'Bc. Pokorná – grafička Plzeň', phone: '+420 728 887 123', email: 'pokorna@grafika-plzen.cz', serviceId: 'grafik', cityId: CITY, address: 'Klatovská třída 1234/56, Plzeň 3', description: 'Bc. Pokorná je freelance grafička v Plzni nabízející návrhy letáků, plakátů a obalového designu. Grafik Plzeň pracuje pro agentury i přímé klienty s rychlými dodacími lhůtami a precizním výsledkem.', picturePath: null, active: true },
  { fullName: 'Studia Kreativa Plzeň', phone: '+420 603 556 890', email: 'studio@kreativa-plzen.cz', serviceId: 'grafik', cityId: CITY, address: 'Husova třída 3456/45, Plzeň 1', description: 'Studia Kreativa je grafická agentura v Plzni s kompletními kreativními službami – logo, web, video a sociální sítě. Grafik Plzeň pomůže firmám budovat silnou vizuální značku a efektivní online prezentaci.', picturePath: null, active: true },
];

async function main() {
  let count = 0;
  for (const p of profiles) {
    const created = await prisma.provider.create({ data: p });
    console.log(`✓ ${created.fullName}`);
    count++;
  }
  console.log(`\nDone. Added ${count} profiles.`);
}
main().catch(console.error).finally(() => prisma.$disconnect());
