import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();
const CITY = 'brno';

const profiles = [
  // ── ELEKTRIKÁŘ ────────────────────────────────────────────────────────────
  { fullName: 'Elektro Beneš Brno', phone: '+420 731 154 872', email: 'info@elektrobenes.cz', serviceId: 'elektrikar', cityId: CITY, address: 'Cejl 72, Brno', description: 'Elektro Beneš nabízí veškeré elektroinstalační práce pro domácnosti i firmy v Brně a okolí. Elektrikář Brno zajišťuje montáž rozvaděčů, havarijní opravy a elektrorevize na klíč.', picturePath: null, active: true },
  { fullName: 'Jiří Novotný – elektrikář Brno', phone: '+420 775 332 110', email: null, serviceId: 'elektrikar', cityId: CITY, address: 'Kounicova 271/13, Brno', description: 'Jiří Novotný provádí komplexní elektroinstalace a opravy v Brně s více než 15 lety praxe. Elektrikář v Brně nabízí rychlé havarijní výjezdy a montáž osvětlení pro byty i kanceláře.', picturePath: null, active: true },
  { fullName: 'ELMONT Brno s.r.o.', phone: '+420 543 211 456', email: 'elmont@elmont-brno.cz', serviceId: 'elektrikar', cityId: CITY, address: 'Dornych 47, Brno', description: 'ELMONT Brno se specializuje na průmyslové a bytové elektroinstalace v Brně a Jihomoravském kraji. Firma zajišťuje projekci, montáž i servis elektrických zařízení pro zákazníky po celém Brně.', picturePath: null, active: true },
  { fullName: 'Pavel Kratochvíl – elektroinstalace Brno', phone: '+420 608 774 221', email: 'p.kratochvil@email.cz', serviceId: 'elektrikar', cityId: CITY, address: 'Hybešova 42, Brno', description: 'Pavel Kratochvíl je zkušený elektrikář působící v Brně a okolí se zaměřením na rekonstrukce bytů a domů. Provádí veškeré elektroinstalační práce v Brně včetně montáže fotovoltaických systémů.', picturePath: null, active: true },

  // ── INSTALATÉR ────────────────────────────────────────────────────────────
  { fullName: 'Instalatér Brno – Roman Sedlák', phone: '+420 774 885 321', email: 'sedlak.instalater@seznam.cz', serviceId: 'instalater', cityId: CITY, address: 'Lidická 26, Brno', description: 'Roman Sedlák nabízí profesionální instalatérské a topenářské práce v Brně a širokém okolí. Instalatér Brno zajišťuje montáž, opravy a rekonstrukce vodovodních rozvodů i topných systémů.', picturePath: null, active: true },
  { fullName: 'Vodo-topo Horáček Brno', phone: '+420 543 245 678', email: 'info@vodotopo-horacek.cz', serviceId: 'instalater', cityId: CITY, address: 'Štefánikova 51, Brno', description: 'Vodo-topo Horáček je zavedená instalatérská firma v Brně s tradicí od roku 1998. Instalatér Brno provádí montáž kotlů, podlahového vytápění a kompletní rekonstrukce koupelen.', picturePath: null, active: true },
  { fullName: 'Nonstop instalatér Brno', phone: '+420 800 100 300', email: 'info@nonstop-instalater-brno.cz', serviceId: 'instalater', cityId: CITY, address: 'Veveří 102, Brno', description: 'Nonstop instalatér Brno zajišťuje havarijní opravy vody a kanalizace 24 hodin denně, 7 dní v týdnu. Rychlý výjezd instalatéra po celém Brně do 30 minut od zavolání.', picturePath: null, active: true },
  { fullName: 'Martin Vlček – instalatér Brno', phone: '+420 731 456 789', email: null, serviceId: 'instalater', cityId: CITY, address: 'Masarykova 17, Brno', description: 'Martin Vlček poskytuje instalatérské služby v Brně zaměřené na montáž a opravy vodovodních baterií, toalet a sprchových koutů. Instalatér Brno nabízí rychlý servis pro domácnosti i bytová společenství.', picturePath: null, active: true },

  // ── MALÍŘ POKOJŮ ──────────────────────────────────────────────────────────
  { fullName: 'Malíř pokojů Brno – Tomáš Král', phone: '+420 608 221 543', email: 'tomas.kral.malir@gmail.com', serviceId: 'malir', cityId: CITY, address: 'Cejl 15, Brno', description: 'Tomáš Král je profesionální malíř pokojů v Brně s více než 20 lety zkušeností s malováním bytů a kanceláří. Malíř Brno nabízí kompletní přípravu povrchů, malování a dekorativní techniky za přijatelné ceny.', picturePath: null, active: true },
  { fullName: 'Malířství Dvořák Brno', phone: '+420 775 112 334', email: 'dvorak.maliristvi@seznam.cz', serviceId: 'malir', cityId: CITY, address: 'Žabovřeská 14, Brno', description: 'Malířství Dvořák nabízí profesionální malování bytů, domů a komerčních prostor v Brně. Malíř pokojů Brno zajišťuje výmalby, nátěry fasád a stříkání barev pro zákazníky v celém Jihomoravském kraji.', picturePath: null, active: true },
  { fullName: 'Malovani-brno.cz – Petr Šimánek', phone: '+420 737 665 441', email: 'info@malovani-brno.cz', serviceId: 'malir', cityId: CITY, address: 'Náměstí Svobody 8, Brno', description: 'Petr Šimánek je zkušený malíř pokojů Brno se specializací na čisté a precizní výmalby bytů, domů a kanceláří. Nabízí bezplatnou cenovou nabídku a záruku na odvedenou malířskou práci v Brně.', picturePath: null, active: true },
  { fullName: 'Lukáš Bárta – malíř Brno', phone: '+420 604 338 772', email: null, serviceId: 'malir', cityId: CITY, address: 'Křenová 68, Brno', description: 'Lukáš Bárta provádí malířské a natěračské práce v Brně pro domácnosti i firmy za konkurenční ceny. Malíř pokojů Brno se zaměřuje na rekonstrukce bytů, nátěry dřeva a kovových konstrukcí.', picturePath: null, active: true },

  // ── TESAŘ ─────────────────────────────────────────────────────────────────
  { fullName: 'Tesařství Procházka Brno', phone: '+420 775 441 220', email: 'tesarstvi.prochazka@email.cz', serviceId: 'tesar', cityId: CITY, address: 'Sladkovského 7, Brno', description: 'Tesařství Procházka nabízí kompletní tesařské práce v Brně – stavba krovů, střešních konstrukcí a pergol. Tesař Brno zajišťuje veškeré dřevěné konstrukce pro novostavby i rekonstrukce v Jihomoravském kraji.', picturePath: null, active: true },
  { fullName: 'Ondřej Malý – tesař Brno', phone: '+420 608 554 119', email: null, serviceId: 'tesar', cityId: CITY, address: 'Brno – Líšeň', description: 'Ondřej Malý je zkušený tesař v Brně specializující se na dřevěné střešní konstrukce, vikýře a přestavby podkroví. Tesař Brno realizuje zakázky pro rodinné domy i bytové komplexy v celém Brně a okolí.', picturePath: null, active: true },
  { fullName: 'Truhlářství a tesařství Veselý Brno', phone: '+420 543 334 217', email: 'vesely@tesarbrno.cz', serviceId: 'tesar', cityId: CITY, address: 'Hájecká 3, Brno – Kohoutovice', description: 'Firma Veselý nabízí tesařské i truhlářské práce v Brně a okolí pod jednou střechou. Tesař Brno provádí krovy, dřevostavby, zahradní altány a opravy historických dřevěných konstrukcí.', picturePath: null, active: true },
  { fullName: 'Radek Horák – tesař a pokrývač Brno', phone: '+420 731 228 904', email: null, serviceId: 'tesar', cityId: CITY, address: 'Tuřanka 12, Brno – Slatina', description: 'Radek Horák nabízí komplexní tesařské a pokrývačské práce v Brně včetně stavby krovů, zateplení střech a montáže střešních oken. Tesař Brno garantuje kvalitní provedení a dodržení termínů.', picturePath: null, active: true },

  // ── TRUHLÁŘ ───────────────────────────────────────────────────────────────
  { fullName: 'Truhlářství Novák Brno', phone: '+420 543 225 678', email: 'info@truhlarstvi-novak-brno.cz', serviceId: 'truhlar', cityId: CITY, address: 'Hněvkovského 30, Brno – Komárov', description: 'Truhlářství Novák vyrábí nábytek na míru a provádí truhlářské práce v Brně již přes 25 let. Truhlář Brno nabízí výrobu kuchyňských linek, vestavěných skříní, dveří a okenních rámů.', picturePath: null, active: true },
  { fullName: 'DREVOART – truhlářství Brno', phone: '+420 775 883 440', email: 'drevoart@drevoart.cz', serviceId: 'truhlar', cityId: CITY, address: 'Vídeňská 105, Brno', description: 'DREVOART je moderní truhlářství v Brně zaměřené na výrobu designového nábytku a interiérových prvků na míru. Truhlář Brno zpracovává zakázky od projektu až po montáž přímo u zákazníka.', picturePath: null, active: true },
  { fullName: 'František Pospíšil – truhlář Brno', phone: '+420 608 114 553', email: null, serviceId: 'truhlar', cityId: CITY, address: 'Brno – Židenice', description: 'František Pospíšil je zkušený truhlář v Brně nabízející výrobu a montáž dřevěného nábytku, schodišť a parket. Truhlář Brno pracuje s masivním dřevem i dřevotřískou dle přání zákazníka.', picturePath: null, active: true },
  { fullName: 'Nábytek na míru Brno – Krejčí', phone: '+420 737 441 225', email: 'krejci@nabytek-brno.cz', serviceId: 'truhlar', cityId: CITY, address: 'Plotní 75, Brno', description: 'Truhlářská firma Krejčí vyrábí nábytek na míru a interiérové prvky pro zákazníky po celém Brně. Truhlář Brno se specializuje na vestavěné skříně, kuchyně a posuvné dveřní systémy.', picturePath: null, active: true },

  // ── ZUBAŘ ─────────────────────────────────────────────────────────────────
  { fullName: 'MUDr. Jana Horáková – zubní ordinace Brno', phone: '+420 543 213 456', email: 'horakova@zubar-brno.cz', serviceId: 'zubar', cityId: CITY, address: 'Česká 18, Brno', description: 'MUDr. Jana Horáková provozuje moderní zubní ordinaci v centru Brna s komplexní péčí pro dospělé i děti. Zubař Brno nabízí preventivní prohlídky, bělení zubů, implantáty a estetickou stomatologii.', picturePath: null, active: true },
  { fullName: 'MDDr. Petr Vlček – zubař Brno', phone: '+420 775 554 332', email: null, serviceId: 'zubar', cityId: CITY, address: 'Kounicova 47, Brno – Královo Pole', description: 'MDDr. Petr Vlček vede zubní ordinaci v Brně Královo Pole zaměřenou na bezbolestné ošetření a moderní stomatologické postupy. Zubař Brno přijímá nové pacienty a nabízí pohotovostní ošetření.', picturePath: null, active: true },
  { fullName: 'Stomatologie Brno – MUDr. Lenka Marková', phone: '+420 543 255 789', email: 'markova@stomatologie-brno.cz', serviceId: 'zubar', cityId: CITY, address: 'Vídeňská 8, Brno', description: 'MUDr. Lenka Marková provozuje stomatologickou ordinaci v Brně se specializací na protetiku a implantologii. Zubní ordinace Brno nabízí celistvou péči o chrup od prevence přes léčbu až po estetické zákroky.', picturePath: null, active: true },
  { fullName: 'Zubní klinika Brno – Dr. Tomáš Bartoš', phone: '+420 533 442 211', email: 'info@zubni-klinika-brno.cz', serviceId: 'zubar', cityId: CITY, address: 'Veveří 56, Brno', description: 'Dr. Tomáš Bartoš vede zubní kliniku v Brně s širokým spektrem stomatologických služeb včetně ortodoncie a implantologie. Zubař Brno přijímá pacienty všech věkových kategorií a nabízí pohodlné ošetření.', picturePath: null, active: true },

  // ── STĚHOVÁNÍ ─────────────────────────────────────────────────────────────
  { fullName: 'Stěhování Brno – Express', phone: '+420 774 633 221', email: 'info@stehovani-brno-express.cz', serviceId: 'stehovaci-firma', cityId: CITY, address: 'Olomoucká 174, Brno', description: 'Stěhování Brno Express zajišťuje rychlé a spolehlivé stěhování bytů, domů a kanceláří po celém Brně a okolí. Stěhovací firma Brno nabízí kompletní balení, transport i montáž nábytku v cílové destinaci.', picturePath: null, active: true },
  { fullName: 'Movers Brno s.r.o.', phone: '+420 543 423 765', email: 'info@movers-brno.cz', serviceId: 'stehovaci-firma', cityId: CITY, address: 'Heršpická 11, Brno', description: 'Movers Brno je profesionální stěhovací firma s moderním vybavením a zkušeným týmem pro stěhování v Brně. Zajišťujeme stěhování bytů, kanceláří i průmyslových provozů v Brně a celé ČR.', picturePath: null, active: true },
  { fullName: 'Stěhovací firma Vlček Brno', phone: '+420 608 778 334', email: null, serviceId: 'stehovaci-firma', cityId: CITY, address: 'Žabovřeská 17, Brno', description: 'Vlček stěhování nabízí spolehlivé a cenově dostupné stěhování v Brně a okolí. Stěhovací firma Brno zajišťuje ochranu nábytku, odvoz odpadu a vyklizení bytů na klíč.', picturePath: null, active: true },
  { fullName: 'FAST Stěhování Brno', phone: '+420 731 556 889', email: 'fast@stehovani-brno.cz', serviceId: 'stehovaci-firma', cityId: CITY, address: 'Dornych 15, Brno', description: 'FAST Stěhování Brno zajišťuje rychlé a bezpečné stěhování pro domácnosti i firmy v Brně. Stěhovací firma Brno disponuje vlastními vozy a zkušenou posádkou dostupnou 7 dní v týdnu.', picturePath: null, active: true },

  // ── ZAHRADNÍK ─────────────────────────────────────────────────────────────
  { fullName: 'Zahradnictví Brno – Karel Sedláček', phone: '+420 608 334 771', email: 'zahrada@sedlacek-brno.cz', serviceId: 'zahradnik', cityId: CITY, address: 'Modřická 37, Brno', description: 'Karel Sedláček nabízí komplexní zahradnické práce v Brně – zakládání zahrad, pravidelná údržba a kácení stromů. Zahradník Brno provádí sekání trávníku, stříhání živých plotů a výsadbu rostlin.', picturePath: null, active: true },
  { fullName: 'Green Garden Brno', phone: '+420 775 441 228', email: 'info@greengarden-brno.cz', serviceId: 'zahradnik', cityId: CITY, address: 'Vídeňská 201, Brno', description: 'Green Garden Brno je profesionální zahradnická firma nabízející návrh, realizaci a údržbu zahrad v Brně. Zahradník Brno se specializuje na anglické trávníky, závlahové systémy a terénní úpravy.', picturePath: null, active: true },
  { fullName: 'Zahradnické práce Brno – Novotný', phone: '+420 731 227 445', email: null, serviceId: 'zahradnik', cityId: CITY, address: 'Brno – Vinohrady', description: 'Novotný zahradnictví zajišťuje veškeré zahradnické práce pro soukromé záhrady i firemní areály v Brně. Zahradník Brno nabízí celoroční péči o zahradu, mulčování a likvidaci zahradního odpadu.', picturePath: null, active: true },
  { fullName: 'Zahradní služby FLORA Brno', phone: '+420 543 558 112', email: 'flora@zahradni-sluzby-brno.cz', serviceId: 'zahradnik', cityId: CITY, address: 'Čechyňská 19, Brno', description: 'FLORA Brno je zahradnická firma s dlouholetou tradicí v Brně specializující se na zakládání a obnovu zahrad. Zahradník Brno provádí výsadbu stromů, keřů a trvalkových záhonů dle přání klienta.', picturePath: null, active: true },

  // ── ÚKLID ─────────────────────────────────────────────────────────────────
  { fullName: 'Úklidová firma Brno – ProClean', phone: '+420 775 228 443', email: 'info@proclean-brno.cz', serviceId: 'uklid', cityId: CITY, address: 'Pekařská 26, Brno', description: 'ProClean Brno nabízí profesionální úklidové služby pro domácnosti, kanceláře a průmyslové prostory v Brně. Úklidová firma Brno provádí generální úklidy, čištění koberců a mytí oken.', picturePath: null, active: true },
  { fullName: 'CleanBrno s.r.o.', phone: '+420 543 441 667', email: 'cleanbrno@cleanbrno.cz', serviceId: 'uklid', cityId: CITY, address: 'Koliště 47, Brno', description: 'CleanBrno je spolehlivá úklidová firma v Brně poskytující pravidelný i jednorázový úklid bytů a firemních prostor. Úklid Brno zajišťuje diskrétní a kvalitní úklidové služby s vlastními ekologickými čisticími prostředky.', picturePath: null, active: true },
  { fullName: 'Úklid Brno – Jana Procházková', phone: '+420 731 664 118', email: null, serviceId: 'uklid', cityId: CITY, address: 'Brno – Žabovřesky', description: 'Jana Procházková nabízí spolehlivý úklid bytů a domácností v Brně a blízkém okolí za příznivé ceny. Úklid Brno zahrnuje pravidelné i generální čištění, žehlení a péči o domácnost.', picturePath: null, active: true },
  { fullName: 'Maidservice Brno', phone: '+420 775 880 334', email: 'info@maidservice-brno.cz', serviceId: 'uklid', cityId: CITY, address: 'Lidická 55, Brno', description: 'Maidservice Brno poskytuje prémiové úklidové služby pro domácnosti a kanceláře v Brně. Úklidová firma Brno nabízí pravidelný týdenní úklid, čištění po rekonstrukci a dezinfekci prostor.', picturePath: null, active: true },

  // ── ZEDNÍK ────────────────────────────────────────────────────────────────
  { fullName: 'Zednické práce Brno – Horák', phone: '+420 608 441 223', email: 'horak.zednik@email.cz', serviceId: 'zednik', cityId: CITY, address: 'Brno – Bystrc', description: 'Horák zednické práce nabízí kompletní zednické a stavební práce v Brně zahrnující rekonstrukce bytů, omítky a obklady. Zedník Brno provádí zednické práce pro soukromé i komerční zákazníky v celém Jihomoravském kraji.', picturePath: null, active: true },
  { fullName: 'STAVBRNO s.r.o.', phone: '+420 543 667 228', email: 'info@stavbrno.cz', serviceId: 'zednik', cityId: CITY, address: 'Vídeňská 122, Brno', description: 'STAVBRNO je stavební firma v Brně nabízející kompletní zednické práce, rekonstrukce a novostavby. Zedník Brno zajišťuje zdění, omítání, pokládku dlažby a veškeré stavební práce na klíč.', picturePath: null, active: true },
  { fullName: 'Pavel Mareš – zedník Brno', phone: '+420 731 558 334', email: null, serviceId: 'zednik', cityId: CITY, address: 'Brno – Královo Pole', description: 'Pavel Mareš je zkušený zedník v Brně nabízející rekonstrukce koupelen, pokládku dlažby a obkladů. Zedník Brno pracuje precizně a s garancí kvality pro zákazníky v Brně a přilehlém okolí.', picturePath: null, active: true },
  { fullName: 'Rekonstrukce bytů Brno – Novák', phone: '+420 775 221 447', email: 'novak.stavby@gmail.com', serviceId: 'zednik', cityId: CITY, address: 'Cejl 88, Brno', description: 'Novák rekonstrukce nabízí komplexní stavební a zednické práce v Brně se zaměřením na rekonstrukce bytů a domů. Zedník Brno provádí sádrokartony, obklady, omítky a celkové přestavby interiérů.', picturePath: null, active: true },

  // ── IT TECHNIK ────────────────────────────────────────────────────────────
  { fullName: 'PC Servis Brno', phone: '+420 543 214 778', email: 'info@pcservis-brno.cz', serviceId: 'it-technik', cityId: CITY, address: 'Česká 12, Brno', description: 'PC Servis Brno nabízí kompletní počítačový servis a IT podporu pro firmy i domácnosti v Brně. IT technik Brno zajišťuje opravy notebooků, správu sítí a instalaci softwaru s rychlým výjezdem.', picturePath: null, active: true },
  { fullName: 'IT Pohotovost Brno', phone: '+420 775 663 441', email: 'pohotovost@it-brno.cz', serviceId: 'it-technik', cityId: CITY, address: 'Koliště 53, Brno', description: 'IT Pohotovost Brno je nonstop počítačový servis dostupný 24/7 pro zákazníky v Brně. IT technik Brno řeší opravy počítačů, obnovu dat, ochranu před viry a správu IT infrastruktury firem.', picturePath: null, active: true },
  { fullName: 'TechHelp Brno s.r.o.', phone: '+420 543 776 118', email: 'help@techhelp-brno.cz', serviceId: 'it-technik', cityId: CITY, address: 'Štefánikova 35, Brno', description: 'TechHelp Brno je specializovaná IT firma poskytující servis počítačů, serverů a počítačových sítí v Brně. IT technik Brno nabízí také cloudové řešení, zálohování dat a kybernetickou bezpečnost pro firmy.', picturePath: null, active: true },
  { fullName: 'Michal Pospíšil – IT technik Brno', phone: '+420 731 884 557', email: null, serviceId: 'it-technik', cityId: CITY, address: 'Brno – Líšeň', description: 'Michal Pospíšil je zkušený IT technik v Brně poskytující servis a opravy počítačů pro domácnosti i malé firmy. IT podpora Brno zahrnuje instalaci systémů, nastavení sítě a rychlou opravu závad.', picturePath: null, active: true },

  // ── ÚČETNÍ ────────────────────────────────────────────────────────────────
  { fullName: 'Ing. Petra Horáková – účetní Brno', phone: '+420 543 221 889', email: 'horakova@ucetni-brno.cz', serviceId: 'ucetni', cityId: CITY, address: 'Náměstí Svobody 18, Brno', description: 'Ing. Petra Horáková nabízí komplexní účetní a daňové poradenství pro firmy i živnostníky v Brně. Účetní Brno zajišťuje vedení účetnictví, zpracování mezd a daňová přiznání pro zákazníky v celém Jihomoravském kraji.', picturePath: null, active: true },
  { fullName: 'ÚČTO Brno s.r.o.', phone: '+420 775 334 662', email: 'info@ucto-brno.cz', serviceId: 'ucetni', cityId: CITY, address: 'Veveří 28, Brno', description: 'ÚČTO Brno je moderní účetní kancelář poskytující vedení účetnictví, daňové poradenství a mzdovou agendu v Brně. Účetní firma Brno spolupracuje s malými i středními podniky a nabízí také online účetnictví.', picturePath: null, active: true },
  { fullName: 'Daňová a účetní kancelář Brno – Blanka Marková', phone: '+420 543 558 334', email: 'markova@ucetnictvi-brno.cz', serviceId: 'ucetni', cityId: CITY, address: 'Lidická 22, Brno', description: 'Blanka Marková vede daňovou a účetní kancelář v Brně s více než 15 lety praxe v oblasti účetnictví a daní. Účetní Brno zpracovává daňová přiznání, roční uzávěrky a zastupuje klienty na finančním úřadu.', picturePath: null, active: true },
  { fullName: 'Účetnictví a daně Brno – Svoboda', phone: '+420 731 447 229', email: null, serviceId: 'ucetni', cityId: CITY, address: 'Brno – Žabovřesky', description: 'Svoboda účetnictví nabízí vedení podvojného i jednoduchého účetnictví pro firmy a živnostníky v Brně. Účetní Brno se specializuje na e-commerce, IT firmy a freelancery s garancí přesnosti a dodržování termínů.', picturePath: null, active: true },

  // ── PRÁVNÍK ───────────────────────────────────────────────────────────────
  { fullName: 'Advokátní kancelář Brno – JUDr. Karel Procházka', phone: '+420 543 215 667', email: 'ak@procházka-brno.cz', serviceId: 'pravnik', cityId: CITY, address: 'Česká 34, Brno', description: 'JUDr. Karel Procházka je zkušený advokát v Brně zaměřený na obchodní právo, nemovitosti a pracovní právo. Advokátní kancelář Brno poskytuje právní poradenství fyzickým i právnickým osobám v celém Jihomoravském kraji.', picturePath: null, active: true },
  { fullName: 'Mgr. Lenka Horáčková – advokát Brno', phone: '+420 775 229 441', email: 'horáčkova@advokatbrno.cz', serviceId: 'pravnik', cityId: CITY, address: 'Náměstí Svobody 4, Brno', description: 'Mgr. Lenka Horáčková je advokátka v Brně specializující se na rodinné právo, dědictví a smluvní právo. Právník Brno nabízí konzultace, sestavení smluv a zastoupení před soudem v celé České republice.', picturePath: null, active: true },
  { fullName: 'AK LEGIS Brno s.r.o.', phone: '+420 543 336 778', email: 'info@legis-brno.cz', serviceId: 'pravnik', cityId: CITY, address: 'Kounicova 16, Brno', description: 'Advokátní kancelář LEGIS Brno poskytuje komplexní právní služby pro firmy i jednotlivce v Brně. Právník Brno se specializuje na obchodní právo, pracovní spory, IT právo a ochranu osobních údajů.', picturePath: null, active: true },
  { fullName: 'JUDr. Tomáš Beneš – advokát Brno', phone: '+420 731 665 228', email: 't.benes@advokatbrno.cz', serviceId: 'pravnik', cityId: CITY, address: 'Štefánikova 71, Brno', description: 'JUDr. Tomáš Beneš je advokát v Brně s praxí v oblasti trestního práva, správního řízení a civilních sporů. Právník Brno zastupuje klienty před všemi stupni soudů a správními orgány v ČR.', picturePath: null, active: true },

  // ── AUTOSERVIS ────────────────────────────────────────────────────────────
  { fullName: 'Autoservis Brno – Pospíšil', phone: '+420 543 441 226', email: 'pospísil@autoservis-brno.cz', serviceId: 'autoservis', cityId: CITY, address: 'Heršpická 828, Brno', description: 'Autoservis Pospíšil v Brně nabízí kompletní opravy a servis osobních i dodávkových vozidel všech značek. Autoservis Brno zajišťuje diagnostiku, výměnu oleje, brzd a pravidelné servisní prohlídky STK.', picturePath: null, active: true },
  { fullName: 'Bosch Car Service Brno – Garážservis', phone: '+420 543 528 711', email: 'garazservis@bosch-brno.cz', serviceId: 'autoservis', cityId: CITY, address: 'Vídeňská 119, Brno', description: 'Garážservis je certifikovaný Bosch Car Service v Brně s komplexní nabídkou autoopravárenských služeb. Autoservis Brno provádí elektrodiagnostiku, klimatizaci, geometrii náprav a opravy motorů.', picturePath: null, active: true },
  { fullName: 'AUTO-OPRAVNA Dvořák Brno', phone: '+420 775 447 334', email: null, serviceId: 'autoservis', cityId: CITY, address: 'Olomoucká 222, Brno – Slatina', description: 'AUTO-OPRAVNA Dvořák je rodinný autoservis v Brně Slatina s více než 20 lety zkušeností s opravami vozidel. Autoservis Brno zajišťuje klempířské a lakýrnické práce, mechanické opravy a pneuservis.', picturePath: null, active: true },
  { fullName: 'Rychloservis Brno', phone: '+420 731 229 885', email: 'info@rychloservis-brno.cz', serviceId: 'autoservis', cityId: CITY, address: 'Dornych 64, Brno', description: 'Rychloservis Brno je autoservis zaměřený na rychlé a cenově dostupné opravy vozidel v Brně. Autoservis Brno nabízí výměnu oleje za 30 minut, opravu pneumatik a výměnu autoskel.', picturePath: null, active: true },

  // ── FOTOGRAF ──────────────────────────────────────────────────────────────
  { fullName: 'Ateliér Brno – Jakub Veselý', phone: '+420 775 556 334', email: 'info@fotoveselý.cz', serviceId: 'fotograf', cityId: CITY, address: 'Česká 15, Brno', description: 'Jakub Veselý je profesionální fotograf v Brně zaměřený na svatební fotografii, portréty a firemní focení. Fotografické studio Brno nabízí kreativní přístup a moderní vybavení pro každou příležitost.', picturePath: null, active: true },
  { fullName: 'Foto Novák – fotograf Brno', phone: '+420 543 221 778', email: 'studio@fotonovak.cz', serviceId: 'fotograf', cityId: CITY, address: 'Masarykova 39, Brno', description: 'Foto Novák je zavedené fotografické studio v Brně s tradicí od roku 2005. Fotograf Brno se specializuje na portrétní, rodinnou a produktovou fotografii pro soukromé klienty i firmy.', picturePath: null, active: true },
  { fullName: 'Eva Horáčková – fotografka Brno', phone: '+420 731 443 227', email: 'foto@evahoráčková.cz', serviceId: 'fotograf', cityId: CITY, address: 'Brno – Žabovřesky', description: 'Eva Horáčková je talentovaná fotografka v Brně specializující se na těhotenské, novorozenecké a rodinné fotografie. Fotograf Brno nabízí příjemnou atmosféru a profesionální výsledky pro celou rodinu.', picturePath: null, active: true },
  { fullName: 'Studio Vision Brno', phone: '+420 775 338 112', email: 'info@studiovision-brno.cz', serviceId: 'fotograf', cityId: CITY, address: 'Koliště 22, Brno', description: 'Studio Vision Brno je profesionální fotografické a video studio v Brně zaměřené na reklamní a komerční produkci. Fotograf Brno zajišťuje produktové focení, video reklamy a firemní prezentace na klíč.', picturePath: null, active: true },

  // ── KADEŘNÍK ──────────────────────────────────────────────────────────────
  { fullName: 'Kadeřnictví Salon Prestige Brno', phone: '+420 543 215 334', email: 'prestige@kadernictvi-brno.cz', serviceId: 'kadernik', cityId: CITY, address: 'Náměstí Svobody 12, Brno', description: 'Salon Prestige je prémiové kadeřnictví v centru Brna nabízející střihy, barvení a keratinové ošetření vlasů. Kadeřník Brno zajišťuje péči o vlasy pro muže i ženy v příjemném prostředí v srdci města.', picturePath: null, active: true },
  { fullName: 'Hair Studio Brno – Markéta', phone: '+420 775 221 558', email: null, serviceId: 'kadernik', cityId: CITY, address: 'Kounicova 23, Brno', description: 'Hair Studio Markéta je oblíbené kadeřnictví v Brně Královo Pole s specializací na moderní střihy a barvení. Kadeřník Brno nabízí konzultace zdarma a ošetření vlasů prémiovými produkty.', picturePath: null, active: true },
  { fullName: 'Kadeřnictví Pavel Horák Brno', phone: '+420 731 558 443', email: 'pavel@kadernik-brno.cz', serviceId: 'kadernik', cityId: CITY, address: 'Lidická 38, Brno', description: 'Pavel Horák je zkušený kadeřník v Brně s více než 18 lety praxe v oboru péče o vlasy. Kadeřnictví Brno nabízí dámské i pánské střihy, trvalé, barvení a rekonstrukci poškozených vlasů.', picturePath: null, active: true },
  { fullName: 'TOP Kadeřnictví Brno', phone: '+420 543 778 229', email: 'info@top-kadernictvi-brno.cz', serviceId: 'kadernik', cityId: CITY, address: 'Česká 27, Brno', description: 'TOP Kadeřnictví Brno je moderní salon v centru Brna nabízející komplexní vlasové služby pro celou rodinu. Kadeřník Brno provádí střihy, barvení, melírování a svatební účesy za příznivé ceny.', picturePath: null, active: true },

  // ── LÉKAŘ ─────────────────────────────────────────────────────────────────
  { fullName: 'MUDr. Jana Nováková – praktická lékařka Brno', phone: '+420 543 213 778', email: 'novakova@lekar-brno.cz', serviceId: 'lekar', cityId: CITY, address: 'Veveří 38, Brno', description: 'MUDr. Jana Nováková je praktická lékařka v Brně přijímající nové pacienty s komplexní péčí o zdraví. Ordinace praktického lékaře Brno nabízí preventivní prohlídky, očkování a doporučení ke specialistům.', picturePath: null, active: true },
  { fullName: 'MUDr. Petr Blaha – obvodní lékař Brno', phone: '+420 775 441 663', email: null, serviceId: 'lekar', cityId: CITY, address: 'Kounicova 62, Brno', description: 'MUDr. Petr Blaha vede ordinaci praktického lékaře pro dospělé v Brně Královo Pole. Lékař Brno zajišťuje odběry krve, EKG, pracovnělékařské prohlídky a akutní ošetření.', picturePath: null, active: true },
  { fullName: 'Poliklinika Brno – MUDr. Tomáš Krejčí', phone: '+420 543 558 889', email: 'krejci@poliklinika-brno.cz', serviceId: 'lekar', cityId: CITY, address: 'Zahradníkova 22, Brno', description: 'MUDr. Tomáš Krejčí ordinuje jako praktický lékař v Brně v moderně vybavené poliklinice. Praktický lékař Brno přijímá nové pacienty a nabízí komplexní primární zdravotní péči včetně telefonických konzultací.', picturePath: null, active: true },
  { fullName: 'MUDr. Alena Procházková – lékař Brno', phone: '+420 731 334 558', email: 'prochazková@lekar-brno.cz', serviceId: 'lekar', cityId: CITY, address: 'Štefánikova 48, Brno', description: 'MUDr. Alena Procházková je praktická lékařka v Brně s individuálním přístupem k pacientům. Lékař Brno se specializuje na preventivní medicínu, chronická onemocnění a výživové poradenství.', picturePath: null, active: true },

  // ── KLEMPÍŘ ───────────────────────────────────────────────────────────────
  { fullName: 'Klempířství Brno – Radek Novák', phone: '+420 608 335 441', email: 'novak@klempir-brno.cz', serviceId: 'klempir', cityId: CITY, address: 'Brno – Bystrc', description: 'Radek Novák je zkušený klempíř v Brně nabízející oplechování střech, výrobu okapových žlabů a opravy střešního pláště. Klempíř Brno provádí veškeré klempířské práce pro rodinné domy i bytové komplexy.', picturePath: null, active: true },
  { fullName: 'Střechy a klempířství Brno – Horák', phone: '+420 775 663 228', email: null, serviceId: 'klempir', cityId: CITY, address: 'Tuřanka 78, Brno – Slatina', description: 'Horák střechy a klempířství nabízí kompletní střešní a klempířské práce v Brně a Jihomoravském kraji. Klempíř Brno provádí pokládku střešní krytiny, oplechování komínů a montáž střešních oken.', picturePath: null, active: true },
  { fullName: 'KLEM-BRNO s.r.o.', phone: '+420 543 441 778', email: 'info@klem-brno.cz', serviceId: 'klempir', cityId: CITY, address: 'Hněvkovského 15, Brno', description: 'KLEM-BRNO je profesionální klempířská firma v Brně specializující se na oplechování atik, teras a balkonů. Klempíř Brno zajišťuje montáž titanzinkových a měděných klempířských prvků na klíč.', picturePath: null, active: true },
  { fullName: 'Josef Kratochvíl – klempíř a pokrývač Brno', phone: '+420 731 447 118', email: null, serviceId: 'klempir', cityId: CITY, address: 'Brno – Kohoutovice', description: 'Josef Kratochvíl je klempíř a pokrývač v Brně s 15 lety praxe v oblasti střešních prací. Klempíř Brno nabízí opravy poruch střech, výměnu klempířských prvků a montáž sněhových zábran.', picturePath: null, active: true },

  // ── REALITNÍ MAKLÉŘ ───────────────────────────────────────────────────────
  { fullName: 'RE/MAX Brno – Pavel Novotný', phone: '+420 543 218 667', email: 'novotný@remax-brno.cz', serviceId: 'realitni-makler', cityId: CITY, address: 'Náměstí Svobody 22, Brno', description: 'Pavel Novotný je zkušený realitní makléř RE/MAX v Brně specializující se na prodej a pronájem bytů a domů. Realitní makléř Brno zajišťuje kompletní realitní servis od ocenění nemovitosti až po podpis smlouvy.', picturePath: null, active: true },
  { fullName: 'Century 21 Brno – Lenka Horáková', phone: '+420 775 558 334', email: 'horakova@century21-brno.cz', serviceId: 'realitni-makler', cityId: CITY, address: 'Lidická 41, Brno', description: 'Lenka Horáková je realitní makléřka Century 21 v Brně se zaměřením na rezidenční nemovitosti a investiční byty. Realitní kancelář Brno nabízí profesionální fotografie, home staging a rychlý prodej nemovitostí.', picturePath: null, active: true },
  { fullName: 'STING Reality Brno', phone: '+420 543 334 889', email: 'info@sting-brno.cz', serviceId: 'realitni-makler', cityId: CITY, address: 'Veveří 102, Brno', description: 'STING Reality je zavedená realitní kancelář v Brně s rozsáhlým portfoliem bytů, domů a komerčních prostor. Realitní makléř Brno zajišťuje kupní smlouvy, úschovu peněz a průběžnou komunikaci se všemi stranami.', picturePath: null, active: true },
  { fullName: 'M&M Reality Brno', phone: '+420 731 556 228', email: 'brno@mmreality.cz', serviceId: 'realitni-makler', cityId: CITY, address: 'Kounicova 48, Brno', description: 'M&M Reality Brno je realitní kancelář s celonárodní sítí poskytující realitní poradenství v Brně. Realitní makléř Brno pomáhá s prodejem, koupí a pronájmem nemovitostí za nejlepší tržní cenu.', picturePath: null, active: true },

  // ── RESTAURACE ────────────────────────────────────────────────────────────
  { fullName: 'Restaurace Špalíček Brno', phone: '+420 542 211 526', email: 'info@spalicek-brno.cz', serviceId: 'restaurace', cityId: CITY, address: 'Náměstí Svobody 15, Brno', description: 'Restaurace Špalíček je tradiční česká restaurace přímo na Náměstí Svobody v centru Brna nabízející poctivou moravskou kuchyni. Restaurace Brno láká hosty na domácí svíčkovou, svíčkovou a čerstvé moravské víno.', picturePath: null, active: true },
  { fullName: 'Pivnice Pegas Brno', phone: '+420 542 210 104', email: 'info@hotelpegas.cz', serviceId: 'restaurace', cityId: CITY, address: 'Jakubská 4, Brno', description: 'Pivnice Pegas je legendární brněnská restaurace a minipivovar v centru Brna s vlastním čepovaným pivem. Restaurace Brno nabízí tradiční česká jídla v autentickém prostředí s pivním sklípkem.', picturePath: null, active: true },
  { fullName: 'Restaurace u Richarda Brno', phone: '+420 543 211 770', email: 'info@uricharda.cz', serviceId: 'restaurace', cityId: CITY, address: 'Masarykova 15, Brno', description: 'Restaurace U Richarda je oblíbená česká restaurace v centru Brna s důrazem na čerstvé suroviny a domácí přípravu. Restaurace Brno nabízí denní menu, neděli s rodinou a večerní degustační zážitky.', picturePath: null, active: true },
  { fullName: 'Černý Orel Brno – restaurace a penzion', phone: '+420 542 214 872', email: 'recepce@cernyorel.cz', serviceId: 'restaurace', cityId: CITY, address: 'Náměstí 4, Brno – Šlapanice', description: 'Černý Orel je rodinná restaurace s bohatou historií v Brně a okolí, nabízející tradiční moravskou kuchyni. Restaurace Brno – Šlapanice je oblíbeným místem pro firemní i soukromé oslavy s kapacitou až 100 osob.', picturePath: null, active: true },

  // ── ARCHITEKT ─────────────────────────────────────────────────────────────
  { fullName: 'Atelier Brno – Ing. arch. Martin Dvořák', phone: '+420 543 215 445', email: 'dvorak@atelier-brno.cz', serviceId: 'architekt', cityId: CITY, address: 'Veveří 56, Brno', description: 'Ing. arch. Martin Dvořák vede architektonický ateliér v Brně zaměřený na rodinné domy, byty a komerční stavby. Architekt Brno nabízí kompletní projektovou dokumentaci, interiérový design a autorský dozor.', picturePath: null, active: true },
  { fullName: 'QARTA architektura Brno', phone: '+420 775 336 118', email: 'info@qarta-brno.cz', serviceId: 'architekt', cityId: CITY, address: 'Příkop 8, Brno', description: 'QARTA architektura je brněnský architektonický ateliér realizující projekty rodinných domů, bytových domů a revitalizací. Architekt Brno se specializuje na moderní a udržitelnou architekturu s důrazem na funkčnost.', picturePath: null, active: true },
  { fullName: 'Studio arch. Procházka Brno', phone: '+420 543 667 334', email: 'prochazka@arch-brno.cz', serviceId: 'architekt', cityId: CITY, address: 'Lidická 44, Brno', description: 'Architektonické studio Procházka v Brně se zaměřuje na interiérový design, rekonstrukce a novostavby rodinných domů. Architekt Brno přináší inovativní řešení prostoru s respektem k přání a rozpočtu klienta.', picturePath: null, active: true },
  { fullName: 'Ing. arch. Jana Marková – architekt Brno', phone: '+420 731 228 447', email: 'markova@architekt-brno.cz', serviceId: 'architekt', cityId: CITY, address: 'Brno – Žabovřesky', description: 'Jana Marková je architektka v Brně s bohatými zkušenostmi s projekty bytových interiérů a rekonstrukcemi. Architekt Brno nabízí 3D vizualizace, stavební povolení a kompletní projektovou dokumentaci.', picturePath: null, active: true },

  // ── PSYCHOLOG ─────────────────────────────────────────────────────────────
  { fullName: 'PhDr. Jana Horáčková – psycholog Brno', phone: '+420 543 213 556', email: 'horáčková@psycholog-brno.cz', serviceId: 'psycholog', cityId: CITY, address: 'Kounicova 34, Brno', description: 'PhDr. Jana Horáčková je klinická psycholožka v Brně nabízející individuální psychoterapii a poradenství pro dospělé. Psycholog Brno se specializuje na zvládání úzkostí, depresí a životních krizí.', picturePath: null, active: true },
  { fullName: 'Centrum psychologické pomoci Brno', phone: '+420 775 441 228', email: 'info@psychologie-brno.cz', serviceId: 'psycholog', cityId: CITY, address: 'Štefánikova 22, Brno', description: 'Centrum psychologické pomoci Brno poskytuje psychoterapii, koučink a poradenství pro jednotlivce i páry v Brně. Psycholog Brno nabízí online i prezenční konzultace se zkušenými psychology a terapeuty.', picturePath: null, active: true },
  { fullName: 'Mgr. Tomáš Blaha – psychoterapeut Brno', phone: '+420 731 556 339', email: null, serviceId: 'psycholog', cityId: CITY, address: 'Veveří 91, Brno', description: 'Mgr. Tomáš Blaha je psychoterapeut v Brně pracující metodou kognitivně-behaviorální terapie pro dospělé a adolescenty. Psycholog Brno nabízí konzultace zaměřené na stres, fóbie, vztahové problémy a seberozzvoj.', picturePath: null, active: true },
  { fullName: 'Psychologická poradna Brno – Mgr. Eva Nováková', phone: '+420 543 334 771', email: 'novakova@poradna-brno.cz', serviceId: 'psycholog', cityId: CITY, address: 'Česká 10, Brno', description: 'Mgr. Eva Nováková vede psychologickou poradnu v Brně zaměřenou na párovou terapii a rodinné poradenství. Psycholog Brno nabízí diskrétní a profesionální konzultace v centru Brna i online přes videohovor.', picturePath: null, active: true },

  // ── OSOBNÍ TRENÉR ─────────────────────────────────────────────────────────
  { fullName: 'Osobní trenér Brno – Jakub Horák', phone: '+420 731 558 226', email: 'horak@trener-brno.cz', serviceId: 'trener', cityId: CITY, address: 'Drobného 26, Brno', description: 'Jakub Horák je certifikovaný osobní trenér v Brně zaměřený na silový trénink, hubnutí a funkční pohyb. Osobní trenér Brno sestaví individuální tréninkový plán a jídelníček na míru pro každého klienta.', picturePath: null, active: true },
  { fullName: 'FitBrno – personal training', phone: '+420 775 338 447', email: 'info@fitbrno.cz', serviceId: 'trener', cityId: CITY, address: 'Lidická 61, Brno', description: 'FitBrno je moderní studio osobního tréninku v Brně se zkušenými trenéry zaměřenými na kondici a zdravý životní styl. Osobní trenér Brno nabízí individuální lekce, skupinové tréninky a online coaching.', picturePath: null, active: true },
  { fullName: 'Martin Veselý – trenér Brno', phone: '+420 608 449 225', email: null, serviceId: 'trener', cityId: CITY, address: 'Brno – Královo Pole', description: 'Martin Veselý je osobní trenér v Brně s certifikací v oblasti sportovní přípravy a rehabilitačního cvičení. Trenér Brno nabízí trénink v tělocvičně i v přírodě a online konzultace pro klienty z celého Jihomoravského kraje.', picturePath: null, active: true },
  { fullName: 'PowerBody Brno – fitness trenér', phone: '+420 543 441 118', email: 'info@powerbody-brno.cz', serviceId: 'trener', cityId: CITY, address: 'Štefánikova 85, Brno', description: 'PowerBody Brno je fitness studio s osobními trenéry zaměřenými na silový trénink a bodybuilding v Brně. Osobní trenér Brno pomáhá klientům dosáhnout fitness cílů prostřednictvím profesionálního vedení a motivace.', picturePath: null, active: true },

  // ── PŘEKLADATEL ───────────────────────────────────────────────────────────
  { fullName: 'Skřivánek Brno – překladatelská agentura', phone: '+420 543 257 800', email: 'brno@skrivanek.cz', serviceId: 'prekladatel', cityId: CITY, address: 'Příkop 6, Brno', description: 'Skřivánek Brno je přední překladatelská agentura v Brně nabízející překlady do více než 80 jazyků. Překladatel Brno zajišťuje odborné překlady, tlumočení a lokalizaci textů pro firmy i soukromé klienty.', picturePath: null, active: true },
  { fullName: 'TLUMOČENÍ & PŘEKLADY Brno – Mgr. Petra Horáková', phone: '+420 775 229 558', email: 'horakova@preklady-brno.cz', serviceId: 'prekladatel', cityId: CITY, address: 'Česká 24, Brno', description: 'Mgr. Petra Horáková je soudní překladatelka v Brně specializující se na překlady z angličtiny, němčiny a francouzštiny. Překladatel Brno provádí úřední překlady s razítkem, odborné překlady a simultánní tlumočení.', picturePath: null, active: true },
  { fullName: 'Babel Translations Brno', phone: '+420 543 338 667', email: 'info@babel-brno.cz', serviceId: 'prekladatel', cityId: CITY, address: 'Koliště 35, Brno', description: 'Babel Translations Brno je moderní překladatelská agentura v Brně zaměřená na technické, právní a marketingové překlady. Překladatel Brno spolupracuje s rodilými mluvčími a garantuje přesnost a rychlé dodání.', picturePath: null, active: true },
  { fullName: 'JTP – překladatel a tlumočník Brno', phone: '+420 731 447 336', email: null, serviceId: 'prekladatel', cityId: CITY, address: 'Brno – Žabovřesky', description: 'Zkušený překladatel a tlumočník v Brně nabízející překlady z češtiny do angličtiny, němčiny a slovenštiny. Překladatel Brno zajišťuje konzistentní a přesné překlady obchodní a technické dokumentace.', picturePath: null, active: true },

  // ── GRAFICKÝ DESIGNER ─────────────────────────────────────────────────────
  { fullName: 'Grafické studio POSITIV Brno', phone: '+420 543 215 778', email: 'info@positiv-brno.cz', serviceId: 'grafik', cityId: CITY, address: 'Náměstí Svobody 6, Brno', description: 'Grafické studio POSITIV Brno nabízí kompletní grafické služby – logo, webdesign, tiskové materiály a branding. Grafický designer Brno vytváří vizuální identitu pro firmy a značky po celé České republice.', picturePath: null, active: true },
  { fullName: 'Martin Procházka – grafický designer Brno', phone: '+420 775 447 229', email: 'martin@grafik-brno.cz', serviceId: 'grafik', cityId: CITY, address: 'Veveří 73, Brno', description: 'Martin Procházka je freelance grafický designer v Brně specializující se na tvorbu log, letáků a firemní identity. Grafik Brno nabízí rychlé dodání, neomezené revize a moderní kreativní přístup.', picturePath: null, active: true },
  { fullName: 'Creative Studio Brno', phone: '+420 543 776 334', email: 'info@creativestudio-brno.cz', serviceId: 'grafik', cityId: CITY, address: 'Lidická 59, Brno', description: 'Creative Studio Brno je grafické a reklamní studio nabízející webdesign, grafiku pro sociální sítě a tvorbu reklam. Grafický designer Brno pracuje s moderními nástroji a pomáhá firmám budovat silnou vizuální identitu.', picturePath: null, active: true },
  { fullName: 'Monika Dvořáčková – grafička Brno', phone: '+420 731 338 554', email: 'monika@grafika-brno.cz', serviceId: 'grafik', cityId: CITY, address: 'Brno – Vinohrady', description: 'Monika Dvořáčková je kreativní grafická designérka v Brně zaměřená na ilustrace, obalový design a firemní materiály. Grafik Brno nabízí originální a profesionální výstupy pro malé i velké klienty.', picturePath: null, active: true },

  // ── UČITEL / LEKTOR ───────────────────────────────────────────────────────
  { fullName: 'Jazyková škola Hello Brno', phone: '+420 543 237 723', email: 'brno@hello.cz', serviceId: 'ucitel', cityId: CITY, address: 'Česká 1, Brno', description: 'Jazyková škola Hello Brno nabízí kurzy angličtiny, němčiny, španělštiny a dalších jazyků pro dospělé i firmy. Lektor Brno zajišťuje skupinové i individuální kurzy s certifikovanými učiteli v centru Brna.', picturePath: null, active: true },
  { fullName: 'Lingua Centrum Brno', phone: '+420 543 217 468', email: 'brno@lingua-centrum.cz', serviceId: 'ucitel', cityId: CITY, address: 'Náměstí Svobody 17, Brno', description: 'Lingua Centrum Brno je jazyková škola v centru Brna nabízející přípravné kurzy na Cambridge a jiné mezinárodní zkoušky. Lektor Brno poskytuje výuku angličtiny, němčiny a italštiny pro začátečníky i pokročilé.', picturePath: null, active: true },
  { fullName: 'Doučování Brno – Mgr. Lucie Horáková', phone: '+420 775 558 113', email: 'doučování@brno-lekce.cz', serviceId: 'ucitel', cityId: CITY, address: 'Brno – Královo Pole', description: 'Mgr. Lucie Horáková nabízí doučování matematiky, fyziky a chemie pro žáky základních a středních škol v Brně. Lektor Brno přizpůsobuje výuku individuálním potřebám každého studenta a garantuje měřitelné výsledky.', picturePath: null, active: true },
  { fullName: 'Akademie jazyků Brno', phone: '+420 543 445 661', email: 'info@akademie-jazyku-brno.cz', serviceId: 'ucitel', cityId: CITY, address: 'Kounicova 67, Brno', description: 'Akademie jazyků Brno je moderní jazyková škola s online i prezenční výukou angličtiny a dalších světových jazyků. Lektoři Brno nabízejí firemní kurzy, intenzivní víkendové kurzy a překlady pro klienty z celého Jihomoravského kraje.', picturePath: null, active: true },
];

async function main() {
  let count = 0;
  for (const p of profiles) {
    const created = await prisma.provider.create({ data: p });
    console.log(`✓ ${created.fullName}`);
    count++;
  }
  console.log(`\nDone. Added ${count} profiles.`);
}
main().catch(console.error).finally(() => prisma.$disconnect());
