import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();
const CITY = 'hradec-kralove';
const CN = 'Hradci Králové';
const CA = 'Hradec Králové';

const profiles = [
  // ── ELEKTRIKÁŘ ───────────────────────────────────────────────────────────
  { fullName: 'Elektroinstalace Šimek Hradec Králové', phone: '+420 495 221 334', email: 'simek@elektro-hk.cz', serviceId: 'elektrikar', cityId: CITY, address: 'Gočárova třída 1122/18, Hradec Králové', description: `Elektroinstalace Šimek je zkušený elektrikář v ${CN} nabízející kompletní elektroinstalace, revize a opravy pro domácnosti i firmy. Elektrikář ${CA} zajistí rychlý výjezd a profesionální elektroinstalační práce v Královéhradeckém kraji.`, picturePath: null, active: true },
  { fullName: 'Elektro Vejvoda Hradec Králové', phone: '+420 495 334 560', email: 'vejvoda@elektro-hk.cz', serviceId: 'elektrikar', cityId: CITY, address: 'Čechovo nábřeží 2345/29, Hradec Králové', description: `Elektro Vejvoda je elektrikář v ${CN} s 17 lety zkušeností v oblasti elektroinstalací bytů, domů a průmyslových objektů. Elektrikář ${CA} provádí montáž rozvaděčů, hromosvodů a fotovoltaiky.`, picturePath: null, active: true },
  { fullName: 'Elektroslužby Horáček Hradec Králové', phone: '+420 603 441 780', email: null, serviceId: 'elektrikar', cityId: CITY, address: 'Ulrichovo náměstí 1234/14, Hradec Králové', description: `Pavel Horáček je certifikovaný elektrikář v ${CN} provádějící revize elektroinstalací a montáž inteligentních domů. Elektrikář ${CA} nabídne rychlý servis a profesionální přístup.`, picturePath: null, active: true },
  { fullName: 'Elektrikář Červinka Hradec Králové', phone: '+420 728 234 902', email: 'cervinka@elektro-hk.cz', serviceId: 'elektrikar', cityId: CITY, address: 'tř. SNP 3456/38, Hradec Králové', description: `Martin Červinka je elektrikář ${CA} provádějící elektroinstalace nových staveb i rekonstrukcí. Nabízí montáž osvětlení, zásuvek a výměnu pojistkových skříní v ${CN} a Královéhradeckém kraji.`, picturePath: null, active: true },

  // ── INSTALATÉR ───────────────────────────────────────────────────────────
  { fullName: 'Instalatér Tomášek Hradec Králové', phone: '+420 495 100 234', email: 'tomasek@instal-hk.cz', serviceId: 'instalater', cityId: CITY, address: 'Gočárova třída 2234/27, Hradec Králové', description: `Instalatér Tomášek nabízí kompletní instalatérské práce v ${CN} – opravy vodovodů, výměnu bojlerů a instalaci koupelen. Instalatér ${CA} zajistí rychlý výjezd a kvalitní práce.`, picturePath: null, active: true },
  { fullName: 'Vodo-Topo Blažek Hradec Králové', phone: '+420 603 441 870', email: 'blazek@vodotopo-hk.cz', serviceId: 'instalater', cityId: CITY, address: 'Čechovo nábřeží 3456/43, Hradec Králové', description: `Vodo-Topo Blažek je instalatér a topenář v ${CN} zaměřený na montáž plynových kotlů a podlahového vytápění. Instalatér ${CA} provádí kompletní rekonstrukce koupelen.`, picturePath: null, active: true },
  { fullName: 'Instalatérství Šimek Hradec Králové', phone: '+420 728 337 123', email: null, serviceId: 'instalater', cityId: CITY, address: 'Ulrichovo náměstí 4567/54, Hradec Králové', description: `Instalatérství Šimek nabízí veškeré instalatérské práce v ${CN}. Instalatér ${CA} se specializuje na opravy úniků vody a instalaci sanitárního vybavení.`, picturePath: null, active: true },
  { fullName: 'Petr Vávra – instalatér Hradec Králové', phone: '+420 495 389 234', email: 'vavra@instal-hk.cz', serviceId: 'instalater', cityId: CITY, address: 'tř. SNP 5678/67, Hradec Králové', description: `Petr Vávra je instalatér ${CA} s 15 lety praxe v opravách a rekonstrukcích vodovodního a topenářského rozvodu. Instalatér v ${CN} nabídne pohotovostní servis 24/7.`, picturePath: null, active: true },

  // ── MALÍŘ ────────────────────────────────────────────────────────────────
  { fullName: 'Malíř Spurný Hradec Králové', phone: '+420 495 228 456', email: 'spurny@malir-hk.cz', serviceId: 'malir', cityId: CITY, address: 'Gočárova třída 2345/35, Hradec Králové', description: `Malíř Spurný nabízí profesionální malování pokojů, bytů a kanceláří v ${CN} a okolí. Malíř ${CA} zajistí přípravu povrchů, stěrkování a výsledný nátěr dle přání zákazníka.`, picturePath: null, active: true },
  { fullName: 'Malířství Červinka Hradec Králové', phone: '+420 603 774 340', email: null, serviceId: 'malir', cityId: CITY, address: 'Čechovo nábřeží 3456/44, Hradec Králové', description: `Malířství Červinka provádí malování a lakýrnické práce pro domácnosti i firmy v ${CN}. Malíř ${CA} nabízí nátěry fasád, dekorativní techniky a výmalbu novostaveb.`, picturePath: null, active: true },
  { fullName: 'Pavel Tomáš – malíř Hradec Králové', phone: '+420 728 441 789', email: 'tomas@malir-hk.cz', serviceId: 'malir', cityId: CITY, address: 'Ulrichovo náměstí 2345/23, Hradec Králové', description: `Pavel Tomáš je zkušený malíř pokojů v ${CN} s precizním přístupem k malování bytů a průmyslových prostor. Malíř ${CA} provádí nátěry na klíč.`, picturePath: null, active: true },
  { fullName: 'Malíř Vejvoda Hradec Králové', phone: '+420 602 554 123', email: 'vejvoda@malir-hk.cz', serviceId: 'malir', cityId: CITY, address: 'tř. SNP 4567/57, Hradec Králové', description: `Tomáš Vejvoda je malíř a lakýrník v ${CN} nabízející veškeré malířské práce. Malíř ${CA} se specializuje na nátěry fasád a interiérů bytů v Královéhradeckém kraji.`, picturePath: null, active: true },

  // ── TESAŘ ────────────────────────────────────────────────────────────────
  { fullName: 'Tesařství Hejda Hradec Králové', phone: '+420 495 441 780', email: 'hejda@tesar-hk.cz', serviceId: 'tesar', cityId: CITY, address: 'Gočárova třída 3456/41, Hradec Králové', description: `Tesařství Hejda provádí výstavbu a rekonstrukci krovů a dřevěných konstrukcí v ${CN}. Tesař ${CA} realizuje pergoly, přístřešky a zahradní stavby v Královéhradeckém kraji.`, picturePath: null, active: true },
  { fullName: 'Krovy Šimek Hradec Králové', phone: '+420 603 221 456', email: null, serviceId: 'tesar', cityId: CITY, address: 'Čechovo nábřeží 4567/56, Hradec Králové', description: `Krovy Šimek je tesař v ${CN} specializující se na výstavbu nových krovů a rekonstrukce střešních konstrukcí. Tesař ${CA} realizuje dřevostavby a střešní práce pro rodinné domy.`, picturePath: null, active: true },
  { fullName: 'Tesař Blažek Hradec Králové', phone: '+420 728 234 780', email: 'blazek@tesarhk.cz', serviceId: 'tesar', cityId: CITY, address: 'Ulrichovo náměstí 5678/71, Hradec Králové', description: `Josef Blažek je zkušený tesař v ${CN} provádějící veškeré tesařské práce od krovů po dřevěné terasy a altány. Tesař ${CA} nabízí montáž schodišť a přístřešků.`, picturePath: null, active: true },
  { fullName: 'Dřevostavby Červinka Hradec Králové', phone: '+420 495 667 890', email: 'cervinka@drevostavby-hk.cz', serviceId: 'tesar', cityId: CITY, address: 'tř. SNP 6789/84, Hradec Králové', description: `Dřevostavby Červinka je tesař a dřevostavitel v ${CN} nabízející výstavbu dřevěných domků a krovů. Tesař ${CA} realizuje zakázkové tesařské práce v celém Královéhradeckém kraji.`, picturePath: null, active: true },

  // ── TRUHLÁŘ ──────────────────────────────────────────────────────────────
  { fullName: 'Truhlářství Vejvoda Hradec Králové', phone: '+420 495 335 660', email: 'vejvoda@truhlar-hk.cz', serviceId: 'truhlar', cityId: CITY, address: 'Gočárova třída 4567/49, Hradec Králové', description: `Truhlářství Vejvoda vyrábí nábytek, dveře a kuchyně na zakázku v ${CN}. Truhlář ${CA} se specializuje na výrobu kuchyňských linek, skříní a dřevěných interiérů.`, picturePath: null, active: true },
  { fullName: 'Zakázkové truhlářství Hejda Hradec Králové', phone: '+420 602 334 560', email: null, serviceId: 'truhlar', cityId: CITY, address: 'Čechovo nábřeží 5678/55, Hradec Králové', description: `Zakázkové truhlářství Hejda vyrábí nábytek a dřevěné interiéry na míru v ${CN}. Truhlář ${CA} nabízí výrobu postelí, stolů a zabudovaných systémů pro domy i byty.`, picturePath: null, active: true },
  { fullName: 'Truhlář Tomášek Hradec Králové', phone: '+420 728 441 560', email: 'tomasek@truhlarnhk.cz', serviceId: 'truhlar', cityId: CITY, address: 'Ulrichovo náměstí 6789/67, Hradec Králové', description: `Tomáš Tomášek je truhlář ${CA} s 16 lety zkušeností ve výrobě dřevěného nábytku a vestavěných skříní. Truhlářství v ${CN} realizuje dřevěné interiéry na klíč.`, picturePath: null, active: true },
  { fullName: 'Nábytek Spurný – truhlář Hradec Králové', phone: '+420 495 678 345', email: 'spurny@nabytek-hk.cz', serviceId: 'truhlar', cityId: CITY, address: 'tř. SNP 7890/81, Hradec Králové', description: `Dílna Spurný je truhlář a výrobce nábytku v ${CN} nabízející zakázkovou výrobu dřevěných prvků pro byty, domy a kanceláře. Truhlář ${CA} zajistí výrobu a montáž nábytku přímo u zákazníka.`, picturePath: null, active: true },

  // ── ZEDNÍK ───────────────────────────────────────────────────────────────
  { fullName: 'Zednictví Horáček Hradec Králové', phone: '+420 495 229 340', email: 'horacek@zednik-hk.cz', serviceId: 'zednik', cityId: CITY, address: 'Gočárova třída 5678/55, Hradec Králové', description: `Zednictví Horáček nabízí kompletní zednické práce v ${CN} – příčky, omítky, obklady a rekonstrukce bytů. Zedník ${CA} realizuje stavební práce pro rodinné domy i bytové jednotky.`, picturePath: null, active: true },
  { fullName: 'Stavební práce Šimek Hradec Králové', phone: '+420 603 456 780', email: null, serviceId: 'zednik', cityId: CITY, address: 'Čechovo nábřeží 6789/69, Hradec Králové', description: `Stavební práce Šimek provádí zednické práce, obklady a dlažby v ${CN} a okolí. Zedník ${CA} zajistí renovaci koupelen, pokládku dlažby a veškeré rekonstrukční práce.`, picturePath: null, active: true },
  { fullName: 'Zedník Vejvoda Hradec Králové', phone: '+420 728 223 456', email: 'vejvoda@zednik-hk.cz', serviceId: 'zednik', cityId: CITY, address: 'Ulrichovo náměstí 7890/87, Hradec Králové', description: `Ladislav Vejvoda je zkušený zedník v ${CN} provádějící omítky, zdění příček a rekonstrukce bytů. Zedník ${CA} nabízí kompletní stavební práce od základů po finální úpravy povrchů.`, picturePath: null, active: true },
  { fullName: 'Stavební firma Červinka Hradec Králové', phone: '+420 495 112 890', email: 'cervinka@stav-hk.cz', serviceId: 'zednik', cityId: CITY, address: 'tř. SNP 8901/101, Hradec Králové', description: `Stavební firma Červinka nabízí kompletní zednické a stavební práce v ${CN}. Zedník ${CA} realizuje zdění, betonáže, stropy a příčky pro soukromé i firemní zákazníky.`, picturePath: null, active: true },

  // ── KLEMPÍŘ ──────────────────────────────────────────────────────────────
  { fullName: 'Klempířství Blažek Hradec Králové', phone: '+420 495 120 780', email: 'blazek@klempir-hk.cz', serviceId: 'klempir', cityId: CITY, address: 'Gočárova třída 6789/61, Hradec Králové', description: `Klempířství Blažek nabízí kompletní klempířské a pokrývačské práce v ${CN} – oplechování střech, parapety a okapy. Klempíř ${CA} provádí montáž a opravy střech.`, picturePath: null, active: true },
  { fullName: 'Střechy Tomáš Hradec Králové', phone: '+420 603 667 560', email: null, serviceId: 'klempir', cityId: CITY, address: 'Čechovo nábřeží 7890/71, Hradec Králové', description: `Střechy Tomáš je klempíř a pokrývač v ${CN} se zaměřením na pokládku střešní krytiny a klempířské práce. Klempíř ${CA} poskytuje záruky na veškeré provedené práce.`, picturePath: null, active: true },
  { fullName: 'Klempíř Spurný Hradec Králové', phone: '+420 728 890 234', email: 'spurny@klempir-hk.cz', serviceId: 'klempir', cityId: CITY, address: 'Ulrichovo náměstí 8901/85, Hradec Králové', description: `Karel Spurný je klempíř ${CA} s 21 lety zkušeností s montáží okapů, oplechováním komínů a opravami střech. Klempíř v ${CN} zajistí kvalitní klempířské práce za přijatelné ceny.`, picturePath: null, active: true },
  { fullName: 'Klempíř Hejda Hradec Králové', phone: '+420 495 334 890', email: 'hejda@klempir-hk.cz', serviceId: 'klempir', cityId: CITY, address: 'tř. SNP 9012/99, Hradec Králové', description: `Roman Hejda je klempíř v ${CN} nabízející opravy střech, oplechování říms a montáž venkovních žaluzií. Klempíř ${CA} pracuje s pozinkovaným, titanzinkovým i měděným plechem.`, picturePath: null, active: true },

  // ── AUTOSERVIS ───────────────────────────────────────────────────────────
  { fullName: 'Autoservis Vejvoda Hradec Králové', phone: '+420 495 252 900', email: 'info@autoservis-vejvoda.cz', serviceId: 'autoservis', cityId: CITY, address: 'Průmyslová 1234/15, Hradec Králové', description: `Autoservis Vejvoda nabízí komplexní opravy a servis vozidel všech značek v ${CN}. Autoservis ${CA} zajistí pravidelné prohlídky, výměnu oleje, brzd a diagnostiku pro zákazníky z Královéhradeckého kraje.`, picturePath: null, active: true },
  { fullName: 'Car Service Hradec Králové – Šimek', phone: '+420 603 334 780', email: 'simek@carservice-hk.cz', serviceId: 'autoservis', cityId: CITY, address: 'Gočárova třída 2345/28, Hradec Králové', description: `Car Service Šimek je autoservis v ${CN} zaměřený na opravy motorů, převodovek a klimatizací. Autoservis ${CA} provádí STK přípravu a komplexní servis osobních i užitkových vozidel.`, picturePath: null, active: true },
  { fullName: 'Auto Horáček – servis Hradec Králové', phone: '+420 495 339 127', email: null, serviceId: 'autoservis', cityId: CITY, address: 'Čechovo nábřeží 3456/43, Hradec Králové', description: `Auto Horáček je rodinný autoservis v ${CN} s tradicí přes 22 let, specializující se na osobní vozy a dodávky. Autoservis ${CA} nabízí pneuservis, geometrii náprav a karosářské práce.`, picturePath: null, active: true },
  { fullName: 'Autoservis Spurný Hradec Králové', phone: '+420 728 667 234', email: 'spurny@autohk.cz', serviceId: 'autoservis', cityId: CITY, address: 'tř. SNP 4567/57, Hradec Králové', description: `Autoservis Spurný je certifikovaný servis v ${CN} pro osobní i užitková vozidla. Autoservis ${CA} zajistí diagnostiku závad, opravy elektroniky a pravidelnou údržbu vozidel.`, picturePath: null, active: true },

  // ── IT TECHNIK ───────────────────────────────────────────────────────────
  { fullName: 'PC Servis Hradec Králové – Šimek', phone: '+420 495 241 801', email: 'simek@pc-hk.cz', serviceId: 'it-technik', cityId: CITY, address: 'Velké náměstí 12, Hradec Králové', description: `PC Servis Šimek je IT technik v ${CN} nabízející opravy počítačů, notebooků a tiskáren pro firmy i domácnosti. IT technik ${CA} zajistí instalaci systémů, obnovu dat a správu sítí.`, picturePath: null, active: true },
  { fullName: 'IT pohotovost Hradec Králové – Vejvoda', phone: '+420 603 778 560', email: 'vejvoda@it-hk.cz', serviceId: 'it-technik', cityId: CITY, address: 'Gočárova třída 2345/31, Hradec Králové', description: `IT pohotovost Vejvoda je zkušený IT technik ${CA} s 17 lety praxe v opravách PC a správě IT infrastruktury. Nabízí nonstop IT pohotovost a vzdálenou správu počítačů v ${CN}.`, picturePath: null, active: true },
  { fullName: 'Comtech Hradec Králové', phone: '+420 495 100 700', email: 'info@comtech-hk.cz', serviceId: 'it-technik', cityId: CITY, address: 'Čechovo nábřeží 3456/39, Hradec Králové', description: `Comtech je profesionální IT servis v ${CN} zaměřený na opravy počítačů, datové zálohy a kybernetickou bezpečnost. IT technik ${CA} poskytuje komplexní ICT podporu pro firmy.`, picturePath: null, active: true },
  { fullName: 'Počítačový servis Blažek Hradec Králové', phone: '+420 728 445 890', email: null, serviceId: 'it-technik', cityId: CITY, address: 'Ulrichovo náměstí 4567/59, Hradec Králové', description: `Počítačový servis Blažek nabízí opravy a upgrade PC a notebooků v ${CN} za dostupné ceny. IT technik ${CA} zajistí reinstalaci systémů, odstranění virů a nastavení Wi-Fi sítí.`, picturePath: null, active: true },

  // ── FOTOGRAF ─────────────────────────────────────────────────────────────
  { fullName: 'Foto Studio Šimková Hradec Králové', phone: '+420 603 447 882', email: 'info@fotohk.cz', serviceId: 'fotograf', cityId: CITY, address: 'tř. SNP 5678/71, Hradec Králové', description: `Foto Studio Šimková je profesionální fotografka v ${CN} se zaměřením na rodinné, těhotenské a newborn fotografie. Fotograf ${CA} nabízí moderní fotografické studio a venkovní focení.`, picturePath: null, active: true },
  { fullName: 'Reportážní fotograf Vejvoda Hradec Králové', phone: '+420 495 108 540', email: 'vejvoda@foto-hk.cz', serviceId: 'fotograf', cityId: CITY, address: 'Gočárova třída 6789/87, Hradec Králové', description: `Michal Vejvoda je reportážní a reklamní fotograf v ${CN} s 12 lety zkušeností. Fotograf ${CA} nabízí firemní fotografii, produktové focení a reportáže z akcí v Královéhradeckém kraji.`, picturePath: null, active: true },
  { fullName: 'Svatební fotograf Hejda Hradec Králové', phone: '+420 728 112 901', email: 'hejda@svatebnifoto-hk.cz', serviceId: 'fotograf', cityId: CITY, address: 'Čechovo nábřeží 7890/101, Hradec Králové', description: `Tomáš Hejda je svatební fotograf v ${CN} specializující se na svatební reportáže a portrétní fotografii. Fotograf ${CA} zachytí každý vzácný okamžik vašeho dne.`, picturePath: null, active: true },
  { fullName: 'FotoArt Hradec Králové – Spurná', phone: '+420 495 334 120', email: 'spurna@fotoart-hk.cz', serviceId: 'fotograf', cityId: CITY, address: 'Ulrichovo náměstí 8901/115, Hradec Králové', description: `FotoArt Spurná je fotografka v ${CN} nabízející portréty, rodinnou a těhotenskou fotografii ve studiu i exteriéru. Fotograf ${CA} klade důraz na přirozené zachycení emocí.`, picturePath: null, active: true },

  // ── UČITEL / LEKTOR ──────────────────────────────────────────────────────
  { fullName: 'Jazyková škola Hradec Králové – Lingua', phone: '+420 495 220 712', email: 'hk@lingua-skola.cz', serviceId: 'ucitel', cityId: CITY, address: 'Velké náměstí 8, Hradec Králové', description: `Jazyková škola Lingua nabízí kurzy angličtiny, němčiny a španělštiny v ${CN} pro děti i dospělé. Zkušení lektoři v ${CA} zajistí efektivní výuku jazyků a přípravu na mezinárodní certifikáty.`, picturePath: null, active: true },
  { fullName: 'Jazykové centrum Hradec Králové', phone: '+420 495 220 780', email: 'info@jazykove-centrum-hk.cz', serviceId: 'ucitel', cityId: CITY, address: 'Gočárova třída 1345/23, Hradec Králové', description: `Jazykové centrum ${CA} nabízí firemní i individuální kurzy angličtiny, němčiny a francouzštiny. Lektor ${CA} zajistí výuku na míru přímo ve firmě nebo v moderních učebnách.`, picturePath: null, active: true },
  { fullName: 'Doučování Hradec Králové – Mgr. Spurná', phone: '+420 728 441 560', email: null, serviceId: 'ucitel', cityId: CITY, address: 'Čechovo nábřeží 2345/25, Hradec Králové', description: `Mgr. Spurná je zkušená lektorka nabízející doučování matematiky, angličtiny a chemie v ${CN}. Lektor ${CA} zajistí individuální přístup k žákům základních a středních škol.`, picturePath: null, active: true },
  { fullName: 'Bc. Horáček – lektor angličtiny Hradec Králové', phone: '+420 603 334 780', email: 'horacek@lektor-hk.cz', serviceId: 'ucitel', cityId: CITY, address: 'Ulrichovo náměstí 3456/43, Hradec Králové', description: `Bc. Horáček je certifikovaný lektor angličtiny v ${CN} s 9 lety praxe ve výuce dospělých a firemní klientely. Lektor ${CA} nabízí individuální i skupinové kurzy na všech úrovních znalostí.`, picturePath: null, active: true },

  // ── RESTAURACE ───────────────────────────────────────────────────────────
  { fullName: 'Restaurace Na Hradě Hradec Králové', phone: '+420 495 229 287', email: 'info@nahrade-hk.cz', serviceId: 'restaurace', cityId: CITY, address: 'Velké náměstí 23, Hradec Králové', description: `Restaurace Na Hradě je tradiční česká restaurace v centru ${CN} nabízející českou kuchyni a regionální speciality. Restaurace ${CA} je oblíbená mezi místními i turisty pro příjemnou atmosféru.`, picturePath: null, active: true },
  { fullName: 'Restaurace U Labské Hradec Králové', phone: '+420 495 220 522', email: 'ulabske@restaurace-hk.cz', serviceId: 'restaurace', cityId: CITY, address: 'Čechovo nábřeží 22, Hradec Králové', description: `Restaurace U Labské nabízí českou a středoevropskou kuchyni s výhledem na řeku Labe v ${CN}. Restaurace ${CA} se specializuje na čerstvé ryby, svíčkovou a tradiční česká jídla.`, picturePath: null, active: true },
  { fullName: 'Restaurace Bílý Lev Hradec Králové', phone: '+420 603 334 456', email: null, serviceId: 'restaurace', cityId: CITY, address: 'Gočárova třída 3456/47, Hradec Králové', description: `Restaurace Bílý Lev je oblíbená restaurace v ${CN} nabízející denní menu a českou kuchyni za dostupné ceny. Restaurace ${CA} láká místní i turisty na domácí jídla z čerstvých surovin.`, picturePath: null, active: true },
  { fullName: 'Pivnice U Šimka Hradec Králové', phone: '+420 495 345 678', email: 'info@pivnice-hk.cz', serviceId: 'restaurace', cityId: CITY, address: 'tř. SNP 4567/67, Hradec Králové', description: `Pivnice U Šimka je tradiční hospoda v ${CN} s autentickým prostředím a poctivou českou kuchyní. Restaurace ${CA} nabízí guláš, řízek a čepované pivo v příjemném prostředí.`, picturePath: null, active: true },

  // ── ZUBAŘ ────────────────────────────────────────────────────────────────
  { fullName: 'MDDr. Šimková – zubní ordinace Hradec Králové', phone: '+420 495 110 890', email: 'simkova@zubar-hk.cz', serviceId: 'zubar', cityId: CITY, address: 'Velké náměstí 32, Hradec Králové', description: `MDDr. Šimková provozuje zubní ordinaci v ${CN} nabízející kompletní stomatologickou péči pro děti i dospělé. Zubař ${CA} zajistí ošetření zubů, bělení a ortodontické poradenství.`, picturePath: null, active: true },
  { fullName: 'Stomatologie Vejvoda Hradec Králové', phone: '+420 495 224 177', email: 'vejvoda@stom-hk.cz', serviceId: 'zubar', cityId: CITY, address: 'Gočárova třída 3456/43, Hradec Králové', description: `Stomatologie Vejvoda je zubní ordinace v ${CN} zaměřená na estetickou stomatologii, implantáty a dentální hygienu. Zubař ${CA} přijímá nové pacienty a nabízí individuální přístup.`, picturePath: null, active: true },
  { fullName: 'Zubní ordinace Tomášek Hradec Králové', phone: '+420 495 128 901', email: null, serviceId: 'zubar', cityId: CITY, address: 'Čechovo nábřeží 4567/49, Hradec Králové', description: `MUDr. Tomášek provozuje zubní ordinaci v ${CN} s komplexními stomatologickými službami včetně chirurgie a protetiky. Zubař ${CA} zajistí odbornou péči o chrup v klidném prostředí.`, picturePath: null, active: true },
  { fullName: 'Dentální centrum Hradec Králové', phone: '+420 495 901 234', email: 'info@dental-hk.cz', serviceId: 'zubar', cityId: CITY, address: 'Ulrichovo náměstí 5678/73, Hradec Králové', description: `Dentální centrum ${CA} je moderní zubní klinika nabízející komplexní péči od prevence po implantologii. Zubař ${CA} nabídne bezbolestné ošetření, ortodoncii a dentální hygienu pro celou rodinu.`, picturePath: null, active: true },

  // ── LÉKAŘ ────────────────────────────────────────────────────────────────
  { fullName: 'MUDr. Červinková – praktická lékařka Hradec Králové', phone: '+420 495 110 455', email: 'cervinkova@lekar-hk.cz', serviceId: 'lekar', cityId: CITY, address: 'Gočárova třída 2234/29, Hradec Králové', description: `MUDr. Červinková je praktická lékařka v ${CN} s komplexní zdravotní péčí pro dospělé. Lékař ${CA} přijímá nové pacienty a zajistí pravidelné prohlídky a vydávání receptů.`, picturePath: null, active: true },
  { fullName: 'MUDr. Šimek – internista Hradec Králové', phone: '+420 495 261 233', email: 'simek@interna-hk.cz', serviceId: 'lekar', cityId: CITY, address: 'Čechovo nábřeží 3345/43, Hradec Králové', description: `MUDr. Šimek je internista v ${CN} specializující se na diagnostiku a léčbu interních onemocnění. Lékař ${CA} nabídne odborné vyšetření a individuální léčebný plán.`, picturePath: null, active: true },
  { fullName: 'Poliklinika Hradec Králové – zdravotní centrum', phone: '+420 495 103 111', email: 'info@poliklinika-hk.cz', serviceId: 'lekar', cityId: CITY, address: 'Komenského 1214/17, Hradec Králové', description: `Poliklinika ${CA} je zdravotní centrum s širokým spektrem praktických a odborných lékařů. Lékař ${CA} nabízí komplexní zdravotní péči pro obyvatele ${CN} a Královéhradeckého kraje.`, picturePath: null, active: true },
  { fullName: 'MUDr. Hejdová – pediatr Hradec Králové', phone: '+420 495 118 766', email: null, serviceId: 'lekar', cityId: CITY, address: 'Ulrichovo náměstí 4567/57, Hradec Králové', description: `MUDr. Hejdová je dětská lékařka – pediatr v ${CN} pečující o zdravý vývoj dětí od narození. Lékař ${CA} poskytuje preventivní prohlídky, očkování a léčbu dětských nemocí.`, picturePath: null, active: true },

  // ── PSYCHOLOG ─────────────────────────────────────────────────────────────
  { fullName: 'PhDr. Šimková – psycholog Hradec Králové', phone: '+420 495 243 210', email: 'simkova@psycholog-hk.cz', serviceId: 'psycholog', cityId: CITY, address: 'Velké náměstí 48, Hradec Králové', description: `PhDr. Šimková je psycholog v ${CN} nabízející individuální psychoterapii, párové poradenství a krizovou intervenci. Psycholog ${CA} pomáhá klientům zvládat úzkosti, deprese a životní krize.`, picturePath: null, active: true },
  { fullName: 'Mgr. Vejvoda – psychoterapeut Hradec Králové', phone: '+420 603 234 341', email: 'vejvoda@terapie-hk.cz', serviceId: 'psycholog', cityId: CITY, address: 'Gočárova třída 4456/57, Hradec Králové', description: `Mgr. Vejvoda je psychoterapeut v ${CN} s výcvikem v kognitivně-behaviorální terapii. Psycholog ${CA} nabízí individuální, párovou a skupinovou terapii pro dospělé i adolescenty.`, picturePath: null, active: true },
  { fullName: 'Centrum psychologické pomoci Hradec Králové', phone: '+420 495 989 123', email: 'info@cpp-hk.cz', serviceId: 'psycholog', cityId: CITY, address: 'Čechovo nábřeží 5678/63, Hradec Králové', description: `Centrum psychologické pomoci ${CA} je poradenské centrum s týmem zkušených psychologů. Psycholog ${CA} nabízí diagnostiku, poradenství a terapii pro děti, dospělé i rodiny.`, picturePath: null, active: true },
  { fullName: 'Mgr. Červinková – terapeutka Hradec Králové', phone: '+420 728 345 123', email: null, serviceId: 'psycholog', cityId: CITY, address: 'tř. SNP 6789/87, Hradec Králové', description: `Mgr. Červinková je psycholožka a terapeutka v ${CN} specializující se na práci s traumatem a úzkostí. Psycholog ${CA} pracuje s dospělými i dětmi metodou EMDR a systemické terapie.`, picturePath: null, active: true },

  // ── PRÁVNÍK ──────────────────────────────────────────────────────────────
  { fullName: 'JUDr. Šimek – advokát Hradec Králové', phone: '+420 495 122 891', email: 'simek@advokatHK.cz', serviceId: 'pravnik', cityId: CITY, address: 'Velké náměstí 36, Hradec Králové', description: `JUDr. Šimek je advokát v ${CN} zaměřený na občanské, obchodní a rodinné právo. Právník ${CA} nabízí právní poradenství, sepis smluv a zastupování klientů před soudy v Královéhradeckém kraji.`, picturePath: null, active: true },
  { fullName: 'Advokátní kancelář Vejvoda Hradec Králové', phone: '+420 495 310 067', email: 'vejvoda@ak-hk.cz', serviceId: 'pravnik', cityId: CITY, address: 'Gočárova třída 1122/16, Hradec Králové', description: `Advokátní kancelář Vejvoda je právní firma v ${CN} specializující se na pracovní právo, nemovitosti a obchodní spory. Právník ${CA} zajistí komplexní právní zastoupení.`, picturePath: null, active: true },
  { fullName: 'JUDr. Červinka – notář Hradec Králové', phone: '+420 495 228 445', email: 'cervinka@notar-hk.cz', serviceId: 'pravnik', cityId: CITY, address: 'Čechovo nábřeží 1234/19, Hradec Králové', description: `JUDr. Červinka je notář a právník v ${CN} zajišťující sepisování závětí, kupních smluv a ověřování podpisů. Právník ${CA} poskytuje notářské a právní služby pro fyzické i právnické osoby.`, picturePath: null, active: true },
  { fullName: 'Mgr. Spurná – rodinné právo Hradec Králové', phone: '+420 728 220 789', email: null, serviceId: 'pravnik', cityId: CITY, address: 'Ulrichovo náměstí 2345/27, Hradec Králové', description: `Mgr. Spurná je právnička v ${CN} specializující se na rodinné právo, rozvody a opatrovnická řízení. Právník ${CA} nabídne empatické a profesionální zastupování v soudních sporech.`, picturePath: null, active: true },

  // ── ÚČETNÍ ───────────────────────────────────────────────────────────────
  { fullName: 'Účetní poradenství Šimková Hradec Králové', phone: '+420 495 243 210', email: 'simkova@ucetni-hk.cz', serviceId: 'ucetni', cityId: CITY, address: 'Velké náměstí 54, Hradec Králové', description: `Účetní poradenství Šimková nabízí vedení účetnictví, daňové přiznání a mzdovou agendu pro firmy v ${CN}. Účetní ${CA} poskytuje kompletní ekonomické poradenství pro OSVČ i právnické osoby.`, picturePath: null, active: true },
  { fullName: 'ECO Consulting Hradec Králové', phone: '+420 495 421 800', email: 'info@eco-consulting-hk.cz', serviceId: 'ucetni', cityId: CITY, address: 'Gočárova třída 4567/57, Hradec Králové', description: `ECO Consulting je účetní firma v ${CN} specializující se na podvojné účetnictví, DPH a daňovou optimalizaci. Účetní ${CA} zajistí přesné zpracování daňových přiznání a roční závěrky.`, picturePath: null, active: true },
  { fullName: 'Bc. Hejdová – účetní a mzdy Hradec Králové', phone: '+420 728 334 456', email: 'hejdova@ucetni-mzdy-hk.cz', serviceId: 'ucetni', cityId: CITY, address: 'Čechovo nábřeží 5678/73, Hradec Králové', description: `Bc. Hejdová je účetní v ${CN} se specializací na zpracování mezd, daňové přiznání a vedení daňové evidence. Účetní ${CA} nabízí přesné a spolehlivé zpracování dokladů pro malé a střední firmy.`, picturePath: null, active: true },
  { fullName: 'AUDIT HRADEC KRÁLOVÉ – účetní kancelář', phone: '+420 603 457 890', email: 'audit@uc-hk.cz', serviceId: 'ucetni', cityId: CITY, address: 'tř. SNP 6789/85, Hradec Králové', description: `AUDIT ${CA.toUpperCase()} je účetní kancelář v ${CN} nabízející komplexní ekonomické a daňové poradenství pro podnikatele. Účetní ${CA} zpracuje daňová přiznání a roční závěrky i pro zahraniční firmy.`, picturePath: null, active: true },

  // ── KADEŘNÍK ─────────────────────────────────────────────────────────────
  { fullName: 'Kadeřnictví Šimková Hradec Králové', phone: '+420 495 111 345', email: null, serviceId: 'kadernik', cityId: CITY, address: 'Velké náměstí 58, Hradec Králové', description: `Kadeřnictví Šimková nabízí střihy, barvení a styling vlasů pro ženy i muže v ${CN}. Kadeřník ${CA} pracuje s prémiovou kosmetikou a zajistí individuální poradenství.`, picturePath: null, active: true },
  { fullName: 'Salon Eva – kadeřnictví Hradec Králové', phone: '+420 495 258 900', email: 'eva@salon-hk.cz', serviceId: 'kadernik', cityId: CITY, address: 'Gočárova třída 2345/33, Hradec Králové', description: `Salon Eva je moderní kadeřnický salon v ${CN} se zkušenými stylisty. Kadeřník ${CA} nabízí barvení, melír, keratin a svatební účesy v příjemném salonu.`, picturePath: null, active: true },
  { fullName: 'Kadeřnictví Vejvoda Hradec Králové', phone: '+420 728 445 789', email: null, serviceId: 'kadernik', cityId: CITY, address: 'Čechovo nábřeží 3456/39, Hradec Králové', description: `Kadeřnictví Vejvoda je rodinný salon v ${CN} nabízející kompletní kadeřnické služby – střihy, barvení a rekonstrukce vlasů. Kadeřník ${CA} zajistí péči o vlasy v přátelské atmosféře.`, picturePath: null, active: true },
  { fullName: 'Studio Moda – kadeřnictví Hradec Králové', phone: '+420 495 235 678', email: 'moda@kadernictvi-hk.cz', serviceId: 'kadernik', cityId: CITY, address: 'Ulrichovo náměstí 4567/57, Hradec Králové', description: `Studio Moda je prémiové kadeřnické studio v ${CN} zaměřené na moderní trendy v barvení a stylingu vlasů. Kadeřník ${CA} nabízí konzultace, střihy a speciální ošetření vlasů.`, picturePath: null, active: true },

  // ── ARCHITEKT ────────────────────────────────────────────────────────────
  { fullName: 'Ing. arch. Šimek – architekt Hradec Králové', phone: '+420 495 422 780', email: 'simek@architektHK.cz', serviceId: 'architekt', cityId: CITY, address: 'Velké náměstí 62, Hradec Králové', description: `Ing. arch. Šimek je architekt v ${CN} nabízející projektování rodinných domů a bytových rekonstrukcí. Architekt ${CA} navrhuje funkční a estetická řešení s důrazem na nízkoenergetické standardy.`, picturePath: null, active: true },
  { fullName: 'Ateliér VÝCHOD – architekti Hradec Králové', phone: '+420 495 534 122', email: 'info@ateliervychod.cz', serviceId: 'architekt', cityId: CITY, address: 'Gočárova třída 2345/36, Hradec Králové', description: `Ateliér VÝCHOD je architektonické studio v ${CN} s portfoliem rezidenčních, komerčních a veřejných staveb. Architekt ${CA} nabídne kompletní projektové služby od studie po realizaci.`, picturePath: null, active: true },
  { fullName: 'Ing. arch. Hejdová – interiéry Hradec Králové', phone: '+420 728 882 445', email: 'hejdova@interier-hk.cz', serviceId: 'architekt', cityId: CITY, address: 'Čechovo nábřeží 3456/45, Hradec Králové', description: `Ing. arch. Hejdová je architektka a interiérová designérka v ${CN} zaměřená na návrhy interiérů bytů a kanceláří. Architekt ${CA} navrhuje prostory s ohledem na funkčnost a přání klienta.`, picturePath: null, active: true },
  { fullName: 'STUDIO HK – architekti Hradec Králové', phone: '+420 495 620 110', email: 'info@studio-hk.cz', serviceId: 'architekt', cityId: CITY, address: 'tř. SNP 4567/51, Hradec Králové', description: `STUDIO HK je architektonická kancelář v ${CN} realizující rodinné domy, rekonstrukce a urbanistické projekty. Architekt ${CA} zajistí projekt od konceptu přes povolení až po dozor na stavbě.`, picturePath: null, active: true },

  // ── REALITNÍ MAKLÉŘ ──────────────────────────────────────────────────────
  { fullName: 'RE/MAX Hradec Králové – realitní kancelář', phone: '+420 495 244 555', email: 'remax@remax-hk.cz', serviceId: 'realitni-makler', cityId: CITY, address: 'Velké náměstí 71, Hradec Králové', description: `RE/MAX ${CA} je realitní kancelář s týmem zkušených makléřů pro prodej a pronájem bytů a domů v ${CN}. Realitní makléř ${CA} zajistí odborné ocenění nemovitosti a efektivní marketing.`, picturePath: null, active: true },
  { fullName: 'Realitní kancelář Šimek Hradec Králové', phone: '+420 495 310 700', email: 'simek@rk-hk.cz', serviceId: 'realitni-makler', cityId: CITY, address: 'Gočárova třída 3456/49, Hradec Králové', description: `Realitní kancelář Šimek je zavedená realitní firma v ${CN} s 14 lety zkušeností na trhu s nemovitostmi. Realitní makléř ${CA} pomůže s koupí, prodejem i pronájmem nemovitostí v Královéhradeckém kraji.`, picturePath: null, active: true },
  { fullName: 'STING realitní Hradec Králové', phone: '+420 728 888 341', email: 'info@sting-reality-hk.cz', serviceId: 'realitni-makler', cityId: CITY, address: 'Čechovo nábřeží 4567/57, Hradec Králové', description: `STING realitní je dynamická realitní kancelář v ${CN} zaměřená na prodej bytů a domů. Realitní makléř ${CA} nabídne profesionální fotografii, 3D prohlídky a právní servis.`, picturePath: null, active: true },
  { fullName: 'Reality Vejvoda Hradec Králové', phone: '+420 603 003 789', email: null, serviceId: 'realitni-makler', cityId: CITY, address: 'Ulrichovo náměstí 5678/65, Hradec Králové', description: `Reality Vejvoda je realitní makléř v ${CN} specializující se na rezidenční nemovitosti. Makléř ${CA} nabídne individuální přístup a kompletní administrativní servis při prodeji i nákupu bytu.`, picturePath: null, active: true },

  // ── ZAHRADNÍK ────────────────────────────────────────────────────────────
  { fullName: 'Zahradnictví Šimek Hradec Králové', phone: '+420 728 334 780', email: 'simek@zahradnictvi-hk.cz', serviceId: 'zahradnik', cityId: CITY, address: 'Průmyslová 2345/28, Hradec Králové', description: `Zahradnictví Šimek nabízí kompletní zahradnické práce v ${CN} – sekání trávníků, výsadbu rostlin a zakládání zahrad. Zahradník ${CA} zajistí pravidelnou údržbu zahrady pro soukromníky i firmy.`, picturePath: null, active: true },
  { fullName: 'Green Garden Hradec Králové', phone: '+420 495 456 234', email: 'info@greengarden-hk.cz', serviceId: 'zahradnik', cityId: CITY, address: 'tř. SNP 3456/43, Hradec Králové', description: `Green Garden je zahradní firma v ${CN} nabízející návrhy a realizaci zahrad a teras. Zahradník ${CA} provede kompletní terénní úpravy, automatické zavlažování a instalaci zahradních prvků.`, picturePath: null, active: true },
  { fullName: 'Zahradní úpravy Hejda Hradec Králové', phone: '+420 728 441 780', email: null, serviceId: 'zahradnik', cityId: CITY, address: 'Gočárova třída 4567/59, Hradec Králové', description: `Zahradní úpravy Hejda je zahradník v ${CN} zajišťující terénní úpravy, výsadbu stromů a sezónní péči o zahrady. Zahradník ${CA} nabídne osobní poradenství a realizaci zahradních projektů.`, picturePath: null, active: true },
  { fullName: 'Arboristika Hradec Králové – Blažek', phone: '+420 603 017 890', email: 'blazek@arboristika-hk.cz', serviceId: 'zahradnik', cityId: CITY, address: 'Průmyslová 5678/71, Hradec Králové', description: `Arboristika Blažek nabízí profesionální péči o stromy, kácení a ošetřování dřevin v ${CN}. Zahradník ${CA} provede výškové práce, redukci korun a odborné posudky zdraví stromů.`, picturePath: null, active: true },

  // ── ÚKLID ────────────────────────────────────────────────────────────────
  { fullName: 'Čistota Hradec Králové – úklidová firma', phone: '+420 495 890 234', email: 'info@cistota-hk.cz', serviceId: 'uklid', cityId: CITY, address: 'Gočárova třída 4567/63, Hradec Králové', description: `Čistota ${CA} je profesionální úklidová firma nabízející pravidelný i jednorázový úklid bytů a kanceláří v ${CN}. Úklid ${CA} zajistí čisté prostředí s ekologickými čisticími prostředky.`, picturePath: null, active: true },
  { fullName: 'CleanPro Hradec Králové', phone: '+420 603 778 901', email: 'cleanpro@uklid-hk.cz', serviceId: 'uklid', cityId: CITY, address: 'Čechovo nábřeží 5678/73, Hradec Králové', description: `CleanPro je úklidová společnost v ${CN} specializující se na úklid po rekonstrukci a generální úklid domácností. Úklid ${CA} nabídne rychlý nástup a záruky spokojenosti.`, picturePath: null, active: true },
  { fullName: 'Paní na úklid Hradec Králové – Vejvodová', phone: '+420 728 456 789', email: null, serviceId: 'uklid', cityId: CITY, address: 'Ulrichovo náměstí 4567/59, Hradec Králové', description: `Paní Vejvodová nabízí pravidelný domácí úklid bytů a domů v ${CN} s osobním přístupem a spolehlivostí. Úklid ${CA} – domácí pomoc pro rodiny a seniory v ${CN}.`, picturePath: null, active: true },
  { fullName: 'TopClean Hradec Králové', phone: '+420 495 345 678', email: 'info@topclean-hk.cz', serviceId: 'uklid', cityId: CITY, address: 'tř. SNP 5678/75, Hradec Králové', description: `TopClean je úklidová firma v ${CN} s komplexní nabídkou čistění koberců, čalounění a mytí oken. Úklid ${CA} provádí profesionální dezinfekce a sanace bytů, kanceláří i průmyslových prostor.`, picturePath: null, active: true },

  // ── STĚHOVACÍ FIRMA ──────────────────────────────────────────────────────
  { fullName: 'Stěhování Hradec Králové – Šimek Transport', phone: '+420 495 334 120', email: 'simek@stehovanihk.cz', serviceId: 'stehovaci-firma', cityId: CITY, address: 'Průmyslová 3456/43, Hradec Králové', description: `Stěhování ${CA} Šimek Transport nabízí profesionální stěhování bytů, kanceláří a firem v ${CN} a celé ČR. Stěhovací firma ${CA} zajistí bezpečné zabalení, přepravu a složení nábytku.`, picturePath: null, active: true },
  { fullName: 'Fast Move Hradec Králové', phone: '+420 603 791 345', email: 'info@fastmove-hk.cz', serviceId: 'stehovaci-firma', cityId: CITY, address: 'Gočárova třída 5678/75, Hradec Králové', description: `Fast Move je rychlá stěhovací firma v ${CN} zajišťující stěhování bytů i firem s vlastním vozovým parkem. Stěhovací firma ${CA} nabídne bezpečnostní balení, demontáž a montáž nábytku.`, picturePath: null, active: true },
  { fullName: 'Stěhování Vejvoda Hradec Králové', phone: '+420 728 678 234', email: null, serviceId: 'stehovaci-firma', cityId: CITY, address: 'Čechovo nábřeží 6789/89, Hradec Králové', description: `Stěhování Vejvoda je spolehlivá stěhovací firma v ${CN} s vlastními stěhovacími vozidly a pojištěním nákladu. Stěhovací firma ${CA} realizuje stěhování po ${CN} i mezinárodní přepravu.`, picturePath: null, active: true },
  { fullName: 'Profi Stěhování Hradec Králové', phone: '+420 495 234 890', email: 'profistehov@hk-move.cz', serviceId: 'stehovaci-firma', cityId: CITY, address: 'tř. SNP 4567/57, Hradec Králové', description: `Profi Stěhování ${CA} je komplexní stěhovací firma pro domácnosti i firmy v Královéhradeckém kraji. Stěhovací firma ${CA} zajistí expresní i plánované stěhování s péčí o každý kus majetku.`, picturePath: null, active: true },

  // ── TRENÉR ───────────────────────────────────────────────────────────────
  { fullName: 'Fitness trenér Šimek Hradec Králové', phone: '+420 728 441 890', email: 'simek@fitnes-hk.cz', serviceId: 'trener', cityId: CITY, address: 'Velké náměstí 76, Hradec Králové', description: `Fitness trenér Šimek je osobní trenér v ${CN} nabízející tréninkové plány a nutriční poradenství. Trenér ${CA} pomůže s hubnutím, nabíráním svalové hmoty a zlepšením kondice.`, picturePath: null, active: true },
  { fullName: 'Petra Vejvodová – osobní trenérka Hradec Králové', phone: '+420 495 560 234', email: 'vejvodova@trener-hk.cz', serviceId: 'trener', cityId: CITY, address: 'Gočárova třída 5678/73, Hradec Králové', description: `Petra Vejvodová je certifikovaná osobní trenérka v ${CN} specializující se na funkční trénink a pilates. Trenér ${CA} nabídne individuální fitness program pro dosažení sportovních cílů.`, picturePath: null, active: true },
  { fullName: 'Sportovní centrum Slavia Hradec Králové', phone: '+420 495 455 666', email: 'info@slavia-hk.cz', serviceId: 'trener', cityId: CITY, address: 'Labská 1025/4, Hradec Králové', description: `Sportovní centrum Slavia nabízí trenéry a sportovní kurzy pro děti i dospělé v ${CN}. Trenér ${CA} zajistí kondičníkurzy, skupinové lekce jógy a fitness tréninky v moderním centru.`, picturePath: null, active: true },
  { fullName: 'Mgr. Červinka – trenér atletiky Hradec Králové', phone: '+420 728 228 901', email: null, serviceId: 'trener', cityId: CITY, address: 'Ulrichovo náměstí 6789/89, Hradec Králové', description: `Mgr. Červinka je trenér atletiky a kondičního tréninku v ${CN} s licencí ČAS. Trenér ${CA} pracuje s dětmi, juniory i dospělými závodníky na atletickém stadionu v ${CN}.`, picturePath: null, active: true },

  // ── PŘEKLADATEL ──────────────────────────────────────────────────────────
  { fullName: 'Překladatelské centrum Hradec Králové', phone: '+420 495 441 760', email: 'info@prekladhk.cz', serviceId: 'prekladatel', cityId: CITY, address: 'Velké náměstí 82, Hradec Králové', description: `Překladatelské centrum ${CA} nabízí odborné překlady z němčiny, angličtiny a dalších jazyků pro firmy i jednotlivce. Překladatel ${CA} zajistí přesné překlady smluv, technických dokumentů a úředních listin.`, picturePath: null, active: true },
  { fullName: 'Mgr. Vejvodová – překladatelka Hradec Králové', phone: '+420 728 778 450', email: 'vejvodova@prekladhk.cz', serviceId: 'prekladatel', cityId: CITY, address: 'Gočárova třída 2345/33, Hradec Králové', description: `Mgr. Vejvodová je soudní překladatelka pro němčinu a angličtinu v ${CN} s oprávněním od Krajského soudu. Překladatel ${CA} provede úřední překlady dokumentů pro státní orgány.`, picturePath: null, active: true },
  { fullName: 'ProTranslate Hradec Králové', phone: '+420 495 229 112', email: 'info@protranslate-hk.cz', serviceId: 'prekladatel', cityId: CITY, address: 'Čechovo nábřeží 3456/43, Hradec Králové', description: `ProTranslate je překladatelská agentura v ${CN} zajišťující překlady do více než 25 jazyků pro firmy a instituce. Překladatel ${CA} nabídne expresní i standardní překlad s garancí kvality.`, picturePath: null, active: true },
  { fullName: 'Bc. Červinka – tlumočník Hradec Králové', phone: '+420 603 113 456', email: null, serviceId: 'prekladatel', cityId: CITY, address: 'Ulrichovo náměstí 4567/41, Hradec Králové', description: `Bc. Červinka je překladatel a tlumočník pro angličtinu a němčinu v ${CN}. Překladatel ${CA} nabízí konsekutivní tlumočení na konferencích, jednáních a firemních akcích.`, picturePath: null, active: true },

  // ── GRAFIK ───────────────────────────────────────────────────────────────
  { fullName: 'Grafické studio Šimek Hradec Králové', phone: '+420 495 450 890', email: 'simek@grafika-hk.cz', serviceId: 'grafik', cityId: CITY, address: 'Velské náměstí 88, Hradec Králové', description: `Grafické studio Šimek nabízí komplexní grafické služby v ${CN} – loga, firemní identitu, tisk a webdesign. Grafik ${CA} zajistí profesionální vizuální komunikaci pro firmy v Královéhradeckém kraji.`, picturePath: null, active: true },
  { fullName: 'PixelArt Hradec Králové – grafický design', phone: '+420 728 334 780', email: 'info@pixelart-hk.cz', serviceId: 'grafik', cityId: CITY, address: 'Gočárova třída 4567/63, Hradec Králové', description: `PixelArt ${CA} je grafické studio specializující se na digitální design, tvorbu webů a reklamní kampaně. Grafik ${CA} nabídne kreativní řešení pro marketing a branding firem.`, picturePath: null, active: true },
  { fullName: 'Bc. Spurná – grafička Hradec Králové', phone: '+420 603 887 123', email: 'spurna.grafika@hk.cz', serviceId: 'grafik', cityId: CITY, address: 'Čechovo nábřeží 5678/73, Hradec Králové', description: `Bc. Spurná je freelance grafička v ${CN} nabízející návrhy letáků, plakátů a obalového designu. Grafik ${CA} pracuje pro agentury i přímé klienty s rychlými dodacími lhůtami.`, picturePath: null, active: true },
  { fullName: 'Studia Kreativa Hradec Králové', phone: '+420 495 556 890', email: 'studio@kreativa-hk.cz', serviceId: 'grafik', cityId: CITY, address: 'tř. SNP 4567/51, Hradec Králové', description: `Studia Kreativa je grafická agentura v ${CN} s kompletními kreativními službami – logo, web, video a sociální sítě. Grafik ${CA} pomůže firmám budovat silnou vizuální značku a efektivní online prezentaci.`, picturePath: null, active: true },
];

async function main() {
  let count = 0;
  for (const p of profiles) {
    const created = await prisma.provider.create({ data: p });
    console.log(`✓ ${created.fullName}`);
    count++;
  }
  console.log(`\nDone. Added ${count} profiles.`);
}
main().catch(console.error).finally(() => prisma.$disconnect());
