import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();
const CITY = 'olomouc';

const profiles = [
  // ── ELEKTRIKÁŘ ───────────────────────────────────────────────────────────
  { fullName: 'Elektroinstalace Pospíšil Olomouc', phone: '+420 585 221 334', email: 'pospisil@elektro-olomouc.cz', serviceId: 'elektrikar', cityId: CITY, address: 'Třída Svobody 1122/18, Olomouc', description: 'Elektroinstalace Pospíšil je zkušený elektrikář v Olomouci nabízející kompletní elektroinstalace, revize a opravy pro domácnosti i firmy. Elektrikář Olomouc zajistí rychlý výjezd a profesionální práce po celém Olomouckém kraji.', picturePath: null, active: true },
  { fullName: 'Elektro Kovář Olomouc', phone: '+420 587 334 560', email: 'kovar@elektro-olmc.cz', serviceId: 'elektrikar', cityId: CITY, address: 'Rooseveltova 2345/29, Olomouc', description: 'Elektro Kovář je elektrikář v Olomouci s 20 lety zkušeností v oblasti elektroinstalací bytů, domů a průmyslových objektů. Elektrikář Olomouc provádí montáž rozvaděčů, hromosvodů a fotovoltaiky.', picturePath: null, active: true },
  { fullName: 'Elektroslužby Horáč Olomouc', phone: '+420 603 441 780', email: null, serviceId: 'elektrikar', cityId: CITY, address: 'Ostružnická 1234/14, Olomouc', description: 'Pavel Horáč je certifikovaný elektrikář v Olomouci provádějící revize elektroinstalací, montáž inteligentních domů a opravy závad. Elektrikář Olomouc nabídne rychlý servis a profesionální přístup.', picturePath: null, active: true },
  { fullName: 'Elektrikář Blažek Olomouc', phone: '+420 728 234 902', email: 'blazek@elektro-olm.cz', serviceId: 'elektrikar', cityId: CITY, address: 'Pekařská 3456/38, Olomouc', description: 'Martin Blažek je elektrikář Olomouc provádějící elektroinstalace nových staveb i rekonstrukcí. Nabízí montáž osvětlení, zásuvek a výměnu pojistkových skříní v Olomouci a Olomouckém kraji.', picturePath: null, active: true },

  // ── INSTALATÉR ───────────────────────────────────────────────────────────
  { fullName: 'Instalatér Krejčí Olomouc', phone: '+420 585 100 234', email: 'krejci@instal-olomouc.cz', serviceId: 'instalater', cityId: CITY, address: 'Kosinova 2234/27, Olomouc', description: 'Instalatér Krejčí nabízí kompletní instalatérské práce v Olomouci – opravy vodovodů, výměnu bojlerů a instalaci koupelen. Instalatér Olomouc zajistí rychlý výjezd a kvalitní práce.', picturePath: null, active: true },
  { fullName: 'Vodo-Topo Šimánek Olomouc', phone: '+420 603 441 870', email: 'simanek@vodotopo-olm.cz', serviceId: 'instalater', cityId: CITY, address: 'Havlíčkova 3456/43, Olomouc', description: 'Vodo-Topo Šimánek je instalatér a topenář v Olomouci zaměřený na montáž plynových kotlů, radiátorů a podlahového vytápění. Instalatér Olomouc provádí kompletní rekonstrukce koupelen.', picturePath: null, active: true },
  { fullName: 'Instalatérství Procházka Olomouc', phone: '+420 728 337 123', email: null, serviceId: 'instalater', cityId: CITY, address: 'Holická 4567/54, Olomouc', description: 'Instalatérství Procházka nabízí veškeré instalatérské a topenářské práce v Olomouci. Instalatér Olomouc se specializuje na opravy úniků vody a instalaci sanitárního vybavení.', picturePath: null, active: true },
  { fullName: 'Jiří Malý – instalatér Olomouc', phone: '+420 587 389 234', email: 'maly@instal-olm.cz', serviceId: 'instalater', cityId: CITY, address: 'Krapkova 5678/67, Olomouc', description: 'Jiří Malý je instalatér Olomouc s 14 lety praxe v opravách a rekonstrukcích vodovodního a topenářského rozvodu. Instalatér v Olomouci nabídne pohotovostní servis 24/7.', picturePath: null, active: true },

  // ── MALÍŘ ────────────────────────────────────────────────────────────────
  { fullName: 'Malíř Veselý Olomouc', phone: '+420 585 228 456', email: 'vesely@malir-olomouc.cz', serviceId: 'malir', cityId: CITY, address: 'Třída Svobody 2345/35, Olomouc', description: 'Malíř Veselý nabízí profesionální malování pokojů, bytů a kanceláří v Olomouci a okolí. Malíř Olomouc zajistí přípravu povrchů, stěrkování a výsledný nátěr dle přání zákazníka.', picturePath: null, active: true },
  { fullName: 'Malířství Horáč Olomouc', phone: '+420 603 774 340', email: null, serviceId: 'malir', cityId: CITY, address: 'Rooseveltova 3456/44, Olomouc', description: 'Malířství Horáč provádí malování a lakýrnické práce pro domácnosti i firmy v Olomouci. Malíř Olomouc nabízí nátěry fasád, dekorativní techniky a výmalbu novostaveb v Olomouckém kraji.', picturePath: null, active: true },
  { fullName: 'Pavel Kříž – malíř Olomouc', phone: '+420 728 441 789', email: 'kriz@malir-olm.cz', serviceId: 'malir', cityId: CITY, address: 'Ostružnická 2345/23, Olomouc', description: 'Pavel Kříž je zkušený malíř pokojů v Olomouci s precizním přístupem k malování bytů, domů a průmyslových prostor. Malíř Olomouc provádí nátěry na klíč včetně přípravy a nákupu materiálu.', picturePath: null, active: true },
  { fullName: 'Malíř Blažej Olomouc', phone: '+420 602 554 123', email: 'blazej@malir-olm.cz', serviceId: 'malir', cityId: CITY, address: 'Pekařská 4567/57, Olomouc', description: 'Tomáš Blažej je malíř a lakýrník v Olomouci nabízející veškeré malířské a lakýrnické práce. Malíř Olomouc se specializuje na nátěry kovových konstrukcí, fasád a interiérů bytů.', picturePath: null, active: true },

  // ── TESAŘ ────────────────────────────────────────────────────────────────
  { fullName: 'Tesařství Macháč Olomouc', phone: '+420 585 441 780', email: 'machac@tesar-olomouc.cz', serviceId: 'tesar', cityId: CITY, address: 'Kosinova 3456/41, Olomouc', description: 'Tesařství Macháč provádí výstavbu a rekonstrukci krovů, střech a dřevěných konstrukcí v Olomouci. Tesař Olomouc realizuje pergoly, přístřešky a dřevěné zahradní stavby.', picturePath: null, active: true },
  { fullName: 'Krovy Šimánek Olomouc', phone: '+420 603 221 456', email: null, serviceId: 'tesar', cityId: CITY, address: 'Havlíčkova 4567/56, Olomouc', description: 'Krovy Šimánek je tesař v Olomouci specializující se na výstavbu nových krovů a rekonstrukce střešních konstrukcí. Tesař Olomouc realizuje dřevostavby a střešní práce pro rodinné domy.', picturePath: null, active: true },
  { fullName: 'Tesař Vávra Olomouc', phone: '+420 728 234 780', email: 'vavra@tesarolm.cz', serviceId: 'tesar', cityId: CITY, address: 'Holická 5678/71, Olomouc', description: 'Josef Vávra je zkušený tesař v Olomouci provádějící veškeré tesařské práce od krovů po dřevěné terasy a altány. Tesař Olomouc nabízí montáž schodišť a zahradních přístřešků.', picturePath: null, active: true },
  { fullName: 'Dřevostavby Kopecký Olomouc', phone: '+420 587 667 890', email: 'kopecky@drevostavby-olm.cz', serviceId: 'tesar', cityId: CITY, address: 'Krapkova 6789/84, Olomouc', description: 'Dřevostavby Kopecký je tesař a dřevostavitel v Olomouci nabízející výstavbu dřevěných domků a krovů. Tesař Olomouc realizuje zakázkové tesařské práce v celém Olomouckém kraji.', picturePath: null, active: true },

  // ── TRUHLÁŘ ──────────────────────────────────────────────────────────────
  { fullName: 'Truhlářství Blažek Olomouc', phone: '+420 585 335 660', email: 'blazek@truhlar-olomouc.cz', serviceId: 'truhlar', cityId: CITY, address: 'Třída Svobody 3456/49, Olomouc', description: 'Truhlářství Blažek vyrábí nábytek, dveře a kuchyně na zakázku v Olomouci. Truhlář Olomouc se specializuje na výrobu kuchyňských linek, skříní a dřevěných interiérů.', picturePath: null, active: true },
  { fullName: 'Zakázkové truhlářství Váchal Olomouc', phone: '+420 602 334 560', email: null, serviceId: 'truhlar', cityId: CITY, address: 'Rooseveltova 4567/55, Olomouc', description: 'Zakázkové truhlářství Váchal vyrábí nábytek a dřevěné interiéry na míru v Olomouci. Truhlář Olomouc nabízí výrobu postelí, stolů a zabudovaných systémů pro domy i byty.', picturePath: null, active: true },
  { fullName: 'Truhlář Janák Olomouc', phone: '+420 728 441 560', email: 'janak@truhlarnolm.cz', serviceId: 'truhlar', cityId: CITY, address: 'Ostružnická 3456/37, Olomouc', description: 'Tomáš Janák je truhlář Olomouc s 16 lety zkušeností ve výrobě dřevěného nábytku a vestavěných skříní. Truhlářství v Olomouci realizuje dřevěné interiéry na klíč dle individuálního návrhu.', picturePath: null, active: true },
  { fullName: 'Nábytek Pokorný – truhlář Olomouc', phone: '+420 585 678 345', email: 'pokorny@nabytek-olm.cz', serviceId: 'truhlar', cityId: CITY, address: 'Pekařská 5678/71, Olomouc', description: 'Dílna Pokorný je truhlář a výrobce nábytku v Olomouci nabízející zakázkovou výrobu dřevěných prvků pro byty, domy a kanceláře. Truhlář Olomouc zajistí výrobu a montáž nábytku přímo u zákazníka.', picturePath: null, active: true },

  // ── ZEDNÍK ───────────────────────────────────────────────────────────────
  { fullName: 'Zednictví Houšek Olomouc', phone: '+420 585 229 340', email: 'housek@zednik-olomouc.cz', serviceId: 'zednik', cityId: CITY, address: 'Kosinova 4567/55, Olomouc', description: 'Zednictví Houšek nabízí kompletní zednické práce v Olomouci – příčky, omítky, obklady a rekonstrukce bytů. Zedník Olomouc realizuje stavební práce pro rodinné domy i bytové jednotky.', picturePath: null, active: true },
  { fullName: 'Stavební práce Macháč Olomouc', phone: '+420 603 456 780', email: null, serviceId: 'zednik', cityId: CITY, address: 'Havlíčkova 5678/69, Olomouc', description: 'Stavební práce Macháč provádí zednické práce, obklady a dlažby v Olomouci a okolí. Zedník Olomouc zajistí renovaci koupelen, pokládku dlažby a veškeré rekonstrukční práce.', picturePath: null, active: true },
  { fullName: 'Zedník Krejčí Olomouc', phone: '+420 728 223 456', email: 'krejci@zednik-olm.cz', serviceId: 'zednik', cityId: CITY, address: 'Holická 6789/87, Olomouc', description: 'Ladislav Krejčí je zkušený zedník v Olomouci provádějící omítky, zdění příček a rekonstrukce bytů. Zedník Olomouc nabízí kompletní stavební práce od základů po finální úpravy povrchů.', picturePath: null, active: true },
  { fullName: 'Stavební firma Veselý Olomouc', phone: '+420 587 112 890', email: 'vesely@stav-olm.cz', serviceId: 'zednik', cityId: CITY, address: 'Krapkova 7890/101, Olomouc', description: 'Stavební firma Veselý nabízí kompletní zednické a stavební práce v Olomouci. Zedník Olomouc realizuje zdění, betonáže, stropy a příčky pro soukromé i firemní zákazníky.', picturePath: null, active: true },

  // ── KLEMPÍŘ ──────────────────────────────────────────────────────────────
  { fullName: 'Klempířství Šimánek Olomouc', phone: '+420 585 120 780', email: 'simanek@klempir-olomouc.cz', serviceId: 'klempir', cityId: CITY, address: 'Třída Svobody 4567/61, Olomouc', description: 'Klempířství Šimánek nabízí kompletní klempířské a pokrývačské práce v Olomouci – oplechování střech, parapety a okapy. Klempíř Olomouc provádí montáž a opravy střech pro rodinné domy.', picturePath: null, active: true },
  { fullName: 'Střechy Blažek Olomouc', phone: '+420 603 667 560', email: null, serviceId: 'klempir', cityId: CITY, address: 'Rooseveltova 5678/71, Olomouc', description: 'Střechy Blažek je klempíř a pokrývač v Olomouci se zaměřením na pokládku střešní krytiny a klempířské práce. Klempíř Olomouc poskytuje záruky na veškeré provedené práce.', picturePath: null, active: true },
  { fullName: 'Klempíř Vávra Olomouc', phone: '+420 728 890 234', email: 'vavra@klempir-olm.cz', serviceId: 'klempir', cityId: CITY, address: 'Ostružnická 4567/47, Olomouc', description: 'Karel Vávra je klempíř Olomouc s 22 lety zkušeností s montáží okapů, oplechováním komínů a opravami střech. Klempíř v Olomouci zajistí kvalitní klempířské práce za přijatelné ceny.', picturePath: null, active: true },
  { fullName: 'Klempíř Kopec Olomouc', phone: '+420 585 334 890', email: 'kopec@klempir-olm.cz', serviceId: 'klempir', cityId: CITY, address: 'Pekařská 6789/85, Olomouc', description: 'Roman Kopec je klempíř v Olomouci nabízející opravy střech, oplechování říms a montáž venkovních žaluzií. Klempíř Olomouc pracuje s pozinkovaným, titanzinkovým i měděným plechem.', picturePath: null, active: true },

  // ── AUTOSERVIS ───────────────────────────────────────────────────────────
  { fullName: 'Autoservis Pospíšil Olomouc', phone: '+420 585 252 900', email: 'info@autoservis-pospisil.cz', serviceId: 'autoservis', cityId: CITY, address: 'Litovelská 1234/15, Olomouc', description: 'Autoservis Pospíšil nabízí komplexní opravy a servis vozidel všech značek v Olomouci. Autoservis Olomouc zajistí pravidelné prohlídky, výměnu oleje, brzd a diagnostiku pro zákazníky z Olomouckého kraje.', picturePath: null, active: true },
  { fullName: 'Car Service Olomouc – Macháč', phone: '+420 603 334 780', email: 'machac@carservice-olm.cz', serviceId: 'autoservis', cityId: CITY, address: 'Holická 2345/29, Olomouc', description: 'Car Service Macháč je autoservis v Olomouci zaměřený na opravy motorů, převodovek a klimatizací. Autoservis Olomouc provádí STK přípravu a komplexní servis osobních i užitkových vozidel.', picturePath: null, active: true },
  { fullName: 'Auto Horáč – servis Olomouc', phone: '+420 585 339 127', email: null, serviceId: 'autoservis', cityId: CITY, address: 'Krapkova 3456/43, Olomouc', description: 'Auto Horáč je rodinný autoservis v Olomouci s tradicí přes 22 let, specializující se na osobní vozy a dodávky. Autoservis Olomouc nabízí pneuservis, geometrii náprav a karosářské práce.', picturePath: null, active: true },
  { fullName: 'Autoservis Šimánek Olomouc', phone: '+420 728 667 234', email: 'simanek@autoolm.cz', serviceId: 'autoservis', cityId: CITY, address: 'Litovelská 4567/57, Olomouc', description: 'Autoservis Šimánek je certifikovaný servis v Olomouci pro osobní i užitková vozidla. Autoservis Olomouc zajistí diagnostiku závad, opravy elektroniky a pravidelnou údržbu vozidel.', picturePath: null, active: true },

  // ── IT TECHNIK ───────────────────────────────────────────────────────────
  { fullName: 'PC Servis Olomouc – Horáč', phone: '+420 585 241 801', email: 'horac@pc-olomouc.cz', serviceId: 'it-technik', cityId: CITY, address: 'Třída Svobody 1234/20, Olomouc', description: 'PC Servis Horáč je IT technik v Olomouci nabízející opravy počítačů, notebooků a tiskáren pro firmy i domácnosti. IT technik Olomouc zajistí instalaci systémů, obnovu dat a správu sítí.', picturePath: null, active: true },
  { fullName: 'IT pohotovost Olomouc – Veselý', phone: '+420 603 778 560', email: 'vesely@it-olomouc.cz', serviceId: 'it-technik', cityId: CITY, address: 'Rooseveltova 2345/31, Olomouc', description: 'IT pohotovost Veselý je zkušený IT technik Olomouc s 15 lety praxe v opravách PC a správě IT infrastruktury. Nabízí nonstop IT pohotovost a vzdálenou správu počítačů v Olomouci.', picturePath: null, active: true },
  { fullName: 'Comtech Olomouc', phone: '+420 585 100 700', email: 'info@comtech-olomouc.cz', serviceId: 'it-technik', cityId: CITY, address: 'Ostružnická 3456/39, Olomouc', description: 'Comtech je profesionální IT servis v Olomouci zaměřený na opravy počítačů, datové zálohy a kybernetickou bezpečnost. IT technik Olomouc poskytuje komplexní ICT podporu pro firmy.', picturePath: null, active: true },
  { fullName: 'Počítačový servis Janák Olomouc', phone: '+420 728 445 890', email: null, serviceId: 'it-technik', cityId: CITY, address: 'Pekařská 4567/59, Olomouc', description: 'Počítačový servis Janák nabízí opravy a upgrade PC a notebooků v Olomouci za dostupné ceny. IT technik Olomouc zajistí reinstalaci systémů, odstranění virů a nastavení Wi-Fi sítí.', picturePath: null, active: true },

  // ── FOTOGRAF ─────────────────────────────────────────────────────────────
  { fullName: 'Foto Studio Horáčková Olomouc', phone: '+420 603 447 882', email: 'info@fotohoracova.cz', serviceId: 'fotograf', cityId: CITY, address: 'Kosinova 5678/71, Olomouc', description: 'Foto Studio Horáčková je profesionální fotografka v Olomouci se zaměřením na rodinné, těhotenské a newborn fotografie. Fotograf Olomouc nabízí moderní fotografické studio a venkovní focení.', picturePath: null, active: true },
  { fullName: 'Reportážní fotograf Šimánek Olomouc', phone: '+420 585 108 540', email: 'simanek@foto-olm.cz', serviceId: 'fotograf', cityId: CITY, address: 'Havlíčkova 6789/87, Olomouc', description: 'Michal Šimánek je reportážní a reklamní fotograf v Olomouci s 14 lety zkušeností. Fotograf Olomouc nabízí firemní fotografii, produktové focení a reportáže z akcí v Olomouckém kraji.', picturePath: null, active: true },
  { fullName: 'Svatební fotograf Kovář Olomouc', phone: '+420 728 112 901', email: 'kovar@svatebnifoto-olm.cz', serviceId: 'fotograf', cityId: CITY, address: 'Holická 7890/101, Olomouc', description: 'Tomáš Kovář je svatební fotograf v Olomouci specializující se na svatební reportáže a portrétní fotografii. Fotograf Olomouc zachytí každý vzácný okamžik vašeho dne s přirozeným přístupem.', picturePath: null, active: true },
  { fullName: 'FotoArt Olomouc – Marková', phone: '+420 585 334 120', email: 'markova@fotoart-olm.cz', serviceId: 'fotograf', cityId: CITY, address: 'Krapkova 8901/115, Olomouc', description: 'FotoArt Marková je fotografka v Olomouci nabízející portréty, rodinnou a těhotenskou fotografii ve studiu i exteriéru. Fotograf Olomouc klade důraz na přirozené zachycení emocí a osobitý styl.', picturePath: null, active: true },

  // ── UČITEL / LEKTOR ──────────────────────────────────────────────────────
  { fullName: 'Jazyková škola Cloverleaf Olomouc', phone: '+420 585 220 712', email: 'olomouc@cloverleaf.cz', serviceId: 'ucitel', cityId: CITY, address: 'Třída Svobody 1345/22, Olomouc', description: 'Jazyková škola Cloverleaf nabízí kurzy angličtiny, němčiny a španělštiny v Olomouci pro děti i dospělé. Zkušení lektoři v Olomouci zajistí efektivní výuku jazyků a přípravu na mezinárodní certifikáty.', picturePath: null, active: true },
  { fullName: 'Jazykové centrum Olomouc', phone: '+420 585 220 780', email: 'info@jazykove-centrum-olm.cz', serviceId: 'ucitel', cityId: CITY, address: 'Rooseveltova 1345/23, Olomouc', description: 'Jazykové centrum Olomouc nabízí firemní i individuální kurzy angličtiny, němčiny a francouzštiny. Lektor Olomouc zajistí výuku na míru přímo ve firmě nebo v moderních učebnách.', picturePath: null, active: true },
  { fullName: 'Doučování Olomouc – Mgr. Blažková', phone: '+420 728 441 560', email: null, serviceId: 'ucitel', cityId: CITY, address: 'Ostružnická 2345/25, Olomouc', description: 'Mgr. Blažková je zkušená lektorka nabízející doučování matematiky, angličtiny a biologie v Olomouci. Lektor Olomouc zajistí individuální přístup k žákům základních a středních škol.', picturePath: null, active: true },
  { fullName: 'Bc. Vávra – lektor angličtiny Olomouc', phone: '+420 603 334 780', email: 'vavra@lektor-olm.cz', serviceId: 'ucitel', cityId: CITY, address: 'Pekařská 3456/43, Olomouc', description: 'Bc. Vávra je certifikovaný lektor angličtiny v Olomouci s 9 lety praxe ve výuce dospělých a firemní klientely. Lektor Olomouc nabízí individuální i skupinové kurzy na všech úrovních znalostí.', picturePath: null, active: true },

  // ── RESTAURACE ───────────────────────────────────────────────────────────
  { fullName: 'Restaurace Caesar Olomouc', phone: '+420 585 229 287', email: 'info@caesar-olomouc.cz', serviceId: 'restaurace', cityId: CITY, address: 'Horní náměstí 23, Olomouc', description: 'Restaurace Caesar je tradiční česká restaurace v centru Olomouce nabízející českou a moravskou kuchyni s čerstvými surovinami. Restaurace v Olomouci je oblíbená mezi místními i turisty pro příjemnou atmosféru.', picturePath: null, active: true },
  { fullName: 'Moravská restaurace U Radnice Olomouc', phone: '+420 585 220 522', email: 'uradnice@restaurace-olm.cz', serviceId: 'restaurace', cityId: CITY, address: 'Dolní náměstí 14, Olomouc', description: 'Moravská restaurace U Radnice nabízí autentickou moravskou kuchyni v historickém centru Olomouce. Restaurace Olomouc se specializuje na svíčkovou, pečené vepřové a tradiční moravské speciality.', picturePath: null, active: true },
  { fullName: 'Restaurace Hanácký dvůr Olomouc', phone: '+420 603 334 456', email: null, serviceId: 'restaurace', cityId: CITY, address: 'Třída Svobody 3456/47, Olomouc', description: 'Restaurace Hanácký dvůr je oblíbená restaurace v Olomouci nabízející denní menu a hanáckou kuchyni za dostupné ceny. Restaurace Olomouc láká místní i turisty na domácí jídla z čerstvých surovin.', picturePath: null, active: true },
  { fullName: 'Pivnice U Kováře Olomouc', phone: '+420 585 345 678', email: 'info@pivnice-olomouc.cz', serviceId: 'restaurace', cityId: CITY, address: 'Kosinova 6789/87, Olomouc', description: 'Pivnice U Kováře je tradiční hospoda v Olomouci s autentickým prostředím a poctivou českou kuchyní. Restaurace v Olomouci nabízí guláš, řízek a regionální speciality s čepovaným pivem.', picturePath: null, active: true },

  // ── ZUBAŘ ────────────────────────────────────────────────────────────────
  { fullName: 'MDDr. Horáčová – zubní ordinace Olomouc', phone: '+420 585 110 890', email: 'horacova@zubar-olomouc.cz', serviceId: 'zubar', cityId: CITY, address: 'Třída Svobody 2234/32, Olomouc', description: 'MDDr. Horáčová provozuje zubní ordinaci v Olomouci nabízející kompletní stomatologickou péči pro děti i dospělé. Zubař Olomouc zajistí ošetření zubů, bělení a ortodontické poradenství.', picturePath: null, active: true },
  { fullName: 'Stomatologie Blažek Olomouc', phone: '+420 585 224 177', email: 'blazek@stom-olomouc.cz', serviceId: 'zubar', cityId: CITY, address: 'Rooseveltova 3456/43, Olomouc', description: 'Stomatologie Blažek je zubní ordinace v Olomouci zaměřená na estetickou stomatologii, implantáty a dentální hygienu. Zubař Olomouc přijímá nové pacienty a nabízí individuální přístup.', picturePath: null, active: true },
  { fullName: 'Zubní ordinace Vávra Olomouc', phone: '+420 585 128 901', email: null, serviceId: 'zubar', cityId: CITY, address: 'Ostružnická 4567/49, Olomouc', description: 'MUDr. Vávra provozuje zubní ordinaci v Olomouci s komplexními stomatologickými službami včetně chirurgie a protetiky. Zubař Olomouc zajistí odbornou péči o chrup v klidném prostředí.', picturePath: null, active: true },
  { fullName: 'Dentální centrum Olomouc', phone: '+420 585 901 234', email: 'info@dental-olomouc.cz', serviceId: 'zubar', cityId: CITY, address: 'Pekařská 5678/73, Olomouc', description: 'Dentální centrum Olomouc je moderní zubní klinika nabízející komplexní péči od prevence po implantologii. Zubař Olomouc nabídne bezbolestné ošetření, ortodoncii a dentální hygienu pro celou rodinu.', picturePath: null, active: true },

  // ── LÉKAŘ ────────────────────────────────────────────────────────────────
  { fullName: 'MUDr. Blažková – praktická lékařka Olomouc', phone: '+420 585 110 455', email: 'blazkova@lekar-olomouc.cz', serviceId: 'lekar', cityId: CITY, address: 'Kosinova 2234/29, Olomouc', description: 'MUDr. Blažková je praktická lékařka v Olomouci s komplexní zdravotní péčí pro dospělé. Lékař Olomouc přijímá nové pacienty a zajistí pravidelné prohlídky, očkování a vydávání receptů.', picturePath: null, active: true },
  { fullName: 'MUDr. Horáč – internista Olomouc', phone: '+420 585 261 233', email: 'horac@interna-olomouc.cz', serviceId: 'lekar', cityId: CITY, address: 'Havlíčkova 3345/43, Olomouc', description: 'MUDr. Horáč je internista v Olomouci specializující se na diagnostiku a léčbu interních onemocnění. Lékař Olomouc nabídne odborné vyšetření a individuální léčebný plán pro pacienty.', picturePath: null, active: true },
  { fullName: 'Poliklinika Olomouc – zdravotní centrum', phone: '+420 585 103 111', email: 'info@poliklinika-olm.cz', serviceId: 'lekar', cityId: CITY, address: 'I. P. Pavlova 6, Olomouc', description: 'Poliklinika Olomouc je zdravotní centrum s širokým spektrem praktických a odborných lékařů. Lékař Olomouc nabízí komplexní zdravotní péči pro obyvatele Olomouce a Olomouckého kraje.', picturePath: null, active: true },
  { fullName: 'MUDr. Janáková – pediatr Olomouc', phone: '+420 585 118 766', email: null, serviceId: 'lekar', cityId: CITY, address: 'Holická 4567/57, Olomouc', description: 'MUDr. Janáková je dětská lékařka – pediatr v Olomouci pečující o zdravý vývoj dětí od narození. Lékař Olomouc poskytuje preventivní prohlídky, očkování a léčbu dětských nemocí.', picturePath: null, active: true },

  // ── PSYCHOLOG ─────────────────────────────────────────────────────────────
  { fullName: 'PhDr. Horáčová – psycholog Olomouc', phone: '+420 585 243 210', email: 'horacova@psycholog-olomouc.cz', serviceId: 'psycholog', cityId: CITY, address: 'Třída Svobody 3456/51, Olomouc', description: 'PhDr. Horáčová je psycholog v Olomouci nabízející individuální psychoterapii, párové poradenství a krizovou intervenci. Psycholog Olomouc pomáhá klientům zvládat úzkosti, deprese a životní krize.', picturePath: null, active: true },
  { fullName: 'Mgr. Blažek – psychoterapeut Olomouc', phone: '+420 603 234 341', email: 'blazek@terapie-olm.cz', serviceId: 'psycholog', cityId: CITY, address: 'Rooseveltova 4456/57, Olomouc', description: 'Mgr. Blažek je psychoterapeut v Olomouci s výcvikem v kognitivně-behaviorální terapii. Psycholog Olomouc nabízí individuální, párovou a skupinovou terapii pro dospělé i adolescenty.', picturePath: null, active: true },
  { fullName: 'Centrum psychologické pomoci Olomouc', phone: '+420 585 989 123', email: 'info@cpp-olomouc.cz', serviceId: 'psycholog', cityId: CITY, address: 'Ostružnická 5678/63, Olomouc', description: 'Centrum psychologické pomoci Olomouc je poradenské centrum s týmem zkušených psychologů. Psycholog Olomouc nabízí diagnostiku, poradenství a terapii pro děti, dospělé i rodiny.', picturePath: null, active: true },
  { fullName: 'Mgr. Váchalová – terapeutka Olomouc', phone: '+420 728 345 123', email: null, serviceId: 'psycholog', cityId: CITY, address: 'Pekařská 6789/87, Olomouc', description: 'Mgr. Váchalová je psycholožka a terapeutka v Olomouci specializující se na práci s traumatem a úzkostí. Psycholog Olomouc pracuje s dospělými i dětmi metodou EMDR a systemické terapie.', picturePath: null, active: true },

  // ── PRÁVNÍK ──────────────────────────────────────────────────────────────
  { fullName: 'JUDr. Šimánek – advokát Olomouc', phone: '+420 585 122 891', email: 'simanek@advokatOlm.cz', serviceId: 'pravnik', cityId: CITY, address: 'Horní náměstí 36, Olomouc', description: 'JUDr. Šimánek je advokát v Olomouci zaměřený na občanské, obchodní a rodinné právo. Právník Olomouc nabízí právní poradenství, sepis smluv a zastupování klientů před soudy v Olomouckém kraji.', picturePath: null, active: true },
  { fullName: 'Advokátní kancelář Horáček Olomouc', phone: '+420 585 310 067', email: 'horacek@ak-olomouc.cz', serviceId: 'pravnik', cityId: CITY, address: 'Třída Svobody 1122/16, Olomouc', description: 'Advokátní kancelář Horáček je právní firma v Olomouci specializující se na pracovní právo, nemovitosti a obchodní spory. Právník Olomouc zajistí komplexní právní zastoupení a poradenství.', picturePath: null, active: true },
  { fullName: 'JUDr. Blažek – notář Olomouc', phone: '+420 585 228 445', email: 'blazek@notar-olomouc.cz', serviceId: 'pravnik', cityId: CITY, address: 'Rooseveltova 1234/19, Olomouc', description: 'JUDr. Blažek je notář a právník v Olomouci zajišťující sepisování závětí, kupních smluv a ověřování podpisů. Právník Olomouc poskytuje notářské a právní služby pro fyzické i právnické osoby.', picturePath: null, active: true },
  { fullName: 'Mgr. Janáková – rodinné právo Olomouc', phone: '+420 728 220 789', email: null, serviceId: 'pravnik', cityId: CITY, address: 'Ostružnická 2345/27, Olomouc', description: 'Mgr. Janáková je právnička v Olomouci specializující se na rodinné právo, rozvody a opatrovnická řízení. Právník Olomouc nabídne empatické a profesionální zastupování v soudních sporech.', picturePath: null, active: true },

  // ── ÚČETNÍ ───────────────────────────────────────────────────────────────
  { fullName: 'Účetní poradenství Váchalová Olomouc', phone: '+420 585 243 210', email: 'vachalova@ucetni-olomouc.cz', serviceId: 'ucetni', cityId: CITY, address: 'Kosinova 3456/43, Olomouc', description: 'Účetní poradenství Váchalová nabízí vedení účetnictví, daňové přiznání a mzdovou agendu pro firmy v Olomouci. Účetní Olomouc poskytuje kompletní ekonomické poradenství pro OSVČ i právnické osoby.', picturePath: null, active: true },
  { fullName: 'ECO Consulting Olomouc', phone: '+420 585 421 800', email: 'info@eco-consulting-olm.cz', serviceId: 'ucetni', cityId: CITY, address: 'Havlíčkova 4567/57, Olomouc', description: 'ECO Consulting je účetní firma v Olomouci specializující se na podvojné účetnictví, DPH a daňovou optimalizaci. Účetní Olomouc zajistí přesné zpracování daňových přiznání a roční závěrky.', picturePath: null, active: true },
  { fullName: 'Bc. Blažková – účetní a mzdy Olomouc', phone: '+420 728 334 456', email: 'blazkova@ucetni-mzdy-olm.cz', serviceId: 'ucetni', cityId: CITY, address: 'Holická 5678/73, Olomouc', description: 'Bc. Blažková je účetní v Olomouci se specializací na zpracování mezd, daňové přiznání a vedení daňové evidence. Účetní Olomouc nabízí přesné a spolehlivé zpracování dokladů pro malé a střední firmy.', picturePath: null, active: true },
  { fullName: 'AUDIT OLOMOUC – účetní kancelář', phone: '+420 603 457 890', email: 'audit@uc-olomouc.cz', serviceId: 'ucetni', cityId: CITY, address: 'Krapkova 6789/85, Olomouc', description: 'AUDIT OLOMOUC je účetní kancelář v Olomouci nabízející komplexní ekonomické a daňové poradenství pro podnikatele. Účetní Olomouc zpracuje daňová přiznání, roční závěrky i reporty pro zahraniční firmy.', picturePath: null, active: true },

  // ── KADEŘNÍK ─────────────────────────────────────────────────────────────
  { fullName: 'Kadeřnictví Horáčová Olomouc', phone: '+420 585 111 345', email: null, serviceId: 'kadernik', cityId: CITY, address: 'Třída Svobody 2345/37, Olomouc', description: 'Kadeřnictví Horáčová nabízí střihy, barvení a styling vlasů pro ženy i muže v Olomouci. Kadeřník Olomouc pracuje s prémiovou kosmetikou a zajistí individuální poradenství o péči o vlasy.', picturePath: null, active: true },
  { fullName: 'Salon Karolína – kadeřnictví Olomouc', phone: '+420 585 258 900', email: 'karolina@salon-olomouc.cz', serviceId: 'kadernik', cityId: CITY, address: 'Rooseveltova 2345/33, Olomouc', description: 'Salon Karolína je moderní kadeřnický salon v Olomouci se zkušenými stylisty. Kadeřník Olomouc nabízí barvení, melír, keratin a svatební účesy v příjemném salonu.', picturePath: null, active: true },
  { fullName: 'Kadeřnictví Blažková Olomouc', phone: '+420 728 445 789', email: null, serviceId: 'kadernik', cityId: CITY, address: 'Ostružnická 3456/39, Olomouc', description: 'Kadeřnictví Blažková je rodinný salon v Olomouci nabízející kompletní kadeřnické služby – střihy, barvení a rekonstrukce vlasů. Kadeřník Olomouc zajistí péči o vlasy v přátelské atmosféře.', picturePath: null, active: true },
  { fullName: 'Studio Moda – kadeřnictví Olomouc', phone: '+420 585 235 678', email: 'moda@kadernictvi-olomouc.cz', serviceId: 'kadernik', cityId: CITY, address: 'Pekařská 4567/57, Olomouc', description: 'Studio Moda je prémiové kadeřnické studio v Olomouci zaměřené na moderní trendy v barvení a stylingu vlasů. Kadeřník Olomouc nabízí konzultace, střihy a speciální ošetření vlasů.', picturePath: null, active: true },

  // ── ARCHITEKT ────────────────────────────────────────────────────────────
  { fullName: 'Ing. arch. Horáček – architekt Olomouc', phone: '+420 585 422 780', email: 'horacek@architektolm.cz', serviceId: 'architekt', cityId: CITY, address: 'Horní náměstí 44, Olomouc', description: 'Ing. arch. Horáček je architekt v Olomouci nabízející projektování rodinných domů a bytových rekonstrukcí. Architekt Olomouc navrhuje funkční a estetická řešení s důrazem na nízkoenergetické standardy.', picturePath: null, active: true },
  { fullName: 'Ateliér MORAVA – architekti Olomouc', phone: '+420 585 534 122', email: 'info@atelierm.cz', serviceId: 'architekt', cityId: CITY, address: 'Třída Svobody 2345/36, Olomouc', description: 'Ateliér MORAVA je architektonické studio v Olomouci s portfoliem rezidenčních, komerčních a veřejných staveb. Architekt Olomouc nabídne kompletní projektové služby od studie po realizaci.', picturePath: null, active: true },
  { fullName: 'Ing. arch. Váchalová – interiéry Olomouc', phone: '+420 728 882 445', email: 'vachalova@interier-olm.cz', serviceId: 'architekt', cityId: CITY, address: 'Rooseveltova 3456/45, Olomouc', description: 'Ing. arch. Váchalová je architektka a interiérová designérka v Olomouci zaměřená na návrhy interiérů bytů a kanceláří. Architekt Olomouc navrhuje prostory s ohledem na funkčnost a přání klienta.', picturePath: null, active: true },
  { fullName: 'STUDIO HANA – architekti Olomouc', phone: '+420 585 620 110', email: 'hana@studio-hana.cz', serviceId: 'architekt', cityId: CITY, address: 'Ostružnická 4567/51, Olomouc', description: 'STUDIO HANA je architektonická kancelář v Olomouci realizující rodinné domy, rekonstrukce a urbanistické projekty. Architekt Olomouc zajistí projekt od konceptu přes povolení až po dozor na stavbě.', picturePath: null, active: true },

  // ── REALITNÍ MAKLÉŘ ──────────────────────────────────────────────────────
  { fullName: 'RE/MAX Olomouc – realitní kancelář', phone: '+420 585 244 555', email: 'remax@remax-olomouc.cz', serviceId: 'realitni-makler', cityId: CITY, address: 'Horní náměstí 55, Olomouc', description: 'RE/MAX Olomouc je realitní kancelář s týmem zkušených makléřů pro prodej a pronájem bytů a domů v Olomouci. Realitní makléř Olomouc zajistí odborné ocenění nemovitosti a efektivní marketing.', picturePath: null, active: true },
  { fullName: 'Realitní kancelář Blažek Olomouc', phone: '+420 585 310 700', email: 'blazek@rk-olomouc.cz', serviceId: 'realitni-makler', cityId: CITY, address: 'Třída Svobody 3456/49, Olomouc', description: 'Realitní kancelář Blažek je zavedená realitní firma v Olomouci s 14 lety zkušeností na trhu s nemovitostmi. Realitní makléř Olomouc pomůže s koupí, prodejem i pronájmem nemovitostí v Olomouckém kraji.', picturePath: null, active: true },
  { fullName: 'STING realitní Olomouc', phone: '+420 728 888 341', email: 'info@sting-reality-olm.cz', serviceId: 'realitni-makler', cityId: CITY, address: 'Rooseveltova 4567/57, Olomouc', description: 'STING realitní je dynamická realitní kancelář v Olomouci zaměřená na prodej bytů a domů. Realitní makléř Olomouc nabídne profesionální fotografii, 3D prohlídky a právní servis k nemovitostem.', picturePath: null, active: true },
  { fullName: 'Reality Kopřiva Olomouc', phone: '+420 603 003 789', email: null, serviceId: 'realitni-makler', cityId: CITY, address: 'Ostružnická 5678/65, Olomouc', description: 'Reality Kopřiva je realitní makléř v Olomouci specializující se na rezidenční nemovitosti. Makléř Olomouc nabídne individuální přístup a kompletní administrativní servis při prodeji i nákupu bytu.', picturePath: null, active: true },

  // ── ZAHRADNÍK ────────────────────────────────────────────────────────────
  { fullName: 'Zahradnictví Šimánek Olomouc', phone: '+420 728 334 780', email: 'simanek@zahradnictvi-olm.cz', serviceId: 'zahradnik', cityId: CITY, address: 'Litovelská 2345/28, Olomouc', description: 'Zahradnictví Šimánek nabízí kompletní zahradnické práce v Olomouci – sekání trávníků, výsadbu rostlin a zakládání zahrad. Zahradník Olomouc zajistí pravidelnou údržbu zahrady pro soukromníky i firmy.', picturePath: null, active: true },
  { fullName: 'Green Garden Olomouc', phone: '+420 585 456 234', email: 'info@greengarden-olm.cz', serviceId: 'zahradnik', cityId: CITY, address: 'Holická 3456/43, Olomouc', description: 'Green Garden je zahradní firma v Olomouci nabízející návrhy a realizaci zahrad a teras. Zahradník Olomouc provede kompletní terénní úpravy, automatické zavlažování a instalaci zahradních prvků.', picturePath: null, active: true },
  { fullName: 'Zahradní úpravy Horáč Olomouc', phone: '+420 728 441 780', email: null, serviceId: 'zahradnik', cityId: CITY, address: 'Krapkova 4567/59, Olomouc', description: 'Zahradní úpravy Horáč je zahradník v Olomouci zajišťující terénní úpravy, výsadbu stromů a sezónní péči o zahrady. Zahradník Olomouc nabídne osobní poradenství a realizaci zahradních projektů.', picturePath: null, active: true },
  { fullName: 'Arboristika Olomouc – Janák', phone: '+420 603 017 890', email: 'janak@arboristika-olm.cz', serviceId: 'zahradnik', cityId: CITY, address: 'Litovelská 5678/71, Olomouc', description: 'Arboristika Olomouc Janák nabízí profesionální péči o stromy, kácení a ošetřování dřevin v Olomouci. Zahradník Olomouc provede výškové práce, redukci korun a odborné posudky zdraví stromů.', picturePath: null, active: true },

  // ── ÚKLID ────────────────────────────────────────────────────────────────
  { fullName: 'Čistota Olomouc – úklidová firma', phone: '+420 585 890 234', email: 'info@cistota-olomouc.cz', serviceId: 'uklid', cityId: CITY, address: 'Třída Svobody 4567/63, Olomouc', description: 'Čistota Olomouc je profesionální úklidová firma nabízející pravidelný i jednorázový úklid bytů a kanceláří v Olomouci. Úklid Olomouc zajistí čisté prostředí s ekologickými čisticími prostředky.', picturePath: null, active: true },
  { fullName: 'CleanPro Olomouc', phone: '+420 603 778 901', email: 'cleanpro@uklid-olomouc.cz', serviceId: 'uklid', cityId: CITY, address: 'Rooseveltova 5678/73, Olomouc', description: 'CleanPro je úklidová společnost v Olomouci specializující se na úklid po rekonstrukci a generální úklid domácností. Úklid Olomouc nabídne rychlý nástup a záruky spokojenosti na veškeré práce.', picturePath: null, active: true },
  { fullName: 'Paní na úklid Olomouc – Horáčová', phone: '+420 728 456 789', email: null, serviceId: 'uklid', cityId: CITY, address: 'Holická 4567/59, Olomouc', description: 'Paní Horáčová nabízí pravidelný domácí úklid bytů a domů v Olomouci s osobním přístupem a spolehlivostí. Úklid Olomouc – domácí pomoc pro rodiny a seniory v Olomouci a přilehlém okolí.', picturePath: null, active: true },
  { fullName: 'TopClean Olomouc', phone: '+420 585 345 678', email: 'info@topclean-olomouc.cz', serviceId: 'uklid', cityId: CITY, address: 'Krapkova 5678/75, Olomouc', description: 'TopClean je úklidová firma v Olomouci s komplexní nabídkou čistění koberců, čalounění a mytí oken. Úklid Olomouc provádí profesionální dezinfekce a sanace bytů, kanceláří i průmyslových prostor.', picturePath: null, active: true },

  // ── STĚHOVACÍ FIRMA ──────────────────────────────────────────────────────
  { fullName: 'Stěhování Olomouc – Horáč Transport', phone: '+420 585 334 120', email: 'horac@stehovaniolm.cz', serviceId: 'stehovaci-firma', cityId: CITY, address: 'Litovelská 3456/43, Olomouc', description: 'Stěhování Olomouc Horáč Transport nabízí profesionální stěhování bytů, kanceláří a firem v Olomouci a celé ČR. Stěhovací firma Olomouc zajistí bezpečné zabalení, přepravu a složení nábytku.', picturePath: null, active: true },
  { fullName: 'Fast Move Olomouc', phone: '+420 603 791 345', email: 'info@fastmove-olm.cz', serviceId: 'stehovaci-firma', cityId: CITY, address: 'Holická 5678/75, Olomouc', description: 'Fast Move je rychlá stěhovací firma v Olomouci zajišťující stěhování bytů i firem s vlastním vozovým parkem. Stěhovací firma Olomouc nabídne bezpečnostní balení, demontáž a montáž nábytku.', picturePath: null, active: true },
  { fullName: 'Stěhování Vávra Olomouc', phone: '+420 728 678 234', email: null, serviceId: 'stehovaci-firma', cityId: CITY, address: 'Krapkova 6789/89, Olomouc', description: 'Stěhování Vávra je spolehlivá stěhovací firma v Olomouci s vlastními stěhovacími vozidly a pojištěním nákladu. Stěhovací firma Olomouc realizuje stěhování po Olomouci i mezinárodní přepravu.', picturePath: null, active: true },
  { fullName: 'Profi Stěhování Olomouc', phone: '+420 585 234 890', email: 'profistehov@olm-move.cz', serviceId: 'stehovaci-firma', cityId: CITY, address: 'Litovelská 4567/57, Olomouc', description: 'Profi Stěhování Olomouc je komplexní stěhovací firma pro domácnosti i firmy v Olomouckém kraji. Stěhovací firma Olomouc zajistí expresní i plánované stěhování s péčí o každý kus majetku.', picturePath: null, active: true },

  // ── TRENÉR ───────────────────────────────────────────────────────────────
  { fullName: 'Fitness trenér Horáč Olomouc', phone: '+420 728 441 890', email: 'horac@fitnes-olomouc.cz', serviceId: 'trener', cityId: CITY, address: 'Třída Svobody 5678/79, Olomouc', description: 'Fitness trenér Horáč je osobní trenér v Olomouci nabízející tréninkové plány a nutriční poradenství. Trenér Olomouc pomůže s hubnutím, nabíráním svalové hmoty a zlepšením kondice.', picturePath: null, active: true },
  { fullName: 'Tereza Blažková – osobní trenérka Olomouc', phone: '+420 585 560 234', email: 'blazkova@trener-olm.cz', serviceId: 'trener', cityId: CITY, address: 'Rooseveltova 5678/73, Olomouc', description: 'Tereza Blažková je certifikovaná osobní trenérka v Olomouci specializující se na funkční trénink a pilates. Trenér Olomouc nabídne individuální fitness program pro dosažení zdravotních i sportovních cílů.', picturePath: null, active: true },
  { fullName: 'Sportovní centrum Sigma Olomouc', phone: '+420 585 455 666', email: 'info@sigma-sport-olm.cz', serviceId: 'trener', cityId: CITY, address: 'Legionářská 1300/23, Olomouc', description: 'Sportovní centrum Sigma nabízí trenéry a sportovní kurzy pro děti i dospělé v Olomouci. Trenér Olomouc zajistí kondičníkurzy, skupinové lekce jógy a fitness tréninky v moderně vybaveném centru.', picturePath: null, active: true },
  { fullName: 'Mgr. Macháč – trenér atletiky Olomouc', phone: '+420 728 228 901', email: null, serviceId: 'trener', cityId: CITY, address: 'Holická 6789/89, Olomouc', description: 'Mgr. Macháč je trenér atletiky a kondičního tréninku v Olomouci s licencí ČAS. Trenér Olomouc pracuje s dětmi, juniory i dospělými závodníky na atletickém stadionu v Olomouci.', picturePath: null, active: true },

  // ── PŘEKLADATEL ──────────────────────────────────────────────────────────
  { fullName: 'Překladatelské centrum Olomouc', phone: '+420 585 441 760', email: 'info@prekladolm.cz', serviceId: 'prekladatel', cityId: CITY, address: 'Horní náměstí 64, Olomouc', description: 'Překladatelské centrum Olomouc nabízí odborné překlady z němčiny, angličtiny a dalších jazyků pro firmy i jednotlivce. Překladatel Olomouc zajistí přesné překlady smluv, technických dokumentů a úředních listin.', picturePath: null, active: true },
  { fullName: 'Mgr. Janáková – překladatelka Olomouc', phone: '+420 728 778 450', email: 'janakova@prekladolm.cz', serviceId: 'prekladatel', cityId: CITY, address: 'Třída Svobody 2345/33, Olomouc', description: 'Mgr. Janáková je soudní překladatelka pro němčinu a angličtinu v Olomouci s oprávněním od Krajského soudu. Překladatel Olomouc provede úřední překlady dokumentů pro státní orgány a instituce.', picturePath: null, active: true },
  { fullName: 'ProTranslate Olomouc', phone: '+420 585 229 112', email: 'info@protranslate-olm.cz', serviceId: 'prekladatel', cityId: CITY, address: 'Rooseveltova 3456/43, Olomouc', description: 'ProTranslate je překladatelská agentura v Olomouci zajišťující překlady do více než 25 jazyků pro firmy a instituce. Překladatel Olomouc nabídne expresní i standardní překlad s garancí kvality.', picturePath: null, active: true },
  { fullName: 'Bc. Blažková – tlumočnice Olomouc', phone: '+420 603 113 456', email: null, serviceId: 'prekladatel', cityId: CITY, address: 'Ostružnická 3456/41, Olomouc', description: 'Bc. Blažková je překladatelka a tlumočnice pro angličtinu a slovenštinu v Olomouci. Překladatel Olomouc nabízí konsekutivní tlumočení na konferencích, jednáních a firemních akcích.', picturePath: null, active: true },

  // ── GRAFIK ───────────────────────────────────────────────────────────────
  { fullName: 'Grafické studio Horáček Olomouc', phone: '+420 585 450 890', email: 'horacek@grafika-olm.cz', serviceId: 'grafik', cityId: CITY, address: 'Horní náměstí 72, Olomouc', description: 'Grafické studio Horáček nabízí komplexní grafické služby v Olomouci – loga, firemní identitu, tisk a webdesign. Grafik Olomouc zajistí profesionální vizuální komunikaci pro firmy v Olomouckém kraji.', picturePath: null, active: true },
  { fullName: 'PixelArt Olomouc – grafický design', phone: '+420 728 334 780', email: 'info@pixelart-olm.cz', serviceId: 'grafik', cityId: CITY, address: 'Třída Svobody 4567/63, Olomouc', description: 'PixelArt Olomouc je grafické studio specializující se na digitální design, tvorbu webů a reklamní kampaně. Grafik Olomouc nabídne kreativní řešení pro marketing a branding firem.', picturePath: null, active: true },
  { fullName: 'Bc. Janáková – grafička Olomouc', phone: '+420 603 887 123', email: 'janakova.grafika@olomouc.cz', serviceId: 'grafik', cityId: CITY, address: 'Rooseveltova 5678/73, Olomouc', description: 'Bc. Janáková je freelance grafička v Olomouci nabízející návrhy letáků, plakátů a obalového designu. Grafik Olomouc pracuje pro agentury i přímé klienty s rychlými dodacími lhůtami.', picturePath: null, active: true },
  { fullName: 'Studia Kreativa Olomouc', phone: '+420 585 556 890', email: 'studio@kreativa-olm.cz', serviceId: 'grafik', cityId: CITY, address: 'Ostružnická 4567/51, Olomouc', description: 'Studia Kreativa je grafická agentura v Olomouci s kompletními kreativními službami – logo, web, video a sociální sítě. Grafik Olomouc pomůže firmám budovat silnou vizuální značku a efektivní online prezentaci.', picturePath: null, active: true },
];

async function main() {
  let count = 0;
  for (const p of profiles) {
    const created = await prisma.provider.create({ data: p });
    console.log(`✓ ${created.fullName}`);
    count++;
  }
  console.log(`\nDone. Added ${count} profiles.`);
}
main().catch(console.error).finally(() => prisma.$disconnect());
